### ISSUE TITLE
First search in the _Contacts_ tab takes about 3 minutes

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2126] opened 2016-03-21 18:58 UTC
Adding an issue for this as reported by the devs during their trip to Uganda. If this is still an issue, we should investigate and resolve.

**Comment by abbyad** [comment] 2016-04-28 19:02
Perhaps @SCdF or @estellecomment have more information on this. Would be good to know if this is still an issue in 2.6.1.

**Comment by SCdF** [comment] 2016-04-29 11:20
We mitigated it with the attached closed PR, by reducing the ways CHPs can close the app (now only via phone restart or app update), which in turn reduces the number of times a search for a contact is the "first" search.

Apart from that I don't think we've done anything. I would imagine though, that might be enough. CHPs tended to quit the app by hammering back a lot when I was talking with them, and this removes that, so I think from their perspective it should have made a big difference.

**Comment by alxndrsn** [comment] 2016-04-29 11:22
> reducing the ways CHPs can close the app (now only via phone restart or app update)
N.B. that the OS can kill the app whenever it chooses to, so these aren't the only things that could force a restart.

**Comment by garethbowen** [comment] 2016-08-30 04:14
This is probably a duplicate of #2665

Assigning to @sglangevin to test.

**Comment by sglangevin** [comment] 2016-08-30 23:31
@garethbowen this is still a concern in v2.8.0, though it's possible that it's because I'm starting out with a log of data as opposed to adding families over time (not sure). After the first search, any subsequent search is quick though.

**Comment by garethbowen** [comment] 2016-08-30 23:36
Reopening as first load is still slow.

**Comment by abbyad** [comment] 2016-10-18 15:11
@sglangevin is this needed for a v2.9 release?

**Comment by sglangevin** [comment] 2016-10-19 07:12
This only applies to the Android app currently, so I'd say we can release 2.9 without it and then try to revisit this at a later date.

**Comment by abbyad** [comment] 2016-10-19 07:20
Sounds good, we'll leave it in the backlog for now then.

**Comment by garethbowen** [comment] 2018-11-26 09:47
There are a bunch of other issues that have been resolved in the same area so I'm closing this as ancient.

**Closed by garethbowen** 2018-11-26 09:47 UTC
Labels: Type: Performance
