### ISSUE TITLE
Re-instate help pages

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1727] opened 2015-12-02 07:21 UTC
Help pages were removed from the app in #1722.  They should be re-instated, and hidden by more valid means when that is required.

**Comment by alxndrsn** [comment] 2016-01-12 11:50
These should be re-instated as individual docs in the db if #1700 is accepted

**Comment by browndav** [comment] 2016-02-09 17:36
Moving this to the backlog for now as we didn't identify it as a priority for this iteration.

**Comment by garethbowen** [comment] 2016-02-18 22:07
Duplicate of #1895

**Closed by garethbowen** 2016-02-18 22:07 UTC
Labels: 0 - Backlog, Technical Debt
