### ISSUE TITLE
Protecting against invalid values for reported_date

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3495] opened 2017-05-22 11:30 UTC
The webapp allows future dates when using the mobile app.  We should validate the reported_date against the server date.  One way to do this might be to warn the user that the date on their system is the wrong one by getting the current date/time from the server.  I'm sure there are lots of considerations here with the reported_date vs sync_date etc but future dates should be disallowed somehow.  It looks like the time is getting derived from the date/time settings from the CHP phones.  I'm not sure it's reasonable to expect thousands of CHPs to have the correct date/time on their phones.

**Comment by Enock1990** [comment] 2017-05-22 11:41
This has been an issue before. Sometime the CHPs phone might be off(not correct). Does this mean that we will always have this issue? cc @derickl

**Comment by sglangevin** [comment] 2017-05-24 17:26
The approach we have taken to this is to warn the user if their date is incorrect. This is already implemented. As of v2.12.0 we'll be keeping track of the date that the report hits the server, which gets us a step closer to dealing with this issue a bit better. The problem is that users are creating reports offline, so we have to use the phone date/time when the report is created. Warning users helps, but they still have to contact someone to resolve the problem.

I like the idea of sending a warning if the phone time and server time are very different from one another. The other thing we can do is alert managers if we're getting CHW reports with times that are very different from the time the report was synced. This might be a more effective way to deal with the issue because then managers would be responsible for making sure that CHWs' phones are set up correctly.

This needs more discussion about how to proceed. Probably best to put this on the list of exploratory design work for a little later in the year. cc @diannakane

**Comment by diannakane** [comment] 2017-06-05 21:04
I've added it to the design ideas repo.

**Comment by garethbowen** [comment] 2018-01-31 20:48
> I like the idea of sending a warning if the phone time and server time are very different from one another. 

We're doing this on app start. If the user is online then we check that the phone time and server time are within 10 minutes and warn if they're not. If the user is offline then we check against a fixed time in the past so if their phone has reset to 0 they'll also get a warning.

I think there must be a bug (or missing feature) in older phones because most phones keep time really well so I'm hoping the root cause of this problem goes away as the phones are replaced.

I don't think there's much more we can do without blocking the CHP actually doing their work so I'm going to close this for now. If anyone comes up with a specific feature to mitigate this bug let me know!

**Closed by garethbowen** 2018-01-31 20:48 UTC
Labels: Needs Triage
