### ISSUE TITLE
Cannot filter `select2` options on android

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1534] opened 2015-11-05 12:49 UTC
# Context

Editing a Family's Primary Caregiver field on `lg.app` on Tecno phone

# Observed

* can scroll the list
* can select an option by poking it
* typing in the filter box -> _No results found_, even if typing something which is visible in the list!

# Expected

Filtering should work.

# Notes

Not a regression ;¬)

**Comment by mandric** [comment] 2015-11-05 13:19
I can also reproduce this on my samsung sIII.

**Comment by browndav** [comment] 2015-11-10 22:43
Deprioritized; Josh reports that the select2 Enketo widgets will not be used during the initial field test.

**Comment by garethbowen** [comment] 2016-02-29 23:40
Related or duplicate of #1534

**Closed** 2016-03-01 01:02 UTC
Labels: 0 - Backlog, Bug, Mobile Only, v0.6
