### ISSUE TITLE
Make bulk importing easier to use

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3936] opened 2017-09-28 23:58 UTC
Up till now a developer has always been required to run the `medic-bulk-utils` data imports. For each data set this takes days to execute which is a complete waste of time. We need to make it easy and safe enough for a tech lead or project to use.

This will require some investigation of requirements, but here are some I can think of.

* Performance. The current solution is very slow.
* Robustness. It fails a lot which makes is slower but also error-prone.
* Resumable (if that's a word). If a failure occurs, rerunning should pick up where it left off.

I don't think we need to be flexible in input data format. We can specify one that works for us and leave it up to the user to ensure their data conforms.

It could either be implemented as an API or as part of medic-configurer. Doing it in the API means we can easily wrap a UI around it, and also all the round trip processing happens on the server. Doing it in medic-configurer means you can import to older versions of webapp but that could cause problems where the data structure has changed.

**Comment by garethbowen** [comment] 2017-10-18 17:55
We can use the latest round of imports to test this: medic/medic-projects#2935

**Comment by abbyad** [comment] 2017-11-03 19:00
We used this successfully for our latest data import. 

The header format is sufficiently complicated that we should update it before closing this issue. I have opened https://github.com/medic/medic-conf/issues/47 to deal with the header format update.

**Comment by abbyad** [comment] 2017-11-03 19:04
I've changed the priority from _High_ to _Medium_ since the current version is functional for urgent needs, but would be good to improve this before we document and release it for wider use.

**Comment by alxndrsn** [comment] 2017-12-19 11:50
@abbyad how does this look?

# csv-to-docs

To convert CSV to JSON docs, use the `csv-to-docs` action.

## property types

By default, values are parsed as strings.  To parse a CSV column as a JSON type, suffix a data type to the column definition, e.g.

	column_one,column_two:bool,column_three:int,column_four:float,column_five:date,column_six:timestamp

This would create a structure such as:

	{
		"_id": "09efb53f-9cd8-524c-9dfd-f62c242f1817",
		"column_one": "some string",
		"column_two": true,
		"column_three": 1,
		"column_four": 2.3,
		"column_five": "2017-12-31T00:00:00.000Z",
		"column_six": 1513255007072
	}

## excluded columns

To exclude a column from the final object structure, give it the type `excluded`:

	my_column_that_will_not_be_a_property:excluded

This can be useful if using a column for doc references.

## doc references

To reference other docs, replace the type suffix with a matching clause:

	location:place WHERE external_id=COL_VAL

This would create a structure such as:

	{
		"_id": "09efb53f-9cd8-524c-9dfd-f62c242f1817",
		"location": {
  		"_id": "7ac33d1f-10d8-5198-b39d-9d61595292f6"
			"name": "some place"
		}
	}

## doc property references

To reference specific properties of other docs:

	location:_id OF place WHERE external_id=COL_VAL

This would create a structure such as:

	{
		"_id": "09efb53f-9cd8-524c-9dfd-f62c242f1817",
		"location": "7ac33d1f-10d8-5198-b39d-9d61595292f6"
	}

Note the special string `COL_VAL` - this matches the CSV column value for the row being processed.

**Comment by abbyad** [comment] 2017-12-20 17:07
Overall looks good, and I like the addition of the `excluded`. I also like that the notation has a resemblance to a known notation (SQL). With that in mind, just a couple questions about making the format more in line with SQL:
- Is there a reason to use `OF` over `FROM`? Eg `location:_id FROM place WHERE external_id=COL_VAL`
    _I had also thought dot notation would be nice here (eg `location:place._id WHERE external_id=COL_VAL`), but then realized that the `WHERE` doesn't look properly associated to `place` anymore._
- Building on the previous point, when using a reference it would match SQL to have the field name at the end using `AS`. Any downsides to this? Eg `_id FROM place WHERE external_id=COL_VAL AS location`
- Do we want to make it possible (or even mandatory) to use `SELECT` at the beginning? Using it may also be clearer that the field is a reference. Eg `SELECT _id FROM place WHERE external_id=COL_VAL AS location`

This _really_ makes it look like SQL. The downside is that it could be misleading since we wouldn't support _all_ SQL notation, but has the benefit of being familiar to external partners.

**Comment by alxndrsn** [comment] 2017-12-20 20:55
This isn't SQL, so I'm not particularly excited about making it look more like SQL.

To specific points:

1. `OF` makes more sense to me
2. I don't understand what this example is meant to demonstrate.  From my recollection, `AS` is used in SQL to alias a table (or temporary table) to a name so that its fields can be referenced later... I don't think that applies here.  Also it makes the matching syntax diverge from the standard column syntax.
3. ...see above

**Comment by abbyad** [comment] 2017-12-20 21:59
I realize this isn't a full fledged SQL, but I think we are better off reusing a familiar notation rather than introducing a completely new notation. 

1. As soon as I saw the `WHERE` I thought this looks like SQL, and I think others will do the same. The `SELECT ___ FROM ____ WHERE ____` notation will be familiar enough to most anyone doing an import. Using `OF` introduces a new concept, yet is practically speaking the same as `FROM`.
2. You're right that `AS` is alias for a table how I had it, but I had meant it as alias for a column -- in which case it should have been before the `FROM`. My example should have been `_id AS location FROM place WHERE external_id=COL_VAL`. 
3. Having `SELECT` emphasizes that this is a reference, and it would make sense that the format be different.

If there are major objections to have this look like SQL, I'd want to hear more about it to find out what the problem is. If that is the case we should be looking at a notation that wouldn't be confused with SQL, perhaps switching `WHERE` to `MATCH`, or some other distinction. That said, from my perspective a SQL-like version would be a lot simpler to grasp by our own tech leads and technical staff with partner organizations, and lead to less confusion. Let's figure out a way that satisfies both our concerns.

**Comment by alxndrsn** [comment] 2017-12-20 22:10
# proposal
```
location:_id of place whose external_id=COL_VAL
```

**Comment by abbyad** [comment] 2017-12-20 22:13
What does the format look like with additional conditions? Currently it is `match=P:X=a&Y=y`, and just curious how that evolves with the proposed format.

**Comment by alxndrsn** [comment] 2017-12-20 22:31
Not currently implemented.  Is this something that's required?

**Comment by abbyad** [comment] 2017-12-21 15:33
Ah ok, I thought it was already implemented since it is documented [here](https://github.com/medic/medic-conf/blob/d55f14dbe090c85e5fac2b18aad9d808034303e6/README.md#reference-to-a-doc-by-matching-properties):
![image](https://user-images.githubusercontent.com/789512/34261538-69fbb90c-e637-11e7-83a4-e63fed67bb7c.png)

Using `and` and `or` makes sense given the rest of the format.

Looking at the format again however I still find it slightly confusing, probably because of the `location:_id` part. I think we are better off having a keyword in there to specify that this is different than the regular format and will be easier to comprehend when reading, eg `location:GET _id OF place WHERE ...` (I prefer `where` to `whose`, and it doesn't look so much like SQL with `GET` and `OF`)

Being explicit in this case would help with clarity, even if it isn't technically necessary, and notice I didn't suggest `SELECT` :)

## Proposal
```
location:GET _id OF place WHERE external_id=COL_VAL and (fieldX=valueX or fieldY=valueY)
```
Keywords may be any case, but documented as (and suggested to use) uppercase for readability purposes.

**Comment by alxndrsn** [comment] 2018-01-26 10:32
:+1:

**Comment by sglangevin** [comment] 2018-01-31 19:08
Just commenting to say that I've used the old header format for CSV and this is working well and is easy to use. Probably need some testing of the new header format before we can close this.

**Comment by ngaruko** [comment] 2018-03-15 08:18
Any tips on how to AT this @alxndrsn ?

**Comment by abbyad** [comment] 2018-03-28 21:24
Given that the goal of this issue is to make importing of new places, people, and forms easier, see if you can do all of that with the instructions documented [here](https://github.com/medic/medic-conf/blob/master/README.md#csv-to-docs).

**Comment by ngaruko** [comment] 2018-04-06 03:42
LGTM

**Closed by ngaruko** 2018-04-06 03:42 UTC
Labels: Configuration, Priority: 2 - Medium, Status: 5 - Ready, Type: Improvement
