### ISSUE TITLE
There is no warning when HBB is used to exit a form

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3462] opened 2017-05-11 16:48 UTC
# Observed:

When filling an enketo form and HBB is (accidentally) pressed, the app navigates back to the previous screen (e.g. the tasks list), losing all form progress.

# Expected:

I would expect the "are you sure you want to leave?" confirmation dialog to be displayed

**Comment by sglangevin** [comment] 2017-05-11 17:18
This is a duplicate of #3086. Closing.

**Closed by sglangevin** 2017-05-11 17:18 UTC
Labels: Bug, Mobile Only
