### ISSUE TITLE
App no longer redirects to login page when not logged in when hitting in-app URL

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1972] opened 2016-02-25 06:43 UTC
On opening a link to alpha.dev this morning, I was presented with a screen suggesting that the app is broken.  On checking the console, it seems more likely that my session has timed out but the forward-to-login functionality is broken.

# Environment

* alpha.dev
* build: likely 2813 (can't check)
* Firefox

# Dramatic screenshot

<img width="1044" alt="screen shot 2016-02-25 at 07 38 03" src="https://cloud.githubusercontent.com/assets/191496/13311937/d01c2f66-db92-11e5-909d-7b34adc992b8.png">

# Steps to recreate

1. open firefox
1. log in to alpha.dev
2. close your browser
3. go to bed, sleep for 8 hours
5. get up, make tea
8. open firefox, and then this link: https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/add/ovc-survey
13. observe _Dramatic screenshot_!!!

**Comment by alxndrsn** [comment] 2016-02-25 06:44
@SCdF caused by https://github.com/medic/medic-webapp/issues/1931?

**Comment by SCdF** [comment] 2016-02-25 08:26
@alxndrsn if by caused by you mean is another example of, then yeah I agree. This is another code path that needs to be checked for a 401 and then redirected. Going to close this as a dupe.

(If you or anyone else can think of any more code paths that we need to check let me know / fix them yourselves, unfortunately I'm not aware of a way of solving this globally).

**Closed by SCdF** 2016-02-25 08:26 UTC
Labels: Bug, Duplicate, Priority, Regression

**Comment by alxndrsn** [comment] 2016-02-25 14:52
I meant "caused by" as in 'this is a new behaviour possibly introduced by the work in ' #1931
