### ISSUE TITLE
deleting a Catchment Area does not update the Contact's "Catchment Area" field

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#954] opened 2015-05-15 10:06 UTC
# Steps to recreate:
1. find a person who is set as contact for a catchment area
1. delete the catchment area
1. browse back to the person
1. refresh the browser
1. observe that the person still has Catchment Area set

# Expected behaviour:
* When a Catchment area is deleted, it should be removed from related contacts

**Comment by alxndrsn** [comment] 2015-05-15 10:08
#945 should be fixed by https://github.com/medic/medic-webapp/pull/946

**Comment by alxndrsn** [comment] 2015-05-15 11:54
Possibly duplicate of https://github.com/medic/medic-webapp/issues/924

**Comment by browndav** [comment] 2015-05-15 20:47
Alex and I talked this morning, and agreed that this is a broader issue that affects several area of the application – specifically, multiple areas of the app are using embedded documents (read: a snapshot of the associated object at time-of-creation) when it might be more appropriate to present a reference (read: the most current version of the associated object). Can we all chat about this via Skype on Monday?

**Comment by browndav** [comment] 2015-05-15 20:56
#947 is conceptually related to this; it's representing the update case, whereas this issue represents the delete case.

**Comment by garethbowen** [comment] 2015-09-03 02:04
Duplicate of #969

**Closed by garethbowen** 2015-09-03 02:04 UTC
Labels: 0 - Backlog, Bug
