### ISSUE TITLE
Pull out and merge horticulturalist upgrade UI

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3749] opened 2017-08-02 17:02 UTC
Get the upgrade UI code production ready.

Wrap it in some code so we can get it into master, but have it disabled until we're ready to use it.

**Comment by SCdF** [comment] 2017-08-03 16:28
@garethbowen / @alxndrsn please take a look at the two linked PRs

**Comment by SCdF** [comment] 2017-08-10 08:55
OK so after reading @garethbowen 's feedback and thinking for a bit, here is what I think I'd need to do to satisfy this:
 - _(implicit in all this is the various bug avoidances and style changes, I just want to go over the main logic beats)_
 - Define a namespace convention for ddocs, where `medic/_design/medic` can be converted to a ddoc name, with version, perhaps `medic:medic:branchOrTagName`
 - Change our push_to_staging script to put with these names and additional branch / version information (eg `medic:medic:3.0.0`)
 - Change the view generating for staging to take this into account
 - Change the webapp UI to work with this change
 - Change api to copy the proposed ddoc to a new database, say called `staging` or maybe `new-releases`. The name (eg `medic:medic:2.3.0` won't be changed. 
 - Change horti to watch the new database (`staging` or `new-releases`) and then use the convention to stop api / sentinel if they've changed, deploy the api and packages in the right places etc.

Open questions:
 - When do we add deployment metadata? Currently it's when api moves it, based on the user who calls api
 - When do we migrate config between ddocs. Currently it's when api moves it.
 - We're making this more generic. While looking for kanso-themed application attachments is generic, knowing what to restart (or even that you're on medic-os in the first place) isn't. How should we deal with this? Should we just hard-code that knowledge for now, or do we need to build up another structure to allow us to do this.

So IMO this is a lot, with some open questions. Because we're implying more genericness (we're not just for deploying medic!) I presume more things will come out of the woodwork as we go.

I would rather not do any of this right now[1].

I'd rather just get the base functionality of being able to deploy medic and friends working and in production, and leave this for horti 2.0. FWIW there are already future things we need to do with horti to make it "perfect", which involves (imo) moving the api, webapp js and html code into the horti package itself (possibly along with the staging db view definitions) to make it more self contained, to get rid of the weirdness that api arguably calls for its own reboot, and get it closer to being usable by other people using CouchDB.

Interested in your thoughts @garethbowen. We can talk tomorrow morning your time if you like.

[1] with the minor logic change of changing api to not directly copy over the ddoc, to fix the bug of our app refresh happening before api / sentinel have been re-deployed. I'd just called it `medic-next` and have it in the `medic` db.

**Comment by garethbowen** [comment] 2017-08-10 09:27
> When do we add deployment metadata? Currently it's when api moves it, based on the user who calls api

It pretty much has to be when api copies it if you want to capture the user, right?

> When do we migrate config between ddocs?

As late as possible, ie: when horti copies the ddoc from staging.

> How should we deal with [making this more generic]?

Hardcoding is fine wherever it doesn't back us into a corner later. I have no clue how to make restarting generic...

The problem with leaving the builds db the way it is now is you will likely end up with a chicken and egg problem - the webapp won't find an available upgrade because it needs to be upgraded to see it. This could be worked around with manual upgrades and the like but that's a pain. A little bit of pain now saves a lot of pain later once everyone depends on horti...

**Comment by SCdF** [comment] 2017-08-10 11:09
I disagree, but I can commit!

Perhaps a minimum set then, is to just change the naming scheme and views
and leave the rest of it. Then the "API" of the staging db is future proof,
and it's unlikely they location of updates will change.

**Comment by garethbowen** [comment] 2017-08-10 20:56
That sounds like a great compromise. We can update the webapp side whenever.

**Comment by SCdF** [comment] 2017-08-14 13:31
Builds repo PR: https://github.com/medic/medic-builds-repo/pull/1

**Comment by SCdF** [comment] 2017-08-18 16:37
OK, we're in the final draft stage.

@garethbowen can you primarily take a look at:
 - https://github.com/medic/medic-api/pull/187
 - https://github.com/medic/medic-webapp/pull/3750

@alxndrsn can you primarily take a look at:
 - https://github.com/medic/horticulturalist/pull/1

As a note, I'll also be merging the builds repo changes: https://github.com/medic/medic-builds-repo/pull/1

**Comment by SCdF** [comment] 2017-08-18 18:06
Oh, @alxndrsn / @garethbowen please don't merge any of these. I'll do it in one horrific go when they're all approved.

**Comment by SCdF** [comment] 2017-09-01 13:58
Missed this one. Merged to master awhile ago (available on 2.14+)

**Comment by ngaruko** [comment] 2017-09-05 03:54
I am tempted to reopen this as I am getting errors when using the horticulturalist UI, errors which might be due to my settings but that a) need some investigating to establish the cause and b)maybe need to be communicated back to the UI if they occur. Alternatively, if the issue was just to get the UI (however functional) into production, we could close this and open another issue for the error below. Your thoughts @SCdF ? 
```upgrade() Upgrading to {"namespace":"medic","application":"medic","version":"3822-form-name-e2e-flake"}…
upgrade() Fetching newDdoc…
upgrade() Fetched newDdoc.
upgrade() Fetching oldDdoc…
upgrade() Fetched oldDdoc.
upgrade() Staging new ddoc as _design/medic:staged
Server error:
 { error: 'conflict',
  reason: 'Document update conflict.',
  name: 'conflict',
  status: 409,
  message: 'Document update conflict.',
  docId: '_design/medic:staged' }```

**Comment by SCdF** [comment] 2017-09-05 06:38
@ngaruko that particular issue is already covered by #3806 .

In theory you shouldn't get this problem if you're using the tool "right", but we should fix it all the same.

**Comment by ngaruko** [comment] 2017-09-06 03:06
Thanks @SCdF. Will close this and leave #3806 to fix this.

**Closed** 2017-09-06 03:06 UTC
Labels: Priority: 2 - Medium, Status: 5 - Ready, Type: Feature
