### ISSUE TITLE
Adding an extra child repeat section scrolls window to top

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1668] opened 2015-11-25 07:27 UTC
Should keep scroll in same place, or scroll a bit to the start of the newly-added section.

I think this is a duplicate, but cannot find the original.

**Comment by garethbowen** [comment] 2015-11-25 09:43
Closing as a duplicate of #1588

**Closed by garethbowen** 2015-11-25 09:43 UTC
Labels: Bug

**Comment by alxndrsn** [comment] 2015-11-25 11:09
Thanks.
