### ISSUE TITLE
I find the minus sign icon used for removing an item from the RHS while bulk deleting to be confusing

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2412] opened 2016-06-20 23:40 UTC
Perhaps we could consider a different icon or moving it to the top right corner to make it clearer that this will remove the report from the RHS list? Partial screenshot for reference.

![image](https://cloud.githubusercontent.com/assets/1286381/16213598/836d6e5e-3705-11e6-9c8c-a4a53c0512aa.png)

@diannakane @Lesterng curious to hear your thoughts/ideas.

**Comment by diannakane** [comment] 2016-06-20 23:44
I agree with your assessment, Sharon. I would prefer an "x" possibly
accompanied by the word "remove" or a checked box that can be unchecked to
signal that it will be deselected rather than deleted, mimicing the LHS
interaction.

On Mon, Jun 20, 2016 at 4:40 PM, Sharon Langevin <notifications@github.com>
wrote:

> Perhaps we could consider a different icon or moving it to the top right
> corner to make it clearer that this will remove the report from the RHS
> list? Partial screenshot for reference.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1286381/16213598/836d6e5e-3705-11e6-9c8c-a4a53c0512aa.png>
>
> @diannakane <https://github.com/diannakane> @Lesterng
> <https://github.com/Lesterng> curious to hear your thoughts/ideas.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2412>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXo4e_O5kswGgVAyJDi0yWFFqOj3Xks5qNyTlgaJpZM4I6O8s>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment] 2016-06-21 02:24
The problem with a "x" is it's unclear whether it's removing from selection or deleting. The problem with a checkbox is when the user unchecks it the row disappears which is not the expected behaviour with a checkbox.

How about I move it to the top right corner and add the label "deselect" or similar?

**Comment by diannakane** [comment] 2016-06-21 16:37
It's really tricky, because removing an item from the RHS is because you
*don't* want to delete it, so anything that's remotely akin to deleting
("remove from list") will likely make a user nervous as that could be
interpreted as a delete action.

@lesterng do you have any suggestions?

Another issue is when I click the current "-" button to remove it, the
change is nearly imperceptible, especially if there are duplicate records
of the same client. Is it possible to make this action slightly more
noticeable?


On Mon, Jun 20, 2016 at 7:24 PM, Gareth Bowen <notifications@github.com>
wrote:

> The problem with a "x" is it's unclear whether it's removing from
> selection or deleting. The problem with a checkbox is when the user
> unchecks it the row disappears which is not the expected behaviour with a
> checkbox.
>
> How about I move it to the top right corner and add the label "deselect"
> or similar?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2412#issuecomment-227323751>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXvwfuvYorqv6_3pO0fJZICQqqwopks5qN0tngaJpZM4I6O8s>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by sglangevin** [comment] 2016-06-21 18:21
I think it would definitely help to put the icon at the top right, but I bet @Lesterng might have some good suggestions, so I'm curious to see what he thinks.

**Comment by nice-snek** [comment] 2017-03-15 09:40
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment] 2017-03-18 00:24
Closing as it is in the top right, which was one of the suggestions above ![image](https://cloud.githubusercontent.com/assets/789512/24067170/7a57fd4c-0b4f-11e7-92b9-cefee7b175fe.png)

@diannakane if you decide to bring this to the design team please open a new issue when there is a new suggestion.

**Closed by abbyad** 2017-03-18 00:24 UTC
Labels: Needs Design Work, Needs Triage, UI/UX

**Comment by diannakane** [comment] 2017-03-20 21:02
@slangevin do you recall if we created an "idea" for this piece of feedback?

**Comment by sglangevin** [comment] 2017-03-21 21:14
I think it's covered by the History/Reports tab audit
