### ISSUE TITLE
Enable users to export, even if they do not have permission to configure

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3113] opened 2017-02-09 20:04 UTC
Right now, all exports are done from a Configuration page. This means that anyone who wants to export must have the `can_configure` permission. However, there are many users who need to export data but should not be allowed to configure. Ideally, we would have separate permissions so that a user could be given access to the export page only, even if they can't access other configuration pages.

Reported by @bishwas-medic: https://github.com/medic/medic-projects/issues/1327

**Comment by SCdF** [comment] 2017-02-21 14:23
Looking at this, I think this needs some design / more consideration potentially?

 - Who gets this permission? AFAICT you can't assign permissions to individual users, but instead only to genres of people. So with that said I'm not sure how you'd make a "you can export but do nothing else" without making a new user type?
 - Can they then see `Configuration` in their menu, with only the Import/Export button visible? Or are we exposing this functionality in a different way for these users?
 - If so, do we also allow them to import? Or just export?
 - Also, which exports are they allowed? Some of them have more privacy implications than others (server logs, audit logs)

**Comment by SCdF** [comment] 2017-02-24 09:04
@sglangevin did you have any thoughts about my thoughts above?

**Comment by sglangevin** [comment] 2017-02-24 18:45
Yes, I will get back to you on this either today or Monday. I have been chatting with @diannakane about it and need to follow up with the tech leads to find out what kinds of exports are going to be needed. I believe the primary one is exporting reports but I want to confirm before we proceed.

**Comment by garethbowen** [comment] 2017-03-06 07:39
FYI this was removed in #2338

The old export allowed users to export reports that matched the search. This is what the `GenerateSearchRequests` service was used for which has been gutted (it's never passed any filters). This service builds a lucene query for the export for Contacts and Reports and thus is only available online. The current button only allows exporting of all reports. If we decide not to allow filtering this should be rewritten so as not to use lucene so it will work offline and won't need to download all the docs from the server unnecessarily.

**Comment by garethbowen** [comment] 2017-03-06 07:40
@sglangevin @diannakane Any updates on the functionality and design?

**Comment by sglangevin** [comment] 2017-03-06 20:11
Sorry for the delay, meant to get back to you on this last week after talking with @diannakane. After talking with the tech leads, we can get by with enabling users (online only) to export all reports and all messages. We were thinking we could implement a way to enable users to access the import/export page in Configuration only (no access to other configuration pages). This could be a link in the hamburger menu to Import/Export or they would have access to the Configuration tab and only see one of the pages (Import/Export).

If you think it would be easier to bring back the Export button to the Reports/History page and make it possible to export a filtered version of reports, then that's fine too. The key is to be able to export Reports and Messages without having access to all of the other configuration pages.

In the future, there are other features that have been requested, including the ability to export a filtered set of reports and the ability to select which columns are exported. Those are not needed right now, but helpful to keep in mind.

**Comment by SCdF** [comment] 2017-03-07 10:29
Sounds like the simplest and most UX-consistent thing to do would be to add the export button back to the contact page and the report page?

**Comment by sglangevin** [comment] 2017-03-07 17:13
Actually, I think just Messages and Reports since those were the requests we had from projects, but you can do Contacts too if you'd like.

**Comment by garethbowen** [comment] 2017-03-13 22:12
My plan is to add the export button back to the Messages, Reports, and Contacts tabs, and to have it ignore the filters and just download all.

I don't like the UX of having a separate tab labelled Configuration which only allowed them to export. And download filtering is based on lucene which we're trying to migrate off.

**Comment by garethbowen** [comment] 2017-03-14 01:20
Instead of ignoring the filters I used the existing code to enable filtering. Because it's server side (as it was in 0.4) it doesn't respect user restrictions, so this should only be enabled for users who are allowed to see all data, hence I used the permission `can_access_directly` (the same as used in 0.4). Implementing a solution that respects user restrictions will need some design so I've put that off for now - this just solves the regression.

Code review please @estellecomment : https://github.com/medic/medic-webapp/pull/3224 (you may need to use ?w=1)

**Comment by garethbowen** [comment] 2017-03-14 19:54
Estelle ran out of time so reassigning to @SCdF for code review please!

**Comment by SCdF** [comment] 2017-03-15 07:16
@garethbowen just some questions, back to you

**Comment by garethbowen** [comment] 2017-03-15 10:52
Done.

**Closed by garethbowen** 2017-03-15 10:52 UTC
Labels: 3 - Code Review, Feature Request, Next Feature Release
