### ISSUE TITLE
Data filter is wrong : allows dates outside of date range

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2244] opened 2016-04-27 11:47 UTC
On lg.dev and lg.app and locally.
![screen shot 2016-04-27 at 13 42 37](https://cloud.githubusercontent.com/assets/911434/14851182/7dfc92ee-0c7e-11e6-96f4-8de2885c4418.png)

**Comment by garethbowen** [comment] 2016-04-27 20:04
I think it's off by one day only. Somewhere we add a day to the filter because some expected records weren't showing up. It's probably a lazy solution to a timezone issue, or maybe something has changed in the system so we no longer need to add the day.

**Comment by abbyad** [comment] 2016-04-27 20:10
This is a duplicate of https://github.com/medic/medic-webapp/issues/2185

**Comment by garethbowen** [comment] 2016-04-27 20:15
Good point. Closing.

**Closed by garethbowen** 2016-04-27 20:15 UTC
Labels: Duplicate
