### ISSUE TITLE
Protractor migration

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#8053] opened 2023-01-27 21:45 UTC
**Describe the issue**
Protractor support has stopped. So we need to migrate as soon as we can
**Describe the improvement you'd like**
See remaining test in this [spreadsheet](https://docs.google.com/spreadsheets/d/1pxOJcl1MgfK8Csh6dx0lSZRRSbgJ3KpqEBJqb9H9fsE/edit#gid=0) > 
**Describe alternatives you've considered**
Have been running protractor and wdio in parallel.

**Comment by garethbowen** [comment] 2023-02-07 19:39
@ngaruko I think this is a duplicate of #7723

**Closed as completed** 2023-02-12 23:29 UTC
Labels: Type: Technical issue
