### ISSUE TITLE
Analytics front page no longer works

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2546] opened 2016-07-22 15:05 UTC
# `/analytics`

## Expected

<img width="1280" alt="screen shot 2016-07-22 at 17 02 07" src="https://cloud.githubusercontent.com/assets/191496/17061293/15eb7a1e-502e-11e6-9c10-7c29711700ca.png">

## Actual

<img width="1280" alt="screen shot 2016-07-22 at 17 00 00" src="https://cloud.githubusercontent.com/assets/191496/17061266/f5dc0658-502d-11e6-952c-65128e7d760c.png">

-----

Stock monitoring isn't even an option on this project!

**Comment by sglangevin** [comment] 2016-07-22 17:52
I remember this working at some point, where you could choose to enable/disable Targets and could enable/disable Analytics (which was ANC only). That seems not to be possible anymore, however. I'm able to enable/disable Targets but not Analytics. Could this have something to do with the fact that tasks and targets were disabled for admin users?

**Comment by garethbowen** [comment] 2016-07-24 20:16
Which analytics modules are available is determined by the AnalyticsModules service. In the case of Stock Monitoring this is deemed available if you have [any scheduled forms configured](https://github.com/medic/medic-webapp/blob/master/static/js/services/analytics-modules.js#L45).

If there is only one module enabled it should redirect you to that module without showing you the select page first so it looks like there's a bug there.

**Comment by garethbowen** [comment] 2016-08-16 02:38
I think this is a dupe of #2557 but it's hard to tell. If not, I can't get this to happen. Closing for testing.

**Closed by garethbowen** 2016-08-16 02:38 UTC
Labels: Bug, v0.4 features in 2.x, v0.4 upgrading
