### ISSUE TITLE
Add family button doesn't open the add family form on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2957] opened 2016-11-29 00:52 UTC
Seen on lg.dev, v2.9.0-alpha.4529. To reproduce:
1. Go to the people tab (on your Android phone)
2. Click the add family button at the bottom
3. Notice that the button gets the pink underline to note that it was tapped, but the form doesn't open.

I also tried clicking on my area and tapping on add family there, but I got the same result.

**Comment by sglangevin** [comment] 2016-11-29 00:56
This issue also applies to the add person button - it doesn't open the form on mobile, it just directs you back to the LHS of the People tab.

**Comment by garethbowen** [comment] 2016-11-29 01:14
Probably caused by #2939

**Comment by garethbowen** [comment] 2016-11-29 01:26
Actually caused by #2920

**Comment by garethbowen** [comment] 2016-11-29 01:49
PR for you @SCdF https://github.com/medic/medic-webapp/pull/2959

**Comment by SCdF** [comment] 2016-11-29 11:20
LGTM, merged.

**Closed by SCdF** 2016-11-29 11:20 UTC
Labels: 3 - Code Review, Bug, Contacts

**Comment by garethbowen** [comment] 2016-12-07 01:28
Backported to 2.9.x

**Comment by sglangevin** [comment] 2016-12-08 22:52
Working well in v2.9.0-beta.9
