### ISSUE TITLE
Base translations use mismatched conventions for places

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2691] opened 2016-08-31 15:37 UTC
I'm assuming that `messages.en` is the base translation for all projects. 

It contains some 0.4-style terms, like calling `clinic` "Catchment Area" : 
https://github.com/medic/medic-webapp/blob/master/translations/messages-en.properties#L3

and also some 2.6+-style terms, like calling `clinic` "Family":
[contact.type.clinic.edit = Edit Family](https://github.com/medic/medic-webapp/blob/master/translations/messages-en.properties#L537)

Is there a convention for which is which? 
Can we clean up old 0.4-style terms?

It also contains some LG-specific terms, like "CHP" (which is probably just wrong): 
https://github.com/medic/medic-webapp/blob/master/translations/messages-en.properties#L540

**Comment by garethbowen** [comment] 2016-08-31 20:43
Yes it'd be a good idea to work towards consistency here. Update the translation in POEditor as you find them.

Also there is bound to be a whole lot of unused keys which should be removed. The difficulty is finding if they're used.

**Comment by estellecomment** [comment] 2016-09-05 14:42
https://github.com/medic/medic-webapp/issues/2711

**Comment by garethbowen** [comment] 2016-10-31 02:43
Closing this as a duplicate of https://github.com/medic/medic-webapp/issues/2768 - if there are any other bad defaults raise separate issues for them.

**Closed by garethbowen** 2016-10-31 02:43 UTC
