### ISSUE TITLE
[android] select2 boxes are unusable

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1395] opened 2015-10-06 16:16 UTC
In Enketo forms, `select2` elements are terrible.

# Observed

## Click on the select2
1. it expands
2. it collapses
3. the keyboard appears

## click again

* same thing happens

## start typing

Even if you type something that exists, it says `No matches found` and displays no selectable options in the dropdown.

**Comment by garethbowen** [comment] 2015-10-06 22:13
According to select2 [mobile devices are supported](https://github.com/select2/select2/issues/2972). It might be an issue with how we're embedding it in our app.

The search returned not matches is a duplicate of #1336.

**Comment by garethbowen** [comment] 2015-10-07 02:52
I can't replicate this on the Techno - the select works as expected, although there isn't much room for selecting a result with the keyboard showing.

**Comment by alxndrsn** [comment] 2015-10-07 08:35
I was testing against `lg.dev.`; perhaps it's been fixed on `develop`.  I will test further.

**Comment by mandric** [comment] 2015-10-16 15:04
I have a branch that is working over here https://github.com/mandric/select2/tree/android-debounce-fix I'm just looking how to integrate it into the build...

**Comment by alxndrsn** [comment] 2015-10-16 15:23
Is this a bug in `select2`'s android support then?  Surprised they would have overlooked that.

**Comment by mandric** [comment] 2015-10-16 15:27
Also select2 4.0 is out and this bug appears to be fixed in that, but would be a little work to upgrade.  It's probably worth an issue to upgrade select2 if we want to keep using it.

**Comment by mandric** [comment] 2015-10-16 15:36
Alex will assign to you for code review and acceptance testing since you are the OP.  Sorry!

I opened a PR with select2 folks, might be easiest to just review that. https://github.com/select2/select2/pull/3840

**Comment by alxndrsn** [comment] 2015-10-16 15:38
ha, thanks! :smile:

**Comment by alxndrsn** [comment] 2015-10-20 09:05
@mandric please let me know which instance I can test this on

**Comment by mandric** [comment] 2015-10-20 11:25
@alxndrsn alpha.dev or lg.dev either one can or should be running latest develop branch.

**Comment by browndav** [comment] 2015-10-21 22:18
@mandric: Should @alxndrsn be code-reviewing this? If so, an update to the assignee would be great. Thanks.

**Comment by mandric** [comment] 2015-10-23 21:04
There are other places in the app where select2 fails in a different way.  Need to fix all the instances of select2.

**Comment by mandric** [comment] 2015-10-26 20:01
Will post some screenshots of bugs I see with select2 here.

**Comment by mandric** [comment] 2015-10-27 00:48
back button does not clear select 2
![screenshot_2015-10-26-20-17-04](https://cloud.githubusercontent.com/assets/25641/10746549/38aa5eaa-7c33-11e5-8848-5ff837be74e3.png)

**Comment by mandric** [comment] 2015-10-27 00:49
impossible to send a message, the `to` dropdown does not retract/clear.
![screenshot_2015-10-26-20-04-53]
(https://cloud.githubusercontent.com/assets/25641/10746551/3c6ecb98-7c33-11e5-8d85-3a2ffa4d2c18.png)

**Comment by mandric** [comment] 2015-10-27 00:50
Can't create a new place, CHP Area dropdown never retracts/clears.
![screenshot_2015-10-26-20-08-16](https://cloud.githubusercontent.com/assets/25641/10746575/7daf064a-7c33-11e5-9cb7-c73c0575643a.png)

**Comment by mandric** [comment] 2015-10-27 00:53
A weird thing that happens when back button is used and click event off the select2 div is fired... 
![screenshot_2015-10-26-20-12-41](https://cloud.githubusercontent.com/assets/25641/10746630/ff402b94-7c33-11e5-9895-a19aee1ed915.png)

**Comment by mandric** [comment] 2015-11-04 16:24
Code review passed over here https://github.com/medic/medic-webapp/pull/1520.

**Comment by mandric** [comment] 2015-11-04 20:08
i’ll have to take this one for acceptance testing because I don’t have a techno device.  We can open up more issues related to other devices or weird things related to select2 but just wanted to make sure we at least fixed the original issue as reported.

**Closed** 2015-11-04 20:25 UTC
Labels: 4 - Acceptance testing, Bug, Priority, Returned
