### ISSUE TITLE
Allow form upload through Configurations UI

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-webapp#3433] opened 2017-05-02 08:20 UTC
Currently we are uploading forms using command line scripts. UI interface to upload these will make it easier to quickly upload the files specially for non-technical users. This will also help users to work from any machine without the need for setting up the required libraries and packages.

**Comment by garethbowen** [comment] 2017-05-02 08:22
Duplicate of #1330

**Comment by alxndrsn** [comment] 2017-05-06 04:10
This is a part of #1330, but not the whole thing.

**Comment by alxndrsn** [comment] 2017-05-06 04:15
PR supplied implementing the basic feature.  There are some clear extensions mentioned in the PR, which may or may not be immediately important to tech leads.

**Comment by garethbowen** [comment] 2017-05-08 09:26
Merge away.

**Comment by sglangevin** [comment] 2017-05-16 22:34
This one seems to have translations missing:
![image](https://cloud.githubusercontent.com/assets/1286381/26131157/35cefedc-3a4d-11e7-95f6-ecd7edf760db.png)

**Comment by alxndrsn** [comment] 2017-05-17 06:07
Looks like the `translate` attribute is missing.  Fixing...

**Comment by alxndrsn** [comment] 2017-05-17 06:18
Should be fixed in `master` now.

**Comment by ngaruko** [comment] 2017-05-26 18:46
LGTM. Would like @bishwas-medic to have a look/test and confirm if this what he (and the tech lead community) was looking for....

**Comment by bishwas-medic** [comment] 2017-05-31 07:28
@ngaruko do we have a test instance online to test out this feature? Or should I try it out on my local machine?

**Comment by sglangevin** [comment] 2017-05-31 19:29
AT for v2.12.0 is on hold while we test v2.11.2 and release it. Once v2.11.2 is released, you'll be able to test the beta of v2.12.0. I'd prefer that this feature be tested using the release with which it will be included as opposed to testing in master.

**Comment by sglangevin** [comment] 2017-06-13 07:18
This doesn't support uploading of meta files (it only supports the old context file format). Meta files are now being used in most projects. These look like the below:
```
{
   "icon": "survey",
   "context": {
       "person": false,
  		"place": false,
  		"expression": "!contact && user.parent.type != 'district_hospital'"
   	}
}
```

**Comment by garethbowen** [comment] 2017-06-16 02:40
I think @alxndrsn meant to close this in favour of #3540 so I'll close it on his behalf now...

**Closed by garethbowen** 2017-06-16 02:40 UTC
Labels: 4 - Acceptance Testing, Returned

**Comment by sglangevin** [comment] 2017-06-19 21:07
Moving to ready now that #3540 has been done and passed AT.
