### ISSUE TITLE
or-output never shows initial value

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4111] opened 2018-01-19 15:27 UTC
`or-output` containing a value that is set in the initial `model` but never changed will never actually show any value.  This can be "fixed" by triggering a change notification on that model item.

cc @sglangevin

**Comment by alxndrsn** [comment] 2018-01-19 16:29
This is much more subtle than initially described, but fixable with:
```
angular.element('/*/div[id=report-form]/*/form').scope().$parent.form.output.update()
```

**Comment by alxndrsn** [comment] 2018-01-19 16:43
This should probably be filed as a bug upstream, but it's hard to isolate.  Visible in current version of `seguimiento` form for CiC.

**Comment by garethbowen** [comment] 2018-01-22 09:32
Scheduled for 2.15.0 so it gets merged to `master` and `2.14.x` before we branch again...

**Comment by alxndrsn** [comment] 2018-01-23 05:39
This has been merged to:
* `master`
* `2.14.x`
* `2.13.x`
and released in `2.13.2`.

**Comment by abbyad** [comment] 2018-01-24 23:06
I may have stumbled upon the source of this issue... otherwise it is a completely different issue :)

Values passed to a Standard form are not accessible on `2.14.0-beta.8`, although they are in `2.13`. We often use a [special `inputs` group](https://github.com/medic/medic-docs/blob/ae4165c1e0a0fa8f00f3d4532f713bf0c3a80a8c/configuration/forms.md#general-structure) to pass info to the form. We often hide that group from the user with a condition [see footnote], or by setting the relevant to `false` as done in the `seguimiento` form. Given that in 2.14 all values for fields that are not relevant are cleared, we can no longer access the default values passed to the form. Removing values when fields may be the same behaviour as ODK Collect, and now done in Enketo, but as we've seen from field visits can be a pain point since entered values are cleared.

Here is an [example form](https://github.com/medic/medic-webapp/files/1661972/issue_4111.zip), where the first page is non-relevant if accessed from a contact profile but relevant from the History tab. You'll see that the input values are not maintained when accessed from the contact profile. 

------------
We use relevant and not a `hidden` appearance so that forms started from the Reports page can see those fields to select the patient. The inputs group is therefore shown with `relevant="./source = 'user'"`. This is used in all Standard forms, as well as for many projects. We reuse the same fields to avoid having them in triplicate: one set for inputs, one for user entered fields, and a third as the coalesced version.

**Comment by abbyad** [comment] 2018-01-26 21:43
I wasn't able to reproduce or AT the issue with the info provided. @sglangevin, @alxndrsn do you have a simplified form showing this issue?

**Comment by abbyad** [comment] 2018-01-26 23:19
Rechecking the test form above, clearing non-relevant fields does not cause this issue. Only fields populated by a select2 are being cleared on page turn, other values and the select2 value itself are not cleared.

Again, this may be a separate issue, or not!

**Comment by abbyad** [comment] 2018-01-26 23:42
And it turns out only calculate fields are being cleared. We were using `calculate` fields with `.` for most input fields so that extra XML tags arent generated. If these are changed to `string` they are *not* cleared. This helps to characterize the issue that I was experiencing. Since this is new in 2.14, it is unlikely the same issue as reported here. Will open a separate issue.

**Closed** 2018-03-01 05:17 UTC
Labels: Enketo, Priority: 2 - Medium, Status: 5 - Ready, Type: Bug
