### ISSUE TITLE
Assign Family to User's place upon creation

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1392] opened 2015-10-05 20:08 UTC
As noted [here](https://github.com/medic/medic-webapp/issues/1259#issuecomment-137843956) an added family should automatically be assigned to the logged in user's assigned place - especially if they are a CHW/CHP. 

Otherwise a person can be added to another district, which has secondary effects like the additional contact filters reappearing.

This may fan out to other issues for other levels of the hierarchy.

**Comment by garethbowen** [comment] 2015-10-14 00:01
If the new contact ends up with a `parent` field which has a string value we go ahead and fetch the parent from the database, so when configuring the form you just need to ensure this field is populated. 

To help populate it the `inputs` group has new fields: `_user_facility_id` and `_user_id`. The former is the user's configured place, and the latter just seemed like useful information to have. So if you configure something like the following it should bind the user's facility into the parent:

```
<bind calculate="/data/inputs/_user_facility_id" nodeset="/data/clinic/parent" type="string"/>
```

**Comment by alxndrsn** [comment] 2015-10-14 08:08
Looks fine, but can we stop using `facility` to mean `place`?

**Comment by garethbowen** [comment] 2015-10-14 19:26
Fair enough. The field is called `facility_id` on the user so I reused that name, but we should rename it at some point.

**Comment by abbyad** [comment] 2015-10-23 14:36
Assigning to @joshnesbit for acceptance testing.

**Comment by joshnesbit** [comment] 2015-10-23 14:55
Logged in as demo on lg.dev (in firefox): When I create a new family, the family is not assigned to a catchment area. Showing the screenshot with the new family (Kate Rockefeller Family) and the higher-level place icon showing in the FAB:

![screen shot 2015-10-23 at 07 52 42](https://cloud.githubusercontent.com/assets/377216/10695956/71199308-795b-11e5-9562-8d0df26aab82.png)

**Comment by joshnesbit** [comment] 2015-10-23 14:57
In case it's helpful, here's another screenshot when I go in to edit that family:

![screen shot 2015-10-23 at 07 56 26](https://cloud.githubusercontent.com/assets/377216/10696001/b020c0bc-795b-11e5-919e-a00759f7d3ca.png)

**Comment by abbyad** [comment] 2015-10-29 19:27
Returning this to be looked at again.

**Comment by garethbowen** [comment] 2015-10-29 19:46
The instance wasn't configured to bind the facility_id. Assigned to @abbyad for acceptance testing.

**Comment by abbyad** [comment] 2015-10-29 21:20
Still not able to get the parent field to be populated, using this [form](https://lg.dev.medicmobile.org/_utils/document.html?medic/form%3Acontact%3Aclinic%3Acreate)

In the xform I have: `<bind calculate="/data/inputs/user/facility_id" nodeset="/data/clinic/parent" type="string"/>`

and have added the following in the model (not sure if it is necessary):
```
<data id="NFAM" version="2015-10-21">
          <inputs>
            <user>
              <facility_id/>
            </user>
          </inputs>
```

**Comment by abbyad** [comment] 2015-10-29 21:27
I was logged in as admin, who wasn't assigned to a place.... but now testing again after setting the place worked well.

Reassigning to @joshnesbit for final acceptance testing.

**Comment by abbyad** [comment] 2015-11-01 18:40
Both @joshnesbit and I are having trouble getting this to work for the demo user (using FF), but it works well for the admin user (using Chrome). Returning to take a closer look at this.

**Comment by garethbowen** [comment] 2015-11-01 20:19
I'm getting this when loading the Add Family form on lg.dev:

```
inbox.js:14 Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:9690)
    at da (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:10172)
    at Ba (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:13956)
    at Aa (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:13853)
    at za (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:13574)
    at Ca (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:14269)
    at Da (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:14303)
    at a (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:30:2890)
    at e (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:30:7545)
    at a.filter.e.FormatDate (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:30:8685)
```

**Comment by garethbowen** [comment] 2015-11-01 22:38
I think this needs #1490 - the prepopulation for contacts isn't complete.

**Comment by garethbowen** [comment] 2015-11-02 00:00
This was broken by the change that included a nested `user` rather than `_user_facility_id` in the inputs. By switching to use the JSON to XML code in the Enketo service as described in #1490 the `/inputs/user/facility_id` should be available and the existing code and configuration should just work.

**Comment by abbyad** [comment] 2015-11-10 12:44
Reopening and returning as I am seeing this problem on 2318.

It may be a config issue, but nothing can't tell what has changed to break this since it still has `<bind calculate="/data/inputs/user/facility_id" nodeset="/data/clinic/parent" type="string"/>`. Given the demo sessions today, I thought it is better to have someone else take a look too.

**Comment by garethbowen** [comment] 2015-11-11 03:36
This works well locally with that form. I'll try against lg.app tomorrow.

**Comment by abbyad** [comment] 2015-11-11 12:45
I know that Josh reported that he was not having this issue, yet I can reproduce consistently with the mobile app using demo user (lg.app). Let me know if you want me to debug further to figure out how/why my setup is different and causing this issue.

**Comment by garethbowen** [comment] 2015-11-11 20:19
@abbyad This is possibly due to bad replication or corrupt data in your local pouchdb. Specifically if your database doesn't have a document at the demo users facility_id.

To check for this, log in as "demo" on your phone, go to the contacts tab and make sure you can see "Busia CHP Area1".

If you can see this contact then it's something else. To get more information please create a family again and if it still doesn't get the parent attached let me know the new family's ID and I'll have a look at the data.

**Comment by abbyad** [comment] 2015-11-12 14:21
I don't see Busia CHP Area1 in the contacts list (due to #1493) but I *can* access it from the link in a family.

I created a [new family](https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/1D2F0828-AFA1-9508-8A13-1CB09ABC961F) again, and it the `parent` place was [not assigned](https://lg.app.medicmobile.org/_utils/document.html?medic/1D2F0828-AFA1-9508-8A13-1CB09ABC961F):
![image](https://cloud.githubusercontent.com/assets/789512/11120457/c3e00974-891d-11e5-857f-45e4140398cb.png)

**Comment by garethbowen** [comment] 2015-11-12 21:26
This works in the browser (desktop and tecno) but not in the app. Very strange, but at least it's reproducible!

**Comment by garethbowen** [comment] 2015-11-12 22:36
The bug is somewhere in the prepopulation code - in recent Chrome it works, but in Chrome 30 the prepopulation data is always `undefined`.

**Comment by alxndrsn** [comment] 2015-11-13 10:04
LGTM

**Comment by alxndrsn** [comment] 2015-11-13 15:45
![Uploading Screen Shot 2015-11-13 at 16.45.05.png…]()

**Comment by alxndrsn** [comment] 2015-11-13 15:45
<img width="1280" alt="screen shot 2015-11-13 at 16 45 05" src="https://cloud.githubusercontent.com/assets/191496/11150020/f3750262-8a25-11e5-8932-42486a050e91.png">

**Comment by abbyad** [comment] 2015-11-13 15:48
Aside from the above bug mentioned by @alxndrsn, the user's place is now properly set for contacts created on the Y4.

**Comment by alxndrsn** [comment] 2015-11-13 15:55
@garethbowen please review commit above which fixes bug shown in screenshot

**Comment by garethbowen** [comment] 2015-11-15 20:35
Good spotting.

**Closed by garethbowen** 2015-11-15 20:35 UTC
Labels: 4 - Acceptance testing, Feature Request
