### ISSUE TITLE
API error messages are not getting propagated to client

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2994] opened 2016-12-07 19:22 UTC
Post a message via curl without the proper fields and you get a 500 Server Error but the body of the error does not get passed through, it only is displayed in log file.

```
$ echo 'message=foo' | curl -d@- $COUCH_URL/api/v1/records
Server error
```

/srv/storage/gardener/logs/medic_medic_medic-api1.log:
```
2016-12-07T16:34:27.279Z - error: Server error:
 Missing required field: from
```

**Comment by nice-snek** [comment] 2017-04-26 05:46
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment] 2017-04-27 00:31
Still a bug.

**Comment by abbyad** [comment] 2017-08-09 18:06
Just noting that we are running into this now while getting a 500 setting up Collect for Standard.

It would be useful to get more info from the 500, since falling back on accessing logs means longer turnaround for fixes because it depends on tech lead or dev team to investigate.

**Comment by garethbowen** [comment] 2017-08-09 21:11
Scheduling - this is a PITA.

**Comment by sglangevin** [comment] 2017-08-09 21:30
@garethbowen do you also have some time to look into the issue from medic-projects that is referenced? The partner is planning to do training this weekend and is blocked by that bug (https://github.com/medic/medic-projects/issues/2626)

**Comment by alxndrsn** [comment] 2017-08-25 12:25
Personally I think the current behaviour is correct, as exposing random error messages to clients is a good way to leak things unexpectedly.

However, have a PR.

**Comment by garethbowen** [comment] 2017-08-27 22:02
I now see your comment and agree fully. I think there is probably a safe solution if we use an additional error property for `responseMessage` or something, so we can include whatever we want for the log, and some safe and user friendly message for the response body. What do you think?

**Comment by alxndrsn** [comment] 2017-08-29 09:30
So e.g. in the example the issue was created for,
```
return callback(new Error('Missing required field: ' + k));
```
would become
```
var message = 'Missing required field: ' + k;
var err = new Error(message);
err.responseMessage = message;
return callback(err);
```
Or some kind of constructor such that the following contains a publishable message:
```
return callback(new ClientShareableError('Missing required field: ' + k));
```
?

**Comment by garethbowen** [comment] 2017-08-29 10:06
Yeah either of those would work. It would be nice to start creating custom Error types!

**Comment by alxndrsn** [comment] 2017-08-29 10:15
Trying to think of a nice name that's not really long.  `PublicError`?  `ExposableError`?  Any ideas?

**Comment by garethbowen** [comment] 2017-08-29 10:17
`UserFacingError`? IDK. It's not easy...

**Comment by sglangevin** [comment] 2017-08-31 13:29
Assigning to @ngaruko for AT.

**Comment by ngaruko** [comment] 2017-08-31 22:42
Tested this with latest build...Two issues:
a) when one (or all the fields) is empty, the message is sent successfully. Is this expected behaviour?
![image](https://user-images.githubusercontent.com/6979995/29948083-19e77696-8f01-11e7-973c-4b64d0b02529.png)
 and in the app:
![image](https://user-images.githubusercontent.com/6979995/29948094-25249868-8f01-11e7-8496-4c48018930d1.png)
  
all fields empty still works: 
![image](https://user-images.githubusercontent.com/6979995/29948317-47644bfc-8f02-11e7-83a3-b7187e56ea6d.png)

b) when there the `from` field is left out, we still have only `server error` sent to client?
![image](https://user-images.githubusercontent.com/6979995/29948129-57187b28-8f01-11e7-9c15-bf11490849e2.png)
 
Did this fix get pumped to medic-webapp @alxndrsn ? and has a) to do with this issue or a different issue altogether?

**Comment by alxndrsn** [comment] 2017-09-01 08:19
> Did this fix get pumped to medic-webapp?

The change was in api, so you'll need to make sure you've got the latest `master` checked out.

**Comment by ngaruko** [comment] 2017-09-03 22:57
Returning because somehow it seems not to be propagating to client.
Server error:
![image](https://user-images.githubusercontent.com/6979995/30007125-e3b81370-915b-11e7-95a5-10aecaef4140.png)
 
but in the client:
![image](https://user-images.githubusercontent.com/6979995/30007132-fc1c1f9c-915b-11e7-9a8f-d669e0b7358c.png)

Running the latest `master` with the commit (https://github.com/medic/medic-api/commit/999bb30ac0e189d73d1db166e38c8b392ffd7401) included:
![image](https://user-images.githubusercontent.com/6979995/30007296-c2086dde-915f-11e7-9f76-c3d5a02b01ad.png)

**Comment by alxndrsn** [comment] 2017-09-04 13:28
Thanks @ngaruko.  Let's try again 😃

**Comment by garethbowen** [comment] 2017-09-04 21:10
Merged and api bumped in master.

**Comment by ngaruko** [comment] 2017-09-04 23:15
LGTM . Thanks @alxndrsn 
![image](https://user-images.githubusercontent.com/6979995/30039906-783f6294-922b-11e7-8f5c-b9234ecc2215.png)

**Closed** 2017-09-04 23:16 UTC
Labels: medic-api, Priority: 2 - Medium, Status: 5 - Ready, Type: Bug
