### ISSUE TITLE
Improve Android back button flow to account for deeper navigation in the person & places tab

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2820] opened 2016-10-11 14:01 UTC
There has been work (see: #1564) to improve how the back button works on Android. There has been additional work in #1565 that stalled earlier in 2016.

Specifically for the people and places tab, there is a gap in navigation rules that has arisen because we can navigate up and down the hierarchy, and into reports and tasks. More specifically, back tends to take you back to the people & places list, even if you are more than one hop away from it.

For example:
- You are a CHW viewing the People & Places list
- You tap a family
- You tap a person in that family
- You realise you tapped the wrong one, and tap the back button
- Currently this goes back to the list, whereas it should go back to the family

Similarly:
- You are a CHW viewing the People & Places list
- You tap a family, and see their list of tasks
- You tap a task to start editing it
- Realising you tapped the wrong task, you tap back
- Once you've confirmed you wish to no longer edit this task, you get put back to the list, whereas it should go back to the family

**Comment by SCdF** [comment] 2016-10-18 14:10
So I took a stab at this in a branch. It's a two steps forward one step back sort of deal unfortunately. Nearly all of the existing back button logic is retained, which is good. More complex navigation situations default to the standard web back functionality, so things hitting back after People List -> Area -> Family -> Person -> Report -> Edit Report will work backwards up each step correctly. Which is also good.

**However**, this has introduced an issue where after the completion of an enketo form (such as editing a person or report), hitting back will take you to the first page of the enketo form you just edited. Ideally you'd expect the back button to skip over enketo forms if you're not currently in one, e.g. if your navigation is People List -> Family -> Add Person -> Complete Add Person to now be viewing the  New Person. hitting back:
 - In master, back goes back to the People list
 - In the branch, back goes back to the start of the new person form
 - Ideally, back would go back to the Family

Unfortunately, I'm not sure what the best way of fixing this is honestly. After the tweaks I made this kind of thing gets really complicated really quickly. I will definitely brainstorm with other devs on it, but there is no clear path to me right now.

It has also been suggested that we could simply aim for consistency between the web and the mobile app, and ditch all custom android navigation rules (with the probable exception of a couple of minor ones, like making sure we never quit / navigate back to the login page). While I think consistency is definitely something worth aiming for, I'm not convinced it applies here, in this way:
 - On mobile the back button is primary form of navigation, so it going through a bunch of useless or unintuitive locations is not a great experience. On tablet / desktop you can always tap a specific link / button to go where you want to go.
 - On mobile the back button can be the *only* form of navigation to certain places, and so if you can create a massive navigation chain it could be a huge pain to get back somewhere if hitting back wasn't always getting you a step "closer" (this is actually an argument against the proposed changes I've made in general, since it's no longer clear how many taps it takes to get from a particular place back to the top menu. I think it's pretty well bounded at the moment though).
 - One form of consistency is between the web experience on every platform. Another is keeping consistency with your platform (ie Android).

In other news, testing these various rules led me to find a couple of bugs that exist regardless of these changes, which I'll be raising shortly.

**Comment by garethbowen** [comment] 2016-10-18 19:12
I think the crux of this issue is getting our routing model correct. Simplistically it sounds like we want the android back button to go up not back in the conventional sense. This maps quite nicely to taking the last route of the URL, eg: `/tasks/{uuid}/submit-report` -> `/tasks/{uuid}` -> `/tasks` -> `/`. This is easily achievable with `$state.go('^')`.

I think this will require significant changes to our routing to ensure that each navigation down the tree adds to the URL rather than changing it.

We have an issue to allow submitting a form while keeping the contact in context which could be worked on at the same time (#2763) and similar ones to do with separating the LHS and RHS (#1368 #2226 #1975 #1565). If we decide to rework the routing we should also solve these issues.

My proposal is for a URL scheme something like: `/{tab}/{id}/{action}`

The `tab` is identical to now and sets the context (eg: colour the bar salmon for People). In desktop this defines what's shown on the LHS (eg: the People list).

The `id` is identical to now and sets the item the user is working on (eg: Sally). This wouldn't actually cause anything render anything on its own but just sets the context ready for the action.

The `action` defines what's shown on the RHS (eg: view item details, submit report, view report, etc).

Examples for mobile:

| URL | Desktop | Mobile | Mobile back button action |
|-------|------|------|
| / | Tasks list on LHS, no selected task on RHS | Task list  | Closes/minimises the app |
| /contacts | People list on LHS, home place on RHS | People list | / |
| /contacts/abc | People list on LHS, `abc` place on RHS | `abc` place | /contacts |
| /contacts/abc/view-report-xyz | People list on LHS, `xyz` report on RHS | `xyz` report (with People colouring) | /contacts/abc |

Open dropdowns and modals will be closed before navigating up the tree just as they are now.

I believe this is consistent with the android style guide. Things it can't handle include: back button navigating to persons parent (instead it'll go to the person list), back button navigating to previous person if you've selected a child (instead it'll go to the person list). Again, I believe my proposal is the expected behaviour.

I like this because it doesn't have confusing edge cases or inconsistencies for the user. Also it solves the issue of separating the RHS and LHS controllers so we can show anything page on the RHS of any list on the LHS.

No doubt this will need further thought and discussion!

**Comment by sglangevin** [comment] 2016-10-19 07:28
@garethbowen I like the overall concept of this and it's cool that we could accomplish viewing reports and/or tasks in the People tab with this new way of doing things.

That said, as a user of the Android app, one of the more frustrating things that I encounter is the fact that clicking back from a person's page takes me all the way back to the list of families. If I have drilled down from my area to a family to a family member and I hit back, I am back at the list of families and have to then find the family again. It's very easy to get lost when you have a long list of families and I don't expect that the back button will take me all the way to the list because the previous page was the family page. This problem is exacerbated if you are logging in higher up in the hierarchy (as a branch manager, for example).

I think this issue is one of the remaining UX issues in the app that is confusing to users and I think we should do something about it. I would keep your proposal as is, but add a special case for the People tab navigation so that we can go up in the people hierarchy, from family member to family to the list. I'm not sure if this can be accommodated in the system that you have described, but I think it's important.

**Comment by garethbowen** [comment] 2016-10-19 08:16
It can be done, but I worry it'd feel inconsistent with how it's implemented everywhere else.

**Comment by sglangevin** [comment] 2016-10-19 08:24
I don't see this as inconsistent because we don't have anything that is equivalent in any other tab. In Tasks, you open a task and then you click back to go back to the list. In Targets, there is just 1 screen. In History, you open a report and then go back to the list.

The People tab is actually a special case as it functions very differently from all other tabs. The UX that is there is very confusing to the user because you are several levels deep and then you go back to the list. We need to be able to handle the special case of the People tab in a way that makes sense to users.

**Comment by garethbowen** [comment] 2016-10-19 08:26
> We need to be able to handle the special case of the People tab in a way that makes sense to users.

Of course.

What if you click parent, child, parent, child, parent, child, then back, back, back. What page are you on? Does back on People always just go to the parent? Or does it go back in the web sense?

**Comment by sglangevin** [comment] 2016-10-19 08:31
I would assume that back goes up the hierarchy. So if you are logged in as a CHW and are on a family member page, the first back goes to the family page, the next back goes to the LHS (list of families) and the third back goes to Tasks tab. If you are logged in as a branch manager and are on a family member page, the first back goes to the family page, the next back goes to the area page with a list of families and the third back goes to the LHS list of areas.

I don't think it needs to go back in the web sense, but others may disagree.

**Comment by SCdF** [comment] 2016-10-19 12:01
> I believe this is consistent with the android style guide. Things it can't handle include: back button navigating to persons parent (instead it'll go to the person list), back button navigating to previous person if you've selected a child (instead it'll go to the person list). Again, I believe my proposal is the expected behaviour.

Firstly, this ticket is an attempt to solve precisely what your suggestion intentionally doesn't solve. While a more understandable routing model is desirable, I don't think it helps this issue by itself.

Secondly, consistency is very much in the eye of the beholder. If I use other android apps that allow drilling down, they behave in the way that I describe above. Some examples:
 - In Twitter, if you tap a tweet, then the user, then followers, then a user, then followers, then a user, then a tweet of theirs, then the list of likes, then a person who liked it… hitting back walks you back up this chain, it does not just you to your timeline
 - In Facebook Lite, performing a similar set of steps (tapping on posts and users and friends etc) again walks you back up the tree
 - In Relay for Reddit similarly, links to other posts inside reddit stack on top of each other, and you reverse the way you came

IDK about twitter or reddit (ha!), but I would be pretty happy presuming our users have used Facebook Lite (the Lite edition especially, as you can only download it in Africa, and it's made for crappier networks).

**Comment by garethbowen** [comment] 2016-10-19 18:38
I'm mostly concerned about internal consistency as, like you say, there's not a lot of consistency with other android apps.

**Comment by SCdF** [comment] 2016-11-14 17:56
Another thought would be to drop the android work entirely and replace it with navigation manipulated through the history api. That api isn't amazing though, we'd need to have a play and see if we can solve the problems the android work solves using it.

**Comment by diannakane** [comment] 2016-11-15 09:57
Changing to nice-to-have since this isn't directly related to SMS workflows. cc: @abbyad

**Comment by garethbowen** [comment] 2016-11-28 20:36
Nobody in the dev team seems to have a clear idea of what's required to close this issue. As it's a nice to have I'm removing it from this milestone.

**Comment by nice-snek** [comment] 2017-04-18 15:41
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment] 2017-04-18 16:56
> Nobody in the dev team seems to have a clear idea of what's required to close this issue. 

No clearer picture has emerged: closing.

**Closed by alxndrsn** 2017-04-18 16:56 UTC
Labels: Contacts, Needs Triage, Nice To Have, UI/UX
