### ISSUE TITLE
{{patient_name}} not found when patient was created by xform

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3419] opened 2017-04-26 17:57 UTC
Reproduce : 
 - create patient through webapp UI (not SMS), and watch it get a patient ID
 - submit a report about patient by SMS (e.g. new pregnancy)
- The patient is found, but the {{patient_name}} in the generated messages is blank.

See below, should be 
`Thank you for registering the pregnancy for {{patient_name}} ({{patient_id}}) ...`
`Did {{patient_name}} attend her ANC visit? When she does ...`
![image](https://cloud.githubusercontent.com/assets/911434/25448823/1153a7f8-2aba-11e7-9777-8bce013bff42.png)

**Comment by estellecomment** [comment] 2017-04-26 17:58
Both created `person` docs have a `name` field so that's not it... Maybe related to fetching the `{{patient_name}}` through registrations, and not finding a registration since the patient was not created by SMS.

**Comment by abbyad** [comment] 2017-04-26 18:05
That almost certainly it, because you were only able to access info from the registration, not all the info from the person's doc.

**Comment by sglangevin** [comment] 2017-04-26 18:11
Since every person has a `person` doc, regardless of how they were created (by SMS using the N form or using an xform in the web app), seems like the ideal thing to do would be to fetch any information directly from the `person` doc. I'm guessing that isn't a quick fix, though.

**Comment by SCdF** [comment] 2017-04-26 18:32
> Both created person docs have a name field so that's not it... Maybe related to fetching the {{patient_name}} through registrations, and not finding a registration since the patient was not created by SMS.

I'm not clear about the forms that you're using, but it shouldn't need to find a registration, since what you're actually doing here is creating a registration (a pregnancy *is* a registration, unless I've misunderstood).

**Comment by abbyad** [comment] 2017-04-26 19:51
It doesn't need the registration per se, but does need patient info which was previously obtained from the registration report.

**Comment by SCdF** [comment] 2017-07-03 15:44
I've started looking at this again. It's not just SMS, at least not in my existing config:

![image](https://user-images.githubusercontent.com/583851/27799869-ccb9270a-600e-11e7-8a1f-57b161d5870a.png)

However, it did work via SMS when I registered them with the `N` SMS form.

**Comment by sglangevin** [comment] 2017-07-03 16:36
@SCdF it had been working for people registered with the `N` SMS form. This issue is specifically for people who are created in the web app using an xform and assigned a Medic ID, then have a pregnancy registered by someone using SMS.

**Comment by SCdF** [comment] 2017-07-03 16:38
@sglangevin there seem to be a few issues. The one I just found in the image above is due to the work done to pull parents out (ie it couldn't find {{contact.name}} in the above message because the contact wasn't hydrated).

I'll raise a separate bug for that and then try to look into this one specifically after fixing that one.

**Comment by sglangevin** [comment] 2017-07-03 16:43
And that is what happens when I look at screen shots before drinking coffee! SGTM.

**Comment by SCdF** [comment] 2017-07-03 16:45
FWIW I've been at work for hours and I'm pretty sure what I just said is the problem is not actually the problem… so… but there *is* a problem! That much is clear…

**Comment by SCdF** [comment] 2017-07-03 16:53
Uhm, OK maybe that issue is data related on my end? It's hard to tell in a development environment. The problem with the screenshot above is that `{{contact.name}}` is supposed to actually be the "clinic"'s contact's name, where clinic is defined by the first parent of the doc's contact that is of type clinic. You can see the logic [here](https://github.com/medic/medic-sentinel/blob/master/lib/messages.js#L83-L94).

That doesn't really make sense to me, but I presume it's something I don't understand about the hierarchy.

So unless that sounds wrong to you I'll ignore it and move back to the original issue.

**Comment by sglangevin** [comment] 2017-07-03 17:01
That does sound right to me - you should be getting the primary contact of the clinic. In the hierarchy in this case, clinic should be CHW Area and the primary contact of the CHW Area should be the CHW.

**Comment by SCdF** [comment] 2017-07-04 14:00
When we generate details that can be passed to the message utils we essentially smush this document and all prior registrations for that patient together into one object. The problem is that this message requires `fields.patient_name` from the original registration. Except when you create a user using the UI it's not technically a registration.

The change I have adds the person document to this collection of details as the `person` property. This allows for a more standard way to reference things like the patient's name: all patients have a person document, only some will have a patient registration.

This allows tech leads / configurers to change instances of `{{patient_name}}` with `{{person.name}}`.

For example, translations like this:
```
Thank you for registering the pregnancy for {{patient_name}} ({{patient_id}})…
```

Should now look like this:

```
Thank you for registering the pregnancy for {{person.name}} ({{patient_id}})…
```

Note: this is currently not available everywhere, just inside the `registration` transition. I did this because this is the only place where we're pulling in previous transitions to use their data in messages, so it's the only place this specific bug is exposed. It would be a nice thing at some point to standardise this better, but that's more of a breaking major revision kind of thing.

**Comment by SCdF** [comment] 2017-07-04 14:13
@alxndrsn check out the PR: https://github.com/medic/medic-sentinel/pull/137

Also note that I've updated translations for that one message that was causing problems, in [English](https://github.com/medic/medic-webapp/commit/1d452d2c195c2325e7e41da024eec7d43a2efa08), [Hindi](https://github.com/medic/medic-webapp/commit/8947fec72b11828a09852764fa1f6ba360fbb266), [Indonesian](https://github.com/medic/medic-webapp/commit/bfb15bf6b9bb7fb88650917e19f2e4c6ea0f59e3) and [Swahili ](https://github.com/medic/medic-webapp/commit/af4ad76f56603b7e6837aa551eecba962d88af01)

**Comment by SCdF** [comment] 2017-07-04 14:15
@sglangevin / @garethbowen  so this is an interesting documentation point. This is very much a changelog sort of change, I don't think there is anywhere specific to log this. How should we deal with this? Pulled out section at the top of the release notes?

**Comment by garethbowen** [comment] 2017-07-04 21:00
@SCdF Yes definitely. Add a 2.13.0 title with a TBD date and add this as a breaking change.

The other option is to alias patient_name as patient.name so existing configurations continue to work. This would be my preferred approach.

**Comment by sglangevin** [comment] 2017-07-04 21:26
Yeah, it would be much better if we can keep this backward-compatible and then work to update existing configurations.

**Comment by SCdF** [comment] 2017-07-05 06:20
@garethbowen / @sglangevin I considered that, but this doesn't actually break anyone's configuration, it just makes it possible for it to work (if that makes sense). I'm not taking `patient_name` away from places that already have it.

Happy to alias though.

**Comment by SCdF** [comment] 2017-07-05 10:14
@garethbowen I think Alex isn't going to be around for a bit: over to you to review :-)

**Comment by garethbowen** [comment] 2017-07-05 22:41
Back to you @SCdF

**Comment by SCdF** [comment] 2017-07-06 07:53
@garethbowen I added the tests you asked for, take another look

**Comment by garethbowen** [comment] 2017-07-06 10:06
Merged. I'll leave it up to you to bump the submodule.

**Comment by sglangevin** [comment] 2017-08-02 20:16
This is working for the auto-reply but not for the scheduled reminder messages. Screenshot from standard.app:
![image](https://user-images.githubusercontent.com/1286381/28892955-963c2e92-7784-11e7-8012-ad993ffc2336.png)

I've changed the translations so that the reminder schedule uses `person.name` instead of `patient_name` but that didn't seem to help. Am I missing something on the config side? Assigning back to you, @SCdF.

**Comment by SCdF** [comment] 2017-08-07 11:57
Looking into this now. It looks like there are multiple entry points for templating a message and I didn't catch them all. I'll look at cleaning that up

**Comment by SCdF** [comment] 2017-08-08 11:32
Fixed for scheduled messages, see: https://github.com/medic/medic-sentinel/pull/156

**Comment by estellecomment** [comment] 2017-08-08 15:30
Couple nits, but LGTM!

**Comment by SCdF** [comment] 2017-08-09 08:35
Merged into master and 2.13.x.

**Closed by SCdF** 2017-08-09 08:35 UTC
Labels: 3 - Code Review, Bug, Returned

**Comment by sglangevin** [comment] 2017-08-10 00:55
Working well in 2.13.0-beta.3. Moving to ready!

**Comment by SCdF** [comment] 2017-08-30 14:11
NB: After some more code investigation on another ticket (#3838) I've decided to drop support for `{{person.name}}`. We're only going to support `{{patient_name}}` instead, as we always did.
