### ISSUE TITLE
Incorrect list of message contacts

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1162] opened 2015-08-18 20:26 UTC
Possibly related to #1161, the items in the left don't match properly, as seen here:

![image](https://cloud.githubusercontent.com/assets/789512/9341772/db4343ce-45c5-11e5-8ec1-29ed5c84782b.png)

**Comment by garethbowen** [comment] 2015-08-26 04:38
Cannot reproduce. I suspect it's been fixed with #1161

**Closed by garethbowen** 2015-08-26 04:38 UTC
