### ISSUE TITLE
Add a screen that shows messages queued to be sent 

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#649] opened 2014-10-08 22:23 UTC
It would be nice to see your outgoing message queue, say before you decide to plug in a gateway.

**Comment by diannakane** [comment] 2016-04-21 20:19
Related to #1849

**Comment by sglangevin** [comment] 2018-06-27 21:33
Consider having a button to show the outgoing message in English if it is being sent in another language.

**Comment by sglangevin** [comment] 2018-06-27 21:47
Related: medic/medic-projects#2816, medic/medic-projects#2719

**Comment by garethbowen** [comment] 2018-08-13 03:32
Related: #3249

**Comment by amandacilek** [comment] 2018-09-12 16:52
For reference, pasting a summary of a few clarifications discussed with Diana and Jill:

*Do we include outgoing messages from the Messages tab, or just those from the Reports tab?*
- Although we were not initially considering including messages from the Messages tab, we do think that they are a helpful inclusion. They are part of the story of what is happening with the gateway.
- Spam loops should hopefully be avoided because we are including outgoing messages only
- In regards to auto replies - for now, let’s include these in the list and see how it goes. Although we are curious how easy it would be to filter them out.

*Will not send tab - do we include past due date or future due date or both?*
- Ideally, we’d like to include both. If forced to choose, we think displaying messages from the past only is the most helpful. PMs might often want to answer the question “why didn’t X message get delivered?” and they can only answer that by checking both the pending tab (if something has stalled or failed) and by checking messages that were not sent for other reasons such as being muted. Future messages are also helpful to see, especially once we give users the ability to "mute" a scheduled message - we don't want a newly muted message to completely disappear - it should be somewhere accessible. In general, we think ALL message status types should live on this page somewhere.
- Our preference is to add a fourth tab so that we have “Will not send” for all future dates, and “Did not send” for all past dates. We like the tabs because they in essence allow us to “filter” and narrow down the lists without actually having a filter function.

*What to do in cases where recipient phone number doesn’t exist*
- Confirmed that we’re fine just keeping these for now. Jill thinks we have a Google phone number library that we check phone numbers against, and is not sure this will be much of an issue in real life. Let’s see how it goes and address separately if it becomes an issue - at that point we might want to create a new ticket to make this a new status type (as it is a different error, and useful to differentiate from the others).

**Comment by diannakane** [comment] 2018-09-13 00:05
For my own understanding...
-- will messages which are muted and appear on the "do not send" list switch over to the "scheduled/due" list when the mute status is cleared? And only those after the time when the schedule was unmuted? (i.e. unmute doesn't apply to the entire past schedule, only future messages)
-- for how long do we try again to send failed messages and when do they permanently fail? 
-- did you all run the naming of the tabs and statuses by a few other teammates and users?

**Comment by amandacilek** [comment] 2018-09-13 00:14
> Will messages which are muted and appear on the "do not send" list switch over to the "scheduled/due" list when the mute status is cleared?
Yes, my understanding is that they would switch over to the "Scheduled" tab, provided that the due date is still in the future. If a muted message is unmuted, but the due date is in the past, it should remain in the "Did not send" tab. The rules for which message appears on which tab are based on the message status. A given message may and should move across tabs as it's status changes.

> For how long do we try again to send failed messages and when do they permanently fail?
My understanding is that we do NOT try again. As soon as a message has reached the status "failed" it will not be retried. In the future we would like to add a "resend" button but that has been removed from the MVP.

> Did you all run the naming of the tabs and statuses by a few other teammates and users?
Not explicitly, but during conversation the only status name that was mentioned as confusing was "Delivered". People have a hard time understanding the difference between "Sent" and "Delivered". We suggested that it might be clearer to change "Delivered" to "Received" but I did not include that in this ticket, as it seemed like a separate issue.

**Comment by diannakane** [comment] 2018-09-13 00:28
Thanks for those clarifications!

The wording that trips me up is "due" in the context of messages that live in the past (because they are no longer due, and arguably the failed ones are "overdue" but cannot be rectified), and "failed" as a status on as differentiated from the tab "will not send" (because neither have been sent and neither will... hence my question about re-trying). I'm OK hearing that I'm in the minority here and don't need to make an issue of it if these terms are clear to others.

**Comment by amandacilek** [comment] 2018-09-13 00:51
Here is why we like having "failed" messages grouped together with other pending message states: We anticipate that the "Due" tab will be the tab where PMs spend the majority of their time. They can go to this tab to either verify that all messages are properly moving quickly through the states, or they can be alerted to messages that have failed or been stuck in a pending state for a long time, indicating a potential gateway issue or some other problem. "Failed" is one of the statuses that PMs care about _most_. If we moved "failed" to a different tab, then PMs would have to toggle between multiple tabs to get the full picture of the health of the system.

Your point is valid about the wording "Due" not quite fitting all of the content on that page. All I can say is we're all well aware that this is not a perfect solution. We've had countless back and forth conversations about how many tabs there should be, what should be on them, and what the tabs should be called, and we all compromised to get here. "Due" vs "Overdue" is a tricky concept, because in reality almost every message will take _some_ time to go through the process and be delivered, so I think they will often be past the exact due date/time even when progressing normally through the pending states...Do you have a suggestion for a name besides "Due" without splitting off to make a separate "Overdue" tab?

In the end, we'd just like to get something out, let people start using it, and gather feedback from there to inform future tweaks or iterations. I don't think changing the name of a tab is too difficult down the road!

**Comment by amandacilek** [comment] 2018-09-13 00:54
> because neither have been sent and neither will

On the contrary, "failed" messages DID attempt to send. Here is the full definition of "failed":
**The sending attempt failed.** Sending will not be retried without user intervention.

**Comment by ngaruko** [comment] 2018-11-22 06:12
LGTM. There is an error message showing on the `Will not send` tab. It might be related to #4899 . So, I will go ahead and close this (as a feature done) and keep #4899 open.

![image](https://user-images.githubusercontent.com/6979995/48884558-03091c80-ee60-11e8-82fe-a30451ee4c66.png)

**Comment by dianabarsan** [comment] 2018-11-22 07:57
Reopening to fix bug related to deleted patients causing messages list to error (https://github.com/medic/medic-webapp/issues/4899#issuecomment-440941632)

**Comment by dianabarsan** [comment] 2018-12-04 09:15
@ngaruko The fix for the deleted patients has been merged into `master` (3.4), with no intention to backporting to 3.3. I deleted the report that caused the error in Admin message queue (id `8cb9904d-cc22-485a-8ef0-0c3d2a1372e2`).

**Comment by dianabarsan** [comment] 2018-12-05 09:53
@ngaruko this issue is part of 3.3.x, not 3.4.x.

**Comment by ngaruko** [comment] 2018-12-12 14:32
LGTM

**Closed by ngaruko** 2018-12-12 14:32 UTC
Labels: Priority: 2 - Medium, Type: Feature
