### ISSUE TITLE
Admin performance on lg.app has regressed

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2744] opened 2016-09-14 18:40 UTC
Navigating through the app is a bit choppy and unreliable. Sometimes, pages load at a normal speed and other times they load slowly - it's inconsistent. In addition, when editing a CHP Area, the speed of search results is highly variable, from within 10 seconds to a few minutes. Futon performance also seems to be affected, though not consistently. I'm seeing speeds of about 10 seconds for the server to respond to requests from the browser.

Can we look into ways to improve performance or reconsider the possibility of having a clone for admin use? Performance has gotten too slow for users to edit contacts.

**Comment by sglangevin** [comment] 2016-09-14 18:42
Search issues seem like they could be related to this extra `contacts_by_freetext` request:
![image](https://cloud.githubusercontent.com/assets/1286381/18525171/3c09407a-7a70-11e6-886f-0c42be9a2b8e.png)

**Comment by SCdF** [comment] 2016-09-23 14:29
@garethbowen didn't you fix this recently? You commited something to stop an errant search with just a space happening right? This looks to be the same thing

**Comment by sglangevin** [comment] 2016-09-23 17:21
Yes, I think we can close this issue - the choppiness was corrected in the most recent update and I was able to reproduce the search issues in #2769

**Comment by garethbowen** [comment] 2016-09-25 19:15
Closing as a duplicate of #2769

**Closed by garethbowen** 2016-09-25 19:15 UTC
Labels: Performance, Regression
