### ISSUE TITLE
Cannot go back for forms in mobile mode

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3814] opened 2017-08-23 04:58 UTC
In `2.13.0-beta.7` mobile mode pressing the `<` button gives an error `Error loading form. Please try again or check with an administrator.` and the following in console: `inbox.js: Error loading form TypeError: Cannot read property 'type' of undefined`

Possibly related to #3813.

**Comment by sglangevin** [comment] 2017-08-23 05:15
This is a duplicate of #3797. Closing.

**Closed by sglangevin** 2017-08-23 05:15 UTC
