### ISSUE TITLE
Errors when reloading a Message tab URL

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1161] opened 2015-08-18 20:25 UTC
Only spinners show when loading [this page](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/messages/eeb17d6d-5dde-c2c0-62c4a1a0ca17fd19):

![image](https://cloud.githubusercontent.com/assets/789512/9341648/27869714-45c5-11e5-8223-229976cd5e80.png)

![image](https://cloud.githubusercontent.com/assets/789512/9341672/4ad3c138-45c5-11e5-8bb7-d59df667025e.png)

**Comment by garethbowen** [comment] 2015-08-26 04:38
Duplicate of #1164

**Closed by garethbowen** 2015-08-26 04:38 UTC
