### ISSUE TITLE
app is not loaded until ddoc request is finished

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1551] opened 2015-11-06 11:51 UTC
Experiencing some strangeness like translations not being translated (seeing translation keys) and click events not firing when logged into lg.dev as admin on the desktop.  This seems dependent on a network request that is fetching the ddoc (2.8M) on first load which can take 10-20 secs depending on your connection.  

https://lg.dev.medicmobile.org/medic/_design/medic?&_nonce=1446809199146

While this request is loading, the app appears to be fully loaded and rendered, except for translations are not translated and some buttons don't work like Send Message FAB.  We probably want to put this behind the loader and/or optimize the request so the entire ddoc does not need to be fetched.  This request should also be behind a /_rewrite or medic-api rather than using the couchdb api directly?

![screen shot 2015-11-06 at 9 45 09 am](https://cloud.githubusercontent.com/assets/25641/10996381/9d72a226-846b-11e5-91a3-645b3b9f3821.png)

**Comment by garethbowen** [comment] 2016-03-01 21:10
I think this is a duplicate of #1173 . Setting to Acceptance Testing to make sure it's fixed.

**Closed by garethbowen** 2016-03-01 21:10 UTC
Labels: 0 - Backlog, Bug, Performance, UI/UX
