### ISSUE TITLE
No button to delete place or person in webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2907] opened 2016-11-10 21:27 UTC
In v2.9 there is no delete place or delete person button in either the desktop or mobile views.

![image](https://cloud.githubusercontent.com/assets/789512/20194939/6dfd4a62-a762-11e6-8500-3b7c9aff8900.png)

![image](https://cloud.githubusercontent.com/assets/789512/20194926/5aaad2e0-a762-11e6-92d0-6e4ccbecc3e8.png)

Delete permissions are set accordingly:
![image](https://cloud.githubusercontent.com/assets/789512/20194824/047f1e62-a762-11e6-8934-9160478cdae0.png)

**Comment by garethbowen** [comment] 2016-11-10 21:41
As far as I know this is by design and I couldn't find anything in the mocks. It was always complicated - you couldn't delete a place that had any children or a person that was the primary contact for a place.

@diannakane Is there supposed to be a delete button somewhere?

**Comment by diannakane** [comment] 2016-11-11 10:18
We planned for it, but not mentioning it is an oversight in the spec. In desktop, we were hoping to hide the delete button within the edit form (see the early lo-fi mockup below), though I'm still not sure what's possible with Enketo. Delete is a rarely used function that may also be disabled for many users, so we were trying to avoid taking up space in the FAB. @garethbowen your point about deleting a place with people in it is a good one -- sounds like that delete should be automatically disabled for such places. Since we determined in #2815 that a primary contact is not a requirement for a place, I don't think we need to automatically restrict a user's ability to delete this person from a place. 

![image](https://cloud.githubusercontent.com/assets/1675870/20211691/4995934a-a808-11e6-8dfa-745c491679d7.png)

In mobile, the edit and delete buttons are to be found in the three dots in the top right of the salmon header. 
![image](https://cloud.githubusercontent.com/assets/1675870/20211722/6b17dbb8-a808-11e6-90e2-ee1dedd76a0f.png)

**Comment by garethbowen** [comment] 2016-11-13 18:54
@diannakane @abbyad Thanks for that Dianna. Is delete a requirement for 2.9.0?

**Comment by abbyad** [comment] 2016-11-13 20:17
Yes, this should be included as part of 2.9. 

@diannakane is the location of the delete button in desktop view ready to implement? This is the current edit form for reference (pending #2333/#2828):
![image](https://cloud.githubusercontent.com/assets/789512/20248521/eae69972-a9b3-11e6-9c71-6b2f3ca56da0.png)

**Comment by diannakane** [comment] 2016-11-14 10:31
Can anyone here answer whether we can implement as mocked above, with delete as a button with the "edit place" form?  If not, we'll have to take another look at the design. 

This is jumping the gun, but if we can't implement it as mocked, the easiest thing to do may be to add the delete button to the RHS FAB in desktop and hide it in the three dots menu in the header of the place or person page in mobile.

**Comment by abbyad** [comment] 2016-11-14 14:16
> If we can't implement it as mocked, the easiest thing to do may be to add the delete button to the RHS FAB in desktop and hide it in the three dots menu in the header of the place or person page in mobile.

Having a FAB delete button in desktop view would be simplest, and can we can get further feedback on it from user testing if we want to revise it in followup releases.

From my understanding if you have `can_delete_place` or `can_delete_person` permission it will show the button, although at times the button would be disabled eg when the place contains people. If you do not have those permissions the button would be completely hidden.

**Comment by garethbowen** [comment] 2016-11-15 00:25
I've added it back to the FAB for both mobile and desktop. It is hidden if you don't have the `can_delete_contacts` permission and disabled if the selected place has children.

This puts it back the way it was in 2.8 thus resolving the regression - I'm not sure how it got deleted in the first place.

I'm not 100% comfortable with adding additional actions in a completely different part of the screen. Instead we should redesign the FABs completely and choose a design that scales better with additional functionality.

I'll leave it up to @diannakane and @abbyad to decide whether further changes are required for 2.9 - if so please raise a different issue.

**Comment by garethbowen** [comment] 2016-11-15 00:26
PR: https://github.com/medic/medic-webapp/pull/2916

**Comment by estellecomment** [comment] 2016-11-15 13:17
Comments in PR.

**Closed** 2016-11-15 19:06 UTC
Labels: 4 - Acceptance Testing, Bug, Priority, Regression

**Comment by abbyad** [comment] 2016-11-17 18:00
Works well in build 4477. Moving to Ready.
