### ISSUE TITLE
Cannot load forms on 2.7.0-alpha.3431

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2403] opened 2016-06-17 17:57 UTC
When trying to open forms (both contact forms and regular forms) I get this error. I have seen this logged in as admin and as a restricted user. The Add Family form seems to work, but the add/edit forms for `health_center` and `district_hospital` do not. None of the regular forms are loading - same error.

![image](https://cloud.githubusercontent.com/assets/1286381/16159876/0bef0a3c-347a-11e6-852a-90da1ba79356.png)

![image](https://cloud.githubusercontent.com/assets/1286381/16159838/d2a4f192-3479-11e6-8f39-05c6ee193459.png)

**Comment by garethbowen** [comment] 2016-06-19 21:14
Assigning to @estellecomment for review. Caused by one missed refactor while doing #1461

**Comment by estellecomment** [comment] 2016-06-20 07:25
LGTM

**Closed** 2016-06-20 07:26 UTC
Labels: 4 - Acceptance Testing, Bug, Priority

**Comment by sglangevin** [comment] 2016-06-23 18:17
This is working again.
