### ISSUE TITLE
"Error: Callback was already called" exception

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1545] opened 2015-11-05 17:10 UTC
I’m seeing `Error: Callback was already called.` error in my console on lg.dev in the desktop as the demo user.  Seems to completely break the app.  Doesn’t appear on my mobile device oddly enough.
![screen shot 2015-11-05 at 3 01 21 pm](https://cloud.githubusercontent.com/assets/25641/10975683/4ef76650-83cf-11e5-8435-34c8b78ff2f4.png)

**Comment by alxndrsn** [comment] 2015-11-05 17:13
Any idea what triggers it?

**Comment by mandric** [comment] 2015-11-05 17:20
Hrm like what request?  It just happens early on when loading the app.  Can you reproduce it?

**Comment by garethbowen** [comment] 2015-11-05 19:09
I've seen it occasionally too, but haven't tracked it down yet.

**Comment by garethbowen** [comment] 2015-11-05 19:16
It looks like it's when one of the functions passed to `async.parallel` or similar calls their callback a second time. Given this it's probably due to the Cache service firing on update or something...

**Comment by mandric** [comment] 2015-11-06 11:17
I wonder if it's a problem related to having multiple instances/tabs of demo user open since they are all listening and updating the same db?

**Comment by alxndrsn** [comment] 2015-11-06 12:41
Completely breaks the app for me.  Happens every time on `lg.dev`.

**Comment by alxndrsn** [comment] 2015-11-06 12:44
Working now.

**Comment by garethbowen** [comment] 2015-11-10 22:45
This was caused by replication code using async.parallel to get the Settings. Because Settings fires callbacks again on change the callback was being fired which is not allowed in async.

**Comment by garethbowen** [comment] 2015-11-10 22:45
Closed by accident...

**Closed** 2015-11-11 14:07 UTC
Labels: 4 - Acceptance testing, Bug
