### ISSUE TITLE
Changing the default language for the web app in configuration doesn't change the language that is displayed

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1018] opened 2015-06-22 20:53 UTC
Changing the default language for the web app in the configuration wizard or in Configuration > Languages doesn't change the language that I see when using the web app. Even a refresh didn't result in the language changing from English to what I had selected as the default. Making the change in the configuration wizard does update the default selection in Config but the displayed language doesn't change.

The only way I've found to update the language I am currently viewing is by going to Edit User Profile and changing the language there. That updates automatically.

**Comment by garethbowen** [comment] 2015-06-23 00:55
This is by design. When a user first logs in we display a dialogue which asks them to pick a locale, which is then saved against the user account. If I select English which happens to be the default, I don't want it changing just because an admin changed the default language.

**Comment by sglangevin** [comment] 2015-06-23 02:43
Ok, so what purpose does the default serve? It sounds like each user is selecting his or her own language.

**Comment by garethbowen** [comment] 2015-06-23 02:58
The default is selected by default, and the "Select a language" window itself is translated into the default which is the most likely to be understood by the user.

**Comment by sglangevin** [comment] 2015-06-25 18:33
So when would a user see the select a language window in the default language if the admin is the one determining the default and the one creating each login? Is it something that they see when logging in for the first time?

**Comment by garethbowen** [comment] 2015-06-25 20:11
All users see a dialogue when they first log in which asks them their language.

**Comment by garethbowen** [comment] 2015-08-16 22:17
Closing as working as expected.

**Closed by garethbowen** 2015-08-16 22:17 UTC
