### ISSUE TITLE
Export kills api

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3821] opened 2017-08-24 07:29 UTC
# Observed

## Client

Calls to the `/export` endpoint with a `query` can crash api.

<img width="942" alt="screen shot 2017-08-24 at 09 26 47" src="https://user-images.githubusercontent.com/191496/29654673-61da812c-88ae-11e7-9bcc-0a0f8b917d26.png">

## Server
```
09:26:41 api.1    | ::1 - - [24/Aug/2017:07:26:41 +0000] "GET /api/v1/export/forms?format=xml&locale=en&query=%7B%22%24operands%22%3A%5B%7B%22type%22%3A%22report%22%7D%5D%7D&schema=%7B%22errors%22%3A%22int%22%2C%22verified%22%3A%22boolean%22%2C%22reported_date%22%3A%22date%22%7D HTTP/1.1" - - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
09:26:41 api.1    | UNCAUGHT EXCEPTION!
09:26:41 api.1    | Server error:
09:26:41 api.1    |  { TypeError: First argument must be a string or Buffer
09:26:41 api.1    |     at ServerResponse.end (_http_outgoing.js:752:13)
09:26:41 api.1    |     at respond (/Users/user/workspaces/medic/api/server-utils.js:30:7)
09:26:41 api.1    |     at Object.error (/Users/user/workspaces/medic/api/server-utils.js:60:5)
09:26:41 api.1    |     at /Users/user/workspaces/medic/api/server.js:348:28
09:26:41 api.1    |     at /Users/user/workspaces/medic/api/controllers/export-data.js:671:16
09:26:41 api.1    |     at getRecordsFti (/Users/user/workspaces/medic/api/controllers/export-data.js:605:16)
09:26:41 api.1    |     at /Users/user/workspaces/medic/api/controllers/fti.js:84:16
09:26:41 api.1    |     at /Users/user/workspaces/medic/api/controllers/utils.js:41:14
09:26:41 api.1    |     at Request._callback (/Users/user/workspaces/medic/api/db.js:73:16)
09:26:41 api.1    |     at self.callback (/Users/user/workspaces/medic/api/node_modules/request/request.js:188:22)
09:26:41 api.1    |   domain:
09:26:41 api.1    |    Domain {
09:26:41 api.1    |      domain: null,
09:26:41 api.1    |      _events: { error: [Function] },
09:26:41 api.1    |      _eventsCount: 1,
09:26:41 api.1    |      _maxListeners: undefined,
09:26:41 api.1    |      members: [] },
09:26:41 api.1    |   domainThrown: true }
09:26:41 api.1    | UNCAUGHT EXCEPTION!
09:26:41 api.1    | Server error:
09:26:41 api.1    |  { Error: Can't set headers after they are sent.
09:26:41 api.1    |     at validateHeader (_http_outgoing.js:504:11)
09:26:41 api.1    |     at ServerResponse.setHeader (_http_outgoing.js:511:3)
09:26:41 api.1    |     at ServerResponse.writeHead (_http_server.js:209:21)
09:26:41 api.1    |     at respond (/Users/user/workspaces/medic/api/server-utils.js:24:7)
09:26:41 api.1    |     at Object.serverError (/Users/user/workspaces/medic/api/server-utils.js:94:5)
09:26:41 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:86:17)
09:26:41 api.1    |     at emitOne (events.js:115:13)
09:26:41 api.1    |     at Domain.emit (events.js:210:7)
09:26:41 api.1    |     at Domain._errorHandler (domain.js:134:21)
09:26:41 api.1    |     at process._fatalException (bootstrap_node.js:326:33)
09:26:41 api.1    |   domain:
09:26:41 api.1    |    Domain {
09:26:41 api.1    |      domain: null,
09:26:41 api.1    |      _events: { error: [Function] },
09:26:41 api.1    |      _eventsCount: 1,
09:26:41 api.1    |      _maxListeners: undefined,
09:26:41 api.1    |      members: [] },
09:26:41 api.1    |   domainThrown: true }
09:26:41 api.1    | exited with code 2
```

# Expected

api shouldn't crash

# Steps to recreate

**Either:**

## 1 click on the Export button

<img width="258" alt="screen shot 2017-08-24 at 09 27 13" src="https://user-images.githubusercontent.com/191496/29654687-70aa9b9c-88ae-11e7-9dad-8b156b30da6b.png">

**Or:**

## 2 with `curl`

```
curl 'http://admin:pass@localhost:5988/api/v1/export/forms?format=xml&locale=en&query=%7B%22%24operands%22%3A%5B%7B%22type%22%3A%22report%22%7D%5D%7D&schema=%7B%22errors%22%3A%22int%22%2C%22verified%22%3A%22boolean%22%2C%22reported_date%22%3A%22date%22%7D'
```

**Comment by garethbowen** [comment] 2017-08-25 04:22
Review please @alxndrsn 

My best guess is you didn't have lucene running which caused an error to be thrown. This error has the error code 503 (Service Unavailable) which our code wasn't detecting as a server error which meant we were trying to respond to the user but never converted the JSON into a string (or buffer) for sending to the client.

We had a few other unit tests which indicated that other libraries throw 503s in this sort of situation and we had caught and handled them specifically. These will now also be considered server errors which is better anyway because it puts the full error in the server log and doesn't leak implementation details to clients.

It'd be good if you could try this out and make sure that Exporting works for you when lucene is running, otherwise we have a second bug!

**Comment by alxndrsn** [comment] 2017-08-25 08:30
PR looks good.  In general I'd say it's a bug to handle `500` as a server error but other `5xx` as 'unknown'.  

I don't have lucene set up locally, but perhaps @ngaruko is in a position to check this functionality?

**Comment by garethbowen** [comment] 2017-08-27 20:24
I've tested it on my lucene. It's not too hard to [set up](https://github.com/medic/medic-webapp/#configure-lucene) if you find yourself needing the functionality.

**Comment by garethbowen** [comment] 2017-08-27 20:26
For AT:

1. Make sure the export button works.
2. Force stop lucene and then make sure the export button fails, and API logs a useful error and stays running.

**Comment by ngaruko** [comment] 2017-08-31 02:44
I am not sure if it is my setup or not but I still get the same error when I try to export. Running the latest build/master on GH...and lucene 2.0.0

**Comment by garethbowen** [comment] 2017-08-31 03:48
The fix wasn't applied to master. I've bumped api in master so hopefully it'll work now...

**Comment by sglangevin** [comment] 2017-08-31 13:25
@ngaruko assigning to you to complete AT.

**Comment by ngaruko** [comment] 2017-08-31 21:45
So basically the issue is about `api` being killed by export. For now it carries on working when errors are raised. However, there are potentially two issues that could be raised separately if applicable: 

1. Lucene does crash on my machine (which might have to do with my configuration of lucene and couchDB, so it needs to be tested on alpha.dev once it is up again)

2. When lucene crashes, the only error we get from the server is `Server error:
 { code: 503, message: { code: 500 } }`, which is not explicit enough (Gareth will look at this and raise an issue if needed)

 So I will close the issue for api still works in both cases.

**Closed** 2017-08-31 21:46 UTC
Labels: Status: 5 - Ready, Type: Bug
