### ISSUE TITLE
Bulk delete does not work on reduced screen size

### ISSUE THREAD

**Issue by ranjuts** [medic/medic-webapp#3453] opened 2017-05-08 05:48 UTC
bug found on instance: tts-indonesia.app.medicmobile.org

Works in normal desktop size
<img width="960" alt="bulk delete 1" src="https://cloud.githubusercontent.com/assets/5404004/25791739/dbb16e8e-33f4-11e7-8ffc-fb8ded5a0df9.png">

Delete all button is greyed out in the reduced screen
<img width="950" alt="bulk delete small" src="https://cloud.githubusercontent.com/assets/5404004/25791750/f7b3116e-33f4-11e7-808d-4a523525f925.png">

cc @alxndrsn

**Comment by sglangevin** [comment] 2017-05-08 16:34
@ranjuts bulk delete is not meant to work on non-desktop screens. Is a reduced screen size being used for this project? Is it a tablet or just a small computer screen?

**Comment by alxndrsn** [comment] 2017-05-09 02:13
@sglangevin this was on a desktop browser with a narrow window.  It surprising (as a user) that everything in bulk delete seems to work on the small screen except for the delete button itself... and likely a one-line fix.

**Comment by sglangevin** [comment] 2017-05-09 22:50
Yeah, I'm also not sure about the intricacies of bulk delete :) This is likely due to the break point between desktop and mobile views. I imagine we'll be adding a tablet-sized breakpoint in over the course of the next few months (between desktop and mobile) which would likely resolve this because tablet view is generally for managers and more similar to the desktop view. If this is needed for a project and an easy fix, go for it.

**Comment by garethbowen** [comment] 2017-11-16 00:49
This is a duplicate of #3808 which is now fixed.

**Closed by garethbowen** 2017-11-16 00:49 UTC
