### ISSUE TITLE
Newly-created tasks should display immediately on a profile

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1549] opened 2015-11-05 21:44 UTC
Right now, you have to refresh to see a newly-created task on a profile. For example, I've just referred Susan and I have a follow up task due in 1 day. Here's what I see when I finish the assessment and submit the report (snackbar notification showed up at the bottom):

![screen shot 2015-11-05 at 1 38 44 pm](https://cloud.githubusercontent.com/assets/377216/10982581/e3bea8aa-83c2-11e5-9ac2-b70c2690f2dd.png)

When I hit refresh once, here's what displays. Interestingly, the actions don't show and I've reproduced this a few times:

![screen shot 2015-11-05 at 1 40 05 pm](https://cloud.githubusercontent.com/assets/377216/10982618/14f893d6-83c3-11e5-90a3-fbf6c7d908f9.png)

When I refresh a second time, everything displays as expected:

![screen shot 2015-11-05 at 1 40 20 pm](https://cloud.githubusercontent.com/assets/377216/10982626/20c457fe-83c3-11e5-875a-61ea5ccfa177.png)

This is important for other workflows, too. For example, when I register a new family and answer "yes" to "Is the primary caregiver pregnant?", it creates a task to register a new pregnancy. I need to click that task straight away when I land on the family's profile page.

**Comment by joshnesbit** [comment] 2015-11-09 01:11
I noticed this looks good for the "register new pregnancy" task on the family profile (after a pregnancy is identified via the new family form). With that form and task, the task shows immediately. 

It still doesn't show the task immediately after a new assessment, but this isn't a blocker for the field test – the CHP will be following up 1-2 days later. It's nice to see the task immediately, as double-confirmation that the form was correctly submitted and the task has been scheduled, but it's not critical.

**Comment by fredatthehub** [comment] 2015-11-09 12:37
Hello, didn't work for me, Pregnancy registration shown on History but no task is shown:

![screen shot 2015-11-09 at 15 23 18](https://cloud.githubusercontent.com/assets/15346836/11033856/d48e074e-86f7-11e5-8f18-21b391012c1e.png)

**Comment by fredatthehub** [comment] 2015-11-09 12:38
Task appears after doing a manual refresh:

![screen shot 2015-11-09 at 15 23 50](https://cloud.githubusercontent.com/assets/15346836/11033876/f637f0c6-86f7-11e5-8c9e-87aa9b6d3bd1.png)

**Comment by joshnesbit** [comment] 2015-11-09 15:40
@fredatthehub I think that's on lg.app, right?

**Comment by alxndrsn** [comment] 2015-11-10 16:05
I'm guessing this is a race condition: saving the data vs generating the new task

**Comment by alxndrsn** [comment] 2015-11-11 15:54
I cannot recreate this issue on `lg.dev`.

**Comment by garethbowen** [comment] 2015-11-11 21:12
I cannot recreate this locally or on lg.dev either.

I don't think this is a race condition but it could be a `$scope.$apply();` problem, where the tasks were updated correctly but the UI wasn't re-rendered. If I'm right, this was fixed in a [commit](https://github.com/medic/medic-webapp/commit/d7f69d4da668710fd3830db82cd28b1cd5bab4e7) 6 days ago which is about the time this issue was filed.

I've added some debug statements so if this happens again we'll have more information about why it failed.

Setting to Acceptance Testing. Please update to the latest and try and reproduce on lg.app or lg.dev. If it happens again, open the console and attach the output to this issue, and reopen and I can have another look at it.

**Closed by garethbowen** 2015-11-11 21:12 UTC
Labels: 1 - Scheduled, Bug, Priority

**Comment by abbyad** [comment] 2015-11-14 05:08
@joshnesbit have you seen this problem again? I think there is a similar (inverse) problem in #1562, but I cannot reproduce the scenario from this issue.

**Comment by joshnesbit** [comment] 2015-11-14 21:27
I can no longer reproduce this. It's working for me on lg.app on my Y4, online and offline.
