### ISSUE TITLE
Blank screen on tasks tab

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1734] opened 2015-12-02 22:06 UTC
Logged into a CHP account, I see a blank screen on the tasks tab. This is different that the "No tasks found" text I'm used to seeing, but I'm not sure if it's an error or not. I was encouraged to file. Here's the screenshot:

![screen shot 2015-12-02 at 10 56 02 pm](https://cloud.githubusercontent.com/assets/377216/11545617/7bc585b6-9948-11e5-969b-a3e297c49d8e.png)

I've downloaded all the data in this browser, as far as I can tell. Refresh doesn't help. I had previously had three danger sign follow up tasks (created during pregnancy registrations), but I couldn't clear those tasks – that led to Marc fixing tasks, and now I'm seeing this blank screen. It's possible this is only an issue for user 2muk045.

I just exited the incognito mode browser, launched it again, signed in, and let the data download. "No tasks found" text shows until I hit refresh, and then the blank page shows again.

**Comment by abbyad** [comment] 2015-12-02 22:14
Putting this in the current iteration to find out if this is an isolated incident or a common issue.

**Comment by abbyad** [comment] 2015-12-05 00:16
Has anyone been able to reproduce this? This could be a severe issue if it happens regularly in the field. 

@alxndrsn, let us know if you have any thoughts on this.

**Comment by sglangevin** [comment] 2015-12-05 01:01
I reproduced this for user 2muk029. After registering several pregnancies, I cleared the acute conditions tasks. After clearing the last task, I saw a blank screen instead of "No tasks found". Closing my browser and opening a new one and signing in as the same user, I got "No tasks found" again, but refreshing and reloading the page had not helped. This was Chrome incognito - happened while loading data for the field test.

**Comment by alxndrsn** [comment] 2015-12-14 07:48
I have seen this occur, but can't confirm if it is just a missing _No tasks found_ message or not.

**Comment by alxndrsn** [comment] 2015-12-15 06:34
This is caused by: [_No tasks found_ is displayed when `$scope.tasks` is empty](https://github.com/medic/medic-webapp/blob/testing/templates/partials/tasks_list.html#L24), but [the task list is filtered to hide resolved tasks](https://github.com/medic/medic-webapp/blob/testing/templates/partials/tasks_list.html#L3).

Proposed fix: when a task is resolved, delete it from `$scope.tasks` instead of filtering in the view.  This should be safe as long as tasks can never become un-resolved.

**Comment by mandric** [comment] 2015-12-16 18:58
Available on lg.dev for acceptance testing.

**Comment by abbyad** [comment] 2015-12-16 19:35
I just discovered something that may be relevant to this issue. On lg.dev (2488) I had a tab open with Tasks another with History. In Tasks I had a list with 20+ tasks. 
- In reports I deleted a record for person X
- In tasks all items disappeared except for the ones related to person X

**Comment by mandric** [comment] 2015-12-16 19:52
Please try again on lg.dev.

**Comment by joshnesbit** [comment] 2015-12-23 00:11
Hey Milan, I can't test this on lg.dev currently because tasks aren't clearing. I haven't seen a blank screen on lg.dev, but I need to clear all the tasks to check the original issue.

**Comment by mandric** [comment] 2015-12-23 00:37
Ok, I'm working on a "generic profile" setup/builds #1764  so we can differentiate bugs based on configuration and application code bugs.  Once this is done we should be able to reproduce and test/confirm all application bugs on alpha.dev...

**Closed** 2016-01-08 11:28 UTC
Labels: 4 - Acceptance testing, Bug
