### ISSUE TITLE
History tab: Change name displayed to be patient name instead of submitter name

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4053] opened 2017-11-20 20:17 UTC
On the History tab, change the name displayed in the LHS to be the patient name (more broadly: the name of the person the form is _about_) instead of the name of the person submitting the form.

This makes the information displayed in the list more useful to our users:
For CHWs, it allows them to scan for patient names instead of seeing their own name repeated on each and every report row.
For managers, it allows them to scan for the names of the CHWs they manage instead of seeing their own name repeated on each and every report row.

**Comment by garethbowen** [comment] 2017-11-20 20:40
@amandacilek What if the report isn't about anyone or has an unknown patient? Should there be some generic text (eg: "_unknown"), the sender's name perhaps with a prefix (eg: "from Gareth"), or no title at all?

**Comment by amandacilek** [comment] 2017-11-20 21:04
That's a great question, I'm going to tag @diannakane and @sglangevin here for their thoughts.

Of the options you list, I would probably rule out putting in some generic text like "Unknown". This doesn't really add value to the user and could be interpreted as an error message.

Putting the sender name there could also work but I worry it might get confusing if we are sometimes displaying patient name and sometimes sender/CHW name. Even with the prefix - it might be too subtle a difference for the users to note.

No title at all sounds like a reasonable option. In the case of something like a community event, then there would only be two lines of text "Community Event" followed by the breadcrumbs... makes sense to me.

What do you think @diannakane ?

**Comment by diannakane** [comment] 2017-11-20 21:41
I can't think of a situation where a report isn't about a person or a place. 

In the app, we require that a user select a person or a place to report about. 
In text forms, the patient ID is a required field. If the ID doesn't match a person in the app, the ID (rather than the name) or "unknown," per Gareth's suggestion, could be displayed on that line. I believe this report would also be marked as invalid with a red dot.

**Comment by sglangevin** [comment] 2017-11-21 00:40
I do think it's possible to create a form in the app where you are not required to select a person or place that the form is about. For example, the community event form (as it is currently designed) doesn't actually collect the name of the community because the community is implied based on the person submitting the form. So in that case, it would be weird to put unknown.

I do think it's reasonable to require that there be some ID in the form that we use to determine what name appears in the list of Reports. @garethbowen how were you thinking of implementing this? Getting the patient_id from the form? Or were you thinking of a totally different way? I'd be ok with implementing something that required us to have a particular form field, but I'm not sure if that is relevant here.

**Comment by garethbowen** [comment] 2017-11-21 01:29
I hadn't thought about it much, but yes I imagine I'd look up the subject by the patient_id or place_id. That's the way the majority of our code works currently.

For the community event form, it sounds like we should have a sentinel transition to work out the submitters place and update the doc with the place_id.

**Comment by SCdF** [comment] 2017-11-21 12:59
> I can't think of a situation where a report isn't about a person or a place.

@diannakane I'm pretty sure they exist, unless we want to consider that all reports are at their base about the highest place in the hierarchy. I believe I've seen surveys and things, where you just fill them out in general, not attached to any one place.

**Comment by sglangevin** [comment] 2017-11-21 17:12
So in most of our text forms, we have a person's ID included. This is all forms other than the person creation form (for person-centered workflows) and registration forms (for case-based workflows, for which this feature would be complicated).

For app forms (xforms) we most often have a `patient_id` field, but there are cases where that field is not there, like surveys and things. However, I think it's reasonable to ask people to include an id field in all xforms. If not patient_id, then place_id (or something else) that we use to decide what to display in the list of reports.

The challenge is what to do when there is no id in the form (either someone forgot to include the id as a field or it's some sort of SMS-based registration form). In the case where someone forgot to include the id as a field, we could leave it blank or show the Medic ID or uuid. In the case where it's an SMS-based registration form, those _should_ all have names in them and we could use the name provided in the form.

**Comment by diannakane** [comment] 2017-11-21 17:50
The differences we're discussing may rest in that it may possible to create a form in the app without a place, but I can't think of a workflow scenario where that happens. It's either about me, the sender, or the place I belong to. Surveys are about a family, stock reports are about me or my place, service reports are about me or my place. Gareth's idea to look up the place above the sender in the hierarchy is a good one. In most cases, it would also be sufficient to attach this to sender. 

In the case where we're not submitting a report from the page of the place or the person or using an ID to reference a place or a person in the SMS form, we could have the report line for "about" be the sender's name.

**Comment by garethbowen** [comment] 2017-11-21 19:26
> ... we could have the report line for "about" be the sender's name.

@diannakane I'm not sure what this means? Are you saying if there is no place or person (eg: a survey form) we should use the sender's name? That makes sense to me because if the form is designed to have no subject, then the closest thing we have to a subject is the sender (ie: the subject of the survey is themselves).

In the case of an SMS being received with an unknown id for a required patient_id/place_id field, we can show the patient ID as the subject as it's the best we can do, and you're right, the red bubble will make it clear why there's no name.

In the case of an SMS being received with _no_ id for a required patient_id/place_id field, should we fall back to "unknown"?

**Comment by diannakane** [comment] 2017-11-21 20:40
> Are you saying if there is no place or person (eg: a survey form) we should use the sender's name? 

Yes

> In the case of an SMS being received with an unknown id for a required patient_id/place_id field...
> In the case of an SMS being received with no id for a required patient_id/place_id field...

Both have required patient_id/place_id fields and neither hit a match in our system. I wonder if it would be less confusing to write "unknown" for both rather than an unmatched ID for one and "unknown" for the other. In this way, "unknown" would communicate that the name is unknown, which is true for both.

**Comment by SCdF** [comment] 2018-02-01 09:26
@sglangevin / @dianabarsan Does we think this requires retraining? If so, should it be in 2.15? Or merged in 3.0 / 3.1?

**Comment by diannakane** [comment] 2018-02-01 09:47
I think it will be evident. The sender will recognize their patient's
names. We can add it to the tour for 3.1 in case of any lingering
confusion. @amandacilek

**Comment by sglangevin** [comment] 2018-02-01 19:09
I agree with Dianna. This is a long-time request from CHWs, so I think it will be an easy adjustment.

**Comment by garethbowen** [comment] 2018-02-15 19:58
Merged and ready for AT.

**Comment by sglangevin** [comment] 2018-03-10 00:36
Noticed this while testing death reporting. Can someone explain to me why [this report](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/c52ee656-10d2-470c-9c30-2c6854af7205) shows up as "Unknown subject" in the history tab? Seems like it should be the patient's name, which is included in the report:
![image](https://user-images.githubusercontent.com/1286381/37235937-cc06863c-23b7-11e8-8f95-401167610e3b.png)

**Comment by dianabarsan** [comment] 2018-03-11 16:30
My guess (as I don't have access to alpha.dev) is that the patient doc has since been deleted. 
It's a very easy change to prioritize data saved within the report doc itself (the patient name) and display that  versus data queried from the DB (ie: search by patient_id). 
@sglangevin Please tell me if you wish that I make this change.

**Comment by garethbowen** [comment] 2018-03-11 22:23
@dianabarsan I had a look on alpha.dev and the contact hasn't been deleted (though that was a good guess!). The problem is the code assumes that `patient_id` is a reference not a uuid. The workaround is to change the field to `patient_uuid` in the form, but I think having a uuid in a `patient_id` field is standard for enketo forms (right @sglangevin ?). We might have to try and determine if the `patient_id` value is a uuid or a shortcode, or alternatively, assume it's a shortcode but if no matches are found assume it's a uuid.

**Comment by dianabarsan** [comment] 2018-03-12 10:22
@garethbowen is correct, the issue is that the patient_id field in the report contained a doc id instead of a shortcode, also the form is missing the patient_uuid field.

**Comment by sglangevin** [comment] 2018-03-12 18:10
Right - the `patient_id` field will always contain a doc id for projects that do not use Medic IDs (shortcodes), which is most of our projects where CHWs are using our Android app. The `patient_uuid` field is not something that we can rely on so we shouldn't be using that as a way to get the patient's name or any info about them.

**Comment by garethbowen** [comment] 2018-03-14 08:16
@sglangevin @amandacilek @dianabarsan The fix for this issue has had a side effect that I didn't expect - now the LHS and the header of the RHS are quite different which I for one find confusing. Here's what it looks like now...

![inconsistent-headers](https://user-images.githubusercontent.com/2064938/37390070-82e7ccfa-27cb-11e8-990f-decadfe27886.png)

1. Now the LHS shows the subject (eg: patient name) but the RHS shows the submitter. I'd expect these two to both show the subject. Perhaps the RHS should have the submitter's name somewhere below?
2. There's also an existing issue that
  - the LHS has:
    - Subject
    - Form name
    - Location
  - but the RHS has:
    - Submitter
    - Location
    - Form name
  - ie: the last two lines are switched. Should these be consistent?
3. And finally, should the location be the location of the subject or the submitter? Usually these will be the same but they don't have to be.

**Comment by dianabarsan** [comment] 2018-03-14 13:43
Also, on LHS, the submitter name could be included in to location. 

![image](https://user-images.githubusercontent.com/35681649/37405784-3dac075a-279e-11e8-9644-8fdd37c22a63.png)

**Comment by amandacilek** [comment] 2018-03-14 15:28
Hey Gareth thanks. Yes I've been wanting to fix the reports RHS. My preference is that it is updated to match the new LHS order:
- Subject (patient) name
- Form name
- Location (breadcrumbs)

Diana is right - we were thinking the location component would give the details of the submitter.
Not entirely sure about your last question though on whether the location should be of the patient or the submitter. I think location of patient but want to double check - tagging @diannakane for her thoughts.

One other thing I've been wanting to do is move the long detailed time information from the right edge to the left edge of the RHS, so it's underneath the main list. This is because as the page scales smaller, having a long line of text on both the left and the right causes some really weird text wrapping. And it kind of makes sense in a way that the right edge keeps only the abbreviated time stamp and the dot, matching the right edge seen on the list in the LHS.

So my proposal would be:
- Subject (patient) name
- Form name
- Detailed time info
- Location (breadcrumbs)

**Comment by diannakane** [comment] 2018-03-15 01:39
The location of the patient makes sense to me, particularly for cases where the submitter is not the CHW. If it's the nurse at a facility, showing the location of the submitter could feel really disconnected from the patient's location in the hierarchy.

Did we account for the submitter to show up anywhere in this new design? A link to their location feels helpful, and we'll still want to search/filter for reports submitted by a particular person, e.g. "sent by CHW Mary."  This may be outside the bounds of what this issue is trying to solve.

**Comment by dianabarsan** [comment] 2018-03-15 18:10
I made a mock of @amandacilek 's update, including submitter name in location breadcrumb (location is still submitter's location). Just as an addition, in the RHS, Patient name could be a link to the corresponding contact page, if desired.  

![image](https://user-images.githubusercontent.com/35681649/37482282-a20c2a2e-288c-11e8-9a73-7e5f3520e169.png)

@sglangevin Could you, please, offer your thoughts?

**Comment by amandacilek** [comment] 2018-03-15 19:25
Did we account for the submitter to show up anywhere in this new design?

@diannakane The submitter name will be shown, listed first in the breadcrumbs, so long as the submitter's area is named after them (which I think it usually is?):
**Janet Mwangi's Area** > Tula Branch > Kiambu District Hospital

I remember us initially thinking this would be sufficient. However we could certainly add the submitter's name in as it's own line. I also think sometimes the submitter's name is mentioned in one of the first form rows right below? Maybe I'm making that up but I have it that way in my mockups.

![screen shot 2018-03-15 at 12 24 36 pm](https://user-images.githubusercontent.com/26235957/37486506-e3e9fc96-284b-11e8-8c6d-8939d8e19666.png)

**Comment by diannakane** [comment] 2018-03-15 19:45
What's confusing me is these breadcrumbs don't necessarily relate to the
submitter. I thought we were saying that the patient's location would be
listed first, e.g. household. If the submitter was someone else, would the
breadcrumbs show that as the first place, e.g. clinic?

**Comment by amandacilek** [comment] 2018-03-15 19:55
Hm it is confusing. If a CHW is submitting a report, then the first item in the breadcrumbs will often be the same whether it is showing CHW's area or the patient's area (they would both fall under "Janet Mwangi's Area"). 

But yeah, say Nurse Mary submits the form for Beatrice. Then the breadcrumbs still say "Janet Mwangi's Area" because they're about the patient and Beatrice Bass belongs to that area. In which case we're still missing the submitter Mary's name, is that what you're saying?

My second point above was proposing that maybe we display this information in a form field, if that is possible. So the form field title is "Submitter name" and then we list the name below. I'm not sure if we're able to do that though.

I'm definitely not opposed to listing the submitter name in the top area, but then I think we need the additional context of the descriptive text "Submitter name:" otherwise it will get confusing to see multiple names and not know which is the patient, which is the CHW, and which is the submitter. That's why I like the form field idea - it has a title.

**Comment by diannakane** [comment] 2018-03-15 20:06
The submitter's name next to the date it was submitted feels sensible and
like it would reinforce the association, maybe accompanied by a label
"submitted by" if we think it's needed.

Why would the breadcrumbs start with the CHW"s area if it's about the
patient, and not with the patient's household?

**Comment by amandacilek** [comment] 2018-03-15 20:13
> Why would the breadcrumbs start with the CHW's area if it's about the patient, and not with the patient's household?

Sorry, yes, in that case they could start with the patient's family, and then list the CHW's area. The CHW's area still applies, it's just going one level deeper. So:
Beatrice Bass Family > Janet Mwangi's Area > Tula Branch > ...

If we've decided we're interested in including the submitter's name as well in the top, why don't I do a few mockups to show what that would look like, explore some options, and we can decide. Not sure if that needs to be in this ticket, or if it should be split off into another ticket?

**Comment by garethbowen** [comment] 2018-03-15 20:17
> Not sure if that needs to be in this ticket, or if it should be split off into another ticket?

In my opinion the current implementation is confusing enough that 2.15.0 shouldn't be released the way it is. Can fix the consistency issue with the LHS (perhaps the way @dianabarsan has suggested?) as part of this issue, and then make it even better with a new issue in 3.0.0?

**Comment by diannakane** [comment] 2018-03-15 20:23
Yeah, Diana's suggestion will solve the problem we intended to solve with
this issue. I think this is a useful catch and worth mocking up, Amanda.
Depending on how simple the solution is and how close you guys are to
releasing 2.15, we could consider including it, but otherwise plan for it
in 3.0.

**Comment by amandacilek** [comment] 2018-03-15 20:41
Sorry if my earlier comments confused things, I was a little confused myself. To make sure I understand:

We like this for now:
- Subject (patient) name
- Form name
- Detailed time info
- **Location (breadcrumbs) based on submitter's location**

And we would like to consider:
- Subject (patient) name
- Form name
- **Submitter's name**
- Detailed time info
- **Location (breadcrumbs) based on patient's location**

**Comment by garethbowen** [comment] 2018-03-15 20:51
My proposal for the LHS and RHS is...

- Subject (patient) name
- Form name
- Subject location (breadcrumbs) (not submitter location)

We can do mockups for including the submitter's name, submitter's location, and moving the details time info and get that done in 3.0 (or whenever).

**Comment by sglangevin** [comment] 2018-03-15 20:53
I don’t think I feel comfortable removing the sender information completely. I think it needs to be there. It seems weird to just see patient information and not know who sent that report.

**Comment by garethbowen** [comment] 2018-03-15 20:56
Yeah, I was waiting to see who would notice that  ;)

How about this...

LHS:

- Subject (patient) name
- Form name
- Subject location (breadcrumbs) (not submitter location)

RHS:

- Subject (patient) name
- Form name
- Subject location (breadcrumbs) (not submitter location)
- "Sent by <submitter name>"

We can do mockups for including the submitter's location and moving the details time info and get that done in 3.0 (or whenever).

**Comment by amandacilek** [comment] 2018-03-15 21:04
I think I'm fine with whatever you guys want to do here for the quick-fix. The main thing is that we've fixed it so the LHS and RHS are more consistent, which is good.

As a point of comparison, here is a very quick mockup close to what I _think_ it might eventually be. I tried out the submitter name on the same line as the detailed time info but it made the line really long and I prefer to just put them on separate lines.
![screen shot 2018-03-15 at 1 58 42 pm](https://user-images.githubusercontent.com/26235957/37490925-617ca9da-2859-11e8-98ff-be2355c46182.png)

**Comment by sglangevin** [comment] 2018-03-15 21:27
I'm fine with that suggestion, @garethbowen. I think that makes it consistent but also keeps a reference to the submitter's name, which I think is useful. The other thing I like about this change is that you can easily get to the family page from the History detail view, which I think is very useful.

**Comment by diannakane** [comment] 2018-03-15 21:43
It feels like sender name and time/date submitted should be formatted
differently from the rest, but I'm fine leaving that for a future
iteration. Let's just make a note to circle back to that, Amanda.

**Comment by sglangevin** [comment] 2018-03-27 00:49
Please backport to 2.15.x for AT in the next 2.15.0 beta.

**Comment by sglangevin** [comment] 2018-03-27 00:50
Just kidding - I see that has already been done. I initially only saw the comment.

**Comment by ngaruko** [comment] 2018-04-04 23:53
LGTM. However there is a small UI error when the format of the report is incorrect (here more LMP more than 42 weeks). Not sure if it has to do with this work but apparently the `{{patient_name}}` is not rendered in the error message and the automated reply.
![image](https://user-images.githubusercontent.com/6979995/38340478-ce2db6ea-38c7-11e8-82fb-b87f08f5762b.png)

**Closed** 2018-04-08 21:33 UTC
Labels: Priority: 3 - Low, Status: 5 - Ready, Type: Improvement
