### ISSUE TITLE
No error message is shown if phone number is not valid

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3471] opened 2017-05-11 17:25 UTC
![screen shot 2017-05-12 at 01 25 25](https://cloud.githubusercontent.com/assets/191496/25962856/e79134cc-36b1-11e7-9276-2dfe0353f3c3.png)

Can be seen on alpha.dev.

**Comment by sglangevin** [comment] 2017-05-11 17:36
This looks like a configuration issue. Error messages need to be included in the form. Which form is this?

**Comment by alxndrsn** [comment] 2017-05-11 17:46
Add Person form on alpha.dev and on a newly-setup project.

**Comment by sglangevin** [comment] 2017-05-11 17:47
Did a bit more digging as this was reported during testing for LG's upgrade and it looks like the workaround being used is a regex, so I'm not sure if we are actually checking to see if the phone number is valid. Seems like not, so we should probably look into this further.

**Comment by garethbowen** [comment] 2017-06-20 04:33
Oooookay. After a deep dive into the unknown, it turns out the `constraintMsg` is only used if you also specify a constraint. So, my workaround is to add `constraint="true"` to the phone `bind` element, eg:

`<bind constraint="true" jr:constraintMsg="Use one of the following formats: +256-XXX-XXX-XXX or 07XX-XXX-XXX. Dashes are not required." nodeset="/data/ephemeral_phone/phone1" type="tel"/>`

![invalid](https://user-images.githubusercontent.com/2064938/27316712-bc395c8a-55d5-11e7-959c-716e2bb29c61.png)

NB: there is a related issue for having different error messages depending on the cause: #1373 

@sglangevin Is this workaround acceptable?

cc @alxndrsn

**Comment by sglangevin** [comment] 2017-06-20 16:33
@garethbowen I'm going to see if there is a way for me to add that to XLSform. If so, then we are good. If not, then we'll need to make sure it's supported in XLSform or that we are adjusting our conversion script to add `constraint="true"` since tech leads are using XLSform to build forms. Having to add `constraint="true"` to the XML every time would be a pain for them.

**Comment by sglangevin** [comment] 2017-06-20 17:59
Cool - so all we have to do is put "true" in the constraint column and we're good to go. I think this workaround is fine for now as it only applies to the phone number field for which we don't include a constraint in the form. We can close this one.

**Closed** 2017-06-20 21:42 UTC
Labels: Bug, No Action Needed
