### ISSUE TITLE
Updated place icons don't display on the LHS of the people tab

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4233] opened 2018-02-22 22:45 UTC
Seen on beta.dev, logged in as admin:
![image](https://user-images.githubusercontent.com/1286381/36568267-32ff972e-17de-11e8-9097-91bc4ec41bd1.png)

The icon displays for adding a new district but not in the list of existing districts. Similar issue with the CHW area icon when logged in as a restricted user (CHW). The CHW area icon doesn't show up in the LHS list next to "Sharon Langevin Area" while the family icon (which is from the previous set of default icons) shows up successfully on the LHS. Has something changed in the code or with the icons? I downloaded the raw files from medic-webapp and uploaded them to this instance.
![image](https://user-images.githubusercontent.com/1286381/36568441-e395d06c-17de-11e8-9f39-0caebed248f8.png)

**Comment by garethbowen** [comment] 2018-02-23 03:28
The problem is the `2.14.x` branch is missing #4063

**Comment by garethbowen** [comment] 2018-02-23 03:34
I've backported the patch so it should work now.

**Comment by sglangevin** [comment] 2018-02-23 22:20
LGTM in 2.14.0-beta.13. One minor issue is that we've swapped the medic-clinic and medic-health-center icons. medic-clinic should be the CHW area icon and medic-health-center should be the blue building with the plus sign on it. @garethbowen can you swap the files? Once that's done we can close this. I think that was missed when the issue to change the icons was AT-ed.

**Comment by garethbowen** [comment] 2018-02-25 20:10
Facepalm... yes I'll do that today.

**Comment by garethbowen** [comment] 2018-02-25 21:23
Merged and backported to `2.14.x`

**Closed** 2018-02-27 21:27 UTC
Labels: Contacts, Priority: 1 - High, Status: 5 - Ready, Type: Bug
