### ISSUE TITLE
Title of form is misaligned in list of reports and reports detail pane

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3758] opened 2017-08-07 22:09 UTC
Seen on v2.13.0-beta.2. The form title is aligned with the icon but should actually be aligned with the other rows of text. Happening on both the LHS and RHS:

LHS:
![image](https://user-images.githubusercontent.com/1286381/29047773-2f70a0d8-7b82-11e7-8970-96879622089c.png)

RHS:
![image](https://user-images.githubusercontent.com/1286381/29047780-384c5468-7b82-11e7-844c-360d3b5f7fc4.png)

**Comment by garethbowen** [comment] 2017-08-08 22:41
@sglangevin I think this is how it was in previous versions too. The problem is we don't know the size of the icon so we can pad out the content correctly. Can this be put off until #3735 (and the related issues) are fixed in 2.14 and can do it properly?

**Comment by sglangevin** [comment] 2017-08-08 22:48
Here are some screenshots from 2.11.3:
![image](https://user-images.githubusercontent.com/1286381/29097843-e947a992-7c50-11e7-8389-c648cd24f578.png)

![image](https://user-images.githubusercontent.com/1286381/29097848-ef8394d8-7c50-11e7-8c0c-6deef4ad98f5.png)

Did something in the code change? The icons look to be the same size to me. I'm not opposed to waiting, just wondering why this looks different.

**Comment by garethbowen** [comment] 2017-08-10 04:24
Introduced with the list item text wrapping change in #3525

**Comment by garethbowen** [comment] 2017-08-10 04:31
Code review please @SCdF

**Comment by garethbowen** [comment] 2017-08-10 04:31
This is to be backported to 2.13.x

**Comment by SCdF** [comment] 2017-08-11 09:38
Merged, backported to 2.13.x

**Closed by SCdF** 2017-08-11 09:38 UTC
Labels: 3 - Code Review, UI/UX

**Comment by sglangevin** [comment] 2017-08-14 21:51
Looking good in 2.13.0-beta.4. Moving to Ready.
