### ISSUE TITLE
Ensure E2E tests run

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1825] opened 2016-01-22 20:26 UTC

**Comment by garethbowen** [comment] 2016-01-25 22:42
Assigned to @SCdF to ensure he can also run the tests. If so I'll consider this issue closed.

**Comment by SCdF** [comment] 2016-01-26 15:29
@garethbowen note that this only boots with node versions later than what we advertise in the readme. I ran it under 5.4.0, but we presumably want to standardise on a particular node version (at least major) before a-okaying this.

Inanycase, it did not work locally for me. I got the following output:

```
Running "protractor:default" (protractor) task
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
F.F

Failures:
1) Auditing audits message deletion
  Message:
    Expected undefined to equal 'not_found'.
  Stack:
    Error: Failed expectation
        at /Users/scdf/Code/Medic/medic-webapp/tests/protractor/e2e/auditing.js:89:25
        at process._tickCallback (node.js:405:9)
  Message:
    Expected undefined to equal 'deleted'.
  Stack:
    Error: Failed expectation
        at /Users/scdf/Code/Medic/medic-webapp/tests/protractor/e2e/auditing.js:90:26
        at process._tickCallback (node.js:405:9)
  Message:
    Expected undefined to equal true.
  Stack:
    Error: Failed expectation
        at /Users/scdf/Code/Medic/medic-webapp/tests/protractor/e2e/auditing.js:103:43
        at process._tickCallback (node.js:405:9)

2) Tasks visit tasks are shown
  Message:
    Failed: No element found using locator: By.cssSelector("#tasks-list ul li[data-record-id=\"123\"] .description")
  Stack:
    NoSuchElementError: No element found using locator: By.cssSelector("#tasks-list ul li[data-record-id=\"123\"] .description")
        at process._tickCallback (node.js:405:9)
    Error
        at Object.<anonymous> (/Users/scdf/Code/Medic/medic-webapp/tests/protractor/e2e/tasks.js:121:24)
    From: Task: Run it("visit tasks are shown") in control flow
    From asynchronous test:
    Error
        at Suite.<anonymous> (/Users/scdf/Code/Medic/medic-webapp/tests/protractor/e2e/tasks.js:108:3)
        at Object.<anonymous> (/Users/scdf/Code/Medic/medic-webapp/tests/protractor/e2e/tasks.js:3:1)

3 specs, 2 failures
Finished in 14.876 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 failed 2 test(s)
[launcher] overall: 2 failed spec(s)
[launcher] Process exited with error code 1
>>
```

Let's talk about it when you're around. First thing I'd like to know is which node version you ran it under. Second thing would be that this is probably a good opportunity to work through some protractor stuff.

**Comment by SCdF** [comment] 2016-01-28 14:56
For clarity: the tests fail on my machine, but they fail _correctly_. As in, the expects in the tests aren't correct. @garethbowen is going to make the expects correct and then work out why that doesn't work on his machine.

**Comment by garethbowen** [comment] 2016-02-01 10:04
Should work now...

**Comment by SCdF** [comment] 2016-02-01 11:56
It passed!

I'm going to give this to @estellecomment now, just to triple check

**Comment by estellecomment** [comment] 2016-02-01 14:51
:( 

Both Firefox and Chrome fail. 
Firefox displays a confirmation dialog which is probably not what we want : 
![screen shot 2016-02-01 at 15 27 50](https://cloud.githubusercontent.com/assets/911434/12720529/aab1d9aa-c8fb-11e5-878a-a70e87383a45.png)

Log : 
```
estellecomment@Estelles-MacBook-Air medic-webapp-2 (develop)*$ grunt protractor
Running "notify_hooks" task

Running "protractor:default" (protractor) task
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
F..

Failures:
1) Auditing audits message deletion
  Message:
    Failed: No element found using locator: By.cssSelector("#message-content ul li[data-record-id=\"b9acd7690c804eb694861bde21d9fafc\"] .data p span")
  Stack:
    NoSuchElementError: No element found using locator: By.cssSelector("#message-content ul li[data-record-id=\"b9acd7690c804eb694861bde21d9fafc\"] .data p span")
        at process._tickCallback (node.js:368:9)
    Error
        at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/auditing.js:69:23)
    From: Task: Run it("audits message deletion") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/auditing.js:55:3)
        at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/auditing.js:4:1)

3 specs, 1 failure
Finished in 26.334 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
>> 
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.

Aborted due to warnings.
```

**Comment by estellecomment** [comment] 2016-02-01 14:52
Chrome log : 

```
estellecomment@Estelles-MacBook-Air medic-webapp-2 (develop)*$ grunt protractor
Running "notify_hooks" task

Running "protractor:default" (protractor) task
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
F.F

Failures:
1) Auditing audits message deletion
  Message:
    Failed: No element found using locator: By.cssSelector(".inbox-items li[data-record-id=\"+64555555555\"]")
  Stack:
    NoSuchElementError: No element found using locator: By.cssSelector(".inbox-items li[data-record-id=\"+64555555555\"]")
        at process._tickCallback (node.js:368:9)
    Error
        at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/auditing.js:67:71)
    From: Task: Run it("audits message deletion") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/auditing.js:55:3)
        at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/auditing.js:4:1)

2) Tasks visit tasks are shown
  Message:
    Failed: No element found using locator: By.cssSelector("#tasks-list ul li[data-record-id=\"123\"] .description.title")
  Stack:
    NoSuchElementError: No element found using locator: By.cssSelector("#tasks-list ul li[data-record-id=\"123\"] .description.title")
        at process._tickCallback (node.js:368:9)
    Error
        at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/tasks.js:121:24)
    From: Task: Run it("visit tasks are shown") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/tasks.js:108:3)
        at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-2/tests/protractor/e2e/tasks.js:3:1)

3 specs, 2 failures
Finished in 14.959 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 2 test(s)
[launcher] overall: 2 failed spec(s)
[launcher] Process exited with error code 1
>> 
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.

Aborted due to warnings.
```

**Comment by SCdF** [comment] 2016-02-01 14:55
To add to this, I'm a terrible person and only tested on Firefox. On `chromium-browser` it doesn't find the driver, even though I installed chromium (via brew cask, idk if that matters). Changing it to `chrome` though, I get it to run, but get similar issues to @estellecomment

**Comment by garethbowen** [comment] 2016-02-01 20:49
It looks like the Firefox issue @estellecomment reported is due to her database having more messages and when the webdriver tries to click on the message which is below the floating buttons it ends up clicking the "Export" button instead. The correct solution is to run the tests in a fresh db, so I'll look at doing that. If that's too difficult I can probably get the test to scroll to bottom before clicking to get it working in the mean time.

**Comment by SCdF** [comment] 2016-02-08 15:54
> The correct solution is to run the tests in a fresh db, so I'll look at doing that. If that's too difficult I can probably get the test to scroll to bottom before clicking to get it working in the mean time.

So this came up when I ran the tests on my laptop (no massive attached screen): they are highly reliant on screen real-estate. To make the tests pass I had to maximise Firefox manually as it started.

Is it unreasonable to have the tests look for things off-screen? Note that I didn't change my database contents or anything like that.

**Comment by garethbowen** [comment] 2016-04-22 01:37
Pull request: https://github.com/medic/medic-webapp/pull/2228

The biggest change is the e2e tests now run against an api spawned on a different port, and against a new db so we have full control over the config and data.

**Comment by estellecomment** [comment] 2016-04-26 13:22
Comments in PR.

Won't run on my machine :( I think it's not able to spawn the api, doesn't find `server.js`?
`grunt e2e` says : 
```
Running "protractor:default" (protractor) task
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Error: spawn node ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
[launcher] Process exited with error code 1
>> Error: spawn node ENOENT
>>     at exports._errnoException (util.js:874:11)
>>     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
>>     at onErrorNT (internal/child_process.js:344:16)
>>     at doNTCallback2 (node.js:441:9)
>>     at process._tickCallback (node.js:355:17)
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.
```

Meanwhile webdriver says nothing special : 
```
15:03:35.914 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
15:03:35.915 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 12960
Only local connections are allowed.
15:03:36.911 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
15:03:36.937 INFO - Executing: [set script timeout: 11000])
15:03:36.941 INFO - Done: [set script timeout: 11000]
```

Printing out `process.cwd()` looks right (medic-webapp's root), and the contents of the `api` subdirectory does contain `server.js`. 
I did run webdriver, npm install in both projects, any other dependencies I'm forgetting?

**Comment by garethbowen** [comment] 2016-04-26 22:05
I can't think of anything obvious. It could be an OS specific issue? What version of node are you running? Make sure you have the correct submodule commit (eg: `git submodule update` in `medic-webapp`).

Would you mind taking the lead on this one? It's hard to debug without being able to reproduce it. Happy to peer on it if we're online at the same time.

**Comment by garethbowen** [comment] 2016-04-26 22:05
Oh, and I've made a bunch of changes given your review comments. Thanks!

**Comment by estellecomment** [comment] 2016-04-28 09:47
Success! Now it works for me.

**Closed** 2016-04-28 10:09 UTC
Labels: 5 - Ready, Technical Debt
