### ISSUE TITLE
Include the default xforms in fresh instances

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3062] opened 2017-01-20 11:45 UTC
We created default (standard?) forms in https://github.com/medic/medic-webapp/issues/2828. 
When you create a fresh instance, they still need to be uploaded by hand. So they're not really default.

Would be better to have them included by default.

**Comment by garethbowen** [comment] 2017-01-26 08:19
There are a range of docs we'd like to create on first run (translations, resources, probably others). If we can find a generic way of attaching docs to the ddoc and then saving them when api starts up that would be useful!

**Comment by nice-snek** [comment] 2017-05-10 08:20
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by sglangevin** [comment] 2017-05-11 21:18
We've now got the Standard version of person and place creation and editing forms that are being used by many projects. Ideally we should bundle those xforms with the app so that they don't have to be uploaded separately. For now, we have a script that uploads all forms and settings that is working pretty well. I'm going to mark this as scheduled as it's the ideal longer-term solution but not high priority at the moment.

**Comment by garethbowen** [comment] 2018-01-31 20:41
This is a duplicate of #3779

**Closed by garethbowen** 2018-01-31 20:41 UTC
Labels: Needs Triage, Status: 1 - Triaged
