### ISSUE TITLE
Confirmation popup should not show on 'Error loading form'? -Mobile 

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3045] opened 2017-01-12 23:36 UTC
Steps to reproduce
1. Alpha.dev >>login as admin >> 
2. People's tab >> Select any entry from the LHS with either family members or health centres >> 
3. Click New Action >> Select an action 
Results: An error is displayed, (see attached screenshot, to be investigated further, separately). 

On small screens (mobile), there is a 'close' button and when clicked, there is a confirmation popup. Since there was no form loaded, I guess this screen should just close. Note: this can be reproduced otherwise and the issue raised here is not about the error message (though this also need further investigation), but the popup

![image](https://cloud.githubusercontent.com/assets/6979995/21912737/9b138b40-d98c-11e6-93ff-7d76e0993fee.png)

**Comment by SCdF** [comment] 2017-01-13 01:24
While this is definitely a bug, I'm not sure it warrants fixing, since it's a UI grossness that only happens if you've got much bigger problems (your configured user is broken).

**Comment by ngaruko** [comment] 2017-01-13 03:49
Agree. The best strategy would be to put some validation to make it impossible to create an invalid entry. But at the same time, if it is not too hard to fix, it would come handy in cases where we couldn't anticipate all invalid scenarii.

**Comment by sglangevin** [comment] 2017-01-23 18:40
We could also resolve this by not going to the form if the form can't be loaded and showing a toast or other error message pop-up saying the form can't be opened prior to getting to the page with the form title at the top and the "Error loading form" message in gray.

**Comment by sglangevin** [comment] 2017-02-01 23:31
Duplicate of #1621 - keeping this one as there is more discussion.

**Comment by garethbowen** [comment] 2017-05-28 23:20
One commit fixes this and the related #1601

**Closed** 2017-05-29 09:41 UTC
Labels: 4 - Acceptance Testing, UI/UX
