### ISSUE TITLE
Family showing as 'District Hospital'

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3138] opened 2017-02-21 00:54 UTC
Steps; 

1. Log in as demo (alpha.dev)
2. Choose a family in LHS
3. Click 'New Person' on RHS FAB

Observed: Form shows "Belongs to 'District Hospital' 
Expected: Some other entity below district (family?)

![image](https://cloud.githubusercontent.com/assets/6979995/23146536/92ada3c2-f83c-11e6-8eaa-e21aaaae418d.png)

**Comment by sglangevin** [comment] 2017-02-23 00:45
This looks like a form config issue to me. Perhaps the forms on alpha.dev need updating.

**Comment by garethbowen** [comment] 2017-02-28 01:04
@sglangevin Confirmed - the create person form on alpha.dev has this hardcoded in it:

```
      <input appearance="db-object" ref="/data/init/id_district_hospital">
        <label>Belongs To</label>
        <hint>District Hospital</hint>
      </input>
```

Closing.

**Closed by garethbowen** 2017-02-28 01:04 UTC
Labels: Configuration
