### ISSUE TITLE
Cannot report via SMS about people who are registered in the web app

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3401] opened 2017-04-20 21:52 UTC
To reproduce:
1. Log into https://clone-barefoot.app.medicmobile.org
2. Click on Arthur's Area
3. Create a new person in that area in the web app. Sentinel will add a patient ID to this person and it will appear in the person's profile.
4. Go to Medic Reporter. Be sure to use Arthur's phone number as the "from" number. His number can be found here: https://clone-barefoot.app.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/31DA4600-27E3-1BEA-8E6E-55F13696C791
5. Send in a report about the person you just created, such as a visit report (V [patient_id])
6. Notice that you get an error, registration_not_found.

Since this person has a Medic ID generated, it should be possible to report about them via SMS, even though they were created in the web app.

**Comment by abbyad** [comment] 2017-04-26 00:53
Just noting that even though the `registration_not_found` error is given, the form is associated to the contact:
![image](https://cloud.githubusercontent.com/assets/789512/25413492/c735b54c-29f8-11e7-91fd-f8bd291b36ca.png)

**Comment by abbyad** [comment] 2017-04-26 13:12
One difference between a person created by app vs SMS is that the ones created by SMS show up in the `registered_patients` view, which is used [here](https://github.com/medic/medic-sentinel/blob/b1d97da65475494f70d1f521e925f611ae7675b4/lib/utils.js#L383).

**Comment by SCdF** [comment] 2017-04-26 16:40
Yeah that'll do it. That view is a bit of a weird one. Most code should instead use the `patient_by_patient_shortcode` view. I'll put together a PR fixing this.

**Comment by SCdF** [comment] 2017-04-26 17:08
Actually this is correct.

The new thing is that you can have patients that are not created as a result of a registration.

The current code is trying to match patient ids to registrations to work out what registrations it can potentially silence. I guess we just want to change this so that it's OK if it doesn't match a known registration, as long as it matches a known patient_id generally.

**Comment by SCdF** [comment] 2017-04-26 17:23
First stab at a PR: https://github.com/medic/medic-sentinel/pull/129

@estellecomment can you take a look at this one?

I'd like to merge into and bump sentinel so I this change can get into alpha.

I'm not able to fully test this kind of thing locally. I need to get some time with @abbyad to go through that, but for now it would be good to get this into a place where it can be tried on alpha.

**Comment by SCdF** [comment] 2017-04-26 17:24
(still active because I haven't tested it basically at all. I'll get setup and do that before closing)

**Comment by SCdF** [comment] 2017-04-26 17:27
TODO: we should also change the "registration_not_found" message to "patient_not_found", because I think in all (certainly nearly all) cases that's what we really mean

**Comment by SCdF** [comment] 2017-05-02 12:50
This has been merged to master.

**Closed by SCdF** 2017-05-02 12:50 UTC
Labels: 4 - Acceptance Testing, Bug, Priority

**Comment by abbyad** [comment] 2017-05-04 02:38
Tested on `2.12.0-alpha.5615` and can no longer reproduce... so it appears to be resolved. Thanks @SCdF!

My testing was not exhaustive though so we should test SMS reports more fully with the release to ensure that there are no regressions.
