### ISSUE TITLE
Clickable portion of action is smaller than item

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3104] opened 2017-02-07 17:34 UTC
When inadvertently clicking on the list item but not on the inner portion the action list is closed as if clicking outside the list - which is not the expected behaviour.

Only a portion of the action item is clickable, as seen in this hover over:
![image](https://cloud.githubusercontent.com/assets/789512/22703093/f00295f8-ed30-11e6-914c-91749f671d96.png)

**Comment by garethbowen** [comment] 2017-02-07 19:50
@abbyad Not a bug, because it works, it's just harder to use than it should be.

**Comment by garethbowen** [comment] 2017-02-08 10:08
I think this is fixed by https://github.com/medic/medic-webapp/commit/b7302e1a1574f75443f6c6d39f9f786178a34e63 a month ago. @abbyad What version did you find this on?

**Comment by abbyad** [comment] 2017-02-08 14:31
Indeed it is fixed in latest.

![image](https://cloud.githubusercontent.com/assets/789512/22741393/2591c634-ede1-11e6-86b2-102978497979.png)

I had labelled it as a `bug` + `ui/ux` because a user clicking it would not get what they'd expect (instead of going to a form it would close the Actions popup).

**Closed** 2017-02-08 19:39 UTC
Labels: No Action Needed, UI/UX
