### ISSUE TITLE
Results page CSS messed up in v2.11

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3369] opened 2017-04-11 21:42 UTC
Issues (as seen in screenshot below, from lg.dev on v2.11.0-beta.2):
- All text appears bold
- Icons are indented too far, overlapping with text (see Diagnosis & Treatment)
- List items (Diarrhoea for 4 days - 1 week) are not aligned correctly (the bullet point appears to be behind the text)

![image](https://cloud.githubusercontent.com/assets/1286381/24932099/e1eb4e9a-1ec4-11e7-8dfc-6fe08e71925d.png)

For comparison, here is the results screen in v2.8.5
![image](https://cloud.githubusercontent.com/assets/1286381/24932131/fe04b42c-1ec4-11e7-82bd-b0bf552740c5.png)

**Comment by garethbowen** [comment] 2017-04-11 21:45
This is really likely to happen again if Enketo decide to change their styling. Investigate if there's a way to easily include the Enketo styles required for functionality (show/hide) and not the styles for their theme. This would allow us to define our own theme which is less likely to change/break between Enketo releases.

**Comment by garethbowen** [comment] 2017-04-11 23:26
I fixed part of the issue in #3248 but obviously missed this bit. That fix was a bit hacky and a more reliable fix described above is a better idea.

**Comment by alxndrsn** [comment] 2017-04-14 13:54
> This would allow us to define our own theme which is less likely to change/break between Enketo releases.

I'm not convinced by this.  Maintaining our own theme for the whole of enketo would be a big job, and it's unlikely we cover all the input types and different ways they can occur in a page with our current set of forms.  Testing would also be required cross-platform.

On the other hand, breakages like this from upstream have not occurred frequently, and detecting and fixing does not seem to be very time-consuming.

---

For resolving this issue: the breakage in #3248 may have been caused by https://github.com/kobotoolbox/enketo-express/issues/495.

**Comment by alxndrsn** [comment] 2017-04-14 14:06
Also worth noting that we are currently handling generation of `note` HTML different to `enketo-core`.  They have moved their markdown processing to XSLT, but we have kept ours in javascript.

**Comment by sglangevin** [comment] 2017-04-17 15:51
Can someone look at this issue this week? LG will be updating soon and we'll need to resolve this before then. cc @alxndrsn @garethbowen since you are the two who have commented. I'd prefer to just fix the items listed above for now and open a new issue for creating our own theme (if we decide we want to do that).

**Comment by sglangevin** [comment] 2017-04-17 16:17
https://clone-lg-kenya.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/40A1CCEC-9CEE-DEE2-AB3E-5143AC15847E/report/pregnancy

Fill in the form for pregnancy and you'll see the issue on the results page.

**Comment by alxndrsn** [comment] 2017-04-17 17:57
Fixed on master.

**Closed** 2017-04-17 17:57 UTC
Labels: 2 - Active Work, Enketo, Priority, UI/UX

**Comment by garethbowen** [comment] 2017-04-17 23:05
LGTM

**Comment by sglangevin** [comment] 2017-05-04 21:51
Works well in v2.11.1-beta.1. Moving to ready.
