### ISSUE TITLE
The report content on the RHS should clear when there is no report on the LHS

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3146] opened 2017-02-22 05:15 UTC
Steps:
1.  go to .../medic/_design/medic/_rewrite/#/reports/
2. Select an entry with report in the LHS
3. Details will appear on the RHS pane
4. Form types dropdown, select an option with no report (like Weight for Length here)

>> Observed: LHS shows 'No Report' but RHS still displays details for the first selected report
>>Expected: RHS to clear show "No Report" 

![image](https://cloud.githubusercontent.com/assets/6979995/23198227/e4db7284-f92a-11e6-9594-95382742dce1.png)

**Comment by SCdF** [comment] 2017-02-22 11:43
imo debatable. you may wish 2 search around while looking at the report, right?

**Comment by nice-snek** [comment] 2017-05-31 13:16
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by garethbowen** [comment] 2017-05-31 21:01
This is by design. Closing.

**Closed by garethbowen** 2017-05-31 21:01 UTC
Labels: Needs Triage
