### ISSUE TITLE
Comments are not stripped out of medic-client map and reduce functions

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4965] opened 2018-11-07 14:48 UTC
Removing these comments would make the ddoc marginally smaller and might make map and reduce functions run quicker.

**Comment by garethbowen** [comment] 2018-11-07 21:12
I ran some extensive testing on possible [performance improvements of minifying views](#4082) (which includes stripping out of comments) and found that...

> PouchDB doesn't perform any faster and potentially performs slower, but it would save us about 9KB of medic-client ddoc size.

Because minification potentially makes debugging harder and could introduce bugs I concluded that it wasn't worth doing.

**Comment by garethbowen** [comment] 2018-11-14 00:39
@alxndrsn Can I close this as as dupe of #4082 or is there more to be done here?

**Closed** 2018-11-14 12:49 UTC
Labels: Needs Triage
