### ISSUE TITLE
TIMEOUT errors watching changes feed For Some Reason™

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4312] opened 2018-03-21 11:33 UTC
I've noticed this over the past few weeks, it at least affects 2.15+, though could be affecting 2.14 as well. It's really easy to tell, just log in as an admin (restricted might also cause this problem) and watch the network log in chrome tools.

You get lots of errors in changes feed watching:
![image](https://user-images.githubusercontent.com/583851/37707446-049708b8-2cfb-11e8-96ef-f60e0760e359.png)
Which when you look in the network log are cancellations because of stalling after 15 seconds:
![image](https://user-images.githubusercontent.com/583851/37707460-1660f694-2cfb-11e8-970f-a793cc6dc3f1.png)
![image](https://user-images.githubusercontent.com/583851/37707475-2493e41a-2cfb-11e8-9fbe-35615f3b17cc.png)
Stalling, according to: https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#timing-explanation
> Stalled. The request could be stalled for any of the reasons described in Queueing.
> Queueing. The browser queues requests when:
> - There are higher priority requests.
> - There are already six TCP connections open for this origin, which is the limit. Applies to HTTP/1.0 and HTTP/1.1 only.
> - The browser is briefly allocating space in the disk cache

The middle one is perhaps the most likely.

This doesn't cause any noticeable problem for users, but effectively means we hold the connection open for 15 seconds and then reestablish, which seems like a waste.

**Comment by SCdF** [comment] 2018-03-21 11:35
Relevant: https://stackoverflow.com/questions/47749806/chrome-stalls-request-for-15-seconds

**Comment by SCdF** [comment] 2018-03-21 11:38
FWIW if I know how to read the Chrome network log admins only have one open pending connection, the _changes feed request noted above.

**Comment by SCdF** [comment] 2018-03-21 11:45
This doesn't happen locally. Both (!) changes feed connections work fine.

In fact local _changes feed connection are marked as 200 not pending when they are in their polling stage, so it turns out I don't know how to read the Chrome network log!

The upshot being that:
 - The medic changes feed seems to always connect successfullly
 - The user changes feed never does, stuck in pending then being repeatedly canceled

Since this happens on servers and not locally, it's likely to be either some weird HTTPS edge case, or a badly configured nginx.

**Comment by SCdF** [comment] 2018-03-21 11:53
Same result in Firefox nightly. Their dev tools give a supposedly clearer answer:
![image](https://user-images.githubusercontent.com/583851/37708253-cffd977c-2cfd-11e8-853a-73392da8fd9b.png)
![image](https://user-images.githubusercontent.com/583851/37708262-d55f1402-2cfd-11e8-9226-1f3711585ae3.png)

_However_, changing that value to 600 (and restarted) doesn't fix the issue, so it's clearly not the only way this problem can occur.

Back to HTTP / nginx as issues IMO

**Comment by SCdF** [comment] 2018-03-21 11:56
@browndav / @henokgetachew do you have any instant thoughts about how nginx could be causing issues here?

URL that works:
 - https://beta.dev.medicmobile.org/medic/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=12742&limit=25

URL that fails:
 - https://beta.dev.medicmobile.org/medic-user-admin-meta/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=461&limit=25

**Comment by henokgetachew** [comment] 2018-03-21 12:29
I just did a quick test and this one worked for me: 
- https://beta.dev.medicmobile.org/medic-user-admin-meta/_changes
I suspect it's the request parameters causing the issues.

**Comment by henokgetachew** [comment] 2018-03-21 12:31
Actually, the whole thing now worked for me with the request parameters as well.

**Comment by SCdF** [comment] 2018-03-21 12:35
@henokgetachew so if you just log in as admin on beta.dev and leave the network + console window open, you don't get errors every 15 seconds?

I do have a crazy network setup here, this could be my fault, though I believe other people (@abbyad ?) have said they've noticed this before as well.

**Comment by sglangevin** [comment] 2018-03-21 21:52
This is definitely happening to me. I've seen it on several servers.

**Comment by SCdF** [comment] 2018-03-21 23:01
@garethbowen you mentioned it might be some kind of timeout? Both of these URLs are the same though, so if it's a couchdb timeout it's not codified in the URL

**Comment by garethbowen** [comment] 2018-03-21 23:03
@SCdF What is the value of the timeout parameter being sent to couch?

**Comment by SCdF** [comment] 2018-03-21 23:06
See this comment:

https://github.com/medic/medic-webapp/issues/4312#issuecomment-374912900

The URLs are the same, and the code for both seem to go through the same paths… the only obvious difference is one is initiated after the other one

**Comment by garethbowen** [comment] 2018-03-21 23:09
If you say so...

**Comment by SCdF** [comment] 2018-04-04 08:35
I'm putting this into 3.0. It seems like a genuine bug, I believe it causes the user db to not replicate properly, and since we don't know why it's happening I think it could easily flip around to cause the main db to not replicate properly.

**Comment by alxndrsn** [comment] 2018-04-10 17:33
I'm not sure if it's deliberate, but calls to `/medic-user-{username}-meta/_changes` are not handled by `api/handlers/changes.js`: https://github.com/medic/medic-webapp/blob/master/api/routing.js#L464

I don't think this can affect the main DB.

**Comment by alxndrsn** [comment] 2018-04-10 17:35
Removing `feed=longpoll` from the request allows it to complete successfully.

**Comment by alxndrsn** [comment] 2018-04-10 17:36
Likewise removing `since=X` from the request allows it to complete successfully.

**Comment by alxndrsn** [comment] 2018-04-10 17:37
It looks like CouchDB is behaving correctly, but nginx is swallowing the `hearbeat`s.

**Comment by alxndrsn** [comment] 2018-04-10 17:45
nginx is logging:
```
connect() failed (111: Connection refused) while connecting to upstream
```

**Comment by alxndrsn** [comment] 2018-04-10 17:45
nginx is actually forwarding the request to concierge...

**Comment by alxndrsn** [comment] 2018-04-11 10:07
<img width="326" alt="screen shot 2018-04-11 at 12 07 18" src="https://user-images.githubusercontent.com/191496/38610364-ec3fbb7a-3d80-11e8-90f0-48bc9c6334f1.png">

Looks like this can be fixed in `api/routing.js` 🙂

**Comment by alxndrsn** [comment] 2018-04-11 10:56
Can't be fixed in `routing.js`.

But looks suspiciously similar to https://github.com/medic/medic-webapp/issues/4199:
> With `hearbeat: 10000` (as we have it set in `DbSyncSrv`), changes requests consistently time out in 15 seconds.

**Comment by alxndrsn** [comment] 2018-04-11 11:49
Command: `curl '${COUCH_URL-/medic}/medic-user-admin-meta/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=737'`

Server | access method | changes result (no timeout param)
---|---|---
local (couch) | pouchdb | no timeout
local (couch) | curl | `{"results":[` received immediately; heartbeats received; no timeout
local (api) | pouchdb |
local (api) | curl | 
remote | pouchdb | timeout after 15s
remote | curl | no data received; no timeout

**Comment by alxndrsn** [comment] 2018-04-11 12:06
Looks to be identical to this (July 2016) https://github.com/medic/medic-webapp/issues/2363#issuecomment-232377434

**Comment by SCdF** [comment] 2018-04-12 07:26
@alxndrsn LGTM, leaving to you to merge / rebase

**Comment by ngaruko** [comment] 2018-05-01 01:35
Tested on `local` and `alpha.dev` (v 3.0.0). There are no errors in the console (watched over a period of time).
![image](https://user-images.githubusercontent.com/6979995/39457813-69745538-4d44-11e8-8d74-51cf09db28f2.png)

**Comment by ngaruko** [comment] 2018-05-01 22:15
The errors show again in 3.0.0 . To reproduce (hopefully)
1. login into `alpha.dev` as admin
2. go to configuration
3. click `upgrade instance`
4. watch the console
![image](https://user-images.githubusercontent.com/6979995/39495631-277aa6d6-4def-11e8-971d-5bfa41a5791e.png).
 Same observation on local instance...
I will keep this closed, since there is another issue (#4424) dealing with this.

**Comment by newtewt** [comment] 2018-09-17 20:16
Seeing these errors again when sitting on gamma.dev. Errors in the linked gist.  Logged in as medic user and sitting on the people tab. 

https://gist.github.com/newtewt/c34a4db356486f9c1a1245c072d217fa
![screen shot 2018-09-17 at 2 27 50 pm](https://user-images.githubusercontent.com/10531066/45647881-02858b80-ba95-11e8-93a7-8ae0a2d3b160.png)
![screen shot 2018-09-17 at 2 28 00 pm](https://user-images.githubusercontent.com/10531066/45647882-02858b80-ba95-11e8-8ede-30cb15660f1b.png)

**Comment by dianabarsan** [comment] 2018-09-18 06:45
I'm wondering if there's something special about `gamma.dev`.

Observed behavior is that, on `gamma.dev` only, all longpoll requests fail after one minute (even if heartbeats are received correctly). `Beta.dev`, which at the moment is running same code as `gamma.dev` (`3.0.0-beta.4`) is not displaying the same behavior:

![beta dev](https://user-images.githubusercontent.com/35681649/45668153-6b681480-bb24-11e8-83e4-6db064ba9b3a.png)
![gamma dev](https://user-images.githubusercontent.com/35681649/45668157-6e630500-bb24-11e8-9fc5-db8d2e33af08.png)

When cURL-ing, the result I get is:
```
curl -X GET \
>   'https://gamma.dev.medicmobile.org/medic/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=3079-g1AAAAFleJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____sxJv41GUpAAkk-zB6p7jU-cAUhcPUpfEwMAojU9pAkhpPUzpOTxK81iAJEMDkAKqng9SzsRGUPkCiPL9YNOTCCo_AFF-H6ycl6DyBxDlYLczPc8CAL8kYqM&limit=25' \
>   -H 'Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
{"results":[





curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

These are requests which go straight to CouchDB (untouched, only proxied by API). I think that these requests fail on CouchDB level.
It seems that `gamma.dev` is running `CouchDB 2.2.0`, while beta.dev is running `CouchDB 2.1.1`

**Comment by dianabarsan** [comment] 2018-09-18 19:48
After checking `gamma.dev` logs, `medic-api` logs are clear, but CouchDB logs are riddled with errors:

```
[error] 2018-09-18T19:43:50.638791Z couchdb@127.0.0.1 <0.18978.911> 9223d4381e req_err(2525593956) unknown_error : normal
    [<<"chttpd:catch_error/3 L353">>,<<"chttpd:handle_req_after_auth/2 L319">>,<<"chttpd:process_request/1 L300">>,<<"chttpd:handle_request_int/1 L240">>,<<"mochiweb_http:headers/6 L124">>,<<"proc_lib:init_p_do_apply/3 L247">>]
```

I've also noticed that `gamma.dev` is on a different Erlang version compared to `beta.dev`. 

@Hareet @henokgetachew do you think these errors could be connected to our failed longpoll requests?

**Comment by Hareet** [comment] 2018-09-18 23:45
@dianabarsan 

At first glance, I thought gamma.dev may have an nginx resource that was running into the HTTP/1.1 and HTTP/2 issue. 
But - I am able to retrieve results using that curl command above forcing both versions of HTTP.   

```
curl --http2 -X GET \
'https://gamma.dev.medicmobile.org/medic/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=3079-g1AAAAFleJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____sxJv41GUpAAkk-zB6p7jU-cAUhcPUpfEwMAojU9pAkhpPUzpOTxK81iAJEMDkAKqng9SzsRGUPkCiPL9YNOTCCo_AFF-H6ycl6DyBxDlYLczPc8CAL8kYqM&limit=25' \
-H 'Authorization: Basic <omitted>'
{"results":[
{"seq":"3088-g1AAAAGHeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____szKYE5_kAgXYU5LMDcwNLLFpwGNMkgKQTLIHmZT4HJ86B5C6eJC6JAYGRml8ShNASuthSs_hUZrHAiQZGoAUUPV8kHImNoLKF0CU7webnkRQ-QGI8vtg5bwElT-AKAe7nel5FgCr5Wqa","id":"appcache","changes":[{"rev":"3-3c788403719909de9d72155e1ba237d2"}],"doc":{"_id":"appcache","_rev":"3-3c788403719909de9d72155e1ba237d2","digest":"md5-v5m4DBGkLmotPYMmTJkIIQ=="}},
{"seq":"3089-g1AAAAGpeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8_


curl --http1.1 -X GET \
> 'https://gamma.dev.medicmobile.org/medic/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=3079-g1AAAAFleJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____sxJv41GUpAAkk-zB6p7jU-cAUhcPUpfEwMAojU9pAkhpPUzpOTxK81iAJEMDkAKqng9SzsRGUPkCiPL9YNOTCCo_AFF-H6ycl6DyBxDlYLczPc8CAL8kYqM&limit=25' \
> -H 'Authorization: Basic <omitted>'
{"results":[
{"seq":"3093-g1AAAAGHeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____sxJv41GUpAAkk-zB6p
```
The couchdb log errors, unfortunately, I think are related to a [misconfigured Couchdb in the docker image](https://github.com/medic/medic-infrastructure/issues/17#issuecomment-421718992) that was inherited. I recently corrected this for the container that I am testing the upgrade process on, but this misconfiguration leads to a bunch of unnecessary log flooding related to authorization. 

### Workarounds: 
- I can launch a reconfigured docker image with some couchdb fixes to test on. If Nick requires his data to be restored as-is, I’ll need a little more time. - Also launch an identical docker image with CouchDB 2.1.1 instead of 2.2.0 that we can test against  Requests: - How can I replicate this issue? The curl command above is working for me. I’m not familiar with the frontend or have any user settings done. 
- @newtewt  can you replicate this behavior locally using the docker image?

### Questions: 
- This could be related a deploy of the ALB ingress controller I’m using (nginx in local regards). I can investigate (and I’ll need some time to deploy) an alternative solution if required

**Comment by dianabarsan** [comment] 2018-09-19 04:11
@Hareet if `gamma.dev` has an nginx which is terminating requests, is this to be expected for all instances? I thought we were not using ngnix anymore and we took steps to remove all nginx related code (like specific headers that make nginx allow these longpoll requests and we added a node library which compresses http responses).

Also, the reason why your cURLs work now is because they are no longer longpolls, changes have happened since then and you receive results instantly. To properly test, you'd have to use the latest `seq` as your `since` parameter.

**Comment by Hareet** [comment] 2018-09-23 03:33
## Update on Longpolling issue:

### Background:
For our hosted solutions on AWS (multi-home docker), we utilize an AWS ALB (application load balancer) resources. In our Kubernetes cluster, we deploy a controller which automatically provisions the necessary AWS resource (ALB) and points it to the correct container port living on the docker instances the cluster manages. If a docker node fails, this kubernetes controller will be in charge of re-provisioning the ALB resource to point to the new docker node (that a different kubernetes controller) will be provisioning and re-deploying containers.

The mainstream kubernetes controller deployed to control AWS ALB resources is from CoreOS - [AWS ALB Ingress Controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller). This solution did not work for us because the controller during its healthchecks, will poll AWS and verify a variety of services are available. Unfortunately, it will fail and error if [AWS does not have WAF regional service available in the deployed AWS region](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/439). WAF is an unrelated aws resource to what this controller should be doing. There is a [pending PR](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/622) to merge a fix which make the controller check which region it is deployed and only verify services that are available in that region prior to erroring out.

Workaround was to deploy a different controller in the kubernetes cluster which would provision the necessary AWS ALB resources. [Zalando](https://github.com/zalando-incubator/kube-ingress-aws-controller) created one which seemed to work fine, but relied on a backend http router daemonset that I deployed in kubernetes cluster called [skipper](https://github.com/zalando/skipper). 

Skipper was causing our failures on gamma.dev. I tried changing multipe configurations for skipper and working with the devs in their Slack channel, but to not avail. I was requested to open up a new issue on their github (still to do).

### Solution:

I pulled Skipper out, and the Zalando Ingress Controller and after multiple other vendor ALB controller deploys, I have resulted in my own scripts setting up the ALB resource until the PR #622 above is merged. This means if a docker node failsover, there is currently a manual step to point the Load Balancer to the new instance. Pulling out the ALB Controller in our kubernetes cluster also impacted how I had planned out our multi-homing solution. That had to be re-configured using different tools pieced together with some scripts.

I deployed my ALB at `https://gamma-longpoll.dev.medicmobile.org` and it points to the same container & datastore that sits behind `https://gamma.dev.medicmobile.org`

I am not sure if I am supposed to retrieve data, but LongPolls are no longer failing after 1 minute:
![longpoll_over_1min](https://user-images.githubusercontent.com/7059119/45923867-6c4fcc00-bebf-11e8-86dc-8c60208b63bc.png)

Although - I am only recieving 
{ "results": [

@dianabarsan - Can you verify by testing against `https://gamma-longpoll.dev.medicmobile.org` that it is working as expected? cc: @newtewt 


### Followup:
Once I know this longpolling issue is working as you expect, I'll rip out the other controllers, and point the domain `https://gamma.dev.medicmobile.org` to go through the working ALB solution.

**Comment by newtewt** [comment] 2018-09-25 14:39
@Hareet  not seeing those errors anymore as well. I'm going to close this again unless you'd like it for tracking something.

**Comment by newtewt** [comment] 2018-10-08 13:21
Closing as the issue has been resolved with @Hareet 's changes.

**Closed by newtewt** 2018-10-08 13:21 UTC
Labels: Priority: 1 - High, Status: 4 - Acceptance testing, Type: Bug
