### ISSUE TITLE
Cannot have `Meta` field in XForm

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2735] opened 2016-09-10 20:58 UTC
I was getting the following errors when trying this [sample XForm](https://github.com/opendatakit/sample-forms/blob/master/eIMCI%20by%20D%20Tree.xml)*:
`Error: Invalid primary instance. Found 2 instanceID nodes but expected 1.`
`nodeset.setVal expected nodeset with one node, but received multiple`
`Error loading form. Error: ["Error trying to parse XML record. Invalid primary instance. Found 2 instanceID nodes but expected 1."]`

I cut parts of the XForm out until I narrowed down the error to having a `Meta` group:

```
    <model>
      <instance>
        <imci id="imci">
          <Meta>
            <formName>IMCI</formName>
            ...
          </Meta>
```

From my testing, the error occurs even if `Meta` is a field and not a group, and it doesn't matter that it is the first element in the group. **However, you don't get the error if you change it to `meta`, or wrap it inside another group.**

Not high priority for now as we can easily work around this limitation, but worth noting to avoid frustration!

---

_\* This form also gets a similar error unless the xmlns is removed from the instance._

```
<instance>
  <imci xmlns="http://dtree.org/e-imci" id="imci">
```

_Also, this form generates a `FormLogicError: Could not evaluate` error, likely because our XPath Evaluator doesn't support the `checklist` function._

**Comment by alxndrsn** [comment] 2016-09-12 08:35
Not sure what might be wrong with `Meta` as a tag name, but `meta` is certainly a (pending?) part of the ODK spec:
> The primary instance also includes a special type of nodes for metadata inside the `<meta>` block.
> – _https://opendatakit.github.io/odk-xform-spec/_

Do you still get the error if you have both a `Meta` and a `meta` block?  If not then the error may just be caused by a missing `meta` block.  There's no mention of `Meta` anywhere in enketo-core.

**Comment by abbyad** [comment] 2016-09-12 14:05
Good thinking. I tested again with each combination of `Meta` and `meta`:

| `Meta` | `meta` | Error? |
|:----------:|:-------------:|:---------:|
|present|present|no|
|present|absent|yes|
|absent|present|no|
|absent|absent|no|

This seems to imply that `meta` is _not_ required, and that `Meta` is forbidden as a top level element in a form - but still no clue why.

**Comment by alxndrsn** [comment] 2016-09-12 14:18
> This seems to imply that `meta` is _not_ required, and that `Meta` is forbidden as a top level element in a form - but still no clue why.

Implies to me just that you can't have `Meta` if you have `meta`.  But I do agree that it's odd!

**Comment by abbyad** [comment] 2016-09-12 14:21
> Implies to me just that you can't have Meta if you have meta. But I do agree that it's odd!

Right, "forbidden" is not correct, but think you mean "can't have Meta if you _don't_ have meta", right?

**Comment by alxndrsn** [comment] 2016-09-12 14:26
Yeah, that!

**Comment by alxndrsn** [comment] 2017-03-22 02:40
I'm surprised by this behaviour - there's nothing in `enketo-core` which suggests that capitalised `Meta` tag should be found when looking for `<meta>`, and on Chrome and Firefox XPath selecters on XML docs look case-sensitive (as they should be): https://jsfiddle.net/nwn88596/.

@marc I'll close this now as a known edge case.  Please re-open if using capitalised `<Meta>` is important or useful, or if this bug is run into frequently by tech leads, and we can investigate further.

**Closed by alxndrsn** 2017-03-22 02:40 UTC
Labels: Bug, Enketo, No Action Needed
