### ISSUE TITLE
Do not allow CHPs to Delete Old Reports

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#1851] opened 2016-01-27 05:01 UTC
In Treatments screen, the DELETE icon is active - it needs to be deactivated as it allows CHPs to delete that particular form.

We can monitor for use of the delete function in the audit logs

What is the treatments screen?  probably just allows deletion of record/report/doc.  if requirement is to block them from deleting reports, then this is LOW risk

What is the user story?

**Comment by katanu** [comment] 2016-02-19 13:41
Took a while to find out what is the treatment screen? Still unsure of it. Is there a way of finding out who logged this for follow up? However, if its the deletion of the historical record, I think it should be greyed out.

**Comment by sglangevin** [comment] 2016-02-19 17:12
@katanu I think whoever reported that meant that CHPs should not be allowed to delete reports from the history page. The current use of edit on the history page is for CHPs to edit the LMP of a particular lady, though I am not certain how frequently that is happening. I don't think we expect any need for a CHP to delete, so I agree that we should go ahead and gray out the delete option. We were requested to continue to allow CHPs to edit just in case they make an error while submitting a form. If they aren't allowed to edit, then they would have to submit another form, which would not be ideal.

**Comment by sglangevin** [comment] 2016-02-29 17:51
@diannakane since there is now a confirmed requirement that we prevent CHPs from deleting based on feedback from the LG team, could we either move this out of "needs design work" or create a new issue for that?

**Comment by abbyad** [comment] 2016-02-29 18:00
I think the design label may be appropriate here because we need to get more information on who can delete and in what situation. If that has already been figured out then this issue should be updated with that info so it can be handed over to the developers.

**Comment by sglangevin** [comment] 2016-02-29 18:05
CHPs cannot delete (restricted users) and admins can - is more info needed than that, @abbyad ?

**Comment by abbyad** [comment] 2016-02-29 18:15
We wanted to know if there are any situations where a CHP could delete. For instance we may find that they need to delete if they immediately realize they made a mistake - in which case we can look at allowing deletes of submissions not older than x days.

If the timeline is pressing for this, and it sounds that it is, we can consider implementing the blanket "CHPs cannot delete" and then revisit this after we have more information. Just to confirm, "CHP" means a user restricted to a "CHP Area"? Branch managers are also restricted users - can they delete any reports? If we implement it as such then branch managers can delete reports submitted by their CHWs as well as their own submissions.

**Comment by sglangevin** [comment] 2016-02-29 18:22
Thanks for the clarification, these are helpful questions. For now, let's implement the blanket "CHPs (users restricted to a CHP area) cannot delete" as that is what was requested. We should continue to do design work and revisit in the future. Branch managers should be allowed to delete reports, both their own and those submitted by their CHPs.

**Comment by sglangevin** [comment] 2016-02-29 20:49
@browndav @abbyad I finished testing deleting. I logged in as admin into the web app (alpha.dev) and deleted a contact. This replicated within about 30 seconds. I then submitted a report from my phone (logged in as demo) and deleted it on the web app. This replicated almost instantly. Finally, I submitted a report, put my phone in airplane mode, deleted it on the web app, then turned airplane mode off. Even with my phone effectively offline during deletion, as soon as I regained connectivity, the report was removed from my phone within 30 seconds. Happy to do further testing, but it seems like deletion is replicating properly.

**Comment by katanu** [comment] 2016-03-04 11:05
After exploring the delete functionality with the CHPs, we have not identified any situation where they would, want to, delete a historical record.The blanket "CHP cannot delete" is best way for now as we continue watching/listening. The edit functionality is limited to the fields that do not affect the decision support app flow-eg the names/phone number/age of children.

**Comment by sglangevin** [comment] 2016-03-04 19:35
Thanks @katanu. I'm not sure that we will be able to immediately implement the limited edit functionality, though it sounds like that would be the ideal scenario. I think we should actually created a new issue for that part. @abbyad can we now remove Needs Design Work and pass this on to a dev?

**Comment by abbyad** [comment] 2016-03-04 20:00
Sure thing, although we were just discussing CHPs being able to delete their test data so that it does not impact Analytics. Which is preferred, having CHPs delete their test data themselves, having an admin delete those reports, or perhaps some other way for handle test data?

**Comment by sglangevin** [comment] 2016-03-04 20:05
There are currently 2 options that are on the table for deleting data, not sure if the second one is feasible. One option is to have a manager delete training data for the branch after the training and before the CHPs start submitting real data. I asked the dev team to look into the speed of deletion at the LG Kampala office so we know if this would be too time-consuming of a task and am waiting to hear back.

The other option is that we would create a training branch and that after training each CHP would be reassigned to their actual branch to begin submitting real data. That way all training data from all branches would be on the training branch. If both options are possible, then we can choose the easier/faster of the two and update LG. They would just need to make sure this is rolled into their operational plan, but they are anticipating needing to do something to deal with training data.

**Comment by abbyad** [comment] 2016-03-04 20:10
Ok, it seems that it is preferred that CHPs not delete over simplicity for clearing out test data. Let's schedule this for the next iteration, and admin users can delete the test data for the CHPs. And hopefully they would have #1000 by then.

**Comment by diannakane** [comment] 2016-03-05 01:08
Sounds like a great plan forward. Thanks, everyone!

On Fri, Mar 4, 2016 at 12:10 PM, Marc Abbyad <notifications@github.com>
wrote:

> Ok, it seems that it is preferred that CHPs not delete over simplicity for
> clearing out test data. Let's schedule this for the next iteration, and
> admin users can delete the test data for the CHPs. And hopefully they would
> have #1000 <https://github.com/medic/medic-webapp/issues/1000> by then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/1851#issuecomment-192445575>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment] 2016-03-08 02:19
I added permissions for "can_delete_messages", "can_delete_reports", and "can_delete_contacts" so we can control access, in this case, denying CHPs. I also added a configuration UI to make it easy to set who can do each permission.

**Comment by SCdF** [comment] 2016-03-08 09:11
So changing these permissions forces an app reload, but I imagine in our current state there is little we can do about that.

**Comment by garethbowen** [comment] 2016-03-08 09:11
Yeah... #1937 :(

**Comment by SCdF** [comment] 2016-03-08 09:12
So I may not have completed some required step but I don't see the three new permissions...? I'm just clicking around to get an idea of what's changed above just looking at the code. I presume you've tested that they show up etc?

**Comment by garethbowen** [comment] 2016-03-08 09:15
I've added them to the default configuration but it won't overwrite your existing configuration, even to add new permissions. You can add them manually through the dashboard settings page.

Perhaps the configuration page should have all the ones we know about hardcoded with all roles unchecked...

**Comment by SCdF** [comment] 2016-03-08 09:17
So is this something that needs to be noted / added to release notes / etc? Or is it presumed that people understand this kind of thing and I'm being a noob?

**Comment by garethbowen** [comment] 2016-03-08 09:20
It's how it used to be managed so should be ok. They will automatically appear on new installs just not upgrades. I'll make the change to the config page so all known permissions show, not just the configured ones.

**Comment by garethbowen** [comment] 2016-03-09 00:12
Assigning back to myself to make the discussed changes.

**Comment by garethbowen** [comment] 2016-03-09 22:54
I've made the translation key changes and updated the configuration page to allow configuration of not-yet-configured permissions. Assigning back to @SCdF for review.

**Comment by SCdF** [comment] 2016-03-10 14:34
Looks good

**Closed** 2016-03-10 14:34 UTC
Labels: 4 - Acceptance testing, Feature Request, Priority
