### ISSUE TITLE
"not well-formed" error when loading enketo form

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1215] opened 2015-08-26 22:24 UTC
1. Click Submit Report
2. Select Registration with LMP
3. Check the JS console

In Firefox I'm getting the following error twice: `not well-formed <unknown>:1:77`

In Chrome I see nothing logged.

Some people are suggesting this is a CORS issue, and others thinking it's a MIME type issue on a dynamically loaded resource. No matter what I'd be surprised if this doesn't cause other errors at some point in the future.

**Comment by alxndrsn** [comment] 2015-09-02 14:24
I think this is a soft error, and unlikely to cause further issues.

It seems to be a regression in jQuery 2.1.2, which is fixed in 3.0.0-beta.  The following gives the same error:

    console.log($($.parseXML("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<empty></empty>")).find('*'));

However, it still happily gives this output:

> Object { 0: <empty>, length: 1, prevObject: Object, context: XMLDocument, selector: "*" }

I'd be surprised if this is causing other issues.

**Closed** 2015-09-02 14:26 UTC
Labels: 3 - Acceptance testing, Bug

**Comment by garethbowen** [comment] 2015-09-02 19:55
It seems to work fine, so good call ignoring this.
