### ISSUE TITLE
Error fetching settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1512] opened 2015-11-02 22:53 UTC
![image](https://cloud.githubusercontent.com/assets/789512/10896822/6b88a23a-818a-11e5-8924-198db460f8d9.png)

**Comment by garethbowen** [comment] 2015-11-03 00:42
This is caused by the Settings regression committed in #1507

**Comment by garethbowen** [comment] 2015-11-03 01:41
I'm treating this as a duplicate of #1507

**Closed by garethbowen** 2015-11-03 01:41 UTC
Labels: 2 - Active Work, Bug
