### ISSUE TITLE
Breadcrumbs in Reports tab display UUID for top-level place in the hierarchy

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3752] opened 2017-08-02 19:26 UTC
Possibly related to #3723. Needs to be fixed before we release 2.13.0.

To reproduce, log in as a restricted user and go to the Reports/History tab. You'll see something similar to the below (screenshot is from standard.app, v2.13.0-beta.2):
![image](https://user-images.githubusercontent.com/1286381/28890892-7bfcc764-777d-11e7-951d-3027df4ebafc.png)

**Comment by garethbowen** [comment] 2017-08-09 01:57
This also affects messages (and probably other places too).

The issue is the top of the hierarchy is above your replication level so the place isn't in your db so you can't work out what the name is. The solutions I can think of are...

1. Don't show any places you can't see in the list. In your example you'd only have "Toronto Health Center" in the list. This is what we do currently on the report content pane.
2. Show some placeholder, eg: "Toronto Health Center - [unknown]"
3. Change replication so you also replicate places that are parents of your place. It seems odd that you're part of a district but don't have any information about that district.

Of these, 1 is the easiest, 3 is maybe the most correct, and 2 is just silly.

@sglangevin Thoughts?

**Comment by garethbowen** [comment] 2017-08-09 23:44
The linked contacts change means the only lineage information that's stored on the doc is the UUID. That means to display the name you have to also replicate the doc that's referenced by that UUID. The replication model only ever looks down the tree, not back up. But I _think_ it makes sense to replicate below, but also directly above your facility, so you can see you're part of District A.

If you agree that it's ok for CHWs to also replicate the places above them on the hierarchy I can have a look and see how hard that would be. If it turns out really complicated we can go back to option 1.

**Comment by sglangevin** [comment] 2017-08-09 23:46
Ok, got it. What happens if CHWs replicate the places above them in the hierarchy? Do they see those places in their list of contacts?

**Comment by garethbowen** [comment] 2017-08-09 23:53
Yeah they will. I think the default view will still be your home place and its direct children, but if you search for the district you will see it. You'd probably also be able to edit it, maybe submit forms, create new health centres, etc... maybe it's not such a good idea.

**Comment by sglangevin** [comment] 2017-08-09 23:54
Yeah, that's exactly what I was thinking. I think it's more complicated than it sounds. Let's start with option 1 and we can then take some time to figure out an approach for option 3 when it is needed.

**Comment by garethbowen** [comment] 2017-08-09 23:55
Deal.

**Comment by garethbowen** [comment] 2017-08-10 23:56
Code review please @SCdF . The PR also resolves #3769 .

This needs to be backported to 2.13.x

**Comment by SCdF** [comment] 2017-08-11 09:18
Merged, backported to 2.13.x

**Closed by SCdF** 2017-08-11 09:18 UTC
Labels: 3 - Code Review, Bug

**Comment by sglangevin** [comment] 2017-08-14 21:50
Looks good in 2.13.0-beta.4. Moving to Ready.
