### ISSUE TITLE
Targets : add a description

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1944] opened 2016-02-22 09:04 UTC
Add a description field to targets, and display it in analytics/targets under a "?" icon in a tooltip.
Something like this (bubble style is not ideal, it's just what Preview had)
![screen shot 2016-02-16 at 13 45 55](https://cloud.githubusercontent.com/assets/911434/13213794/9b8b4938-d94b-11e5-8b34-6339f34626b8.png)

**Comment by garethbowen** [comment] 2017-09-11 11:04
The target widget has been redesigned and will be updated in 2.14.0 to be less confusing so I'm going to close this as a duplicate of #2522

**Closed by garethbowen** 2017-09-11 11:04 UTC
