### ISSUE TITLE
Cannot access app offline after hard close

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1566] opened 2015-11-13 16:05 UTC
Quoting @joshnesbit from https://github.com/medic/medic-webapp/issues/1343#issuecomment-156243714:

> I'm offline on my Android device (Nexus LG phone). App was already open (from previous load), and I was able to add a family / see the family. Switching to tasks tab showed the red error message for error loading tasks. Hard closed, tried opening, and saw the white error screen. Couldn't access lg.app URL, with the following error message: net::ERR_NAME_NOT_RESOLVED

> Can others confirm they're able to use the app on the Y4s, after a hard close?

When I test this I get `Webpage not available`.

**Comment by alxndrsn** [comment] 2015-11-13 16:19
Same behaviour observed here.

**Comment by mandric** [comment] 2015-11-13 18:01
Seems to work fine for me on Samsung SIII:

1) load app (based on lg.dev) and view some contacts/tasks
2) close out app so it's not running in background
3) turn off mobile and wifi data
4) start app again and it loading contacts/tasks seems normal

**Comment by mandric** [comment] 2015-11-13 18:01
Let me try adding a family...

**Comment by browndav** [comment] 2015-11-13 18:01
Are you turning off the 802.11 and cellular radios entirely, or just disabling data?

**Comment by alxndrsn** [comment] 2015-11-13 18:03
I'm turning off wifi; no SIM card present.  Working on `lg.dev` but not on `lg.app`.

**Comment by mandric** [comment] 2015-11-13 18:04
Adding family works fine too.  

I turned off/disabled wifi and mobile data.  That doesn't turn off cell radio completely but disables data functionality. I can try airplane mode too...

**Comment by mandric** [comment] 2015-11-13 18:07
Experience in airplane mode was equivalent (basic testing worked).

**Comment by abbyad** [comment] 2015-11-13 18:15
@mandric, what chrome/webview version do you have on the S3?

**Comment by mandric** [comment] 2015-11-13 18:31
SAMSUNG-SGH-I747
WebView in org.medicmobile.webapp.mobile.livinggoods (Version/4.0 Chrome/30.0.0.0)

**Comment by mandric** [comment] 2015-11-13 18:39
Sorry let me clarify, this testing was using the livinggoods app (branded app) built from latest medic-android and using a fixed_app_url (in src/livinggoods/res/values/strings.xml) of https://lg.app.medicmobile.org.

**Comment by browndav** [comment] 2015-11-13 18:43
If you open the Chrome remote debugger with the error page pulled up and the phone offline, doing the following on the Javascript console seems to get the app to start:

```js
window.location = 'https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/';
```

Is it possible that the container application just needs a trailing slash on the default URL? That's obviously not the correct™ fix, but might point us to an issue with base URL handling in the app.

**Comment by mandric** [comment] 2015-11-14 10:56
Verified this works from the app store now:

1. Totally uninstall everything LG-related.
2. Install the LG app from the play store.
3. Start it online and let it bootstrap / replicate until you see all of the usual contacts.
4. Hard close the app.
5. Take the phone entirely offline at the OS level.
6. Start the app. 
7. Observe there is no `Webpage not available` error and app works normally.

**Comment by joshnesbit** [comment] 2015-11-14 21:15
@mandric, I followed your directions on my Y4 and see this at step 7:

![opening app offline](https://cloud.githubusercontent.com/assets/377216/11165866/c1dff4f8-8ad1-11e5-96e9-48786a9e0ee5.png)

**Comment by mandric** [comment] 2015-11-14 22:51
OK @joshnesbit re-opening. Surprised because the trailing slash shows up in the error too.

**Comment by mandric** [comment] 2015-11-14 22:52
Anyone else with a Y4 want to give this a test?

**Comment by joshnesbit** [comment] 2015-11-14 23:58
Hey @mandic, this is strange! I just got this to work three times in a row on my Y4. The app loads and works fine after a hard close. The screenshot above was what I saw 3 hours ago – but it's working now.

**Comment by mandric** [comment] 2015-11-15 00:24
Yeah that is strange, especially because the error showed the trailing slash.  I thought maybe you got an old build somehow but on the old builds the error was without the trailing slash.  Maybe we'll try to reproduce on more devices and maybe should add some logging if it continues.

**Comment by abbyad** [comment] 2015-11-16 00:44
Assigned to @browndav to take another look at this, but anyone who can should pick this up due to the priority.

**Comment by browndav** [comment] 2015-11-16 15:34
I'll check this today with a clean installation.

**Comment by browndav** [comment] 2015-11-16 15:41
It's entirely possible to see that message if you open the app for the first time, but hard-close it before it's finished bootstrapping / populating the application cache. I'll try to confirm that too if I can't reproduce otherwise.

**Comment by alxndrsn** [comment] 2015-11-16 18:21
@browndav is there a ticket for displaying a prettier error?

**Comment by browndav** [comment] 2015-11-16 18:26
Just created. There's also #838, which was the older desktop non-offline issue.

**Comment by alxndrsn** [comment] 2016-01-12 14:37
(closed in error - waiting for code review)

**Comment by garethbowen** [comment] 2016-02-09 19:14
Assigned to @estellecomment for code review.

**Comment by estellecomment** [comment] 2016-02-09 19:43
That added slash LGTM. Thankfully 3 months was enough code review time to be really sure of it.

**Closed** 2016-02-29 19:28 UTC
Labels: 4 - Acceptance testing, Bug

**Comment by sglangevin** [comment] 2016-02-29 20:36
This is working well after having tried disabling data connection both before and after hard-closing the app. Moving to Ready.
