### ISSUE TITLE
Assessment follow-up schedule discrepancy 

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1757] opened 2015-12-14 08:36 UTC
Assessment follow-up schedule description (Follow-up in 2 days) on the summary page, not matching the task schedule within the contact (Follow-up in a day). 

![image](https://cloud.githubusercontent.com/assets/15346836/11776264/c6558c86-a256-11e5-9443-3736980a009b.png)
 
![image](https://cloud.githubusercontent.com/assets/15346836/11776285/e5c52c2a-a256-11e5-8971-127874f30bf4.png)

![image](https://cloud.githubusercontent.com/assets/15346836/11776294/f56cdd8a-a256-11e5-9a0b-5b198a6ad46b.png)

**Comment by abbyad** [comment] 2015-12-16 19:55
It appears that the relative day is time dependent.

For example, it is Wed Dec 16 2015 14:51:00 GMT-0500 and I get "today" for as task due tomorrow earlier in the day - Thu Dec 17 2015 12:42:33 GMT-0500.

If I set the task time to 23:59 on the 17th, I get "in 1 day"

**Comment by abbyad** [comment] 2015-12-16 20:28
Looking at tasks we currently have date+time granularity, but are trying to get daily granularity throughout. This had the undesired effect seen here.

The rules set a `Task.date` usually using `Utils.addDate()`, and then to emit or resolve the task uses `Utils.isTimely()` and `Utils.addDate()`. We need to make sure that all of these are at daily granularity in the config, or preferably in the webapp to avoid such errors when configuring new deployments.

**Comment by alxndrsn** [comment] 2015-12-17 12:15
Should a task be "due" at the _end_ of a day?  E.g. a task due Tuesday would be due at 23:59, or more accurately 00:00 Wednesday minus 1ms.  It might even be appropriate to say that a Tuesday task is due 00:00 Wednesday.

**Comment by btbonval** [comment] 2015-12-19 06:32
This might be related to the time zone bug: https://github.com/medic/medic-webapp/issues/1732

**Comment by abbyad** [comment] 2016-03-03 20:21
Ready for Review, and also on `lg-testing.app` for testing.

As a consequence of this change, some tasks may only appear a day later than previously experienced. For example, an assessment that has a followup in two days will have the task show up only a day before - tomorrow, not today. @sglangevin please note where we need to adjust task window accordingly.

**Comment by garethbowen** [comment] 2016-03-03 21:05
I don't think this is the right approach because it means every configuration will need these lines. Also I'm not convinced it will work in all cases as it might be a timezone issue as @btbonval pointed out.

Let's fix it in code instead so relativeDay works as expected in all timezones.

**Comment by alxndrsn** [comment] 2016-03-04 08:44
@garethbowen is it clear what the bug is here, or where the time/timezone is being used incorrectly?

**Comment by garethbowen** [comment] 2016-03-04 08:51
It's not clear to me yet, no. I'm not even sure which output is "correct". Or it might not even be a timezone issue. But whatever the problem is it would suck for every configuration ever to have to set the time to 23.59 to get it to work...

**Comment by alxndrsn** [comment] 2016-03-04 09:04
Agreed.

**Comment by abbyad** [comment] 2016-03-07 01:12
Since the recommendation it to not handle this in the config then it should be returned and assigned to someone else to pick up as a dev issue. I will leave the config as it is for now until this is fixed in the webapp.

We are already showing tasks on a daily resolution so this change in the webapp code would make sense... until we need tasks with finer granularity. @diannakane can you think of any cases in the near future where we would need a task done by a specific time of day, not by end of day?

**Closed** 2016-03-16 06:49 UTC
Labels: 4 - Acceptance testing, Bug, Priority

**Comment by abbyad** [comment] 2016-03-18 09:39
This is working, except that the end date is off by one. 

We can change all the schedule dates, but likely better to fix the isTimely function to match the day granularity so that it is less confusing to the configurer.

For instance, a `start` of 2 will show the task when it is `in 2 days` or less, and `end` date of 3 will show the task up to `3 days ago`.

**Comment by abbyad** [comment] 2016-03-18 09:43
Passes initial acceptance testing.

Assigning to @sharon to complete testing before moving to Ready.

**Comment by sglangevin** [comment] 2016-06-16 21:38
This has been working for a while, moving to ready.
