### ISSUE TITLE
Android URL settings error hides Save button

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1236] opened 2015-09-03 03:13 UTC
1. Use the unbranded app
2. Type in an incorrect URL
3. Hit Save and a helpful error should show up
4. Change the URL to a correct one

You should now be able to hit save again, but I've had cases where the save button was completely obscured by the error message. It seems to be a little random as sometimes the error message will disappear when I start changing the URL.

We have a lot of unused vertical real estate here, so I think we should just show the error inline in the page rather than floating it over the button.

**Comment by alxndrsn** [comment] 2015-09-03 14:22
Duplicate of https://github.com/medic/medic-android/issues/8.

I don't think in-line "error" messages are the way to go - we're currently using Android's built-in [`setError()`](https://developer.android.com/reference/android/widget/TextView.html#setError%28java.lang.CharSequence%29) method.

As discussed in the other ticket, this seems to be bad behaviour by the Tecno phone.

Would adding vertical space between [save] button and URL textview be acceptable?

@abbyad may have opinions too

**Comment by garethbowen** [comment] 2015-09-03 21:36
Yeah a little vertical space would work fine. Maybe have the save button bottom aligned?

**Closed** 2015-09-04 09:26 UTC
Labels: 3 - Acceptance testing, Bug
