### ISSUE TITLE
[android] User cannot open app when offline

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1343] opened 2015-09-28 22:16 UTC
When you switch off all connectivity (wi-fi, mobile data, basic mobile network) and attempt to open the app, this screen appears:

![screenshot_2015-09-28-15-08-16](https://cloud.githubusercontent.com/assets/377216/10150257/6a9b959c-65f3-11e5-92b2-a7ec012b8fd8.png)

Users must be able to open and use the app without any internet or mobile network connectivity.

**Comment by browndav** [comment] 2015-09-28 22:18
That's pretty important. Scheduling for this week; likely high priority if we can reproduce.

**Comment by abbyad** [comment] 2015-09-28 23:00
The workflow that we need to demo at the end of this iteration can be done online, so I would leave this for the end of this iteration.

**Comment by garethbowen** [comment] 2015-10-07 02:56
Verified. It looks like the app tries to load `/medic/login`. Instead it should direct users to the app, which will redirect them back to login if they're logged out.

**Comment by alxndrsn** [comment] 2015-10-09 13:26
I've implemented the fix as described, but it doesn't seem to improve matters.  May need extra work to get the cookie persisted between application runs (if this is desired).

**Comment by alxndrsn** [comment] 2015-10-09 14:31
I'm finding it difficult to recreate the issue as described, or to get appcache behaving in a useful way.  I also created #1419; it's potentially linked.

**Comment by garethbowen** [comment] 2015-10-11 18:47
To recreate the issue you need to stop the app running and then restart with connections disabled.

**Comment by alxndrsn** [comment] 2015-10-13 15:04
Progress!  App now shows the loading spinner for a bit before redirecting to the missing login page.

**Comment by garethbowen** [comment] 2015-10-13 19:07
It's worth adding that we only support offline mode for restricted users. Because admin connects directly to couch it will fail when offline,

**Comment by alxndrsn** [comment] 2015-10-13 19:16
Yeah, I've been working on that assumption.  Seems to work now on desktop...but on mobile just gives a white screen when the app is re-opened when offline.

**Comment by garethbowen** [comment] 2015-10-15 00:23
I forgot to link this issue. I committed a patch which appears to fix the redirecting to login bug: https://github.com/medic/medic-webapp/commit/5dda7baaff79d878f0f737d9436518a09d2eb403

**Comment by garethbowen** [comment] 2015-10-15 00:53
@alxndrsn This should be fixed now, but there might be additional edge cases to find so I'll leave it with you.

One thing that keeps tripping me up is appcache doesn't work if you omit the trailing `/` from the URL.

**Comment by browndav** [comment] 2015-10-15 01:08
Code review done, and the patch tests out good over here. Moving to ready. @joshnesbit: I'm updating lg.app right now, can you give this a test in about 15 minutes or more from now?

**Comment by joshnesbit** [comment] 2015-11-12 21:36
I'm offline on my Android device (Nexus LG phone). App was already open (from previous load), and I was able to add a family / see the family. Switching to tasks tab showed the red error message for error loading tasks. Hard closed, tried opening, and saw the white error screen. Couldn't access lg.app URL, with the following error message: net::ERR_NAME_NOT_RESOLVED

Can others confirm they're able to use the app on the Y4s, after a hard close?

**Comment by abbyad** [comment] 2015-11-13 16:02
I am seeing the same issue on my Y4. Reopening the issue.

**Comment by abbyad** [comment] 2015-11-13 16:03
On second thought, I will open a new issue instead.

**Comment by alxndrsn** [comment] 2015-11-13 16:04
:+1:

**Closed by abbyad** 2015-11-13 16:03 UTC
Labels: 5 - Ready
