### ISSUE TITLE
Not at top of content when opening Report in mobile and tablet view

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#855] opened 2015-03-27 15:28 UTC
Similar to and likely related to #808, RHS is not at top of content when opened in mobile/tablet view. This happens consistently, even on fresh reload. Opens fine in desktop mode.

**Comment by garethbowen** [comment] 2015-04-01 03:50
As you suspected, this is a dupe of #808. Closing this in favour of that.

**Closed by garethbowen** 2015-04-01 03:50 UTC
Labels: Bug, UI/UX
