### ISSUE TITLE
Form Export Feature Gives Duplicates

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#779] opened 2015-01-26 00:54 UTC
The form export feature (`export/forms/:form`), when exporting individual reports, creates exactly 36 duplicates for each report item (Equal to the number of `emit`s in the couchdb `map` function when `doc.form` is not null).  This affects analytics as we depend on the exports (The forms checked were not ANC)

The documents are not duplicated on couchdb's end.

**Comment by garethbowen** [comment] 2015-01-26 23:43
Possible duplicate of #697

**Closed** 2015-01-26 23:52 UTC
