### ISSUE TITLE
User can't change their own password

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2440] opened 2016-06-28 13:30 UTC
Reported by @Enock1990, when trying to change his password.
![2016-06-28 4](https://cloud.githubusercontent.com/assets/911434/16417169/1d4567b2-3d45-11e6-8be9-0801786efe43.png)

**Comment by alxndrsn** [comment] 2016-07-05 12:30
Locally I receive an error as above, but the password _is_ changed.  More details from the error:

<img width="1280" alt="screen shot 2016-07-05 at 13 29 14" src="https://cloud.githubusercontent.com/assets/191496/16584532/7fe73f3e-42b4-11e6-846c-86f972e6a5c2.png">

**Comment by garethbowen** [comment] 2016-07-14 02:52
I think the original issue is a dupe of #2294 - if you refresh the page with the old code the user name would be blank which is showing in the URL that 404s. This is now fixed in alpha.

Furthermore @alxndrsn found the secondary bug which I've fixed.

**Closed** 2016-07-14 10:08 UTC
Labels: 4 - Acceptance Testing, Bug
