### ISSUE TITLE
New family automatically added to branch, no option to select CHP area

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2193] opened 2016-04-13 00:09 UTC
add place > family from contacts tab (Dianna Kane Family) automatically added to Busia Branch. No option to select a CHP area to add to, nor any place to change this, that I can tell. 

I will include this in the Contacts design issues, but wanted to call it out in case it affects our current deployments.

**Comment by garethbowen** [comment] 2016-04-13 00:22
I think this is by design. The LG forms were designed to be used by CHPs who only have access to one branch.

**Comment by diannakane** [comment] 2016-04-13 00:35
Families are generally added to CHP areas though, not branches, but maybe
it is configured to automatically enroll to your CHP area and I'm messing
it up by using the Admin log-in.

Good to know this is configurable though. We want to be able to add and
assign a family to any CHP area we choose with an admin or facility log-in
and will include it as an option in the UX (to be hidden if desired). This
will satisfy the story of a nurse enrolling a new family and assigning them
to the CHP Area where they live.

On Tue, Apr 12, 2016 at 5:22 PM, Gareth Bowen <notifications@github.com>
wrote:

> I think this is by design. The LG forms were designed to be used by CHPs
> who only have access to one branch.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2193#issuecomment-209162135>
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment] 2016-04-13 00:41
Ahh right. The family is added to whatever place is configured for the user you've logged in as. It would be good to reconfigure the contact forms to have an extra page for which CHP area want the family to be assigned to, which can be skipped over when you only have one option.

**Comment by alxndrsn** [comment] 2016-05-31 11:28
It doesn't seem like this requires work at this time.  Please re-open if I got that wrong.

**Closed** 2016-05-31 11:28 UTC
Labels: No Action Needed
