### ISSUE TITLE
Creation of family allows for duplicates

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3130] opened 2017-02-20 04:42 UTC
Steps:
1. logged in lg.dev
2. people's tab
3. Busia CHP Area
4. New Family
5. Select an existing person
6. Select family
7. 'Yes' to "Would you like to name the place after the primary contact: "Adele Manga's Family"?" and Submit.
8. Do it over and over

>>Expected: Warning/Error maybe like 'the name/family already exist' or ?
>> Current :: Lots of 'families' are created with the same name. Maybe that is expected in case people have the same name?

![image](https://cloud.githubusercontent.com/assets/6979995/23112295/273f055c-f794-11e6-8bc1-842b377c1abd.png)

**Comment by SCdF** [comment] 2017-02-20 11:44
Are you seeing this in production? Or just in test data?

It's unclear if we would be able to simply ban families with identical names, though I imagine we could add a validation step and a few to furnish us with that data if we a) were comfortable with it and b) it was an actual problem. However… http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by sglangevin** [comment] 2017-02-23 00:49
We specifically do not look for duplicates for names of families because there may be multiple families with the same name and limiting that would be restrictive for CHWs.

**Comment by garethbowen** [comment] 2017-02-27 22:21
Closing as by design.

**Closed by garethbowen** 2017-02-27 22:21 UTC
