### ISSUE TITLE
Cannot open certain families on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3854] opened 2017-08-31 14:25 UTC
Web app version: 2.13.0-beta.10
Android container version: 0.1.157

This can only be reproduced on mobile - families load correctly in the browser.

When clicking on certain families, I get the following error in the console:
![image](https://user-images.githubusercontent.com/1286381/29928150-34d4d352-8e36-11e7-8faf-0dc967ad065d.png)

**Comment by sglangevin** [comment] 2017-08-31 14:26
You can reproduce by logging in as demo1 on lg.dev. PM me for the password.

**Comment by sglangevin** [comment] 2017-08-31 14:55
This bug does not exist in the most recent version of the Android app (0.3.6) so we may be able to safely ignore it.

**Comment by garethbowen** [comment] 2017-09-03 22:22
I expect this will be a duplicate of #3855

**Closed** 2017-09-03 23:15 UTC
Labels: Won't fix: Duplicate
