### ISSUE TITLE
V2 scheduling EDDs on a Sunday for all ANC registrations

### ISSUE THREAD

**Issue by billwambua** [medic/medic-webapp#3563] opened 2017-06-20 13:28 UTC
Before V2, all EDDs fell on a Sunday but it was not apparent because the shown EDD did not include the day of the week was not indicated e.g 2017-11-13

But now the EDD includes the day of the week e.g Sun, Aug 6th, 2017. See below screenshots.

![ancp1](https://user-images.githubusercontent.com/17000106/27338181-30ce0472-55dd-11e7-8499-26beb3270d26.png)
![ancp2](https://user-images.githubusercontent.com/17000106/27338182-30d47082-55dd-11e7-8baf-2a7558ac3b2d.png)
![ancp3](https://user-images.githubusercontent.com/17000106/27338180-30c7c7c4-55dd-11e7-823e-d66eb60ab040.png)

This has been confusing the partners as they feel the calculation involved may not really be accurate as it should be. 
See the issue as reported on `medic-projects` https://github.com/medic/medic-projects/issues/2232

The suggestion is that the date formatting could be changed to NOT have the day of the week i.e Sun, or the Sentinel code could be changed to remove the specification for `startOf('week');` and instead just calculate from the exact provided date so that the EDD is an exact addition from the stated LMP.

**Comment by henokgetachew** [comment] 2017-06-20 14:07
@billwambua I have removed the screenshots.

**Comment by henokgetachew** [comment] 2017-06-20 14:23
I was just a part of a call discussing this with the partner.  The issue with making it on Sunday, even though it's an approximation and we're referring to the week, is that since doctors don't get in on Sundays and they are instead on call.  Instead, they propose choosing Wednesday of that week.

**Comment by sglangevin** [comment] 2017-06-20 16:21
@henokgetachew @billwambua I would have liked to finish this discussion in medic-projects before moving this issue over. Thanks @henokgetachew for removing the screenshots.

To me, this sounds like a partner-specific issue but I also imagine that most other clinics are not staffed on Sundays. The problem is that we are collecting "weeks since LMP" so we don't know exactly which day the last period started, which means calculating the EDD using LMP + 280 days would also not be accurate.

And finally, before we were to choose a random day like Wednesday, I'd like to get feedback from other partners on what their preferences are. I was thinking that Monday would make more sense since it's the start of the week and might work better across the board.

Do we have other partners that we can talk to who can give their opinions on this? Or perhaps @aikajanet or @katanu have opinions?

**Comment by garethbowen** [comment] 2017-06-20 21:39
This is configurable per project either through the UI at `/configuration/settings/advanced` or via app_settings properties `date_format` (for dates) and `reported_date_format` (badly named, but for datetimes).

**Comment by henokgetachew** [comment] 2017-06-21 08:39
@garethbowen is the configuration for how we are displaying the date or can we actually choose which day of the week the EDD falls on?

**Comment by garethbowen** [comment] 2017-06-21 08:46
@henokgetachew I was just talking about the part about removing Sunday from the output, but it looks like that's known already. Choosing which day of the week the EDD falls on is not configurable.

**Comment by henokgetachew** [comment] 2017-06-21 10:00
Yeah, that was my understanding as well.  That was our second proposal to them: just changing the format to not show the day of the week.

**Comment by ranjuts** [comment] 2017-07-04 06:15
@garethbowen we can't configure which day of the week the EDD falls on but can we configure to not have if fall on the start of the week but on the exact day calculated? The reminders are sent on the exact day so I would assume it is possible to calculate the EDD similarly?

We have had partners be confused here in Nepal as well ( @PawanMM can comment more) because of this same issue. However, I want to clarify that it is not specifically because it's a Sunday but because its rounded off (referring to what Henok mentioned re doctors not being on regular duty then, and I agree with Sharon here that this preference of a particular day would be partner specific so should not be applied to our webapp as a general feature). I agree that EDD is not accurate regardless of how it is calculated but the fact that we are basing it off of 'weeks since LMP' the users are already rounding it off once (before data is sent). If we configure to have it fall only on Sunday or a particular day of the week, we are rounding it off once more which makes it harder for our partners to trust the date. 

Changing the date format to not show the day of the week would be a bandaid solution that would only work with new partners that haven't yet noticed this.

**Comment by garethbowen** [comment] 2017-07-04 08:50
@ranjuts I completely agree. The code to round down to the start of the week was added about four years ago and I have no idea what the rationale was. Unfortunately it is hardcoded into sentinel. For now the bandaid solution is all I've got.

@sglangevin I think we should remove the rounding code in 2.13.0. I'm a little concerned that someone may be relying this behaviour as it's been part of the app for so long. Can we ask around and find out?

I suspect nobody even realised this was happening and will be happy with it being fixed.

**Comment by ranjuts** [comment] 2017-07-04 11:57
Thanks Gareth. If this was done around four years ago @mandric might know what the rationale was? Perhaps @diannakane as well?

**Comment by mandric** [comment] 2017-07-04 17:38
Yes a prehistoric choice indeed, made by Rowan in fact, probably according to the initial OHW project spec that spawned that feature.  It's in one of the earliest commits of sentinel and the git history wasn't preserved (looks like a copy from kujua-lite) so there's not much to go on.  I imagine it has something to do with calculations or analytics that are easier to do if you standardize on a week day that begins a week.  https://github.com/medic/medic-sentinel/blob/39a2914525e5dff825e665662b96528cfc2c0f87/test/unit/ohw_registration.js#L46

**Comment by sglangevin** [comment] 2017-07-04 18:33
@garethbowen I'd like to finish the other priorities that are already in 2.13.0 - several items are still not complete. I had planned to schedule this one for 2.14.0 so that we could also handle any changes needed to message scheduling per our conversation on Slack.

**Comment by garethbowen** [comment] 2017-07-04 21:15
Ok. I'll add this to the 2.14.0 project. Should be a quick fix.

**Comment by sglangevin** [comment] 2017-08-31 13:26
Assigning to myself for AT.

**Comment by sglangevin** [comment] 2017-09-11 22:53
AT blocked on #3894.

**Comment by sglangevin** [comment] 2017-09-14 21:17
LGTM. EDD is now scheduled based on the day the pregnancy registration is submitted.

**Closed by sglangevin** 2017-09-14 21:17 UTC
Labels: medic-sentinel, Status: 4 - Acceptance testing, Type: Bug
