### ISSUE TITLE
README - Some issues during my first-time developer experience

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#4826] opened 2018-09-14 09:05 UTC
I got a development environment up and running this week on Ubuntu (no horticulturalist and no medic-os). Overall the docs were great and the path forward was clear but sometimes bumpy. Thought I'd share some of the stumbling blocks/learnings.

Happy to chip in and improve things if you agree with any of these issues. I marked the issues I have been unable to resolve - grateful for any tips! 

1. I set my own password when the CouchDB install prompted me to create the admin account. I tried to use the dofferent admin password via env but got stuck by a few hardcoded spots. Gave up after a couple, but maybe either fix that or just mention to use `admin:pass`
1. Setting `require_valid_user` also means Fauxton doesn't work within a browser. This is a super nice tool for getting started and learning about CouchDB! Was helpful for me to set `httpd/WWW-Authenticate = Basic realm="administrator"` maybe just a [link](https://github.com/apache/couchdb/issues/1305).
1. Can remove the details about CouchDB 1.x. Seems unnecessary since 2.x is listed as "required".
1. The reference to `load_messages.js` may be more helpful if it also linked to sample data.
1. [Unresolved] The command to set `max_http_request_size` didn't work for me. The command has an extra `'` in it. I get `{"error":"not_found","reason":"no such node: couchdb@localhost"}` when I execute. So far doesn't seem impactful.
1. [Unresolved] I'm having some problems with `husky` and `prettier-quick` reformatting pages as part of git precommit. Have it disabled for now, but maybe this is familiar to somebody.

**Comment by dianabarsan** [comment] 2018-09-28 07:16
Closing this as all points have been resolved, except for one.
The one unresolved point (nb. 4 regarding sample data) should be dealt with as a separate issue.

**Closed by dianabarsan** 2018-09-28 07:16 UTC
Labels: Help Wanted, Priority: 2 - Medium, Status: 1 - Triaged, Type: Technical issue

**Comment by dianabarsan** [comment] 2018-09-28 11:55
@kennsippell 
This has acutally been discussed and (somewhat) decided when the `prettier` formatter was added. 
The discussion and it's conclusion is available on the PR (https://github.com/medic/medic-webapp/pull/4760#issuecomment-413831006)

**Comment by srsudar** [comment] 2019-04-28 23:05
I'm seeing similar issues following the README.

Not sure if it's productive to pile on here, but here they are as an FYI. I can open a new issue if you think these are worth addressing.

1. I needed node <12, as otherwise I got errors with v8. Something about no method `IsNearDeath`. Maybe v12 is having an existential crisis. Fixing this was easy using `nvm use 11`.
2. `npm ci` was failing because `gyp` required python 2.x. This too was relatively straight forward using `conda`.
3. I couldn't get the `docker-compose` route to succeed on Mac 10.14.4, but this is mostly fine since I am hoping to hack on the source, not just deploy it. I was able to get `docker-compose` working both on GCP and my Ubuntu workstation. If it is also supposed to work on Mac, there might be something going on.
4. The bind address suggested during couch installation for me was `127.0.0.1`. When running `npm start` the API was failing, complaining that it couldn't find `couchdb@localhost`. Instead I had to use `COUCH_NODE_NAME=couchdb@127.0.0.1`.
5. After running `npm start` succesfully, I can navigate to `http://localhost:5984/medic/login`. Unlike when starting with `docker-compose`, I didn't see any output from `grunt`/`npm` with an admin password. When I try with my couch credentials, I get directed to `http://localhost:5988/admin/` with the output: `{"error":"unauthorized","reason":"Authentication required."}`. Did I miss an admin user somewhere?  Which credentials should I be using?

**Comment by garethbowen** [comment] 2019-04-28 23:24
Thanks for letting us know @srsudar !

With item 5, the credentials should be the same as your couchdb credentials.

Would you mind raising issues for each of these points with as much information as you can to help us reproduce them?

**Comment by srsudar** [comment] 2019-05-03 03:49
Did the CSV sample data ever come about? I don't see another issue as suggested, but I'd love to have some data to play with.

**Comment by srsudar** [comment] 2019-05-06 20:21
It sounds like there is some sample data somewhere. I'd love to see some sample data and/or a test deployment with some fake data if such a thing exists!

**Comment by garethbowen** [comment] 2019-05-06 21:42
We were working on that recently. @newtewt Have you got a script you can share?

**Comment by newtewt** [comment] 2019-05-07 12:11
Yeah we have a set of sample CSVs to use with medic-conf. The script still needs some work but the manual commands are still available. The csvs are currently on our private google drive. We'll need to work out where to share.

**Comment by srsudar** [comment] 2019-05-07 12:42
Even just the schema would be something. I can populate a few lines with lorem ispum. As it is I don't even think I know enough about the CSVs to fake it.

**Comment by newtewt** [comment] 2019-05-07 12:47
@srsudar  I've attached the demo data. It's very basic and repetitive. Have you applied the standard config to your environment? If not I can give you some steps. 
[Seed Data(csv-to-docs).zip](https://github.com/medic/medic/files/3152674/Seed.Data.csv-to-docs.zip)

**Comment by srsudar** [comment] 2019-05-12 04:07
Thank you, I'd love some steps!

**Comment by garethbowen** [comment] 2019-05-12 22:01
@newtewt Maybe we should update the README with an optional section on installing standard config and demo data?
