### ISSUE TITLE
Task issues for restricted user when a report is deleted on the server

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3189] opened 2017-03-02 18:06 UTC
Follow-up from testing related to #3001. We need to fix these before we release v2.10.0.

A few outstanding issues related to deletion of reports. The deleting part works well but tasks are still not disappearing/reappearing as expected (i.e. a refresh is needed for them to disappear/reappear correctly). These were found on 2.10.0-beta.8, tested on lg.dev.

To reproduce, delete any report when logged in as admin on the web app and then look at different tabs when logged in as a restricted user.
1) Tasks that were cleared by a report that has since been deleted do not reappear on the tasks tab. Example: If you delete an assessment follow-up, the follow-up task should reappear on the tasks tab and it doesn't.
2) Tasks that were cleared by a report that has since been deleted do not reappear in the tasks section of the person's profile. Same example as above, the follow-up task should reappear on the profile of the person the task is about.
3) Tasks that were generated based on a report that has since been deleted do not disappear from the tasks section of the person's profile. Example: register a pregnancy with risk factors. This generates a follow-up task (pregnancy visit) for the woman. Then delete the pregnancy registration. The task disappears from the tasks tab but not from the woman's profile page.

**Comment by SCdF** [comment] 2017-03-03 08:09
From what I can tell from the code, the rules themselves have to check whether a report is deleted? Going by [this code](https://github.com/medic/medic-webapp/blob/master/static/js/services/rules-engine.js#L143-L158). That would lead me to think either a) we should change this to delete the data_record fact entirely, or b) this is an issue with the rules over the code.

**Comment by garethbowen** [comment] 2017-03-06 00:17
Code reviews please @SCdF . These two PRs are unrelated.

The root cause for 1 & 2 was that a task was being marked resolved even if the report that was resolving it was marked deleted. In [the first PR](https://github.com/medic/medic-webapp/pull/3200) I've made a change to the `Utils.getMostRecentReport` function to fix this. This can be worked around in production in pre-2.10 versions by avoiding the use of the `Utils.getMostRecentReport` and `Utils.getMostRecentTimestamp` functions.

The root cause for 2 & 3 was that the contact profile was only ever updating tasks and never removing them. In [the second PR](https://github.com/medic/medic-webapp/pull/3201) the code now splices tasks out of the task list when they are `deleted` or `resolved`.

**Comment by SCdF** [comment] 2017-03-06 08:25
Both LGTM, merged, over to you to pick into 2.10.

**Closed** 2017-03-06 08:48 UTC
Labels: 4 - Acceptance Testing, Bug

**Comment by sglangevin** [comment] 2017-03-06 20:09
@garethbowen this is looking really great! Thanks for putting the time in to fix these issues - everything related to tasks is working exactly as expected. The only remaining issue I'm seeing is that Targets don't update until a refresh after a report is deleted. Is that a small thing we can fix now? If not, it can wait.

**Comment by garethbowen** [comment] 2017-03-06 20:11
Oh man, I forgot about Targets. Let me pop the code and find out... :mag:

**Comment by garethbowen** [comment] 2017-03-06 20:28
Ok. It looks like that's a regression caused by the change to `Utils.getMostRecentReport` and `Utils.getMostRecentTimestamp` where we used to get the deleted report returned and now don't. I think this is better fixed in configuration. I can update the Utils to provide a convenience method if you like? eg: pass `true` to include deleted reports.

**Comment by sglangevin** [comment] 2017-03-06 20:32
Sounds good. Let me see if I can figure out a good solution in config and if not, then a convenience method would be great.

**Comment by sglangevin** [comment] 2017-03-07 20:21
Working well.
