### ISSUE TITLE
Remove `can_access_directly` permission

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4144] opened 2018-01-30 09:39 UTC
If a `district_admin` has the `can_access_directly` permission then they'll end up using the couchdb filtered replication instead of our performant version. This is due to an inconsistency where the DbSync service checks if the user has the `admin` or `national_admin` role but the changes handler in api checks for the `can_access_directly` permission.

This caused a bug recently where a restricted users initial replication was timing out due to the native filtered replication algorithm.

1. Modify the changes handler to be consistent with the DbSync service and check for `admin` or `national_admin` roles.
2. Investigate other areas the permission is used to see if it can be removed.

**Comment by rmhowe** [comment] 2018-02-01 15:41
@garethbowen do you know if there was a reason the `district_admin` had the `can_access_directly` permission? (or any reason that this should ever be the case?)

**Comment by sglangevin** [comment] 2018-02-01 18:59
That sounds like a misconfiguration to me. We've run into this before where incorrect permissions were applied to a particular instance by mistake. I think since in our case the `district_admin` is always the restricted user, there is no reason they would ever need the `can_access_directly` permission.

**Comment by garethbowen** [comment] 2018-02-01 20:00
I agree with Sharon - it's hardly used, and where it is used it doesn't make any sense to set it on a district_admin. I suspect someone either misclicked, or because we have [insufficient documentation on permissions](https://github.com/medic/medic-docs/blob/master/configuration/permissions.md), didn't know what it was for.

**Comment by rmhowe** [comment] 2018-02-02 12:54
The only other use in the app then is to determine whether the user can see the `Export` icon in the action bar in the Reports, Contacts, and Messages tabs. Not sure how configurable this needs to be? If we still need it for this purpose we can just rename the permission to something more sensible (like `can_view_export_action`).

**Comment by sglangevin** [comment] 2018-02-02 18:38
As long as `national_admin` people can see the `Export` icon, that will keep things consistent with what is currently happening. `district_admin` people don't see Export now anyway.

**Comment by rmhowe** [comment] 2018-02-06 21:03
@alxndrsn ready for review

**Comment by sglangevin** [comment] 2018-03-16 04:16
Should this have removed the permission from the list of permissions? Or does config have to be updated for that to happen? I'm wondering because beta.dev has been upgraded and I still have this permission listed on the permissions page.
![image](https://user-images.githubusercontent.com/1286381/37503519-21c9ec70-2896-11e8-9ef0-d406219092ab.png)

**Comment by sglangevin** [comment] 2018-03-16 16:16
Since @rmhowe is out, assigning to @garethbowen - feel free to redistribute.

**Comment by garethbowen** [comment] 2018-03-18 20:56
@sglangevin My guess is that your existing configuration hung around it's just not used any more. We should clean this up in a migration.

Unassigning myself so anyone can pick it up.

**Comment by garethbowen** [comment] 2018-03-22 19:59
Back to you @alxndrsn

**Comment by ngaruko** [comment] 2018-04-05 03:44
LGTM

**Comment by garethbowen** [comment] 2018-05-15 02:09
This migration is badly broken and should not have passed AT. It looks like the code changed significantly between code review and commit. This migration blows away all your permissions so you get reset back to default. This is a blocker for 2.15.0.

**Comment by garethbowen** [comment] 2018-05-15 09:44
In 3.0.0 this is fixed as part of #4541 which changes how we store permissions.

**Comment by garethbowen** [comment] 2018-05-15 10:07
As far as I can tell this never made it in to the `2.15.x` branch so shouldn't have passed AT. I'll backport it now and submit for AT again.

When ATing ensure that the permission is removed and also that all other permissions remain and don't revert to default.

**Comment by garethbowen** [comment] 2018-05-15 10:17
Code review please @alxndrsn

**Comment by ngaruko** [comment] 2018-05-24 05:35
Confirmed on `beta.dev` version `2.15.0-beta.12` . The `can_access_directly` permission has been removed from the list...
![image](https://user-images.githubusercontent.com/6979995/40466203-907fcdce-5f78-11e8-887e-141863db1485.png)

**Closed by ngaruko** 2018-05-24 05:35 UTC
Labels: Priority: 2 - Medium, Status: 5 - Ready, Type: Bug
