### ISSUE TITLE
Fix broken "Reporting Rates" interface in release

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1030] opened 2015-06-23 21:34 UTC
From medic/medic-projects#30: the pie-chart "Reporting Rates" interface is obviously broken – we're seeing Javascript errors related to `.scrollHeight` and `.forEach` on an `undefined` object. We should fix this.

**Comment by garethbowen** [comment] 2015-06-23 23:40
The UI screenshotted in that issue was [fixed in January 2015](https://github.com/medic/medic-webapp/commit/44aed97f159588f813595008e43267ac0b074758). I've just fixed a couple of bugs introduced since then and it's mostly working. The major flaw I found is the UI only displays data on the first scheduled form, and provides no way to switch between forms.

**Comment by garethbowen** [comment] 2015-06-24 09:08
It's working in `develop`, but needs a fair bit of migration to get working in a release.

**Comment by mandric** [comment] 2015-06-24 13:08
I'll use this issue until it's working in a release.

**Comment by browndav** [comment] 2015-07-28 18:01
Update: on Monday, we agreed it'd be a good idea to add facility selection back in, possibly borrowing/reusing the facility selection dropdown from the `Reports` tab. Mixed in with this issue is some general learning/getting-up-to-speed with Angular.

@mandric: Just for planning purposes, can you give a quick update / remaining effort estimate?

**Comment by abbyad** [comment] 2015-07-29 00:41
We already have tentative design discussed already in #1056, just calling out that we should have this feed back into the design process that will yield some mockups for the update.

@mandric, can you check in with @Lesterng about this?

**Comment by browndav** [comment] 2015-08-03 23:08
From today's call: we agreed that we'd take the non-routed easy approach to form selection to try to get this shippable by end of day Tuesday (7/3).

**Comment by mandric** [comment] 2015-08-04 21:50
```
( ) confirm dropdowns are not affecting other tabs
(x) doesn't work on direct link (or refresh)
( ) doesn't show selected values in dropdown 
(?) should filter health centers based on district
(x) rename /analytics/stock /analytics/reporting and Stock Monitoring -> Reporting Rates
( ) use Facility instead of FacilityRaw
( ) delete unused kujua-reporting views (maybe kujua-reporting.views.facilities_by_parent)
(?) rename format.facility to format.name
( ) write tests and fix tests
```

**Comment by abbyad** [comment] 2015-08-11 12:36
@mandric, can you please point me to an instance with data for acceptance testing.

**Comment by mandric** [comment] 2015-08-11 16:56
http://52.25.132.140/medic/_design/medic/_rewrite/#/analytics/

**Comment by abbyad** [comment] 2015-08-11 20:11
Thanks @mandric, this looks great!

I am digging through for acceptance testing and will post issues here as I go.

On first pass, I see the text in French, regardless of my locale and see this in the console:
![image](https://cloud.githubusercontent.com/assets/789512/9209213/53a27250-4043-11e5-8a2f-f003ed4a903f.png)

Also, clicking on a form expands to a "Loading..." but get this error in the console: `TypeError: exports.info.getForm is not a function`

**Comment by mandric** [comment] 2015-08-11 20:39
Marc, that locale issue might be be because of the IH Senegal settings I'm using to demo/test are a little weird. 

You should never see a "Loading..." maybe you're not looking at a fresh copy?  I also just pushed a related fix, please try again.

**Comment by abbyad** [comment] 2015-08-11 20:55
As far as the mobile view goes, nice job on making it usable in its current form. There are some UI tweaks for the mobile view but they can likely wait.

Here are some other things I noticed:

**(1) The Form filter** box should show the form name, not just the form code. For many projects the form codes are not known or don't have special significance, especially by the higher level managers that are looking at the Reporting Rates. This is especially true of projects using Medic Collect or SIM apps, since the form code is only used behind the scenes and never seen by a user. We should reuse the same icon and look as the Reports tab:
![image](https://cloud.githubusercontent.com/assets/789512/9209927/3788de20-4047-11e5-91e1-8a6f599bda19.png)


**(2) Health Center filter** seems confusing to me since it doesn't cascade from the Districts filter. Unless it is a 5 minute task to make this cascading, I would actually remove this filter for now - you can navigate to the Health Center via the district.


**(3) Period dropdown** would fit well as a top level dropdown, like the "filters". Changing it and having it modify the pie chart above and the content below doesn't feel right.


**(4) Blank page** when switching between tabs:
![image](https://cloud.githubusercontent.com/assets/789512/9209532/046f746a-4045-11e5-8390-124c523924d5.png)
![screen shot 2015-08-11 at 16 21 34](https://cloud.githubusercontent.com/assets/789512/9209538/0d090ffa-4045-11e5-9007-249020483ce7.png)
To reproduce load Reporting Rates, go to another tab, then back to Analytics tab. The page displays properly again after a reloading.


**(5) Datetime format** should be that which is configured in app_setting
![image](https://cloud.githubusercontent.com/assets/789512/9209821/89304462-4046-11e5-9920-112cf9ba2640.png)


**(6) X Icon** looks like a close or a delete:
![image](https://cloud.githubusercontent.com/assets/789512/9210229/10cc3ed8-4049-11e5-9b95-7317b19903be.png)
It may be better to have a warning/exclamation

**(7) Reply and Message icons** use different icons, but probably better off using the same envelope. We can revisit this during a UI pass at a later time.

**Comment by abbyad** [comment] 2015-08-11 22:01
Looping @yembrick in here to provide some feedback for acceptance testing as the Analytics Lead.

**Comment by browndav** [comment] 2015-08-11 22:42
Just to be clear, we may not want/need to fix all of the UI/UX issues immediately. Worth a chat during our iteration call (or earlier if needed).

**Comment by mandric** [comment] 2015-08-12 02:27
@abbyad thanks for the feedback.

2) I did the health center dropdown to mimic the siblings dropdown that we used to have so you can quickly jump between sibling health centers without going back and forth. It seemed useful to me to have a list of health centers anyway, maybe not.

4) This should be fixed, maybe you were getting cache.  Let me know if you can reproduce it after a hard refresh.

**Comment by abbyad** [comment] 2015-08-17 21:06
@mandric, do you mind updating the Acceptance Testing Instance to close off acceptance testing?

**Comment by mandric** [comment] 2015-08-17 21:46
Should be updated @abbyad.

**Comment by abbyad** [comment] 2015-08-18 01:43
Thanks, seeing the updates.

After a successful load, switching Districts yields errors and get a blank analytics content section. Here are the console errors:
![image](https://cloud.githubusercontent.com/assets/789512/9320506/dec18a8a-4528-11e5-9181-32aa8ab6651c.png)

**Comment by abbyad** [comment] 2015-08-18 01:47
Actually, refreshing the page I get time outs, so it is likely related. Not sure why the instance is not responding anymore. @mandric, are you able to reach http://52.25.132.140/medic/_design/medic/_rewrite/ ?

**Comment by mandric** [comment] 2015-08-20 03:11
Now available at https://rc.dev.medicmobile.org/medic/_design/medic/_rewrite#/messages.

**Comment by mandric** [comment] 2015-08-25 15:20
After discussion with @abbyad decided to go with removing the health centers list for item (2).   A filtered dropdown of health centers (siblings) might be  added to the next iteration.

**Comment by mandric** [comment] 2015-08-26 02:13
@abbyad I just pushed a new rc have a look when you have a moment.

**Comment by abbyad** [comment] 2015-08-26 03:07
Thanks @mandric. After drilling down from the District Level to the Health Center level, how do you go back to the District view? Right now the two ways I can do it is with the browser's Back button, or by reselecting the same district from the District dropdown. This comment is relevant regardless of whether the Health Centers dropdown was removed or not.

It may be useful to have a simple breadcrumbs at the top, or a back button. Unless one of these is actually quick and low risk to implement, I'd say we leave it as for this release with this known issue, and come back to it to do UX/UI updates during a future iteration.

**Comment by mandric** [comment] 2015-08-26 13:10
That's true we're missing navigation breadcrumb or two, back button should also work fine though.  I'll push forward the release and create another issue for UI tweaks.

**Comment by mandric** [comment] 2015-08-26 13:13
We might even hold off on the UI tweaks since we're doing a UI revamp on develop (#1032)?

**Comment by mandric** [comment] 2015-08-26 13:46
I'm closing this, we should work on navigation and UI tweaks on the new issues in the newer branches.

**Closed by mandric** 2015-08-26 13:46 UTC
Labels: 5 - Released, Bug
