### ISSUE TITLE
Error after submitting form that causes all tasks and add family button to disappear and makes targets tab blank

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3157] opened 2017-02-24 00:56 UTC
Seen on alpha.dev (v2.10.0-alpha.4874), logged in as demo user. 

All affected tabs work fine after a refresh. Note that this bug is a blocker that will prevent Android projects from upgrading to v2.10 and will likely affect Standard.

Here is the console output:
![image](https://cloud.githubusercontent.com/assets/1286381/23285769/13408dd6-f9e8-11e6-9632-dea99e723c8d.png)

Tasks tab before submitting report:
![image](https://cloud.githubusercontent.com/assets/1286381/23285834/62d1aff6-f9e8-11e6-88d8-edf5b915cd1a.png)

Tasks tab after submitting report:
![image](https://cloud.githubusercontent.com/assets/1286381/23285824/526f6c02-f9e8-11e6-81b7-c3eb227e34bb.png)

People tab before submitting report:
![image](https://cloud.githubusercontent.com/assets/1286381/23285849/753f0080-f9e8-11e6-9580-6e7d537a49ff.png)

People tab after submitting report:
![image](https://cloud.githubusercontent.com/assets/1286381/23285814/48cc44fe-f9e8-11e6-9f51-c08c1977a794.png)

Also affects Targets. Here is the console error:
![image](https://cloud.githubusercontent.com/assets/1286381/23285875/b16140f0-f9e8-11e6-90c7-c136981fd4a4.png)

And a blank Targets tab after report submission:
![image](https://cloud.githubusercontent.com/assets/1286381/23285884/bea8f2bc-f9e8-11e6-847f-ce337354c16e.png)

**Comment by SCdF** [comment] 2017-02-24 09:57
@garethbowen side note: can we change the alpha builds so they provide source maps like they do locally? Would be helpful in this kind of thing. Might even want to do it for betas.

**Comment by SCdF** [comment] 2017-02-24 10:17
Creating a report via the history page does not reproduce this AFAICT

**Comment by SCdF** [comment] 2017-02-24 10:18
Nor can I reproduce by completing a task.

**Comment by SCdF** [comment] 2017-02-24 17:49
Reproduced by adding an assessment to a child in the contact view.

**Comment by SCdF** [comment] 2017-02-24 18:42
So the problem is here: https://github.com/medic/medic-webapp/blob/master/static/js/controllers/contacts-content.js#L347-L352
```
          function(areTasksEnabled, tasks) {
            if ($scope.selected) {
              $scope.selected.areTasksEnabled = areTasksEnabled;
              $scope.selected.tasks = tasks;
              if ($scope.selected.children.persons) {
                $scope.selected.children.persons.forEach(function(child) {
```

Just not sure if we should be also checking for `$scope.selected.children`'s existence or worrying that it doesn't exist.

**Comment by SCdF** [comment] 2017-02-24 18:44
@garethbowen I've run out of time today. You're welcome to look at this when you wake up, otherwise I'll pick it up on my Monday.

**Comment by garethbowen** [comment] 2017-02-26 21:31
PR please @SCdF : https://github.com/medic/medic-webapp/pull/3161

We should include this in 2.10.0

**Comment by SCdF** [comment] 2017-02-27 08:38
Looks good, merged. There isn't a 2.10.x branch yet so this is just in master.

**Closed by SCdF** 2017-02-27 08:38 UTC
Labels: 4 - Acceptance Testing, Bug, Priority
