### ISSUE TITLE
All requests to CouchDB seem to time out after 10 seconds

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2325] opened 2016-05-27 22:45 UTC
When loading lg.app contacts, history, or messages, requests seem to time out after 10 seconds. This also happens when trying to edit contacts, but is not reproduced reliably. Seems to be dependent on server load and the amount of work CouchDB is currently doing in terms of updates. Needs more investigation as we should consider increasing the timeout - would be helpful to find where this timeout is set.

**Comment by alxndrsn** [comment] 2016-06-07 14:10
I have just seen a 10s timeouts on a call to `contacts_by_name` and multiple calls to `data_records_read_by_type?group=true` in Chrome.  When I used Chrome's _Copy as cURL_ feature, the `Cookie` header was missing, and unsurprisingly on executing the `curl` call, the response was immediate and `{"error":"unauthorized","reason":"Authentication required."}`.  I guess this is a bug/feature of chrome developer tools, but mentioning it here just in case.

**Comment by alxndrsn** [comment] 2016-06-07 14:22
Definitely looks like pouch or the browser doing the cut-off – requests using curl can take e.g. 16s to complete without being cancelled.

**Comment by alxndrsn** [comment] 2016-06-07 15:35
This is caused by us not overriding the default ajax timeout for pouchdb in 2.6.3.  It _looks_ like it's getting set at https://github.com/medic/medic-webapp/commit/8bf43cb03893d903532c5101301c5d0ce435fcb8#diff-bc29864eda30e12a926c14a5d77573b5L30, but actually the options object is being passed to the wrong function there.

The bug is no longer present in `develop`: https://github.com/medic/medic-webapp/blob/develop/static/js/services/db.js#L26 - looks like it was fixed in #2183 - two months ago!  This was a month before 2.6.3 was released, so it's not clear why the fix was not in the release.

**Closed** 2016-06-08 09:38 UTC
Labels: 4 - Acceptance testing, Desktop Only, Duplicate, Performance
