### ISSUE TITLE
Build Targets tab

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1278] opened 2015-09-08 00:05 UTC
Determine when the exact target definitions are final, check content for errors, implement all target-generating rules and/or queries using definitions, merge content in to `git` and any build/CI systems/scripts.

**Comment by abbyad** [comment] 2015-12-22 17:27
This is a duplicate of https://github.com/medic/medic-webapp/issues/1230

**Comment by abbyad** [comment] 2015-12-22 17:29
On second thought, reopening this one for the implementation, and closing the "design" issue #1230.

**Comment by abbyad** [comment] 2015-12-22 17:33
Latest mockup from #1278 via @Lesterng:
![image](https://cloud.githubusercontent.com/assets/789512/11961635/da120dba-a8a7-11e5-8bf7-fd35e4ad3d71.png)

@browndav, @garethbowen as part of implementing the "targets" page we should consider how this fits with the postgres work and if/how we can build some configurable analytics in the webapp for future projects.

**Comment by garethbowen** [comment] 2016-02-08 21:40
Primary targets for LG:

Under-5 Sick Child Assessments                                20
Under-1 Sick Child Assessments                                4
Pregnancies Registered                                            7
% Newborn Care Visit within 48 hours                          90%
% of Under-5 Referrals followed-up within 24 hours         90%
Fever tested with mRDT                                        60%

**Comment by garethbowen** [comment] 2016-02-10 08:39
I'll work on a Configuration UI but the raw configuration you'll need to add is something like this...

```json
...
    "tasks": {
        "rules": "define Contact { contact: null, reports: null }\ndefine Task {  _id: null,  doc: null,  contact: null,  icon: null,  date: null,  title: null,  fields: null,  resolved: null,  priority: null,  priorityLabel: null,  reports: null,  actions: null }\ndefine Target { _id: null, type: null, pass: null, date: null }\nrule GenerateEvents {\nwhen { c: Contact }\nthen {\n  c.reports.forEach(function(report) {\n    emit(\"target\", new Target({ _id: report._id, type: 'report', pass: true, date: report.reported_date }));\n    emit(\"target\", new Target({ _id: report._id, type: 'registration', pass: report.form === 'R', date: report.reported_date }));\n  });\n}}",
        "targets": {
            "enabled": true,
            "items": [
                {
                    "id": "report",
                    "type": "count",
                    "name": [
                        {
                            "content": "Report submissions",
                            "locale": "en"
                        }
                    ],
                    "icon": "report",
                    "goal": 35
                },
                {
                    "id": "registration",
                    "type": "percent",
                    "name": [
                        {
                            "content": "Registration reports",
                            "locale": "en"
                        }
                    ],
                    "icon": "pregnancy",
                    "goal": 50
                }
            ]
        }
     }
...
```
This sets up two targets: one for 35 reports per month, and one that registrations (form type R) should make up 50% of the reports.

**Comment by estellecomment** [comment] 2016-02-11 16:51
Progress!
![screen shot 2016-02-11 at 17 50 03](https://cloud.githubusercontent.com/assets/911434/12983084/fcf16c00-d0e7-11e5-9aba-7c1db5af445e.png)
![screen shot 2016-02-11 at 17 50 20](https://cloud.githubusercontent.com/assets/911434/12983085/fcf2e364-d0e7-11e5-93df-ee1f94ab2e09.png)

**Comment by estellecomment** [comment] 2016-02-12 16:11
![screen shot 2016-02-12 at 17 09 45](https://cloud.githubusercontent.com/assets/911434/13012434/7f1ade0a-d1ab-11e5-9af9-e5ebc32987c5.png)
![screen shot 2016-02-12 at 17 10 00](https://cloud.githubusercontent.com/assets/911434/13012435/7f391550-d1ab-11e5-88a4-65bd3f8108ca.png)

Next step : navigation. Currently if you only have one type of analytics, the navigation is disabled, and you can't get to the page. (for now type in `<url>/analytics/targets` to reach it)

**Comment by estellecomment** [comment] 2016-02-15 16:59
Done! 

@garethbowen, I'm seeing weird navigation for the multiple-module case, though it could be because I'm faking it and the code is breaking. Are you getting that too?

Dropdown displays "Antenatal care" while the page is actually `/targets`
![screen shot 2016-02-15 at 14 40 18](https://cloud.githubusercontent.com/assets/911434/13055103/ac46a3fa-d40d-11e5-8dc5-9c90006eb5f2.png)

**Comment by estellecomment** [comment] 2016-02-15 17:00
assigning Gareth for code review.

**Comment by garethbowen** [comment] 2016-02-15 20:57
@estellecomment I've added a couple of comments to https://github.com/medic/medic-webapp/commit/d20af79f43a3a97e5b3c71749245a444562d5d1c . 

It looks really good. I think we need to make some more space for the smallest screens (320 width), as you can see below the Registration Reports title overlaps the icon.

![1278-mobile](https://cloud.githubusercontent.com/assets/2064938/13059857/02a4763a-d492-11e5-85af-659b81539d21.png)

Firstly you can get rid of all horizontal padding and margins (in mobile) so the target goes right to the edge of the screen, eg:

![1278-no-pad](https://cloud.githubusercontent.com/assets/2064938/13060006/31923698-d493-11e5-94a1-404e89bcbd46.png)

Secondly I think it might flow better if for the icon, the title, and the monthly goal, we used floating instead of bootstrap columns. This is because we don't control the width of the icon, so we can't know it'll fit in `col-xs-2` or anything else. So instead float the icon left, float the title left right beside it, and float the monthly goal right to give the title as much room as possible. We'll have to test line wrapping for really long goal titles.

**Comment by estellecomment** [comment] 2016-02-16 12:48
Here goes, in 320px : 
![screen shot 2016-02-16 at 13 45 55](https://cloud.githubusercontent.com/assets/911434/13076618/bb28ca32-d4b3-11e5-9c5d-21afe209f2c3.png)

Very long titles will look weird, but longish ones are fine. 
And languages with very long words might run into trouble, so let's never deploy in Turkey.

**Comment by garethbowen** [comment] 2016-02-16 22:21
Translation commit: https://github.com/medic/medic-api/commit/44ddff325761bd80604f90da67310a3fd4a1300a

**Comment by garethbowen** [comment] 2016-02-16 22:22
@estellecomment Just a couple more comments in https://github.com/medic/medic-webapp/commit/ce24204eed4b7c16b0c09e11e970037febd8ab33 and https://github.com/medic/medic-webapp/commit/261ff09ecd533b4dfcf4cec571d815a6ecb6c977

**Comment by estellecomment** [comment] 2016-02-17 10:58
@garethbowen All done! I moved the css classes around to keep the same gutters in anc and stock, they're all good.

**Comment by garethbowen** [comment] 2016-02-17 20:23
Apologies to the reviewer - I botched the merge and had to cherry pick the commits into develop so you can't just compare the branch. The relevant commits are everything from Estelle's previous comment till now. Here's the [unified comparison](https://github.com/medic/medic-webapp/compare/4800b7fbbbd29890de1095396568af68c7d758e5...210b82967bd4711f506e4a5b460a0af777d36cc2) for your code reviewing pleasure.

**Comment by garethbowen** [comment] 2016-02-17 20:34
To configure targets first go to Configuration > Targets and click the Enable button so the Targets analytics modules is shown in the UI. Then click Add New Target, and fill in the form. The Unique ID you provide here will be used in the next step.

Now configure the nools rules to emit a target. First define the target object:

```js
define Target {
  _id: null,
  type: null,
  pass: null,
  date: null
}
```
Then emit a target instance at the appropriate time, for example to met a target for number of reports submitted in a month:
```js
rule GenerateEvents {
when { c: Contact }
then {
  c.reports.forEach(function(report) {
    emit("target", new Target({
      _id: report._id, // unique within the type
      type: 'report', // matches the Unique ID configured above for grouping instances together.
      pass: true, // whether this is a pass or a fail (more info below)
      date: report.reported_date // used to calculate whether this instance contributes to this months goal
    }));
  });
}}
```

The `pass` field above should always be `true` for Count targets, but for Percent targets it's used to calculate number of passes over number total.

**Comment by SCdF** [comment] 2016-02-18 09:08
Should clicking enable make that button change at all? It doesn't visually make any indication that anything's changed. It just looks at me all like
![image](https://cloud.githubusercontent.com/assets/583851/13138424/1f9bcc14-d61f-11e5-92bf-603785f49975.png)

(Chrome Incog)

**Comment by estellecomment** [comment] 2016-02-18 09:08
Thanks for great explanations above! Are they getting saved into documentation anywhere?
 - Could you also give a `percent` example? (I don't get why you would emit when it's not a pass... :( )
 - I suggest using another `type` than `report` for the example, because it's confusing with the `report` object in `c`)
(yes this is a Documentation Review, should I not do this to avoid discouraging you from writing documentation?)

UX notes : (none are show-stoppers)
 - once on a target's config page, you can't navigate back : `Submit` sends you back to the same page after a refresh. Back button to `configuration/targets` would be nice. (you can still pick from the dropdown menu though)
 - in a target's config page, a preview of the icon you pick would be nice. (Otherwise with just the icon names you're like "What's reports icon again?" and "Is pregnancy-4 the biggest or smallest of the set?" )
 - Can we add a `description` field to targets, and display it in `analytics/targets` under a "?" icon? Don't think the title will always be a good enough description. Something like this (sorry for ugly bubble):
![screen shot 2016-02-16 at 13 45 55](https://cloud.githubusercontent.com/assets/911434/13138400/56474808-d627-11e5-835d-46b586fe02b1.png)

**Comment by SCdF** [comment] 2016-02-18 09:12
Also, I always get a failed save when I try to add a random target. I get this in the console:
![image](https://cloud.githubusercontent.com/assets/583851/13138534/b68dd9b4-d61f-11e5-8035-dc1184958731.png)

**Comment by estellecomment** [comment] 2016-02-18 09:17
@SCdF should change to this : 
![screen shot 2016-02-18 at 10 15 49](https://cloud.githubusercontent.com/assets/911434/13138651/a4265be4-d628-11e5-89d3-6e5680d32330.png)
(though I didn't set mine up through the UI, edited the design doc instead)

**Comment by garethbowen** [comment] 2016-02-18 09:18
Looks like a bug with the "empty" configuration where you can neither enable nor configure it. I'll patch it now.

**Comment by SCdF** [comment] 2016-02-18 09:25
_(If there is a nicer way of doing code reviews in this situation let me know, otherwise I'm going to just do this)_
Should this line https://github.com/medic/medic-webapp/compare/4800b7fbbbd29890de1095396568af68c7d758e5...210b82967bd4711f506e4a5b460a0af777d36cc2#diff-6d1e6074e4c4c65d5e8888bb64a06457R23
a) be in a separate function?
b) cap the return value to 100 (ie if my goal is 10 and I've made it to 11 should the result be 100 or 100)?

**Comment by estellecomment** [comment] 2016-02-18 09:36
b) I like the idea that you can have 110% of your target : reward over-achievers! The position of things still looks right, the progress bar doesn't go overboard in that case.
c) Hmmm. Goal : "zero deaths in delivery" (or whatever) Though that's a fail-only target, I would not measure my staff's achievement like this...

**Comment by SCdF** [comment] 2016-02-18 10:48
Does this https://github.com/medic/medic-webapp/compare/4800b7fbbbd29890de1095396568af68c7d758e5...210b82967bd4711f506e4a5b460a0af777d36cc2#diff-8794be7903dbece1299122ebb51eb912R117 need to do anything special to be translated? Or are we using those strings just as symbols / keywords?

**Comment by garethbowen** [comment] 2016-02-18 10:51
They are translated [in the UI](https://github.com/medic/medic-webapp/blob/develop/templates/partials/configuration_targets_edit.html#L41). It's confusing because most of our keys have English punctuation.

**Comment by SCdF** [comment] 2016-02-18 11:31
Is this https://github.com/medic/medic-webapp/compare/4800b7fbbbd29890de1095396568af68c7d758e5...210b82967bd4711f506e4a5b460a0af777d36cc2#diff-0c0cd4a24146ff1933bf7bedc90adb4dR16 enough info? Is anyone going to notice this?

**Comment by SCdF** [comment] 2016-02-18 12:36
So I've read the code and mucked about with the UI a bit. Would be good to have a chat about it in mode detail (how it works etc) for knowledge sharing. Apart from that looks good!

**Comment by estellecomment** [comment] 2016-02-18 12:38
> Does this 4800b7f...210b829#diff-8794be7903dbece1299122ebb51eb912R117 need to do anything special to be translated? Or are we using those strings just as symbols / keywords?

Translated here : https://github.com/medic/medic-webapp/compare/4800b7fbbbd29890de1095396568af68c7d758e5...210b82967bd4711f506e4a5b460a0af777d36cc2#diff-005a710c0ad49979109a3afa935929b6R41

**Comment by estellecomment** [comment] 2016-02-18 12:39
awww gareth answered it already dammit

**Comment by garethbowen** [comment] 2016-02-18 20:54
I'll close this for now - @SCdF ping me when you're free for an overview of how it all works.

**Closed by garethbowen** 2016-02-18 20:54 UTC
Labels: 3 - Code Review, Feature Request

**Comment by abbyad** [comment] 2016-02-18 22:03
This is working very well and was easy to configure. Nice job @gareth and @estellecomment! 

Moving to Ready and will open new issues as we do more testing.

**Comment by garethbowen** [comment] 2016-02-22 09:48
# Demo walkthrough

## Configuration

![configuration-list](https://cloud.githubusercontent.com/assets/2064938/13214727/39835a12-d9b6-11e5-89e2-815f46c0cdd6.png)

![configuration-form](https://cloud.githubusercontent.com/assets/2064938/13214732/3c0d0ec2-d9b6-11e5-9a17-7192bae93a7c.png)

![configuration-rules](https://cloud.githubusercontent.com/assets/2064938/13214736/402cae18-d9b6-11e5-9f59-9ac178882496.png)

## Display

![targets](https://cloud.githubusercontent.com/assets/2064938/13214718/36224c3e-d9b6-11e5-81f4-dd47c6b65943.png)

**Comment by abbyad** [comment] 2016-02-22 18:15
Adding screenshots for a fully configured instance:

## mobile view
![pasted image at 2016_02_22 12_44 pm](https://cloud.githubusercontent.com/assets/789512/13227677/d255c65e-d965-11e5-99fe-a3f6f06dbec3.png)

## small desktop view
![image](https://cloud.githubusercontent.com/assets/789512/13227715/fac33ea0-d965-11e5-8826-e6cd5308deee.png)

## large desktop view
![image](https://cloud.githubusercontent.com/assets/789512/13227749/34ba544a-d966-11e5-9bda-86ee03089e8f.png)

**Comment by alxndrsn** [comment] 2016-02-22 18:15
:+1: looking good!
