### ISSUE TITLE
Single delete and bulk delete does not immediately remove items from LHS in Reports/History

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3001] opened 2016-12-08 20:37 UTC
Doing a bulk delete of all items did not immediately remove the items from the LHS, but they are gone after a page refresh.

**Comment by sglangevin** [comment] 2017-01-23 18:53
This was working when I tested on a previous version.

**Comment by abbyad** [comment] 2017-01-30 15:49
@ngaruko can you try to reproduce this testing deleting some and then all messages?

**Comment by abbyad** [comment] 2017-02-07 01:10
We are seeing similar issues where single deletes are not being removed from the LHS, and that tasks are not removed until a refresh. The part about tasks used to occur frequently due to a config issue, but doesn't seem to be the case this time.

**Comment by sglangevin** [comment] 2017-02-08 23:18
I tested task clearing again on the latest alpha (2.10.0-alpha.4810) and tasks were clearing on alpha.dev as expected. However, I am seeing an error in the console after submitting a form that is supposed to generate a task, which may be related to the original issue. If I refresh, the task appears with no errors. Screenshot of console below:
![image](https://cloud.githubusercontent.com/assets/1286381/22761869/78d195ce-ee11-11e6-9b7a-ff8bba61bca0.png)

I am also seeing that reports submitted from the app do not appear in the History/Reports tab without a refresh, which may be a related issue. (I'm testing as a restricted user)

**Comment by sglangevin** [comment] 2017-02-08 23:22
I'm able to reproduce the original issue in this ticket as well on the latest alpha (logged in as admin). When I delete while logged in as an online user, the reports don't immediately disappear from the LHS of the online user's view and they don't immediately disappear from the restricted user's view.

**Comment by abbyad** [comment] 2017-02-09 01:41
That screenshot seems to indicate an error in the task rules on that instance, so perhaps a separate issue.

**Comment by abbyad** [comment] 2017-02-09 02:29
On a second look, there is no `persons` in the task-rules for that instance, so unlikely that the task rules itself is at fault.

**Comment by abbyad** [comment] 2017-02-22 16:57
Able to reproduce on latest alpha (4880) using a restricted user:

After bulk deleting the top four reports, the items on the LHS remain. Clicking on one of them shows the error that it is not found ...because it has been deleted.

![image](https://cloud.githubusercontent.com/assets/789512/23222452/f4788bda-f8f5-11e6-9724-c1fe9bd2538d.png)

**Comment by garethbowen** [comment] 2017-02-27 03:39
CR please @SCdF : https://github.com/medic/medic-webapp/pull/3163

**Comment by SCdF** [comment] 2017-02-27 10:59
Choice.

**Comment by sglangevin** [comment] 2017-03-01 23:10
This is working well for bulk deletes but not for single deletes. When bulk deleting, the reports disappear from the LHS as expected but for single deletes, they don't disappear from the LHS without a refresh. 

I've also noticed that deletes in general are replicating from server to restricted user but the docs are still visible in the restricted user's app until you navigate away from the History tab and then come back to the History tab. Ideally, they should disappear immediately from the restricted user's LHS.

In addition, I've encountered a bug on my Y4 (lg.dev, v2.10.0-beta.7) where I'm logged in as a restricted user. After deleting a report on the server, it didn't disappear from the phone. I then went to the About page and clicked reload. Now I cannot load tasks or targets and see the following error messages in the console. I'm thinking it's related to trying to generate tasks/targets based on the deleted doc. I'm not seeing this issue on my laptop where I am logged in as a restricted user, only seeing it on the Y4. A second reload on the Y4 appears to have resolved the issue, and on a subsequent test, I found that the report disappeared from History on the phone after navigating away from History and then back to History.

![image](https://cloud.githubusercontent.com/assets/1286381/23485405/1dcd7550-fe90-11e6-9932-a6f6cfbf79a9.png)
![image](https://cloud.githubusercontent.com/assets/1286381/23485413/2a1c772a-fe90-11e6-95a3-f041f85fe96f.png)

**Comment by garethbowen** [comment] 2017-03-02 00:49
@sglangevin How did you delete the report from the server? In the webapp as admin or behind the scenes?

**Comment by garethbowen** [comment] 2017-03-02 00:50
Also, can you give me the ID of the report you deleted?

**Comment by sglangevin** [comment] 2017-03-02 00:52
In webapp as admin. I don't have the ID of the report I deleted earlier, but I can try to reproduce now and give you the ID.

**Comment by sglangevin** [comment] 2017-03-02 00:55
Report ID (lg.dev): 880D9448-DB28-05CD-B7AE-94CCD20648B5

Deleted as admin logged into web app. It didn't disappear from the LHS of the admin's History tab immediately, as expected. It also only disappears from the restricted user's History tab after navigating away from History and then coming back. FWIW either a refresh or navigating away from the tab and then returning to the tab in the web app as admin also makes the report disappear from the LHS.

**Comment by garethbowen** [comment] 2017-03-02 07:16
Three code reviews please @SCdF 

1. https://github.com/medic/medic-webapp/pull/3183 This fixes the reports and reports-content changes listeners. The main problem is the delete code was only being called if you had the deleted report selected. Much better to let the list controller handle removing from the list and the content controller handle deselecting the report.
2. https://github.com/medic/medic-webapp/pull/3184 This popped up while testing. I got an exception in one of the handlers and it crashed the changes handler completely. This means it will recover from uncaught exceptions.
3. https://github.com/medic/medic-webapp/pull/3185 There are two exceptions in the screenshots above that seemingly have nothing to do with this issue. I tracked them down to assumptions in the rules engine. I'm surprised they were hit in this case, but it is valid to have a fact with a null contact so we need to handle that case.

**Comment by garethbowen** [comment] 2017-03-02 07:17
These all need to be merged to `2.10.x` once approved.

**Comment by SCdF** [comment] 2017-03-02 09:33
All good. I've left them unmerged, because they need to be merged into master and 2.10.x so I'll let you do that. Let me know what you'd expect next time

**Closed** 2017-03-02 09:47 UTC
Labels: 3 - Code Review, Bug, Regression
