### ISSUE TITLE
Add translations for form field labels

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1563] opened 2015-11-11 16:27 UTC
Console and network panels look normal but translation strings not getting translated.  Logged in as admin. 

https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/E4E7476C-331A-6578-9402-CE2BA097EDEF

![screen shot 2015-11-11 at 2 25 39 pm](https://cloud.githubusercontent.com/assets/25641/11096231/2ebc36da-8880-11e5-89fd-2d636d8facae.png)

**Comment by abbyad** [comment] 2015-11-11 16:34
@mandric, is it only the translation strings for the form fields? If that is the case I was planning on translating them all once those `output` fields are finalized.

**Comment by mandric** [comment] 2015-11-11 16:35
Ok maybe we should open an issue for that instead?

**Comment by mandric** [comment] 2015-11-11 16:37
Even if I swap lg.dev for lg.app I get the same result.

**Comment by mandric** [comment] 2015-11-11 16:40
I'll just assign this to you Marc.

**Comment by abbyad** [comment] 2015-11-11 16:48
As mentioned here in https://github.com/medic/medic-webapp/issues/1211#issuecomment-150354569 I think we should show the default label if no translation is found. I suggest we use this issue as a feature request for that as it may be quicker to build this feature than write and maintain the form specific translations. Moving this from a bug to feature request, and will add the labels for the field test (if still needed) as part of #1276 .

**Comment by garethbowen** [comment] 2015-11-11 18:33
I have noticed a bug when rendering form labels where on first load the labels are untranslated, but if you click another tab and go back then they translate as expected. I think this is due to using $translate.instant before the translations have loaded. I'll see if I can confirm this and raise a bug.

**Comment by abbyad** [comment] 2015-11-12 13:50
@garethbowen, are you saying that the this Feature Request is already, implemented but not working?

**Comment by alxndrsn** [comment] 2015-11-12 16:16
@abbyad I don't think these fields have a "default label" defined in the xform.  I'm looking at https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/assessment.xml, so please point me in the right direction if this is not it.

Would be simple to add a simple 'translation' from the keys, if that is helpful, e.g.:

key | translation
---|---
`report.assessment_follow_up.patient_id` | _Patient Id_
`report.assessment_follow_up.patient_name` | _Patient Name_
`report.assessment_follow_up.referral_follow_up_needed` | _Referral Follow Up Needed_

**Comment by abbyad** [comment] 2015-11-12 17:17
You're right @alex, they are in the XLSform, but not in the XForm. What you are describing fits with #1333.

In the meantime for the field test I will add them manually as translation keys once the forms are finalized.

**Comment by garethbowen** [comment] 2015-11-12 18:58
@abbyad My comment refers to a different bug for when translation values _are_ provided, and I couldn't replicate it, so just ignore that comment for now.

We could add some smarts to the enketo form admin page to automatically add translation keys when forms are uploaded.

**Comment by abbyad** [comment] 2015-12-08 22:58
Pending code review, changes to app_settings are ready to be pushed to lg.app during the next update.

**Comment by alxndrsn** [comment] 2015-12-14 07:45
Looks fine.

**Closed by alxndrsn** 2015-12-14 07:45 UTC
Labels: 4 - Acceptance testing, Feature Request

**Comment by abbyad** [comment] 2015-12-15 21:26
If `translations` is omitted we get `TypeError: Cannot read property
'forEach' of undefined` [here](https://github.com/medic/medic-webapp/blob/714d465f5e5148372c455c3e55a9ec5f6dbbbd0e/static/js/app.js#L320)

We should test for translations before doing the forEach, but in the
meantime added blank translations to the new keys.
