### ISSUE TITLE
validation property values with spaces should not leave properties on the doc.

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1224] opened 2015-08-28 16:36 UTC
If you define a validation property like `test` (that includes trailing whitespace) the doc is saved with that property name for some ungodly reason.  Probably because during validation we create that property name on the doc temporarily while it's being processed.  Write a test and a fix on medic-sentinel.

**Comment by estellecomment** [comment] 2017-02-27 09:00
I tried adding spaces to validation fields, and adding a separate validation field with a space, and I can't reproduce this. Closing.

**Closed by estellecomment** 2017-02-27 09:00 UTC
Labels: 0 - Backlog, Bug, Needs Triage
