### ISSUE TITLE
hard-refresh breaks form add view

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1412] opened 2015-10-08 15:48 UTC
# Steps to recreate

reload e.g. http://localhost:5988/medic/_design/medic/_rewrite#/reports/add/V and click [**Submit**]
# Observed

Exception is thrown:

> TypeError: Cannot read property 'form' of null

Presumably caused by `$scope.selected` being `null` at:

> ``` js
> Enketo.save($scope.selected.form, $scope.form, $scope.selected._id)
> ```
# Expected

Form should save, or validation error should occur
# Notes
- `setSelected({ form: 'V' })` is called as part of controller init
- by the time `$scope.save()` is called, `$scope.selected` is `null`
- `$scope.selected` is actually null by the time the form is finished _rendering_

**Comment by alxndrsn** [comment] 2015-10-08 16:11
Weird race condition:
1. when report is loaded, `setSelected()` is called
1. `setSelected()` is calling `settingSelected()`
1. `settingSelected()` is setting `$scope.showContent = true`, but in a `$timeout()` call
1. this means that the back button is visible when the Report list is loaded, so `clearSelected()` is getting called

**Comment by alxndrsn** [comment] 2015-11-11 10:57
(can't hard-refresh in android app)

**Comment by garethbowen** [comment] 2017-05-30 01:45
This appears to be fixed in the latest alpha (cannot reproduce). Assigning to AT to get proper testing.

**Closed by garethbowen** 2017-05-30 01:45 UTC
Labels: 0 - Backlog, Bug, Desktop Only
