### ISSUE TITLE
Update developer onboarding documentation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3924] opened 2017-09-18 21:42 UTC
Review the existing developer onboarding documentation and make sure it's correct and up to date. Reorganise it if necessary so everything is in one place (eg: maybe move the dev setup from the README into medic-docs?).

**Comment by SCdF** [comment] 2017-10-20 13:28
Duplicate of #2498

**Closed by SCdF** 2017-10-20 13:28 UTC
Labels: Documentation, Priority: 3 - Low, Status: 1 - Triaged, Type: Technical issue
