### ISSUE TITLE
sending message with + on demo.app with some contacts gives error

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1071] opened 2015-07-17 04:22 UTC
https://demo.app.medicmobile.org/

![screen shot 2015-07-16 at 11 18 56 pm](https://cloud.githubusercontent.com/assets/25641/8740560/12c2b68c-2c11-11e5-9c85-3dacf3156666.png)

I'm assuming this because our mock phone numbers fail to validate with libphonenumber?  Should we create an issue to only use phone numbers that validate for contacts in our demo data?

**Comment by alxndrsn** [comment] 2015-07-17 14:33
Yeah, that definitely seems to be the cause.  A good first step would be to update the demo data with valid phone numbers, but I can definitely see arguments against this!  Perhaps we should invent our own country (`+10...`, `+71...`)?

**Comment by abbyad** [comment] 2015-07-17 18:55
I think this was done on purpose. We do not want to automatically send messages to real numbers. If you want to test sending to a real number you can edit a contact's phone number.

**Comment by mandric** [comment] 2015-07-17 19:04
The demo shouldn't send any messages to any numbers, we can avoid that by marking every message as sent before its sent (maybe think of it as a fake gateway process).  We can accomplish that by enabling the resolve_pending transition, but that's currently only in beta/alpha... we should probably add it to release otherwise the demo appears a little broken?  Why would we put bad phone numbers in a demo that can't be used?  Anyway minor thing I guess, just thought it was worth reporting.

**Comment by abbyad** [comment] 2015-07-17 19:48
> Why would we put bad phone numbers in a demo that can't be used?

Because we don't want to be spamming anyone. The demo data can be used by anyone internal or general public in our live demo. 

Perhaps the best way to avoid spamming, yet also allow better testing/demoing, is to use +1-NNN-555-0100 through 0199 as the mock numbers. Those are reserved for fictional use, so we shouldn't be spamming anyone, and pass as valid phone numbers.

**Comment by SCdF** [comment] 2017-01-29 01:07
@browndav please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by browndav** [comment] 2017-02-28 16:55
Closing as `Ancient`; no longer applies to current codebase.

**Closed by browndav** 2017-02-28 16:55 UTC
Labels: Ancient
