### ISSUE TITLE
Some settings are hard to understand

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2122] opened 2016-03-21 09:26 UTC
Settings have evolved slowly over time so sometimes their current names are weird to the non-initiated.
- [ ] "Only Expect Forms" in app-settings is the opposite of "Accept plain-text messages" in the user-facing settings. Matching the two would be nice, and/or extra help text to describe in app-settings.
- [ ] Date formats : examples and links to examples/docs would be nice to know what formats are possible
- [ ] Patient ID format : just entering the number of digits would be simpler. E.g. "5" instead of "1111" + check digit. The user shouldn't have to know that there's a check digit.
  If we want to allow letters, then we could keep the existing format (though without mentioning the check digit thing), and give several examples of formats.
- [ ] "ANC Forms" should really be "ANC analytics config"

**Comment by SCdF** [comment] 2016-03-21 10:07
> Patient ID format... ...If we want to allow letters,

I think it wasn't clear to some people you could even _allow_ letters in the ID. Which in turn leads to confusion as to why the format is how it is

**Comment by estellecomment** [comment] 2016-03-21 11:04
Priority : 2/5

**Comment by abbyad** [comment] 2017-02-15 18:03
All of these would be quick edits to include in the current release (2.10) and since they are documentation only won't cause regressions.

I would suggest that we only do the following:
- ~"Only Expect Forms" in app-settings is the opposite of "Accept plain-text messages" in the user-facing settings. Matching the two would be nice, and/or extra help text to describe in app-settings.~
  - Possibly confusing, but already well documented

- **Date formats : examples and links to examples/docs would be nice to know what formats are possible.**
  - Add link to http://momentjs.com/docs/#/displaying/format/ in configuration/settings/advanced
  - Add link to http://momentjs.com/docs/#/displaying/format/ in Dashboard's app_settings page

- ~Patient ID format : just entering the number of digits would be simpler. E.g. "5" instead of "1111" + check digit. The user shouldn't have to know that there's a check digit. If we want to allow letters, then we could keep the existing format (though without mentioning the check digit thing), and give several examples of formats.~
  - Hint already clarified check digit: `Format of generated numerical identifiers. Note, an extra check digit is always used, so the default value (1111) generates a length of 5, e.g. '92345'.`

-  **"ANC Forms" should really be "ANC analytics config"**
    - This section may become obsolete, but may as well be clearer about its use. Suggest changing "ANC Reports" (as it is in v2) to "ANC Forms" and putting a subtitle saying "Specified forms can be used in the built-in ANC Analytics"

**Comment by garethbowen** [comment] 2017-02-21 03:44
CR please @estellecomment : https://github.com/medic/medic-webapp/pull/3139

I just did the points recommended by @abbyad

**Comment by estellecomment** [comment] 2017-02-21 08:58
@abbyad Thanks!

A comment : I don't really find "ANC forms" clearer than "ANC reports" as a section title...
I found it confusing in the first place because forms were already defined in the forms section, so I didn't understand why you'd redefine ANC forms someplace else.
I think the section is about configuring ANC analytics, so I'd find it clearer with a title like "Forms for ANC analytics" for instance. Something with "ANC analytics" in the title, or at least "Analytics".

Thoughts?

(@garethbowen CR looks good apart from that point)

**Comment by abbyad** [comment] 2017-02-21 21:36
This section could be used by something else than Analytics (eg DIY/Standard config pages), but would not have other Analytics settings. For that reason I preferred keeping the generic title. Is the context clear enough for internal purposes with the new hint, and the field labels? If not then naming it `Forms for ANC analytics` is fine with me.

By the way, the change to Forms instead of Reports is because we use "report" as a submitted instance of a "form".

**Comment by garethbowen** [comment] 2017-02-21 21:56
I've merged what I've done so far. @estellecomment I'm happy to make any further changes, just wanted to get what I've done so far into the 2.10 release.

**Closed by garethbowen** 2017-02-21 21:56 UTC
Labels: 3 - Code Review, Documentation

**Comment by estellecomment** [comment] 2017-02-23 08:16
@abbyad 
+1 for changing reports -> forms, thanks!

I'd be in favor of describing what it currently does as clearly as possible, rather than what it could potentially do in the future. We don't really know what we'll do in the future... I'm fine changing it again later if necessary, this is not an expensive change.
I would also rather have the title be clear by itself (as much as possible), rather than have to read the full description to understand what it's about.
So yeah, "Forms for ANC analytics" would work nicely :)
