### ISSUE TITLE
Firefox, Webkit: Verify/Unverify button not working properly

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1111] opened 2015-07-31 19:18 UTC
On a recent Webkit nightly, the 'Verify' and 'Unverify' operations throw an error and fail to update the record. On the latest version of Firefox, an error is thrown and the operation appears to be unsuccessful, but a full page reload reveals the requested modification.

Webkit:
![1](https://cloud.githubusercontent.com/assets/763977/9015457/f85cb130-377d-11e5-98fc-139c5cb54841.jpg)

Firefox:
![2](https://cloud.githubusercontent.com/assets/763977/9015466/09ec6bde-377e-11e5-91d3-21f6391f4966.jpg)

This is possibly related to issues #1108 and #1112  – the currently-logged-in user seems to be null in these cases, for some reason.

**Comment by garethbowen** [comment] 2015-08-05 01:20
I agree this is probably caused by the null userCtx as in #1112. Closing this as #1112 is closed.

**Closed by garethbowen** 2015-08-05 01:20 UTC
Labels: 1 - Scheduled, Bug
