### ISSUE TITLE
Ability for a form to affect an existing schedule

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#928] opened 2015-05-06 00:31 UTC
It would be helpful if the receipt of a new form could affect an existing notification schedule. For example, a pregnancy is registered into an ANC schedule. If a CHW submits a danger sign form for that pregnancy ID, the ANC schedule would be amended according to the different demands of a high-risk pregnancy. 

+@jane@medicmobile.org

**Comment by abbyad** [comment] 2015-05-06 00:47
This is similar to #842, but different in that this one does not affect a field currently on the original registration form.

For the case of danger signs, we could add a danger sign field to the original registration form, in which case this issue would be a duplicate of 842 since the registration would be reprocessed with the update. However, adding fields to registration forms is tricky if the Compact TextForms format is used. The extra fields could make it impossible to parse properly if they are optional or strings, as they would be in this instance.

It seems as though we need a concept of silent fields defined on a form that are required to *not* be in a form, but can be updated at a later time. This would help with other fields as well, such as adding a delivery date for a pregnancy.

**Comment by garethbowen** [comment] 2016-03-01 21:34
One way to fix this is to generate messages just in time, for example, by using the rules engine to generate messages: #1860

**Comment by abbyad** [comment] 2016-03-01 21:39
Good point, and I think we are now waiting to do this once the schedules are generated by tasks.

**Comment by nice-snek** [comment] 2017-03-15 09:40
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment] 2017-03-15 09:45
Please re-open and schedule when required for specific project work.

**Closed by alxndrsn** 2017-03-15 09:45 UTC
Labels: 0 - Backlog, Feature Request, Needs Triage
