### ISSUE TITLE
For a CHW, hide the CHP area on the family profile

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1550] opened 2015-11-05 22:14 UTC
Right now, the family profile includes the CHP area ("Busia CHP Area1"). Ideally, we'd hide this. When logged in as demo on lg.dev in Chrome, I see:

![screen shot 2015-11-05 at 2 00 06 pm](https://cloud.githubusercontent.com/assets/377216/10983421/3fc1726e-83c7-11e5-815c-e5ae6abff90e.png)

If we can't hide it, it shouldn't be clickable – right now, it takes the CHP to a confusing screen showing an alternative list of families:

![screen shot 2015-11-05 at 2 12 00 pm](https://cloud.githubusercontent.com/assets/377216/10983431/47ad42a0-83c7-11e5-9a39-ffb086776f2e.png)

We might keep it as-is for admins, but this change is needed for CHWs.

**Comment by garethbowen** [comment] 2015-11-17 03:04
Duplicate of #1579

**Closed by garethbowen** 2015-11-17 03:04 UTC
