### ISSUE TITLE
View code replicates

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1810] opened 2016-01-22 19:42 UTC

**Comment by alxndrsn** [comment] 2016-01-22 20:11
Any chance of some more detail on this one/

**Comment by garethbowen** [comment] 2016-03-29 03:13
I think this means we shouldn't replicate the view code to the client. However, it's necessary because we query the views in pouch so it's needed on the client side. We _could_ separate the server side views from the client side views by having another ddoc. This would allow us to greatly reduce the size of the ddoc sent to the client as we could strip out lots of other server side only bits too.

@estellecomment Is this what you meant?

**Comment by estellecomment** [comment] 2016-03-29 07:26
This is copied over from @browndav 's notes from the Jan meetup, I don't remember. Dave, any thoughts?

**Comment by browndav** [comment] 2016-03-30 21:47
Gareth's explanation matches my recollection. I think separating out the views that are only used by the server could be a win for reasons other than bandwidth too: if a views is removed, the map/reduce functions won't be evaluated on put/post to maintain indexes, and in theory all write operations should get a little faster.

**Comment by garethbowen** [comment] 2016-07-05 04:25
Duplicate of #2206

**Closed by garethbowen** 2016-07-05 04:25 UTC
