### ISSUE TITLE
Error when accessing Schedules

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#862] opened 2015-03-30 13:23 UTC
I got the following when opening Schedules from the Configuration tab:

`{"error":"not_found","reason":"Document is missing attachment"}`

Reloading the page and selecting Schedules again worked.

**Comment by browndav** [comment] 2015-05-15 21:04
@garethbowen: Believe we resolved this; am I remembering correctly?

**Comment by garethbowen** [comment] 2015-05-18 12:06
Yes this is a duplicate of #911

**Closed by garethbowen** 2015-05-18 12:06 UTC
Labels: 0 - Backlog, Bug
