### ISSUE TITLE
Clicking edit on a district, health center, heatlh area is showing error.

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4808] opened 2018-09-05 19:41 UTC
Created a new health district, health center, and area. Clicking Edit from any of these is generating an error `Error loading form. Please try again or check with an administrator.`

**Steps to reproduce**:
Login as admin to gamme.dev
Navigate to Nick's 3.0 District
Click Edit

**What should happen**:
 User is presented with the form to edit the district information. 

**What actually happens**:
An error is displayed. 

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/ae616526-8a69-4322-a4c5-c48616d1e094/edit

```
Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.
inbox.js:3 r {message: "Could not evaluate: if (boolean( /model/instance[1…","quote":"\"","v":""}]}]] [cur={"t":"?","v":""}]", name: "FormLogicError", stack: "Error↵    at new r (https://gamma.dev.medicmobile.…medic/_design/medic/_rewrite/js/inbox.js:3:355212"}message: "Could not evaluate: if (boolean( /model/instance[1]/data/district_hospital/contact/_id ), "", message: Stuff left on stack. [stack=[{"t":"root","tokens":[]},{"t":"fn","v":"if","tokens":[{"t":"bool","v":true},{"t":"str","quote":"\"","v":""}]}]] [cur={"t":"?","v":""}]"name: "FormLogicError"stack: "Error↵    at new r (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:762421)↵    at t.require.79.t.evaluate (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:777892)↵    at f (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:802789)↵    at HTMLInputElement.<anonymous> (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:803290)↵    at Function.each (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:959043)↵    at require.141.C.fn.init.each (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:957328)↵    at Object.update (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:802050)↵    at w.require.80.w.init (https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:785959)↵    at https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:2593152↵    at https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/js/inbox.js:3:355212"__proto__: Errorconstructor: ƒ r(t)arguments: (...)caller: (...)length: 1name: "r"prototype: Errorconstructor: ƒ r(t)__proto__: Object__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[FunctionLocation]]: inbox.js:3[[Scopes]]: Scopes[1]0: Global {type: "global", name: "", object: Window}__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: Object
s.window._medicMobileTesting.n.forEach.s.console.(anonymous function) @ inbox.js:3
require.80.w.init @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
i @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
N @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
t @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
l @ inbox.js:3
a @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
n @ inbox.js:3
contact @ inbox.js:3
(anonymous) @ inbox.js:3
instantiate @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
st @ inbox.js:3
V @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
t @ inbox.js:3
(anonymous) @ inbox.js:3
$broadcast @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
t @ inbox.js:3
(anonymous) @ inbox.js:3
dispatch @ inbox.js:3
m.handle @ inbox.js:3
inbox.js:3 Error loading contact form. Error: ["FormLogicError: Could not evaluate: if (boolean( /model/instance[1]/data/district_hospital/contact/_id ), \"\", message: Stuff left on stack. [stack=[{\"t\":\"root\",\"tokens\":[]},{\"t\":\"fn\",\"v\":\"if\",\"tokens\":[{\"t\":\"bool\",\"v\":true},{\"t\":\"str\",\"quote\":\"\\\"\",\"v\":\"\"}]}]] [cur={\"t\":\"?\",\"v\":\"\"}]"]
    at inbox.js:3
    at inbox.js:3
    at inbox.js:3
    at i.$digest (inbox.js:3)
    at inbox.js:3
    at h (inbox.js:3)
    at inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
i @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
N @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
t @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
l @ inbox.js:3
a @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
n @ inbox.js:3
contact @ inbox.js:3
(anonymous) @ inbox.js:3
instantiate @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
st @ inbox.js:3
V @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
t @ inbox.js:3
(anonymous) @ inbox.js:3
$broadcast @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
t @ inbox.js:3
(anonymous) @ inbox.js:3
dispatch @ inbox.js:3
m.handle @ inbox.js:3
```

**Environment**:

- Instance: gamma.dev
- Browser: Chrome, Firefox
- Client platform: MacOS
- App: webapp
- Version: 3.0.0-beta.4

**Comment by newtewt** [comment] 2018-09-20 18:28
Looks good.

**Comment by ngaruko** [comment] 2018-10-11 19:58
This seems to be happening still. Did you want to have another look @vimemo ?
To reproduce:
1. log in `gamma.dev` as admin.
2. create a new place (district, health center or area) or  (or pick up an existing one)
3. Click on edit

The following error occurs
![image](https://user-images.githubusercontent.com/6979995/46830355-dbed1300-cdfc-11e8-9696-986b764096de.png)

**Comment by vimemo** [comment] 2018-10-11 21:09
@ngaruko, the current 3.1 beta still does not have this fix. It should be included in the next release.

**Comment by ngaruko** [comment] 2018-10-12 01:34
Thanks @vimemo. There are a couple of UI misaligned items (see screenshots). Not sure if they have to do with this fix or if it is in the form?
![image](https://user-images.githubusercontent.com/6979995/46842752-f2f72980-ce2b-11e8-97aa-f9144343d19d.png)

**Comment by vimemo** [comment] 2018-10-12 14:45
@ngaruko, I think this would be a different issue. More like this one: https://github.com/medic/medic-webapp/issues/4682

**Comment by garethbowen** [comment] 2018-10-14 20:48
Closing. This can be testing in the next 3.1.0 beta.

**Closed by garethbowen** 2018-10-14 20:48 UTC
Labels: Priority: 1 - High, Status: 4 - Acceptance testing, Type: Bug
