### ISSUE TITLE
webdriver-manager breaks after running integration tests

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2627] opened 2016-08-11 15:35 UTC
To re-create:
- Have a clean workspace, `npm install`ed correctly etc
- Update and start the webdriver: `./node_modules/.bin/webdriver-manager update` `./node_modules/.bin/webdriver-manager start`
- Run all of the tests: `COUCH_URL='whatever' grunt test`
- This will run standard tests, then integration tests that require api is built into your local node_modules, then e2e tests. This should pass.
- Kill webdriver, try to start it again

What should happen: It should work like it did the first time, or worst case you need to run update again before it works

What actually happens:

```
$ ./node_modules/.bin/webdriver-manager start
module.js:442
    throw err;
    ^

Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/scdf/Code/Medic/medic-webapp/node_modules/.bin/webdriver-manager:18:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
scdf at SCdF in ~/Code/Medic/medic-webapp on send_message_two_point_oh▲
$ ./node_modules/.bin/webdriver-manager update
module.js:442
    throw err;
    ^

Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/scdf/Code/Medic/medic-webapp/node_modules/.bin/webdriver-manager:18:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

This means you get **one** full test run before having to do a full `rm -rf node_modules && npm install` (just the install by itself doesn't do it).

I'm reasonably confident this is a negative side effect of the integration testing npm installing into node_modules.

**Comment by nice-snek** [comment] 2017-04-26 05:46
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by browndav** [comment] 2017-05-30 10:24
I'm now unable to reproduce this a current build of Selenium / webdriver; rerunning `./node_modules/.bin/webdriver-manager start` seems to work for me regardless of how the previous process died (even tried signal 9).

Marking as `Ancient` for now and passing off to @SCdF for a final check – if it's no longer a problem for you either, just unassign yourself IMO.

Here's what I was running:

```03:21:31.310 INFO - Launching a standalone Selenium Server
03:21:31.336 INFO - Java: Oracle Corporation 25.131-b11
03:21:31.336 INFO - OS: Mac OS X 10.12.5 x86_64
03:21:31.345 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
```

**Comment by SCdF** [comment] 2017-05-30 11:23
Oh I'm sure this is no longer relevant. If it comes up again we can raise it again.

**Closed** 2017-05-30 11:23 UTC
Labels: Ancient
