### ISSUE TITLE
Add migration to handle pending scheduled_tasks which don't have a uuid

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3272] opened 2017-03-23 01:25 UTC
On old instances, it _seems_ that we can have scheduled_tasks' messages which do not have a uuid.  If one of these messages has a sate of `pending` (or presumably `scheduled`), then the sms-gateway controller in api will try to give it to the gateway, but at some stage it will be rejected (not immediately clear if that's in the controller or just that gateway itself is ignoring those messages).  These messages should be updated to either:

A. have a uuid, or perhaps more usefully
B. be marked as failed 

ref https://github.com/medic/medic-webapp/issues/3271
ref https://github.com/medic/medic-projects/issues/1645#issuecomment-288587948

**Comment by garethbowen** [comment] 2017-03-23 02:32
@alxndrsn Is this a duplicate of this issue? https://github.com/medic/medic-webapp/issues/3015

**Comment by alxndrsn** [comment] 2017-03-23 06:14
It definitely looks the same, but comments on #3015 imply that it was applied to 0.4.x.  However, https://github.com/medic/medic-projects/issues/1645 was seen on `0.4.16`.

**Comment by mandric** [comment] 2017-03-23 12:45
If you want to update UUIDs on 0.4 you have to run a migration manually. https://github.com/medic/medic-api/tree/0.4.x/migrations/add-uuid-to-scheduled-tasks

**Comment by garethbowen** [comment] 2017-03-23 19:53
@alxndrsn It was applied to 0.4, but 0.4 doesn't have any mechanism to run migrations, so it was a bit useless. We decided at the time that nobody should run `medic-gateway` against 0.4 so it's not an issue. Workarounds: don't use `medic-gateway`, upgrade to 2.10, run the migration manually.

The third one is problematic because the instance will still be running an unsupported software combination and will possibly hit another error.

**Comment by garethbowen** [comment] 2017-03-23 21:01
Closing due to workarounds mentioned above. Reopen if there's more we should do.

**Closed by garethbowen** 2017-03-23 21:01 UTC
Labels: 1 - Scheduled, Bug

**Comment by alxndrsn** [comment] 2017-03-24 02:05
@bishwas-medic FYI

**Comment by bishwas-medic** [comment] 2017-03-24 10:52
@alxndrsn should we revert all older projects back to SMSsync until the v2 upgrades are done? Or just the ones that we are seeing the issues with?

**Comment by alxndrsn** [comment] 2017-03-28 11:25
TBH I'd be much happier upgrading old projects to gateway, and fixing any specific issues we see.

**Comment by sglangevin** [comment] 2017-03-28 21:54
Sounds like running the migration manually should resolve this particular issue, right?

**Comment by garethbowen** [comment] 2017-03-28 21:55
Yes.

**Comment by garethbowen** [comment] 2017-03-28 21:57
A summary of the discussion from this mornings planning meeting...

Don't upgrade 0.4 instances to medic-gateway.
When upgrading to 2.x also update to medic-gateway.
Where projects have already been migrated to medic-gateway don't change them back. Attempt to resolve issues (like this one) manually until 2.x is ready and then upgrade ASAP.
