### ISSUE TITLE
Update History tab form type filter to include all forms

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2260] opened 2016-04-29 18:17 UTC
On the History tab, the form type filter currently includes only forms that are accessible from the History tab. This means that some forms are missing, things that are only accessible from contact profiles. Update the form type filter so that all forms appear.

**Comment by garethbowen** [comment] 2016-05-01 21:11
This should have been fixed by #1409.

**Comment by garethbowen** [comment] 2016-05-01 23:36
@sglangevin On #1409 @abbyad wrote
> [the form type filter] should however include all non-contact XForms - meaning all forms except for the contact forms.
I'll assign this to him to respond...

**Comment by sglangevin** [comment] 2016-05-02 14:51
The only forms currently visible are the forms that are set to show up on the History tab as actions (available when you hit the + sign). There are many other forms, like follow up forms in particular, that are not available in the filter. Specific examples include assessment follow up, pregnancy visit, pregnancy referral follow up. These are forms that can only be accessed from tasks. They should not be available as actions on the History tab but should be available as filters.

**Comment by abbyad** [comment] 2016-05-04 18:03
This appears to be a duplicate of https://github.com/medic/medic-webapp/issues/1409#issuecomment-206637390. It seems to have been resolved but not brought into the current builds. I have marked it to be included as part of 2.6.2 in #2240.

**Closed** 2016-05-04 21:33 UTC
Labels: Duplicate, Reports, v2.x
