### ISSUE TITLE
Relative dates for reports in LHS only has day precision

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3287] opened 2017-03-26 07:21 UTC
In the reports LHS list, the relative date at which the report was received is precise by one day (today/yesterday/x days ago) : 
![image](https://cloud.githubusercontent.com/assets/911434/24329375/b66a8616-1224-11e7-9706-92c48fb8317b.png)

As a comparison, in the messages tab, more precision : 
![image](https://cloud.githubusercontent.com/assets/911434/24329380/d30644ae-1224-11e7-9042-9083fa58f814.png)

I'd expect the high-precision date for reports too. @diannakane is that what you would expect?

**Comment by estellecomment** [comment] 2017-03-26 07:23
@amandacilek you're probably also interested

**Comment by sglangevin** [comment] 2017-03-27 19:51
@estellecomment what is the user story you have in mind for needing more precise date/time?

**Comment by diannakane** [comment] 2017-03-28 00:42
@estellecomment I haven't heard many complaints about this. I think we did
it to make it readable at a quick glance, and if you view the report on the
RHS, you can see the high-precision date/time. I'm open to revising it if
it's no longer serving us. Looking forward to hearing your thoughts.

**Comment by abbyad** [comment] 2017-03-28 01:34
We introduced daily time resolution because of [issue #1947](https://github.com/medic/medic-webapp/issues/1947) when we first started doing offline access because the time was not being refreshed. From what I remember daily time resolution was never requested from users to begin with. 

@garethbowen has the underlying reason become obsolete now?

**Comment by garethbowen** [comment] 2017-03-28 02:50
@abbyad Not as far as I know. Closing as by design. Please reopen if the design is found to be wrong!

**Closed by garethbowen** 2017-03-28 02:50 UTC

**Comment by estellecomment** [comment] 2017-03-28 04:38
It's helpful to be able to differentiate between different reports sent by the same person recently, or spotting new reports when you're watching for them. I don't know if it's a common use case.

Looks like it's not trivial because of livelist though, so not a big deal.

**Comment by diannakane** [comment] 2017-03-28 19:18
I could see the day granularity being the exact time and everything older
than that reverting to days/weeks in the list view. We'll consider when
doing the History tab update in Q2. cc: @amandacilek
