### ISSUE TITLE
New Pregnancy Reg - Danger signs not shown at end

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1631] opened 2015-11-20 13:14 UTC
If danger signs are flagged during a registration, they are not being shown in the summary page at the end.

Below is a screenshot from the current v1.6 of what that looks like:

![screenshot_2015-11-20-16-06-45](https://cloud.githubusercontent.com/assets/15346836/11300639/cc9cc25c-8fa1-11e5-832f-a7510515c067.png)

**Comment by alxndrsn** [comment] 2016-01-12 17:52
Closing this.  Please re-open in `medic-projects` if the issue is still occurring.

**Closed by alxndrsn** 2016-01-12 17:52 UTC
