### ISSUE TITLE
Error executing changes callback

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4009] opened 2017-11-03 00:04 UTC
Not too sure where this error is coming from, but I'm seeing it a lot on beta.dev logged in as a restricted user.

![image](https://user-images.githubusercontent.com/1286381/32356042-d2a9abd0-bfef-11e7-9e6d-848f208f4fbc.png)

**Comment by sglangevin** [comment] 2017-11-03 00:06
It's also showing up when logged in as admin.

**Comment by SCdF** [comment] 2017-11-03 08:50
Duplicate of #3985 

This is fixed in 2.14.x branch, but is not yet in a beta. Do you want me to cut one?

**Comment by SCdF** [comment] 2017-11-03 08:58
Actually it costs me nothing, let's just tag it anyway: https://travis-ci.org/medic/medic-webapp/builds/296679144

**Comment by SCdF** [comment] 2017-11-07 15:34
Actually it's costing me a lot: the e2e builds are surprisingly flaky on this branch…

**Closed** 2017-11-13 00:38 UTC
Labels: Priority: 2 - Medium, Status: 5 - Ready, Type: Bug, Won't fix: Duplicate
