### ISSUE TITLE
In update_markets script: Switching to the market you're currently on produces incorrect URLs

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3549] opened 2017-06-13 19:16 UTC
We're using `sed` somewhat imprecisely in `update_markets.sh`, which leads some operations that should be safe to effectively "brick" the dashboard metadata and require manual editing/intervention through Futon.

To reproduce: run `./update_markets.sh "$COUCH_URL" release_v2` twice. Observe that the URL inside of the updated docs is now `release-v2-v2`, which is invalid.

We should either: (i) change our use of `sed` to be portable and safe under all circumstances; (ii) rewrite this script using a language and/or tool with a real URL parser; or (iii) completely deprecate this script due to a rewrite of dashboard.

**Comment by garethbowen** [comment] 2017-06-22 10:44
Closing this as a duplicate of #3492

**Closed by garethbowen** 2017-06-22 10:44 UTC
Labels: 0 - Backlog, Bug, Configuration
