### ISSUE TITLE
Pull sentinel data out into its own database

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3423] opened 2017-04-27 08:42 UTC
This should reduce writes to documents, causing less conflicts.

**Comment by SCdF** [comment] 2017-04-27 11:29
Dropping it out of milestone because I don't think this actually in itself reduces conflicts, though it is still something I'd like us to do.

---

Hey @mandric when you're around can we chat about this. I'd like to understand the thought process behind this metadata, and what it's for.

Questions:
 - The sentinel framework creates the metadata, but only if the individual transitions make changes to the doc. Why only if the document has been written to? Hasn't it been processed regardless?
 - This data it used by itself to make sure it doesn't run the transition twice: i.e. that the metadata write doesn't then cause another transition run. Is this technically needed? How does this interact with the (soft) requirement that transitions should be able to be run multiple times
 - This data is also used by some transitions to determine if they need to be run. Is *this* required? Should these transitions not be able to work this out based on what they have changed? Or is this just a good shortcut? Does this work if the document wasn't written to? 

Does it make sense to you to for me to make the following changes:
 - Drop the `maintain_info_document` transition (which atm just stores the last replication date), and incorporate its functionality into the transition framework
 - Move the transition metadata onto the info document instead of it being against the actual document
 - Change it so the transition metadata is always written to the info document, regardless of whether the document was changed

**Comment by SCdF** [comment] 2017-04-27 14:01
Re-scheduling this because I managed to dupe https://github.com/medic/medic-webapp/issues/2569 and it is scheduled. This ticket now has more information against it though, so I'm closing that one as a dupe and keeping this one.

**Comment by SCdF** [comment] 2017-05-05 08:35
@mandric can you respond to the above comment please? https://github.com/medic/medic-webapp/issues/3423#issuecomment-297687977

**Comment by SCdF** [comment] 2017-05-31 20:22
I've renamed this to cover a little bit more which all related.

We should also:
 - Move `sentinel-meta-data` and `shortcode-id-length` (and any other meta docs that basically only sentinel cares about) into a new `medic-sentinel` DB
 - When we pull out the transition metadata move that into a document in the new `medic-sentinel` DB

This is useful, both because it separates concerns, but also because it make write / permission management of these documents easier.

**Comment by alxndrsn** [comment] 2017-09-12 13:27
I think we should do this soon, as I understand it would:
* reduce traffic in the changes feed, improving:
  - performance for the main couch instance
  - bandwidth usage to all clients
* simplify sentinel logic for deciding which changes are relevant to it

**Comment by michaelkohn** [comment] 2017-10-12 05:50
In reference to https://github.com/medic/medic-webapp/issues/3944#issuecomment-335160042 , just want to make sure we'd still have access to the `-info` content in PostgreSQL (right now we are only replicating the `medic` database to PostgreSQL).

**Comment by SCdF** [comment] 2018-02-01 09:39
This is related to #4128 , as these info documents are doubling the number of documents in the DB, which is probably slowing down both sentinel, but also view generation in general.

**Comment by alxndrsn** [comment] 2018-02-01 09:45
+1 for moving the info docs into a separate DB and making our changes feed half the size!

@sglangevin Can we schedule this?

**Comment by sglangevin** [comment] 2018-02-01 19:12
We've scheduled #4128 so let's start with that. Once we do the investigation, we can decide on which improvements we want to make and when. This ticket sounds like a clear win, but I'd like to do the investigation first and see if it's at the top of the list before we proceed. I was hoping that if we have time in 2.15, we could add a sentinel performance improvement, but that could also be scheduled for 3.0.

**Comment by michaelkohn** [comment] 2018-02-02 09:13
Those info docs were mostly added for analytics purposes (LG).  If we move them to a different DB, they won't be replicated to PostgreSQL.  While we can configure which DB in Couch we want couch2pg to read from, we don't really have a way to direct that data into the same DB in PostgreSQL without things getting messed up (update sequences, migrations, etc...).

So, we should talk about how moving these to a different DB will effect PostgreSQL / couch2pg as well.

**Comment by SCdF** [comment] 2018-02-02 10:52
It should be reasonably straightforward to modify couch2pg to support multiple couch dbs, or at least allow you to run multiple instances without them fighting each other.

**Comment by ngaruko** [comment] 2018-05-02 05:59
Lookking at couchDB, `medic-sentil` has been moved to its own db. 
![image](https://user-images.githubusercontent.com/6979995/39507506-4c886b32-4e32-11e8-8720-eeea3fef18fd.png)

I understand @michaelkohn has expressed concerns about the implication of this move to `analytics` functions. Are you satisfied with suggested solutions above @michaelkohn before we close this?

**Comment by SCdF** [comment] 2018-05-02 08:20
@michaelkohn the data would be:
 - Specific to the running of sentinel
 - Doesn't need to be replicated down to users

Rest assured that 3.0.0 won't be released until the couch2pg changes have been throughly tested and approved by you and your team, against both 3.0.0 and 2.x (ie supporting both situations correctly). Once the PRs are ready to be merged we'll be (or you and Victor will be) chatting about how to best test this against prod data / situations to make sure we don't break anything.

**Comment by ngaruko** [comment] 2018-05-03 00:28
I guess we can close this issue at the moment and raise specific issues that might crop up later during the overall release testing, inviting @michaelkohn to keep an eye on features that may be affected.

**Comment by SCdF** [comment] 2018-05-21 08:10
@vimago / @ngaruko is it correct that this is closed? Victor has been working on changed to couch2pg and medic-couch2pg to support these changes, and the dev on that is just now concluding, and linked to this ticket. Is there another ticket that links to that work?

**Comment by ngaruko** [comment] 2018-05-22 03:34
Adding @michaelkohn to `assignees` and re-opening this for further testing...

**Comment by ngaruko** [comment] 2018-07-25 02:55
To AT this completely, I guess we need to[ install  and set up](https://github.com/medic/medic-projects/tree/master/middleware/upstart) `medic-couch2pg ` on  `alpha.dev`, a docker instance. I just want to check with @browndav and the SRE team if we should go ahead and ask @michaelkohn to [create the PostgreSQL Database](https://github.com/medic/medic-projects/tree/master/middleware/upstart) for `alpha.dev` ? Or are there any alternative equivalent options @michaelkohn  @browndav ?

**Comment by browndav** [comment] 2018-07-27 06:17
The Docker images already contain `medic-couch2pg` for a (currently-unused in production) local replica, and do not use upstart for service supervision. If you're able to find a way to AT this locally or on a copy of rdbms.dev (which is currently the actual production environment for `medic-couch2pg`), that will be most expedient. Alternatively, please contact @henokgetachew and/or @hareet and they should be able to advise further. Thanks!

**Comment by michaelkohn** [comment] 2018-08-16 21:16
@vimemo , I was going to type up some testing scenarios for @ngaruko for this but it's not clear to me how this ended up getting implemented.  

1. Are we expected to **(A)** run multiple `couch2pg` processes for every project? Or **(B)** was `couch2pg` updated to allow me to specify multiple `COUCHDB_URL`'s in the same `.conf` file? Or **(C)** etc....?
2. Will pre-upgrade `-info` docs be moved from the `medic` DB to the `medic-sentinel` DB post-upgrade?
3. What should I expect to see in PostgreSQL.... any new tables/fields/etc?
4. Is it safe to assume we can use the same credentials for the `medic-sentinel` DB that we are using for the `medic` DB?

**Comment by vimemo** [comment] 2018-08-17 14:46
Hello @michaelkohn / @ngaruko :

A couple of couch2pg processes are needed to replicate medic and medic-sentinel. Don't know if you are currently using [medic-couch2pg](https://github.com/medic/medic-couch2pg) but this takes care of starting both processes.

We are backward compatible, the process looks for -info in the medic db first and moves that to medic-sentinel on a per request basis.

Same tables/fields. We only added: couchdb_progress.source to identify the db source being replicated. Same credentials for both medic and medic-sentinel.

 Please let me know if anything is not clear. I can try to document this a bit more. Thank you.

**Comment by michaelkohn** [comment] 2018-08-17 16:07
Hmm.... running multiple `couch2pg` services is not really ideal because 

1. Records from the 2 DBs won't be in sync (in PostgreSQL, you'll have `-info` records for `data_record`'s that haven't sync'd yet or `data_record`'s without `-info` records).
2. It will call `refresh_matviews()` multiple times and that process alone already takes nearly 4h for some projects.  Running `refresh_matview()` multiple times *simultaneously* is going to fry our server.

While not ideal, I could probably live with **`#1`** in the short term because not many partners care about the `-info` records and we could simply set the `COUCH2PG_SLEEP_MINS` for that process to be very short.  **`#2`** concerns me more, though I suppose we could add an env variable (which defaults to `true` if not provided) that says whether or not to call `refresh_matviews()`.

**Comment by michaelkohn** [comment] 2018-08-17 16:15
For **`#2`**... I think we could actually use the `V0_4_MODE ` env variable to disable matview refreshes.

**Comment by michaelkohn** [comment] 2018-08-17 17:02
Just had a chat with Victor and he clarified that by running `medic-couch2pg`, it will automatically sync the `medic-sentinel` database as well, so we don't need to run two processes to sync the 2 databases.

**Comment by michaelkohn** [comment] 2018-08-17 23:44
## Expected Behavior
**NOTE** I'm only documenting what I know to be important from an Analytics/PostgreSQL standpoint.  Someone else should chime in with acceptance criteria for other relevant functionality.

### CouchDB

_Note: The sub-bullet points below which indicate how the `xxx_replication_date` should be populated are here for clarity only.  The rules for updating these 2 fields has not changed.  The only thing that should change (from a CouchDB standpoint) after this update is the actual location of the `-info` doc_.

- If a **new document** is **created** in the `medic` DB, it's `-info` doc will be created in `medic-sentinel`.  
  - `initial_replication_date` will be set to `now()`.
  - `latest_replication_date` will be set to `now()`.
- If an **existing document** is **edited** and it **doesn't already have** an `-info` doc, the `-info` doc will be created in `medic-sentinel`.
  - `initial_replication_date` will be blank.
  - `latest_replication_date` will be set to `now()`.
- If an **existing document** is **edited** and it **already has** an `-info` doc and that `-info` doc is in the **`medic`** DB, the `-info` doc will be ***moved*** to the `medic-sentinel` DB.
  - `initial_replication_date` will not be updated.
  - `latest_replication_date` will be set to `now()`.
- If an **existing document** is **edited** and it **already has** an `-info` doc and that `-info` doc is already in the **`medic-sentinel`** DB, the `-info` doc, the `-info` doc does _not_ need to move and:
  - `initial_replication_date` will not be updated.
  - `latest_replication_date` will be set to `now()`.

### PostgreSQL

#### Running the new version of `medic-couch2pg` on an existing PostgreSQL database
- A new `source` field is added to the `couchdb_progress` table.
- The existing row in `couchdb_progress` will be updated to set `source` to `medic` (i assume, since this is the `Update Seq` of the `medic` DB).
- A new row will be added to `couchdb_progress` with the `seq` set to `0` and the `source` set to `medic-sentinel` (I assume).
- `couch2pg` runs on both the `medic` and `medic-sentinel` DB
- `couchdb_progress.seq` is updated for both `medic` and `medic-sentinel` sources.
- The structure and content in the `couchdb` table in PostgreSQL should look no different than it did before the upgrade.  Essentially this table should not notice any changes before and after the upgrade.

#### Running the new version of `medic-couch2pg` on a new PostgreSQL database
- Really the only difference from above is that `couchdb_progress` will initially be populated with the two records (one for each `source`) rather than updating the existing one.

@vimemo does this sound right to you?

@ngaruko if the above is true, then the first step is verifying all the `CouchDB` tests pass since we won't even be able to see that in PostgreSQL (ie we won't know which DB the `-info` docs are coming from since they'll all just be in the one `couchdb` table in PostgreSQL).

My assumption that we shouldn't see anything different in the `couchdb` table may be completely wrong based on @SCdF's https://github.com/medic/medic-webapp/issues/3423#issuecomment-385900534 because I really have no idea what else will be in `medic-sentinel`.   I hope we aren't going to be seeing a bunch of unnecessary documents being replicated down to PostgreSQL now.

**Comment by vimemo** [comment] 2018-08-20 18:02
@michaelkohn / @ngaruko : Sounds right to me. I am not exactly sure about those timestamps but the replicated -info (postgres records) with regard to new/existing docs should be the same as before this upgrade.

**Comment by michaelkohn** [comment] 2018-08-20 23:49
Thanks @vimemo.

@ngaruko I think our testing strategy in PostgreSQL will depend on what we expect to see in `medic-sentinel` (which I do not know the answer to).  If everything in `medic-sentinel` is already currently in the `medic` DB, then we might be able to just compare `pg_dump`'s (with a bit of [finessing](https://github.com/akaihola/pgtricks)).  The only difference I would expect to see is in `couchdb_progress` table.

I'm thinking we can have 2 webapp environments... one on v2.x.x and one on v3.0.0 (which would include this change).  Ideally we would clone an existing production environment... and actually do this on a couple different versions (so doing this over a couple different clones).

**v2.x.x Environment**
Have the existing version of `medic-couch2pg` installed and run `medic-couch2pg` from that v2.x.x environment on a corresponding PostgreSQL DB. 

**v3.0.0 Environment**.
Have the new version of `medic-couch2pg` installed.  Take a clone of the project's existing database.  Create a brand new database and run all the scripts from that projects PG github folder.   Run 2x`medic-couch2pg`, one for each database (the empty one and the cloned one).

**Testing**

1. Run through a number of test scenarios on both environments.  Creating docs, editing docs, deleting docs, SMS, collect, mobile, admin.... I imagine we already have some scenarios scripted for this.  We'd have to make sure to test all the scenarios mentioned in the CouchDB section [here](https://github.com/medic/medic-webapp/issues/3423#issuecomment-414013844).
2.  Perform all these scenarios on both environments (v2.x.x and v3.0.0). 
3.  Validate the changes in CouchDB
4. All 3 PostgreSQL DBs should look almost exactly the same with the exception of the `couchdb_progress` table.
5. Do the `pg_dump`, finesse, and compare the `pg_dump` files.

So the environment setup would look something like this.
![medic-webapp 3423 testing 1](https://user-images.githubusercontent.com/10096985/44372488-ffe54580-a498-11e8-9462-3a7a70f2fcb6.png)

**Comment by newtewt** [comment] 2018-09-04 20:29
> Ideally we would clone an existing production environment.

@michaelkohn  do you have a recommended production instance we should close for this test? 



@henokgetachew  @Hareet  would this be something you could setup for testing or give guidance on how we could possibly do it locally?

> I'm thinking we can have 2 webapp environments... one on v2.x.x and one on v3.0.0 (which would include this change). Ideally we would clone an existing production environment... and actually do this on a couple different versions (so doing this over a couple different clones).
> 
> v2.x.x Environment
> Have the existing version of medic-couch2pg installed and run medic-couch2pg from that v2.x.x environment on a corresponding PostgreSQL DB.
> 
> v3.0.0 Environment.
> Have the new version of medic-couch2pg installed. Take a clone of the project's existing database. Create a brand new database and run all the scripts from that projects PG github folder. Run 2xmedic-couch2pg, one for each database (the empty one and the cloned one).

**Comment by michaelkohn** [comment] 2018-09-04 21:18
@newtewt 

Here are a few good options:

https://lg-kenya.app.medicmobile.org (Mobile 2.13.7)
https://barefoot.app.medicmobile.org (SMS 2.14.4)
https://dpho-banke.app.medicmobile.org (SMS 2.13.5 - Nepali)
https://muso-mali.app.medicmobile.org (Mobile 2.16.0)

**Comment by newtewt** [comment] 2018-09-10 19:53
@henokgetachew @Hareet would this be something you could setup for testing or give guidance on how we could possibly do it locally?

I'm thinking we can have 2 webapp environments... one on v2.x.x and one on v3.0.0 (which would include this change). Ideally we would clone an existing production environment... and actually do this on a couple different versions (so doing this over a couple different clones).

v2.x.x Environment
Have the existing version of medic-couch2pg installed and run medic-couch2pg from that v2.x.x environment on a corresponding PostgreSQL DB.

v3.0.0 Environment.
Have the new version of medic-couch2pg installed. Take a clone of the project's existing database. Create a brand new database and run all the scripts from that projects PG github folder. Run 2xmedic-couch2pg, one for each database (the empty one and the cloned one).

**Comment by newtewt** [comment] 2018-09-21 15:28
@henokgetachew  @Hareet  hey could you guys have a look and give a suggestion on where we could accomplish this environment setup?  Thanks

@michaelkohn  would it be possible to setup a time and run through this together? I still don't know much about this portion of the app and might be able to wrap testing up faster that way.

**Comment by michaelkohn** [comment] 2018-09-21 18:37
@newtewt yep.  I'll ping you on Slack to figure out a time.

**Comment by newtewt** [comment] 2018-10-01 13:44
@Hareet  looks like the infrastructure ticket is resolved. Would we be able to move forward with this ticket sometime this week?

https://github.com/medic/medic-infrastructure/issues/17

**Comment by Hareet** [comment] 2018-10-01 15:00
> v3.0.0 Environment.
Have the new version of medic-couch2pg installed. Take a clone of the project's existing database. Create a brand new database and run all the scripts from that projects PG github folder. Run 2xmedic-couch2pg, one for each database (the empty one and the cloned one).


@newtewt You can use one of the test upgrade processes I just completed. I used an existing projects database and it's running on 3.0 on a container. I'll ping you the details.

I'm not sure if I understand the empty database use:
Do you need to create a new empty database inside the same project (that has an existing db)? or spin up an empty (brand new) project and use the old db's couch2pg scripts?
The latter is resolved by using your local docker container and configuring the scripts to point to localhost. The former you can do manually once you pop into the test upgrade container.

@henokgetachew - Can you help with his v2.x environment?

**Comment by newtewt** [comment] 2018-10-01 18:45
@Hareet  I am assuming I could do the postgresql DBs on my local machine but not 100%.  As they're just getting data out of couchdb and dumping into postgresql. @michaelkohn  would this be acceptable to run the 3 different postgresql dbs locally?

**Comment by newtewt** [comment] 2018-10-01 19:28
Awesome. I'll get that setup and then try to work out a time with @michaelkohn  to get through this.  Thanks

**Comment by newtewt** [comment] 2018-10-04 18:03
I am seeing medic-couch2pg pulling data from 2.18 instance on beta-old and from 3.0 on my local docker to postgres running locally in a docker container as well. The count from `select count(*) from couchdb;` is showing as expected after creating, deleting, updating, changing admin settings, and using sms forms. 

The seq number is updating as expected with whats on the medic(2.18) or medic and medic-sentinel (3.0). 

The only outstanding item I'd say here is going from 2.18 to 3.0 and seeing it work with everything from being just in the medic database.   

@Hareet  @henokgetachew  is it possible to get a 2.18 environment setup that I can then move to 3.0?

**Comment by newtewt** [comment] 2018-10-11 17:42
After the recent change we are now in sync with counts in the couchdb and the postgressql databases. Looks like we are good to close this one.

**Closed by newtewt** 2018-10-11 17:42 UTC
Labels: Priority: 2 - Medium, Status: 4 - Acceptance testing, Type: Performance, medic-sentinel

**Comment by garethbowen** [comment] 2018-10-11 19:42
Fixed in `3.0.x` in https://github.com/medic/medic-webapp/commit/691bb864ff28aa4fd9143af7661c71021a0660fb
