### ISSUE TITLE
Cannot update a contact's phone number without an error

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2661] opened 2016-08-23 15:17 UTC
When you try to edit the phone number of a person, you get an error while saving because the system thinks the number is not unique. To reproduce, go to a person, click edit, then click Submit to try to save that person (they must have already had a phone number).

**Comment by sglangevin** [comment] 2016-08-24 21:45
![image](https://cloud.githubusercontent.com/assets/1286381/17949257/5e6615c0-6a09-11e6-843c-1afcabdb443a.png)

**Comment by estellecomment** [comment] 2016-08-25 15:53
I see it on lg.dev.
I can't reproduce it locally, even with same version (2.8.0-beta.6), minifying, and using the same `contact:person:edit` form.

More tomorrow...

**Comment by estellecomment** [comment] 2016-08-26 09:00
Ha!

[This line](https://github.com/medic/medic-webapp/blame/2.8.0-beta.6/static/js/enketo/widgets/phone-widget.js#L52) : 
`var contactBeingEdited = angular.element( $( '.enketo form' ) ).scope().enketo_contact;`
is failing because the `.scope()` is not found. 
And that's because [`angular.element(blah).scope()`](https://docs.angularjs.org/api/ng/function/angular.element) needs [Debug Data](https://docs.angularjs.org/guide/production#disabling-debug-data) enabled to work! 
And we enable it [only for localhost](https://github.com/medic/medic-webapp/blob/2.8.0-beta.6/static/js/app.js#L66).

**Comment by estellecomment** [comment] 2016-08-26 09:16
It should be fixed already by https://github.com/medic/medic-webapp/commit/375bfc984a11d2414f73dd14e539298de5e77dba, which is tagged 2.7.1, so I'm not sure what happened there. Looks like the release branch hasn't merged for a while. 
@garethbowen ?

History for the file : 
https://github.com/medic/medic-webapp/commits/master/static/js/enketo/widgets/phone-widget.js

**Comment by garethbowen** [comment] 2016-08-28 20:32
@estellecomment I have no idea how GH works out the tag because it seems kind of random. This was fixed in #2420 which hasn't been included in [2.7.x](https://github.com/medic/medic-webapp/blob/2.7.x/static/js/enketo/widgets/phone-widget.js#L52) or [2.8.x](https://github.com/medic/medic-webapp/blob/2.8.x/static/js/enketo/widgets/phone-widget.js#L52).

I'll make sure this makes it in to 2.8.0.

**Comment by garethbowen** [comment] 2016-08-28 20:33
This is a duplicate of #2420

**Closed by garethbowen** 2016-08-28 20:33 UTC
Labels: 2 - Active Work, Bug
