### ISSUE TITLE
When I change the outgoing message language, outgoing messages are still sent in English

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1190] opened 2015-08-21 19:06 UTC
Changing the outgoing message language in Configuration > Languages works as expected but that change doesn't actually change what is sent out. I'm still getting reminders in English even after changing the language in Configuration. 

Also, changing the language in Configuration > Languages doesn't change the language that is highlighted in the configuration wizard. (Changing the language in the configuration wizard DOES change the language selected in Configuration though)

I also tried changing the language and then closing and re-opening Medic Mobile but that didn't seem to help either. Still only getting English responses.

**Comment by garethbowen** [comment] 2015-10-19 03:30
@sglangevin It looks like it's working as designed. Messages are generated when the report is received, so if you submit the report and then change the default locale the existing scheduled messages will stay in the previous default locale. We have a plan to replace this process with one that only generates the message when it's due to be sent which would fix this bug. Can you please confirm if any reports received after you change the default outgoing locale have scheduled messages generated in the new locale?

> Also, changing the language in Configuration > Languages doesn't change the language that is highlighted in the configuration wizard.

I tried this also, and it worked (after a refresh). Can you please verify that this is the case and split this off in a new bug if required?

**Comment by sglangevin** [comment] 2015-10-19 16:37
@garethbowen I am still seeing only English messages. I tested using both Medic Reporter and texting from my phone and no luck on getting the schedules to appear in the selected language for outgoing messages. My process was to change the language for outgoing messages, send a registration, then check the created schedule to see what language it was in. 

As for the second issue of changing what is highlighted in the configuration wizard, that seems to be working now.

**Comment by katanu** [comment] 2015-10-22 07:27
Wanted to add our voice here, and confirm, that this is an issue that we
have had with some of our projects now-the outgoing messages are not in the
configured language: e.g-AMREF Ethiopia-made to be in Amharic and they go
out in Swahili, CA-Narok-meant to go out in Swahili, but go out in English
and the Child Fund Senegal-meant to be in French, but go out in Swahili.

On Mon, Oct 19, 2015 at 7:37 PM, sglangevin <notifications@github.com>
wrote:

> @garethbowen <https://github.com/garethbowen> I am still seeing only
> English messages. I tested using both Medic Reporter and texting from my
> phone and no luck on getting the schedules to appear in the selected
> language for outgoing messages. My process was to change the language for
> outgoing messages, send a registration, then check the created schedule to
> see what language it was in.
>
> As for the second issue of changing what is highlighted in the
> configuration wizard, that seems to be working now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/1190#issuecomment-149274733>
> .
>



-- 

--------
Join our community. Sign up for Medic Mobile's newsletter.
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>

Jane Katanu  Africa Regional Designer
Medic Mobile
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=6911deb493&e=c511575255>
 +254727823672
@Medic
<http://medicmobile.us8.list-manage2.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=95a573475f&e=c511575255>
 Facebook
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=7282d6a45d&e=c511575255>
 ,

**Comment by sglangevin** [comment] 2015-10-26 18:49
Update: I did a bunch of testing on my Windows laptop to see if I could get the schedules in the expected languages. Using Medic-Reporter and setting the locale worked, I was able to get messages in the language of the locale that I sent. I also tested using a curl command from my terminal and was able to successfully send in registrations but the schedules were only in English, regardless of the language that I selected for outgoing messages in config. Curl commands with locales worked, so I'm pretty sure that this issue is limited to registrations coming without locales, which applies to all registrations for DIY. I have also reproduced this using 0.5 and a GSM modem: text message registrations only create English schedules, regardless of the language selected for outgoing messages in Config.

Note that this issue cannot be reproduced on 0.4, it is an issue on 0.5 only.

**Comment by mandric** [comment] 2015-10-26 19:13
If you specify a `locale` query param on the URL you use to submit a message then you are setting a value the report/doc in `sms_message.locale`.  Depending on the context this can override other locale settings, like a system level one in app settings.  So when schedules are generated and sms_message.locale is different than the app_settings value it will override.  I think this is what you are experiencing.     I also think this applies to all versions.

This would allow you to support responses and schedules in multiple locales on two different phone numbers.  For example you can configure the gateway (or when using curl for that matter) to use a query param like ?locale=fr to do doc-level locale setting.  We haven't really decided whether or not we want to make this part of the public API though.  If you look at the couchdb log you can see the locale query param being set.

**Comment by sglangevin** [comment] 2015-10-26 19:18
That makes sense. So I was sending in registrations with no locales and getting English schedules, even if I had set the outgoing message language to another language - I tested French and Swahili. The issue is that registrations that don't specify locales only seem to create English schedules when they should create schedules in the language selected in Config. For now, supporting schedules in multiple languages based on different phone numbers is not required, but could be an interesting feature to explore down the line.

**Comment by mandric** [comment] 2015-10-26 19:20
It exists because it was was required for a past project.  Doesn't mean it shouldn't be removed or refactored though.

**Comment by sglangevin** [comment] 2015-10-26 19:22
I don't have a strong opinion there - this issue is to solve the problem of English-only schedules when schedules for registrations received without locales should be in the language selected by the user in the configuration wizard or on the configuration tab of the app.

**Comment by mandric** [comment] 2015-10-26 20:22
Ok this is likely an issue with the sms_message.local value overriding the app settings value.

**Comment by abbyad** [comment] 2015-10-29 14:56
Assigned to @garethbowen for code review.

**Closed** 2015-10-29 18:48 UTC
Labels: 4 - Acceptance testing, Bug

**Comment by sglangevin** [comment] 2015-10-30 18:40
Took me some time to get set up to test, but this is working well.
