### ISSUE TITLE
Ability to add unique `patient_id` to contacts created using app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3000] opened 2016-12-08 14:17 UTC
We should be able to add/edit the person's short ID (`patient_id`) in the default forms to add/edit people.

This is a followup to #2828.

**Comment by sglangevin** [comment] 2017-01-27 23:31
@abbyad is this a feature we need for SMS workflows in v2 or a nice-to-have?

**Comment by abbyad** [comment] 2017-02-18 12:12
A patient ID needs to be added to the person forms if you want to submit SMS reports about people created via the app. The feedback we got during prep for Standard config is that you'd want to be able to submit SMS about all patients, even if they were added at the health facility. After discussion with @SCdF related to #3082, instead of adding the patient ID as an editable field it is better to have sentinel add the patient ID to ensure uniqueness. If a project wants to use externally generated IDs they can still add them to the person creation forms. Renaming the issue accordingly.

This feature is not required for migrating v0.4 projects, but is a required feature for SMS workflow projects that are supported by app workflows at the facility, which is the way many v2 projects are being designed.

**Comment by abbyad** [comment] 2017-02-28 19:43
Removing my assignment since this now requires dev work in sentinel (see #3166 for more info)

**Comment by SCdF** [comment] 2017-03-08 17:21
PR: https://github.com/medic/medic-sentinel/pull/114

@mandric could you take a look at this one plz. 

NB: this does mean we're going to generate ids for CHWs as well. I'm cool with this (as is Marc). I think honestly it could be useful if people want to be able to submit CHW reports in the future via SMS. The one down-side is that the field is `patient_id`. Ideally it would be `person_id`, but it's used in configs, and generally spread throughout the code, so if we're going to fix it I think it's going to be a separate piece of work.

**Comment by mandric** [comment] 2017-03-08 19:34
See PR, couple questions on this one.

**Comment by SCdF** [comment] 2017-03-09 11:00
@mandric I answered your questions hopefully. Let's talk when you're around on Slack / Hangouts

**Comment by mandric** [comment] 2017-03-09 15:33
@SCdF sounds good.  (Seems redundant to keep pinging here in the issue as well as the PR.  I think once the issue is tagged code review we can assume discussion is moved to a PR.)

**Comment by SCdF** [comment] 2017-03-14 10:22
This work has been completed and merged to master.

A/T: Any which way you create a `person` / patient, you should get a patient_id created for that person (NB: make sure sentinel is running, and you have enabled the new transition)

**Comment by abbyad** [comment] 2017-04-06 18:04
The very first time I tested this two people were created:
- [doc 1](https://clone-barefoot.app.medicmobile.org/_couch/_utils/document.html?medic/4e8b44624f528af64152afa72128ebb8)
- [doc 2](https://clone-barefoot.app.medicmobile.org/_couch/_utils/document.html?medic/4e8b44624f528af64152afa72128dbde)

The docs are practically identical, even the `reported_date` is the same down to the ms. The only differences are `patient_id`, and naturally the couch fields (`_id`, `_rev`). The [New Person SMS report](https://clone-barefoot.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/4e8b44624f528af64152afa72128d03f) that created the person has only one `patient_id` attached to it. That form uses the `add_patient` trigger.

I have not been able to reproduce this. Reopening, but we could open a new issue if preferred.

**Comment by SCdF** [comment] 2017-04-07 07:43
@abbyad can I get some reproduction steps please (I'm aware you've been able to reproduce it, but I mean, can you list what you did specifically?)

**Comment by SCdF** [comment] 2017-04-07 08:37
@abbyad my coffee just kicked in: this ticket is about adding a patient id to created person documents. The work on this ticket doesn't actually involve creating person document at all. You can see the crux of the work here: https://github.com/medic/medic-sentinel/blob/master/transitions/generate_patient_id_on_people.js

I'm going to re-close this, since there is nothing wrong[1] with this work, and create a new ticket for you.

[1] That we've noticed, so far, fingers crossed, touch wood, and so on.

**Closed by SCdF** 2017-04-07 08:37 UTC
Labels: 2 - Active Work, Contacts, Returned
