### ISSUE TITLE
[enketo] Submit button stays disabled after correcting validation errors

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1298] opened 2015-09-14 10:24 UTC
# Environment
* Chrome
* Firefox

# Steps to recreate
1. in _Reports_ tab, select an ANC report
1. click `[edit]`
1. delete the value for *Pregnancy ID*
1. click `[submit]`
1. observe validation error on *Pregnancy ID* field
1. enter pregnancy ID `12345`
1. defocus the *Pregnancy ID* field
1. observe validation error is removed, but `[submit]` button is still grayed out

# Expected behaviour
In final step, we should see the `[submit]` button return to normal 'active' state.

**Comment by garethbowen** [comment] 2015-09-14 11:22
Good spotting. I believe this is fixed in https://github.com/medic/medic-webapp/commit/add004929272814ab38babd7319b9054e1146c9f because I can no longer reproduce it.

**Closed by garethbowen** 2015-09-14 11:22 UTC
Labels: 1 - Scheduled, Bug
