### ISSUE TITLE
Browser OOM crash on Enketo db-object prepopulated forms

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4319] opened 2018-03-22 13:16 UTC
When an Enketo form which contains a `db-object` field, prepopulated with a circular referenced object (f.e. generated by LineageModelGenerator), is loaded, an infinite loop runs which either causes an Out of Memory crash or Throws a Maximum call stack size exceeded error.

![image](https://user-images.githubusercontent.com/35681649/37772462-60e56c48-2de3-11e8-9391-6b0cb3c29f00.png)

Can be observed in alpha.dev when editing any district_hospital which has a primary contact, editing any health_center which has a primary contact, editing any household (area) which has a primary contact, or submitting a form (from the contact page) for a contact which is its parent's primary contact.

**Comment by SCdF** [comment] 2018-03-22 13:39
Interesting that this is a problem now and not before (we were always recursing).

In any case, we probably want to still recurse (otherwise why would be hydrating at all), so we should either:
 - stop generating recursive objects when we hydrate
 - change our recursion here to depth first (since that's how people would expect the references to sit I think?) and block recursion into objects we've already recursed into
 - Or maybe just do a depth limit (maybe 10, or some max lineage depth number + 1 for top-level contact?) and not have to think about it

**Comment by rmhowe** [comment] 2018-03-27 14:19
I can't reproduce this locally on 2.15 or on beta.dev even with the latest standard forms (but can locally on 3.0 and alpha.dev) so I'm assuming this is a bug introduced recently, probably by the shared lineage library as the shared library may be adding in extra data that webapp may not use/be expecting. I'd suggest moving this issue to 3.0.

**Comment by sglangevin** [comment] 2018-03-27 14:38
Let's move this if it's not an issue in 2.15.0.

**Comment by SCdF** [comment] 2018-03-27 15:03
@rmhowe when you say you can't reproduce it, are you saying that if you open a form with a recursive lineage attached it doesn't do it?

I've 99% sure I've seen this on 2.15.

**Comment by sglangevin** [comment] 2018-03-27 15:27
The original issue was filed against alpha, which would have been on 3.0. Is this the same issue that @abbyad had reported a while back? I think that was on a comment on another issue or on Slack that I now can't find. I remember him testing on 3.0 and (I think) on 2.15 and he found that there wasn't an issue on 2.15. It's possible that he actually tested on 2.14 and found no issue there. @abbyad do you remember/can you clarify?

**Comment by rmhowe** [comment] 2018-03-27 15:35
@SCdF yes exactly, attempting to edit the same form on `2.15.x` had no issues while on `master` produced the bug.

**Comment by dianabarsan** [comment] 2018-03-27 15:37
I've also just tested it on `2.15.x` branch using same configuration as before and the form works correctly.

**Comment by SCdF** [comment] 2018-03-27 16:20
Awesome, clearly my brain is part of the 1%!

**Comment by ngaruko** [comment] 2018-04-18 01:39
Tested on `alpha.dev` (version `3.0.0-alpha.9880`). >> People >> select from the LHS >>> Edit
Observed: `Primary Contact` dropdown comes pre-populated with some UUID and some errors in the console (`RangeError: Maximum call stack size exceeded`).
![image](https://user-images.githubusercontent.com/6979995/38906439-e144e738-430a-11e8-9edf-551a77f61de2.png)

On `beta.dev` (version `2.15.0-beta.9`), the UUID appears for a second and is quickly replaced by the actual primary contact. No console errors:
![image](https://user-images.githubusercontent.com/6979995/38906672-18cf0bf6-430c-11e8-865d-80517019a068.png)

**Comment by dianabarsan** [comment] 2018-04-18 06:55
I think `alpha` is not deployed properly and you're observing the behavior this issue was reporting.

**Comment by ngaruko** [comment] 2018-04-18 21:41
Thanks @dianabarsan . I understand `alpha` is outdated at the moment and cannot be deployed at the moment after the death of `kanso`( RIP, dear Kanso!).... I am marking this as ready since it is passing on `beta.dev` and `local` (when there is a `primary contact`).

**Closed** 2018-04-18 21:42 UTC
Labels: Priority: 1 - High, Status: 5 - Ready, Type: Bug

**Comment by dianabarsan** [comment] 2018-04-19 04:41
@ngaruko `beta.dev` was never affected by this bug, it was exclusive to `alpha` (`3.0.0`). I guess if you've tested it locally, it should be sufficient.
