### ISSUE TITLE
Send Report dropdown menu items are misaligned

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3469] opened 2017-05-11 17:05 UTC
Even I can see that this isn't quite right:

![screen shot 2017-05-12 at 01 04 24](https://cloud.githubusercontent.com/assets/191496/25962076/020bf51a-36af-11e7-9d2f-001fa7bfa307.png)

**Comment by sglangevin** [comment] 2017-05-11 18:15
Yeah, this has been bugging me for a while and should be fixed. If it's an easy fix to center everything vertically, we can schedule this. Otherwise I'd wait until a little later.

**Comment by garethbowen** [comment] 2017-06-20 01:35
@sglangevin Believe it or not, it isn't possible to fix this. The problem is the arrow is floated to the right, and we don't know how high the row is going to be (it may have no image or a small image or a large image, the text could wrap, etc).

I suggest we get rid of the chevron altogether. We don't use it anywhere else, not even in the "submit report" menu on the Reports tab. If we removed it then the menu would look like this:

Firefox:
![firefox](https://user-images.githubusercontent.com/2064938/27312574-562ed4be-55bd-11e7-82d1-27cdc9e47c3f.png)

Chrome:
![chrome](https://user-images.githubusercontent.com/2064938/27312582-5cba7e46-55bd-11e7-89f7-dc74f84a0d4e.png)

**Comment by sglangevin** [comment] 2017-06-20 19:15
The chevron was there in the original design for this menu, so I'm not sure I want to eliminate it without thinking about other possible alternatives.

@amandacilek @diannakane given that we aren't able to center the chevron in the row due to the row being variable height, do you have any suggestions on the way forward? Our options are:

- Remove the chevron entirely
- Come up with something else that would look fine if either top or bottom-aligned

**Comment by amandacilek** [comment] 2017-06-20 19:30
As I understand the history here, the arrow was added to make the row look more like an actionable, clickable thing. I think the greater question is how do we make these clearly look like actions.

Our Material Design navigation updates re-think how actions are represented (FAB button that opens up a bottom panel with a grid of actions). But that solution is down the road...

If I had to do a quick fix of this area, I would probably recommend limiting the size of the icon to a standard predictable size (we've talked about this in relation to other pages and I don't see why it wouldn't apply here as well. Should be app-wide standard 30 x 30 px or whatever), and then locking the text down to one row of text that truncates with ellipsis if necessary. Wherever possible, we should always be encouraging text that is short and to the point. As these are basically the same as tasks and form titles, I think one line should be sufficient. If a title were really long, the first part of the title, in combination with the icon, should be enough to understand what it is without the text displayed in full.

**Comment by garethbowen** [comment] 2017-06-20 22:15
I've checked with @sglangevin and she's comfortable that restricting icons to 30x30px throughout the app is acceptable in all our existing projects as nobody is using icons larger than this. If we need larger icons at a later date (eg: Targets widgets) then we can either upload two different sized icons or upload large svgs that will scale down nicely wherever we want the small size.

**Comment by amandacilek** [comment] 2017-06-20 23:49
Suggestion:
![screen shot 2017-06-20 at 4 49 07 pm](https://user-images.githubusercontent.com/26235957/27360840-6bcb2f78-55d8-11e7-9c21-20d6cf2b9567.png)

**Comment by amandacilek** [comment] 2017-06-20 23:51
This is consistent with my recent suggestions for other content rows (icon is 10px from left edge, and row text starts 50px in).

**Comment by garethbowen** [comment] 2017-06-21 00:56
Quoting some guy...

> Believe it or not, it isn't possible to fix this.

Actually it turns out it is possible. _cough_. So I've fixed the vertical alignment without restricting the size of the icon. I've also made the Reports > Submit Report menu look the same as the People > Action menu because they both list available forms. Now it looks like this:

![flexy](https://user-images.githubusercontent.com/2064938/27362217-f6f7aed4-5680-11e7-8b62-afdbf971057a.png)

@amandacilek Please raise a new issue for making the improvements you suggested over the entire site so it can be prioritised.

@estellecomment Code review please!

**Comment by estellecomment** [comment] 2017-06-21 08:48
One comment, otherwise cool

**Closed** 2017-06-21 10:45 UTC
Labels: 4 - Acceptance Testing, UI/UX

**Comment by sglangevin** [comment] 2017-08-02 22:15
These look much better in 2.13.0-beta.2!
