### ISSUE TITLE
/api/sms shouldn't throw errors just log problems

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3672] opened 2017-07-17 12:29 UTC
The `/api/sms` endpoint should not throw errors if it encounters problems with the data gateway is passing it.

For example, if gateway attempts to update a message who's documented has been deleted we should just note this and not return an error to gateway.

The guiding philosophy here is that gateways are deployed in remote situations and are a pain to debug, whereas api is online and easy to access, and so that is where the failures should be exposed.

**Comment by SCdF** [comment] 2017-07-17 12:33
@alxndrsn check out the PR linked above, and let me know if that's what you're thinking.

**Comment by alxndrsn** [comment] 2017-07-17 15:08
LGTM

**Comment by henokgetachew** [comment] 2017-07-26 13:56
API is still throwing exceptions when this happens.  Reopening.

**Comment by henokgetachew** [comment] 2017-07-26 20:35
@mandric the PR is linked above that fixes the remaining change that needs to be made.

**Comment by mandric** [comment] 2017-07-27 18:48
Looks to be superseded by https://github.com/medic/medic-api/pull/185

**Comment by henokgetachew** [comment] 2017-07-28 09:04
Yup and the fix has been confirmed to work in the field because it has been applied as a hot patch - the team needed it urgently.

**Comment by garethbowen** [comment] 2017-08-14 04:17
@mandric @henokgetachew So this can be closed now, right?

**Comment by henokgetachew** [comment] 2017-08-17 09:19
Yup closing this.

**Comment by henokgetachew** [comment] 2017-08-31 12:08
This has been AT'ed in the field because it was urgently needed as pointed out above.  Closing and moving this to released.

**Closed by henokgetachew** 2017-08-31 12:08 UTC
Labels: Status: 4 - Acceptance testing
