### ISSUE TITLE
Create and document a procedure for clearing test data

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2038] opened 2016-03-08 00:58 UTC
We need a procedure for clearing out test/example data before a branch transitions from testing to production. This procedure will need to accommodate rolling releases to multiple branches on the same instance, and will likely need to at least be able to restrict its scope to a user and a up-to-and-including date. The procedure should clear all CHP-creatable entities: contacts, facilities, reports, and messages.

To do:
- [x] Verify with LG that some combination of user scoping and date scoping is granular enough.
- [x] Document the procedure in the form of a human-readable checklist
- [x] Test the checklist steps using a copy of the current production instance, and verify that all items are cleared.
- [ ] Ensure no regressions are seen after the mass-deletion
- [ ] Ensure mass-deletions replicate correctly to mobile devices

**Comment by SCdF** [comment] 2016-04-04 20:09
LG says "everything on or before this date" is good enough

**Comment by SCdF** [comment] 2016-04-04 20:10
Next steps: tiny script

**Comment by estellecomment** [comment] 2016-04-04 20:10
Extra info : we will be doing the deletions for LG initially. 
Eventually, bulk_delete feature will enable LG (and other partners) to do it themselves.

**Comment by SCdF** [comment] 2016-04-04 20:13
Sounds like we need to go through a thought process on what happens if we delete something and then need to bring it back later. How would that work? Would we solve it with replication? Or are we comfortable just saying that once we delete something it's gone?

**Comment by SCdF** [comment] 2016-04-04 20:14
Also:

- [ ]  test that the deletions make it down to the phones

**Comment by abbyad** [comment] 2016-04-04 20:20
I have an uncommited* "dumb" bulk-delete that deletes all reports in a view if that is useful here.

_*uncommited for fear of it being inadvertently used on a live instance_

**Comment by estellecomment** [comment] 2016-04-06 12:00
The medic-api doesn't cover deletions, so I'm going to assume calling the DB directly is fine. @abbyad let me know if that's wrong.

**Comment by estellecomment** [comment] 2016-04-07 08:35
Assumptions : 
 - Training data is restricted to a given branch (‘district_hospital’ type), and to a time span (start and end timestamp)
 - Branch contains CHP areas (‘health_center’ types). CHP areas were created ahead of time, and won’t be deleted by this process.

Deletion plan : 
 - CHPs can create families (‘clinic’ type). All families created within the training period, in the branch in training, will be deleted.
 - CHPs can add members to families (‘person’ type). All members created within the training period, in the branch in training, will be deleted.
 - CHPs can fill in reports. Any report filed by anyone of the branch (CHP, branch admin) within the training period will be deleted.
 - CHPs can send messages. Any message sent by anyone of the branch (CHP, branch admin) within the training period will be deleted.

Note : that means if any “real” CHP areas or families or family members were created during that time, or any “real” reports or messages sent, they will be deleted. Can LG make sure this won’t happen? (@sglangevin)
If they can’t, we can restrict deletions to a given set of CHP areas. In this case, is the trainer also creating data? Is that trainer a CHP in the app, or a different type?

**Comment by estellecomment** [comment] 2016-04-07 08:41
More assumptions : pre-existing (“real”) families and family members will not be edited. (if they are, this process will ignore it)

**Comment by estellecomment** [comment] 2016-04-07 08:57
Oh wait, no "Messages" tab in CHP view, right? So no deletion of messages. Let me know if that's not right.

**Comment by SCdF** [comment] 2016-04-07 16:17
@estellecomment made some comments on the commit.

If you think the script will live for a reasonable amount of time you might wish to consider cleaning it up but if it's just a once-off script it probably doesn't matter.

**Comment by sglangevin** [comment] 2016-04-08 00:50
@estellecomment I've reviewed and agree with your Assumptions. On the Deletion Plan, CHPs can't create messages (as you noted), so you don't need to worry about those. Deleting families (type 'clinic'), people (type 'person') and reports will suffice.

I believe for all branches we will delete data for everyone from the branch at the same time. The only time I know of where we will need to exclude certain CHP Areas will be for Mukono, where some CHPs have already been using the app for a while and new ones will be trained. This branch won't go live for a while though.

LG confirmed that no real data will be entered during training. Trainers have accounts on lg.dev, so even if they enter data during training (they probably won't) it won't need to be deleted as it won't be on the production instance.

Let me know if I missed anything! We are getting confirmation on the exact time of day for deletion. Most likely we can run the deletion any time after April 15th. We are getting confirmation on the cutoff time so that we can delete all data entered before that time.

**Comment by estellecomment** [comment] 2016-04-08 09:47
Outputs pretty log. Gonna think about how to keep track of deletions to revert them later if needed.

```
11:39:40 scripts (develop) *$ node delete_training_data.js http://admin:pass@localhost:5984/medic 52857bf2cef066525b2feb82805fb373 1458735592585 1458736086553

Starting deletion process with
dbUrl = http://admin:pass@localhost:5984/medic
branchId = 52857bf2cef066525b2feb82805fb373
startTimeMillis = 1458735592585
endTimeMillis = 1458736086553


Deleting reports
Reports for branch : 408
Filtered by date : 13
Deleted : 13:
[ { ok: true,
    id: '18EB8F27-85FC-ECAF-AC57-1CD985104341',
    rev: '34-dde6568f763830cecb10b4417d9e745a' },
.....
  { ok: true,
    id: 'F9290A3A-9BCD-BA5D-9056-CA468E45899E',
    rev: '34-76bb4dae955d6c02d52c55c673caa74f' } ]
Reports deleted!

Deleting persons
Contacts for branch : 547
Filtered by date : 3
Filtered by type person : 2
Person F6DA3C83-6AE9-60CA-BFFB-B5DDF7D0BA82 is contact for 0 facilities
[]
Person C4AA03A1-80C6-76E7-B500-563FB108D73C is contact for 1 facilities
[ 'A8B6EB72-EBDF-702E-8C4D-CC632BC4E36A' ]
Removed contact F6DA3C83-6AE9-60CA-BFFB-B5DDF7D0BA82 from 0 facilities
[]
Removed contact C4AA03A1-80C6-76E7-B500-563FB108D73C from 1 facilities
[ { ok: true,
    id: 'A8B6EB72-EBDF-702E-8C4D-CC632BC4E36A',
    rev: '46-580593304aa75a722e4fc6f4acbadf87' } ]
Deleted : 1:
[ { ok: true,
    id: 'F6DA3C83-6AE9-60CA-BFFB-B5DDF7D0BA82',
    rev: '41-37a414ea10d46ad46df24fb505b24945' } ]
Deleted : 1:
[ { ok: true,
    id: 'C4AA03A1-80C6-76E7-B500-563FB108D73C',
    rev: '41-1b9670e64f277c6f8380f7ee676238c9' } ]
Persons deleted!

Deleting clinics
Contacts for branch : 545
Filtered by date : 1
Filtered by type clinic : 1
Deleted : 1:
[ { ok: true,
    id: 'A8B6EB72-EBDF-702E-8C4D-CC632BC4E36A',
    rev: '47-a21e4921bf58e1d9cb3b65dc1d67c067' } ]
Clinics deleted!
```

**Comment by estellecomment** [comment] 2016-04-08 10:23
Next : 
 - check it replicated to mobile devices. 
 - make a copy of lg.dev, run script on it, click around to make sure it looks right

**Comment by SCdF** [comment] 2016-04-08 11:52
Seems fine again, bar one potential issue in comments

**Comment by sglangevin** [comment] 2016-04-08 19:30
@estellecomment not sure where this comment should go, but we should either stop the server from receiving any data or back up the data (or both) prior to running the deletion since we know we can't get the data back once we do this.

**Comment by estellecomment** [comment] 2016-04-11 12:22
Deletions get replicated to the phones just fine. Yay!

However, watch out for **conflicts** : if the phone is offline, then edits a training doc, and then only gets back online and receives the deletion, that will create a conflict for the doc. The edited-deleted-conflicted doc will not be deleted on the phone, and it will eventually reappear on server, too.

This can happen especially easily with viewing an unread report (it's an edition because it sets the read status from unread to read).

An easy way to fix it is to **rerun the deletion script**. That takes care of it.

**Comment by estellecomment** [comment] 2016-04-14 07:36
Human-readable instructions : https://github.com/medic/medic-webapp/blob/develop/scripts/delete_training_data_HOWTO

Questions : 
 - Where to put the db backup copy? I suggest same server, call it `medic-backup-20160413`.
 - Where to put the backup files output by the script? They contain patient data (though it should all be fake training data, but who knows, maybe they trained with real names/patients)
 - Is killing `medic-api` enough to block incoming user changes, or can data come in some other way?
 - How do you kill/start `medic-api` on prod machine?
 - The `_users` DB won’t be backed up. I think that’s fine.

Assigning to @browndav because you know about prod machines setup, and @henokgetachew because it's possible tech leads will have to do this. How does it look? What did I miss?

**Comment by estellecomment** [comment] 2016-04-15 15:12
Assigning to @mandric, who maybe knows these things?

**Comment by btbonval** [comment] 2016-04-19 02:00
We do have a case where a Training User was assigned to a real branch. That user's data is not valid, but there is potentially real data during the same time frame.
https://github.com/medic/medic-projects/issues/172#issuecomment-211677567

Unsure if this warrents a new script, a modification of this script, or a larger discussion on SOPs.

**Comment by mandric** [comment] 2016-04-19 16:43
Delete script feedback below, I'm happy to do it or someone else can pick it up.

( ) Use COUCH_URL so we don't need to put admin/pass on the command line
( ) don't print the password/url
( ) Do date conversion in node? I pass in 2015-11-23 and you do new Date(arg).valueOf()
( ) Why use pouchdb, use straight couchdb api? (remove external dependencies so you don't have to do npm install foo)  If using _bulk_docs should we also use all_or_nothing option?
( ) I've never seen this before?
    {startkey: [branchId], endkey: [branchId + '\ufff0'], include_docs: true}
( ) Put the how-to/help docs in the script under usage? Maybe make them more concise too.
( ) create logs dir if doesn't exist, or if one isn't specified automatically create one with a date in it so it's always unique?
( ) confirm we append to logs, don't overwrite

Recommend running like this:

sudo /boot/svc-down medic-core && \
sudo /boot/svc-down gardener && \
sudo /boot/svc-up medic-core openssh 

sudo cp /path/to/couchdb/data/medic.couch  medic-$(date +%Y%d%m%H%M%S).couch && \
sudo /boot/svc-up medic-core couchdb

[ run delete script ]

sudo /boot/svc-up medic-core && sudo /boot/svc-up gardener

**Comment by estellecomment** [comment] 2016-04-25 12:46
> Why use pouchdb, use straight couchdb api? (remove external dependencies so you don't have to do npm install foo)

To use couchdb api you need to escape all the args in the URL, I couldn't get it to work, it drove me crazy. PouchDB api is more convenient. I added a `package.json` file for easy deps install.

> I've never seen this before? `{startkey: [branchId], endkey: [branchId + '\ufff0'], include_docs: true}`

It picks all the keys starting by `[branchId]`. The `\ufff0` tells it where to stop (the "last" character). From https://wiki.apache.org/couchdb/View_collation#String_Ranges

**Comment by estellecomment** [comment] 2016-04-25 13:00
> If using _bulk_docs should we also use all_or_nothing option?

Hmmm. In case of conflict, all_or_nothing will insert a conflicting revision. These conflicted docs may or may not get replicated to clients. I think I'd rather have the deleting fail for a doc than have it in conflicted state. So I'd say no, but happy to get more opinions.

**Comment by estellecomment** [comment] 2016-04-25 16:22
Deletion done!
Logs are at `~/data_deletion_20160425`. 

There were issues with DB timeouts, which are probably caused by couch reindexing after deletions and so being slower to serve requests, and so the client times out. But the requests are still being run successfully, so it leads to situations where you don't know if your data is deleted or not. 
I extended the `os_process_timeout` to 100k millis, and that helped. And also rerun the script until all the data was dead!

 - [ ] make big queries in batches to avoid db timeouts

**Comment by estellecomment** [comment] 2016-05-03 08:54
Update : I still want to add a prompt break in this, like "This is what's going to be deleted. Are you sure"? Because right now, if you mess up the order of the script args, or get the values wrong, or skip an arg, you might not be in dryrun mode when you think you are, or not be deleting what you think you are, and it's very bad. 

And then I'll close this!

**Closed** 2016-05-03 09:34 UTC
Labels: 2 - Active Work, Feature Request, v2.6
