### ISSUE TITLE
HBB should ‘cancel’ Report Bug modal.

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3091] opened 2017-01-30 21:43 UTC
Steps to reproduce:

1. Log into Medic Mobile
2. Go to ‘People’s’ tab or ‘Targets’
3. Settings >> Report bug
4. Report bug modal pops up
5. Press the HBB

**Expected** : Report bug modal should close and app be back to whatever screen/tab was open
**Current behaviour:** The Report bug modal does not close, until the app goes back to ‘Tasks’ tab

**Comment by garethbowen** [comment] 2017-01-30 21:44
This goes for all modals.

**Comment by nice-snek** [comment] 2017-05-10 08:20
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by mandric** [comment] 2017-06-19 17:51
Any updates here @ngaruko?

**Comment by garethbowen** [comment] 2018-10-31 08:43
@ngaruko Can you try this again? I expect it to work...

**Comment by garethbowen** [comment] 2018-12-03 08:51
Closing as cannot reproduce.

**Closed by garethbowen** 2018-12-03 08:51 UTC
Labels: Type: Bug
