### ISSUE TITLE
Errors during initial replication

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2141] opened 2016-03-29 06:54 UTC
A few screenshots of the errors I saw. Some were similar to what I saw in Uganda last week.

![image](https://cloud.githubusercontent.com/assets/1286381/14074768/29e34482-f4dc-11e5-9f54-5b493045e4d8.png)
![image](https://cloud.githubusercontent.com/assets/1286381/14074774/322697b6-f4dc-11e5-9326-b22d9413cc7b.png)
![image](https://cloud.githubusercontent.com/assets/1286381/14074814/7b6ab308-f4dc-11e5-916c-9f3336222ba8.png)

**Comment by garethbowen** [comment] 2016-03-29 09:06
That looks like expected behaviour to me. Initial replication didn't complete within 30 seconds, so the request timed out and the app attempted to start up which resulted in the other errors.

**Comment by sglangevin** [comment] 2016-03-29 14:06
@garethbowen is there a way to increase the time allotted for initial replication? Or is that what we were looking at on that other ticket? I'm guessing the answer is no.

**Comment by garethbowen** [comment] 2016-03-29 19:13
We can control the initial replication timeout, but doing so potentially delays the standard background sync.

I'm thinking about changing the way we do initial replication so for first load none of the app loads until replication completes, and it'll have no timeout and retries if necessary. Then the second load of the app will skip initial replication altogether.

**Comment by garethbowen** [comment] 2016-04-06 02:49
Closing as this is expected behaviour. Please reopen if these errors cause a problem for the users.

**Closed by garethbowen** 2016-04-06 02:49 UTC
