### ISSUE TITLE
Disable delete button for a place with restricted user associated with it.

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3044] opened 2017-01-12 19:19 UTC
Steps to reproduce: 
1. Create a restricted user >>Configuration >> Users >> Add User
2. User type -Restricted to their place
3. Select a place (best to create a place to delete first for a shared environment to avoid deleting someone's 'data')
4. select associated contact (??)
5. Password and Submit

...
6. Peole's tab
7. Look for the place selected in 3 and delete
8. Now we have got an 'invalid user' (as in #3041), ie restricted to a place but the palce has been deleted.
9. Also, in the users list, the 'Place' column is still ticked after place has been deleted.

![image](https://cloud.githubusercontent.com/assets/6979995/21904566/029cf824-d969-11e6-83e9-685c7a956470.png)

**Comment by nice-snek** [comment] 2017-04-26 05:46
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment] 2017-04-26 09:32
@ngaruko please confirm if this is worth fixing

**Comment by ngaruko** [comment] 2017-07-17 05:16
@alxndrsn It is not a really popular use case I would think. So if it takes a lot of effort to fix, it is definitely not worth the time IMO.

**Comment by garethbowen** [comment] 2017-07-17 10:00
I'm going to call this a duplicate of #969

**Closed by garethbowen** 2017-07-17 10:00 UTC
Labels: Feature Request, Needs Triage

**Comment by ngaruko** [comment] 2017-07-17 18:55
Fair call
