### ISSUE TITLE
Couch can take many minutes to supply the changes feed on app first-load

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1782] opened 2015-12-18 16:06 UTC
Investigating on my local machine the option of synching only non-user-specific data while the splash screen is running (#1270), I came across the following alarming performance:
```
$ time curl 'http://localhost:5984/medic/_changes?timeout=25000&heartbeat=10000&filter=medic%2Fdoc_by_place&_nonce=1450453351782&limit=1&id=nonsense'
{"results":[
  {"seq":32780,"id":"resources","changes":[{"rev":"53-57565c3cbb1168dc2c6f3338828398f0"}]}
],
"last_seq":32780}

real	3m46.008s
user	0m0.006s
sys	0m0.010s
```
Why is couch change feed filtering so slow?

Related: #1780 #1781 #1665

**Comment by alxndrsn** [comment] 2015-12-18 16:16
```
$ time curl 'http://localhost:5984/medic/_changes?timeout=25000&heartbeat=10000&filter=medic%2Fdoc_by_place&_nonce=1450453351782&limit=1&id=nonsense&since=32780'
{"results":[
{"seq":35047,"id":"form:pregnancy_follow_up","changes":[{"rev":"225-26ad7a31d5af66f5264ec36adfb92c8a"}]}
],
"last_seq":35047}
real	0m22.268s
user	0m0.004s
sys	0m0.005s
```

**Comment by alxndrsn** [comment] 2015-12-18 16:16
```
$ time curl 'http://localhost:5984/medic/_changes?timeout=25000&heartbeat=10000&filter=medic%2Fdoc_by_place&_nonce=1450453351782&limit=1&id=nonsense&since=35074'
{"results":[

{"seq":36722,"id":"form:assessment","changes":[{"rev":"284-e3419972ed35e263d28d293a3dce9940"}]}
],
"last_seq":36722}

real	0m14.626s
user	0m0.004s
sys	0m0.005s
```

**Comment by alxndrsn** [comment] 2015-12-18 16:23
```
$ time curl 'http://localhost:5984/medic/_changes?timeout=25000&heartbeat=10000&filter=medic%2Fdoc_by_place&_nonce=1450453351782&limit=1&id=nonsense&since=36722'
{"results":[
{"seq":36725,"id":"form:assessment_follow_up","changes":[{"rev":"185-e490dbb6f8de9a5a0812cfe543d814bb"}]}
],
"last_seq":36725}

real	0m0.060s
user	0m0.004s
sys	0m0.005s
```

**Comment by alxndrsn** [comment] 2015-12-18 16:25
Unsuprisingly, it seems like the time taken to find the next doc is proportional to the difference in sequence number between previous and newly-found docs.

The weird thing is that parsing 33,000 docs should take 270 seconds.  That's about 100 docs per second.

**Comment by alxndrsn** [comment] 2015-12-18 16:25
https://stackoverflow.com/questions/19165078/increase-speed-of-couchdbs-changes-feed-while-applying-a-filter

**Comment by alxndrsn** [comment] 2015-12-18 16:28
>  ...found that the filter increases the response by orders of magnitude. For ~6k documents the _changes response time was (on average) 4 seconds with no filter, and that jumped to 40 seconds with a filter applied.
> –_https://stackoverflow.com/questions/19165078/increase-speed-of-couchdbs-changes-feed-while-applying-a-filter_

**Comment by alxndrsn** [comment] 2015-12-18 16:30
Maybe it's just a fact of life - this post describes our problem fairly accurately, and no direct solution is offered: http://qnalist.com/questions/2386580/slow-filtered-changes-feed

**Comment by alxndrsn** [comment] 2015-12-21 09:59
Might be useful to create a separate view for each user.  Each would be defined like the [`doc_by_place` filter](https://github.com/medic/medic-webapp/blob/testing/lib/filters.js#L16).

**Comment by alxndrsn** [comment] 2015-12-21 10:25
...or even a separate ddoc - otherwise [all views will need updating whenever a new view is added to the `users` ddoc:

> Note that all views in a single design document get updated when one of the views in that design document gets queried. 
> –_https://wiki.apache.org/couchdb/Introduction_to_CouchDB_views_

**Comment by alxndrsn** [comment] 2016-01-04 18:17
To see how the filter function is eventually included in the ddoc:
```bash
$ curl 'http://admin:pass@localhost:5984/medic/_design/medic' | jq .filters
{
  "data_records": "function(){return require(\"lib/app\")[\"filters\"][\"data_records\"].apply(this, arguments);}",
  "design_doc": "function(){return require(\"lib/app\")[\"filters\"][\"design_doc\"].apply(this, arguments);}",
  "tasks_by_id": "function(){return require(\"lib/app\")[\"filters\"][\"tasks_by_id\"].apply(this, arguments);}",
  "doc_by_place": "function(){return require(\"lib/app\")[\"filters\"][\"doc_by_place\"].apply(this, arguments);}"
}
```

**Comment by SCdF** [comment] 2016-01-05 11:48
I'm going to say the Javascript function's weird loading situation is probably not a performance concern.

Running the `doc_by_place` filter locally eventually returns the `resources` document, 1345 documents in, taking ~13 seconds. Replacing the filter with `function(doc, req){return doc._id === \"resources\"}` takes ~13 seconds

_(it once anomalously took 8.5 seconds, but couldn't reproduce it and that's still really slow)_

**Comment by SCdF** [comment] 2016-01-05 15:20
Erlang filters seem to be, from the limited testing I've done, an order of magnitude faster.

I have not rebuilt the entire filter in Erlang, but I have replicated the simple resource filter above. I also split out the python into its own design document to remove the possibility that the large design doc is causing issues (ie parsing the JSON each time).

So testing the following:
```json
{
   "_id": "_design/js_filters",
   "_rev": "2-49e4fd1d9cc774162cb5604ba49d8c1a",
   "filters": {
       "resources": "function(doc){return doc._id === \"resources\"}"
   }
}
{
   "_id": "_design/erlang_hacks",
   "_rev": "2-6e508caf6a019c1f3058c48d95f4650f",
   "filters": {
       "resources": "fun({Doc}, {Req}) ->  case proplists:get_value(<<\"_id\">>, Doc) of <<\"resources\">> -> true; _ -> false end end."
   },
   "language": "erlang"
}
```

And got the following results (which bear out after repeating them multiple times: I have not tried multiple concurrents):

```
scdf at MacBook-Pro in ~
$ time curl 'http://admin:pass@localhost:5984/medic/_changes?timeout=25000&heartbeat=10000&filter=js_filters%2Fresources&limit=1&id=nonsense'
{"results":[
{"seq":1345,"id":"resources","changes":[{"rev":"53-57565c3cbb1168dc2c6f3338828398f0"}]}
],
"last_seq":1345}


real	0m9.151s
user	0m0.004s
sys	0m0.007s
scdf at MacBook-Pro in ~
$ time curl 'http://admin:pass@localhost:5984/medic/_changes?timeout=25000&heartbeat=10000&filter=erlang_hacks%2Fresources&limit=1&id=nonsense'{"results":[
{"seq":1345,"id":"resources","changes":[{"rev":"53-57565c3cbb1168dc2c6f3338828398f0"}]}
],
"last_seq":1345}


real	0m0.903s
user	0m0.004s
sys	0m0.006s
```

This seems to bear out that there is subsequent overhead in parsing and interpreting Javascript.

Another weird occurrence I've noticed is that filters in the same design document seem to be affecting each other's performance. I see stuff like this:

```
Running order:
medic/resources       ~9s
js_filters/resources  ~9s
medic/doc_by_type     ~12s
medic/resources       ~12s (for some amount of time, even through CouchDb restarts, then later back to 9)
js_filters/resources  ~9s (still, is not affected)
```

Which makes me somewhat doubt the validity of my setup, at least for ±25% quality results.

**Comment by SCdF** [comment] 2016-01-06 21:17
Here, have some Erlang: https://gist.github.com/SCdF/50b69e655595c56f679e

NB: haven't fully tested this but it appears to work.

On my local machine it runs 3x faster than the equivalent JS code. This is not the 10x we were experiencing before, which is a shame. Having said that, this code is probably not optimal, since I started learning Erlang this morning.

It's also twice the length of the equivalent JS, partially due to my Erlang being more verbose than JS, and partially due to me writing some helper functions to make the code more readable.

**Comment by SCdF** [comment] 2016-01-07 13:19
I updated the Erlang a little based on a quick reading of their optimisation guide (tl;dr; prefer head|tail on lists over more complex stuff, and my own observation that anon function calls are expensive). On my local machine taking the limit off the query (so it pulls all relevant docs for [I'm guessing] the admin user) JS runs in ~68 seconds and Erlang runs in ~18 seconds, which is 3.7x faster.

Not that this is an exhaustive test, but both functions do return the same documents, which is encouraging.

**Comment by SCdF** [comment] 2016-02-16 19:32
@alxndrsn I think it's safe to close this yes?

**Comment by alxndrsn** [comment] 2016-02-16 20:58
I'm not sure it's a very constructive ticket, but it might be interesting to have some numbers to compare before and after.  It also might be sensible to consider #1864 as a part of this.

**Comment by SCdF** [comment] 2016-02-22 20:05
I will create some terrible local benchmarks for the changes feed (so just curl, not in the app) with a 2x2 of:
 - JS vs. Erlang
 - Audit in same dir vs different dif

**Comment by SCdF** [comment] 2016-02-26 12:51
As promised:

 | Pre-split | Post-split
---|------------|----------
JS | ~101s | ~87s
Erlang | ~47s | ~33s

I compacted the DB before each run. On a laptop, so a healthy amount of scepticism is recommended.

**Closed** 2016-02-26 12:51 UTC
Labels: 5 - Ready, Performance

**Comment by alxndrsn** [comment] 2016-02-26 14:12
We'd best remember to compact post-migration on production databases.

**Comment by SCdF** [comment] 2016-02-26 14:13
I just did it as a matter of course because as I understand it auto-compaction happens. We don't have evidence that it actually made it faster as I didn't test pre-compaction.

**Comment by alxndrsn** [comment] 2016-02-26 14:33
Worth doing if we don't know either way.  Surely quicker to do it than measure the benefits.
