### ISSUE TITLE
couchdb 2.0 does not have _users by default?

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3431] opened 2017-05-01 17:28 UTC
In [the Readme](https://github.com/medic/medic-webapp/#setup-couchdb-on-a-single-node):
```
$ curl -X POST http://admin:secret@localhost:5984/_users   -H "Content-Type: application/json"   -H "Content-Type: application/json"   -d '{"_id": "org.couchdb.user:admin", "name": "admin", "password":"pass", "type":"user", "roles":[]}'
```
Fresh Couch 2.0 install:
```
{"error":"not_found","reason":"Database does not exist."}
```
Fix:
```
$ curl -X PUT http://admin:secret@localhost:5984/_users
{"ok":true}
```
Found this strange/odd but maybe it's worth noting in the readme.

**Comment by alxndrsn** [comment] 2017-05-02 08:04
I think this is a duplicate of https://github.com/medic/medic-webapp/issues/3225 - it might give you some ideas.  Perhaps we to check explicitly at e.g. API startup that this db is present in the expected place.

**Comment by SCdF** [comment] 2017-05-02 08:35
Yes. You have to follow the CouchDB 2.0 setup instructions.

**Comment by mandric** [comment] 2017-05-05 18:18
As far as I can tell creating a _users database is not part of the CouchDB 2.0 setup instructions.  Do you have a link to what you are referring to?

**Comment by SCdF** [comment] 2017-05-08 07:50
@mandric following the setup wizard thing in Fauxton.

**Comment by garethbowen** [comment] 2017-06-28 01:58
@mandric Can we close this now?

**Comment by mandric** [comment] 2017-06-29 17:29
Seems like for some reason you want to ignore two reports from different developers that _users is not found during setup because of user error?  If user error is what was agreed upon then it's fine to ignore them and close.  Otherwise we should update the docs with the PUT _users command or that mention need to run something in futon to finish the couchdb2 setup.

**Comment by SCdF** [comment] 2017-06-29 17:36
@mandric it's in the docs http://docs.couchdb.org/en/2.0.0/install/

**Comment by mandric** [comment] 2017-06-29 18:19
Can we add a link to that in the readme?

**Comment by mandric** [comment] 2017-06-29 18:27
PR on the way...

**Closed** 2017-06-30 06:46 UTC
Labels: 6 - Released, Documentation

**Comment by bash-stack** [comment] 2021-02-01 03:30
( use `PUT` since you do not update data `POST` WILL FAIL )


FAILING EXAMPLE:
```
root@couchdb1:/home/couchdb/couchdb# curl -s -X POST "http://$COUCHDB_USER:$COUCHDB_PASSWORD@couchdb$TASK_SLOT:5984/_users" --data-binary '{"_id": "org.couchdb.user:testuser","name": "testuser","roles": [],"type": "user","password":"testpass"}'
{"error":"not_found","reason":"Database does not exist."}
```

WORKING EXAMPLE
```
root@couchdb1:/home/couchdb/couchdb# curl -s -X PUT "http://$COUCHDB_USER:$COUCHDB_PASSWORD@couchdb$TASK_SLOT:5984/_users" --data-binary '{"_id": "org.couchdb.user:testuser","name": "testuser","roles": [],"type": "user","password":"testpass"}'
{"ok":true}

```
