### ISSUE TITLE
Admin view shouldn't show a home place

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2890] opened 2016-11-07 14:21 UTC
Admin log-in should not show a "home place" at the top of the LHS and should show only the "district" level 3 places. 

![screen shot 2016-11-03 at 12 11 17](https://cloud.githubusercontent.com/assets/1675870/20060929/2dfcd878-a506-11e6-8c1d-138e5a4484c7.png)

**Comment by garethbowen** [comment] 2016-11-07 20:31
@diannakane I think your admin must be configured with a facility_id referencing Busia Branch. This is a misconfiguration of the admin. Can you try clearing the facility_id and check again?

**Comment by abbyad** [comment] 2016-11-07 21:49
Typically admins are associated to a place to know what to see in the hierarchy, and a person to be able to complete a form. This seems to break the assumption that the admin does not have a place/person, which is used for these designs.

@diannakane we may need to reconsider how admins are associated to a place and person to figure out what they should see at the top of the LHS.

**Comment by diannakane** [comment] 2016-11-08 11:06
@garethbowen How do I clear the facility_id?

@abbyad Ah, so the role of admin permissions doesn't necessarily mean they
aren't associated with a place. The "admin" role we designed for is not
based on permissions role, but rather on someone with "root access" (no
place). If we want to assign admin privileges to a person at a place, that
shouldn't affect what they see in the LHS (the places they directly manage).

**Comment by sglangevin** [comment] 2016-11-15 01:16
The facility_id is necessary if we want the admin user to be able to complete reports. If that's not necessary, then the facility_id can be cleared from the admin user in Futon.

**Comment by abbyad** [comment] 2016-11-17 18:05
The new forms from #2828 do not use the `facility_id`, so a home place will not show in the LHS for admins unless they are legitimately assigned to a place.

Having figured out what the problem is I think we can close this issue as there is no action needed.

**Closed by abbyad** 2016-11-17 18:05 UTC
Labels: Contacts, Priority, UI/UX, v2.x
