### ISSUE TITLE
context_by_type_freetext view seems to run with no search term

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2584] opened 2016-07-28 01:48 UTC
![image](https://cloud.githubusercontent.com/assets/1286381/17198490/6ca51ac2-542a-11e6-98a8-f5504b7ebf35.png)

This leads to the following error in the console:
![image](https://cloud.githubusercontent.com/assets/1286381/17198497/79b80710-542a-11e6-9722-38ff0dc4e67e.png)

Which comes from here:
![image](https://cloud.githubusercontent.com/assets/1286381/17198506/8d26061c-542a-11e6-9f2c-b31bf2a64432.png)

This causes very large amounts of data to be downloaded (over 100MB) and degrades performance. I'm not exactly sure how to reproduce it, but will keep trying.

**Comment by sglangevin** [comment] 2016-07-28 01:50
Now it seems to happen every time - sometimes before the first call to `contacts_by_freetext` and sometimes between other calls to that view.

**Comment by sglangevin** [comment] 2016-07-28 02:00
Also, to add: you can reproduce this by going to a CHP area, clicking edit, then searching for a person in the supervisor field. Select that person and hit Submit.

**Comment by garethbowen** [comment] 2016-07-28 10:31
Sharon and I are both having difficulty reproducing this so I'll kick it out of the iteration.

**Comment by garethbowen** [comment] 2016-10-31 02:46
Closing as can't reproduce. Reopen if it happens again.

**Closed by garethbowen** 2016-10-31 02:46 UTC
Labels: Bug, v2.x
