### ISSUE TITLE
User Data Partitioning

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1689] opened 2015-11-26 04:55 UTC
I am currently logged in as training34 and I am to see all the registered families and all tasks for other users. I believe this shouldn't be the case. I have tried with other user logins and its the same.

![screen shot 2015-11-26 at 07 46 03](https://cloud.githubusercontent.com/assets/15346836/11415357/e794eab0-9412-11e5-8fc5-29b58ce0dded.png)

![screen shot 2015-11-26 at 07 46 15](https://cloud.githubusercontent.com/assets/15346836/11415364/f4fb8fc4-9412-11e5-895e-0e04e04aaf3a.png)

 
![screen shot 2015-11-26 at 07 46 24](https://cloud.githubusercontent.com/assets/15346836/11415368/04ddb534-9413-11e5-99f4-bbc27ed81e95.png)

**Comment by alxndrsn** [comment] 2015-11-26 07:48
@fredatthehub this looks like the `demo` account's data.  I think you're seeing it because you have previously logged in as `demo` on this computer, and you haven't cleared local data.  There's an open issue for this, but I can't find it right now; perhaps @garethbowen can remember the number.

**Comment by garethbowen** [comment] 2015-11-26 19:21
Duplicate of #1005

**Closed by garethbowen** 2015-11-26 19:21 UTC
Labels: 1 - Scheduled, Bug, Priority
