### ISSUE TITLE
When I delete a contact, they still appear as the primary contact for a place

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#940] opened 2015-05-08 19:01 UTC
I set a contact as the primary contact for a catchment area. After deleting that contact, that person still appears as the primary contact for the catchment area, though when I click to edit the place, the primary contact field is blank and that person is not listed in the drop-down for primary contact.

**Comment by garethbowen** [comment] 2015-05-11 10:35
Although it doesn't look the same I think this is a duplicate of #920 and thus, already fixed. Please try again to prove me wrong  :)

**Comment by sglangevin** [comment] 2015-05-14 23:35
Working now, though I have to refresh the screen to get the contact to disappear from the left pane.

**Comment by sglangevin** [comment] 2015-07-22 21:15
So now the contact deleted successfully from the left pane but the deleted person is still listed as the contact for the place. When I click edit place, the primary contact field is blank and if I select the blank option and submit, the deleted person still shows up under the place's contact field in the UI. I tried refreshing the screen and no luck. 

Editing the contact, selecting another person and submitting, then editing again and selecting the blank option was successful in clearing the Contact field though.

**Comment by garethbowen** [comment] 2015-09-03 02:05
The new issue is a duplicate of #969

**Closed by garethbowen** 2015-09-03 02:05 UTC
Labels: 2 - Active Work, Bug, Returned
