### ISSUE TITLE
Cannot access History on mobile

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1541] opened 2015-11-05 13:53 UTC
Opening the _History_ section on Tecno takes me straight to a specific item (report-content ctrl).  Pressing the `<` button from here browses backwards... but not to the _History_ list!

**Comment by garethbowen** [comment] 2015-11-05 19:08
This is probably a duplicate of:  #1541

**Comment by garethbowen** [comment] 2015-11-05 19:18
Closing as a duplicate of #1515

**Closed by garethbowen** 2015-11-05 19:18 UTC
Labels: 0 - Backlog, Bug, UI/UX
