### ISSUE TITLE
Registering Pregnancy Under Tasks Section Showing HTML Source Code

### ISSUE THREAD

**Issue by guptasanchay** [medic/medic-webapp#1704] opened 2015-11-28 22:11 UTC
The form is fine up until this point

<img width="376" alt="screen shot 2015-11-28 at 2 08 19 pm" src="https://cloud.githubusercontent.com/assets/15477845/11454217/c3f30510-95d9-11e5-8820-d071cec746f6.png">

Then after hitting next, the app returns this screen:

<img width="373" alt="screen shot 2015-11-28 at 2 08 01 pm" src="https://cloud.githubusercontent.com/assets/15477845/11454226/e5a3fce6-95d9-11e5-9704-8425140eadc4.png">

**Comment by guptasanchay** [comment] 2015-11-28 22:13
After submitting the pregnancy registration form, the task is also not cleared from the task page

**Comment by abbyad** [comment] 2015-11-29 16:02
This is a duplicate of https://github.com/medic/medic-webapp/issues/1696 and fixed by https://github.com/medic/medic-webapp/commit/f7b914942445feadc06ac37b6a2a96bc951fdb32

**Closed by abbyad** 2015-11-29 16:02 UTC
