### ISSUE TITLE
Clicking a task from a profile should open that task

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1553] opened 2015-11-09 01:06 UTC
Right now, clicking a task from a profile takes me to the task list. At that point, I can't click on the task from the task list (I have to switch tabs first). 

Try clicking on any task from a family profile or family member profile to reproduce. I may be wrong, but it seems as though the LHS in Tasks tab is showing when we need the RHS to show.

**Comment by abbyad** [comment] 2015-11-09 15:08
From what I can tell the URL is that of the proper task (with the task id), not that of the LHS. This is required for the field test, so marking it as high priority.

**Comment by abbyad** [comment] 2015-11-09 19:09
@mandric, I noticed that in desktop view it is showing the proper task details page in the RHS.... but should show the form directly since there is a single action and no description.

**Comment by alxndrsn** [comment] 2015-11-09 20:30
:+1:

**Comment by mandric** [comment] 2015-11-10 11:07
Build 2318 or greater should have this fix.  We can updated lg.dev or lg.app and tested it.

**Comment by mandric** [comment] 2015-11-13 22:26
Direct linking or loading a task through a contact does not autoload the form anymore.  e.g. https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/tasks/5094D87A-1522-AF1D-9CC1-9A57107D0D9B-treatment-referral-followup-1

**Comment by mandric** [comment] 2015-11-14 13:02
Actually not sure this is a regression because I don't think direct linking was ever working properly.

**Comment by abbyad** [comment] 2015-11-14 13:16
I am pretty certain this worked as recently as a couple of weeks ago, perhaps @joshnesbit can confirm. Either way, hopefully we can fix this in time for the field test.

**Comment by joshnesbit** [comment] 2015-11-14 21:25
I have only seen this working as it is now on lg.app. Here's what I'm seeing:

Profile of a person with a task due -> click task card -> go to task info screen with "follow up" button -> click "follow up" button -> complete form for that task -> submit and land back on the original task info screen

Ideally, we'd skip the task info screen when it isn't needed. More importantly, the user needs to land at the main task list (or back at the original profile).

**Comment by joshnesbit** [comment] 2015-11-14 21:31
Also, right now, I'm stuck when I land back on the original task info screen. The X doesn't do anything, and clicking "follow up" takes me back to the form.

**Comment by mandric** [comment] 2015-11-15 15:12
The problem here is the task is being [set by the tasks-content controller](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/tasks-content.js#L77) before they are done being generated so just gets set to null every time.  Somehow we need to wrap the tasks-content controller in the [tasks controller generator call](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/tasks.js#L58) so it only sets selected tasks when we actually have them.

**Comment by mandric** [comment] 2015-11-16 19:42
To fix this we need a way to know when tasks are finished generating/loading or a way to fetch an individual task separately during the tasks-content loading.

**Comment by garethbowen** [comment] 2015-11-16 23:46
I've added a comment to the commit, and there are some unit tests failing on travis.

**Comment by garethbowen** [comment] 2015-11-16 23:56
Nice

**Closed by garethbowen** 2015-11-16 23:56 UTC
Labels: 4 - Acceptance testing, Bug, Priority
