### ISSUE TITLE
Enketo date-picker should store dates in UTC

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2655] opened 2016-08-22 23:44 UTC
Currently we are moving between UTC and local time, causing tasks to display on incorrect days and form context for the new `ageInDays` function to be off by a day in some timezones. We should store all dates in UTC to avoid confusion and strange behavior.

**Comment by SCdF** [comment] 2016-08-23 08:56
I don't want to blow the scope of the ticket out, but perhaps this is probably a good opportunity to check all of our date storage and make sure we understand what is and isn't in UTC. IMO everything should be UTC because it's a nice simple rule to remember and reason about. If we can't do that we could at least document the rules somewhere so it's clear.

**Comment by garethbowen** [comment] 2016-08-23 09:03
UTC storage was checked as part of #2185 . Interestingly enketo dates are marked as being ok... Anyway, double check and fix if necessary, but all other dates should be fine.

**Comment by garethbowen** [comment] 2016-11-15 03:20
@sglangevin Can you give me an example of a form with this problem and/or a report submitted with a form with the problem?

From my testing it appears that `dateTime` outputs a timezone specific datetime, eg: `2016-11-06T16:15:00.000+13:00`. We can work with this - yes it's annoying it's not UTC but we can convert it to UTC easily.

The difficulty is with `date` fields, because without the time you cannot convert to another timezone. ie: is an EDD of "15-May" in +1200 timezone the same as "14-May" in -1200? If so, when a user in +1200 enters "15-May" should we just store that as "15-May" in 0000 (ie: UTC)?

**Comment by sglangevin** [comment] 2016-11-21 19:01
@garethbowen sorry for the delayed response. Is it possible to store a `date` field in local time then? I think the problem is that we get a `date` from a form and then I think it gets converted to UTC somewhere, but the tasks appear in local time. So that results in tasks appearing on the correct day but with the incorrect due date. E.g. a task appears on Wednesday, saying it was due yesterday. This happens in a postnatal care workflow where we're just collecting the date of birth but not converting to a `dateTime` and also in the Muso malnutrition workflow where if a child is malnourished, the follow-up tasks get regenerated each time a follow-up is done so that we can track the Shakir strip color (if there are 3 yellows in a row, that has to trigger a referral). The first follow-up for malnutrition appears normally, but the ones that are regenerated are all off by a day due to the fact that I'm converting a `reported_date` to an ISO string, passing it to the form, then getting the date back in the task rules to generate more tasks. By the time I get to generating more tasks, the date is not a Javascript date anymore, so the timing gets messed up.

Based on your answer, I think I know how to resolve this issue in the forms that I have, but I'm wondering if we should figure out some rules so that it's clear what timezone we're in and what the person configuring forms should expect.

**Comment by garethbowen** [comment] 2016-11-21 21:01
> Is it possible to store a date field in local time then?

@sglangevin The problem is dates don't have timezones, only datetimes do. Can you point me to the configuration you're talking about so I can see where the problem occurs?

**Comment by sglangevin** [comment] 2016-11-29 01:51
One place where I've faced this is with the Muso configuration. This happens when you do a patient assessment and the child is diagnosed with malnutrition, then do a malnutrition follow-up. 

Here is the task rule for the malnutrition follow-up: https://github.com/medic/medic-projects/blob/master/muso/tasks/task-rules.js#L570

Some additional info on the workflow/config:
Malnutrition tasks are all cleared each time a malnutrition follow-up is done so that we can keep track of the number of yellow strips. During the initial assessment and during each follow-up, the child is tested for malnutrition. If they are at risk of being malnourished (yellow strip) we need to keep track of that as 3 yellow strips in a row triggers a referral. That could be the initial yellow strip plus yellow strips on the first 2 follow-ups or 3 yellow strips during follow-ups.

The problem occurs when the CHW does the malnutrition follow-up (the tasks generated from the initial assessment are fine). We have to pass the initial assessment date (date the child was flagged for malnutrition follow-ups) from follow-up form to follow-up form via a task. However, I think this process ends up causing us to lose the timezone information. The result is that the tasks appear on the correct day but have the incorrect due date (e.g. a task shows up on Tuesday and says "due yesterday").

**Comment by garethbowen** [comment] 2016-11-29 03:50
@sglangevin As far as I can see none of the muso forms use a datepicker. It looks like the assessment date comes from the reported_date of the patient_assessment report, is that correct?

The configuration has a bunch of code like this: `date.toISOString().substring(0,10)`. If you're in a US TZ this could easily subtract a day from the due date. For example,

1. if the report date is "2016-11-02T05:00:00-0900"
2. this is converted to "2016-11-01T20:00:00Z" (UTC)
3. which is converted to "2016-11-01"
4. which is converted back to the US users timezone for rendering: "2016-11-01T09:00:00-0900"
5. which is shown to the user as "2016-11-01"

I don't think we should ever reduce the accuracy of Dates because once you've dropped it you can never get it back. So if we have a datetime (eg: reported_date in this case) we need to always store it as a datetime and only drop certain information when rendering it to the user (the task rendering already drops the time information automatically).

Why was the `substring` added? Can we instead store the date without discarding any information?

**Comment by sglangevin** [comment] 2016-11-29 15:29
@garethbowen yes, the assessment date come from the reported_date of the patient_assessment report. I think the accuracy of the reported_date is being reduced by passing it from the task rules to the form and then back to the rules again. Here is the form in question: https://github.com/medic/medic-projects/blob/master/muso/forms/tori/malnutrition_followup.xml

The code you are highlighting actually fixes the issue for some of the other tasks (I used it as a workaround) and it is not used in the part that I had referred been talking about related to malnutrition. I'd like to remove that code completely, if there is a better way to make this work. I thought if the app could store everything in UTC and then just display in local time, then it would work correctly, but I don't know the inner workings very well.

**Comment by garethbowen** [comment] 2016-11-29 18:56
@sglangevin I have verified that the app stores everything correctly and displays in local time, although this can cause problems when viewing the task from a TZ that differs from the one the report was submitted in. The bug is in the configuration. Remove all those hacks and if you can reproduce the old issue raise a bug for that.

**Comment by garethbowen** [comment] 2016-11-29 20:45
Assigning to @sglangevin to fix the task configuration and verify that resolves the issue.

**Closed by garethbowen** 2016-11-29 20:45 UTC
Labels: 1 - Scheduled, Bug, Enketo

**Comment by sglangevin** [comment] 2016-12-07 00:46
This is now fixed - we confirmed that dates are being stored and handled in UTC and that it was a configuration issue.
