### ISSUE TITLE
`accept_patient_reports` expect `data_record.fields.patient_id`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3536] opened 2017-06-09 10:54 UTC
`accept_patient_reports` crashes on a `data_record` that doesn't have `fields.patient_id`. 
But v0.4 format has it in `data_record.patient_id` instead, which is also where `patient_registration` seems to add it : https://github.com/medic/medic-sentinel/commit/a44dba9705a7ed7928adfafa4101184edc297c08#diff-a0dcbc68959b7037de3e15353c473b00R169
So it's a normal thing to happen. 

So edit `accept_patient_reports` to use either `data_record.fields.patient_id` or `data_record.patient_id`.

**Comment by estellecomment** [comment] 2017-06-09 11:12
@SCdF assigning you as reviewer since you're the last person to have fiddled with it. Please confirm that doing this actually makes sense. :)
PR : https://github.com/medic/medic-sentinel/pull/134

**Comment by estellecomment** [comment] 2017-06-09 16:25
Backtracking from code review, looks like this might be expected behavior. I'll figure it out and either close or put back in review.

**Comment by sglangevin** [comment] 2017-06-14 07:05
The root cause of this was a failure in migrations. Closing and removing from 2.12.0.

**Closed by sglangevin** 2017-06-14 07:05 UTC
Labels: 2 - Active Work, Bug
