### ISSUE TITLE
Hide reports from branch managers

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2648] opened 2016-08-18 14:54 UTC
Hide reports from users at higher or lower levels of the hierarchy from where they were originally filed.

**Comment by SCdF** [comment] 2016-08-19 16:53
@alxndrsn the travis failure looks like its because the function that was replaced with an if call also deals with unassigned. You may need to extract that out to continue to support that feature.

**Comment by SCdF** [comment] 2016-08-19 16:54
( @alxndrsn ignore that above comment, I see that you've done it, clearly I never refreshed this page.. deleting that comment and this one now)

**Comment by garethbowen** [comment] 2016-08-22 19:41
This doesn't work. Reopening.

**Comment by garethbowen** [comment] 2016-08-22 22:40
Issues I can see with this solution...

1. It affects 0.4 and DIY users - try to find a way to turn this on/off based on a permission.
2. The API changes handler hasn't been updated to be consistent which means the solution probably isn't working at all.
3. I think it'll break on upgrade because users with the old view code will request docs they're no longer allowed to see with the new view code. Currently this 403s the request so the user will never replicate the ddoc containing the updated view code.

**Comment by garethbowen** [comment] 2016-08-23 03:54
The last bit left is to sort out how to switch this on/off. My thoughts so far are to change the view so instead of `[ contactId ]` it's keyed by `[ contactId, depth ]`, for example if given this report:

```js
{
  _id: 'a',
  contact: {
    _id: 'b',
    parent: {
      _id: 'c'
    }
  }
}
```

These keys would be emitted: `['b',0]`,`['c', 1]`.

A user who is at district "c" who can see all levels would query the view for keys: `['c', 0]`, `['c', 1]`, `['c', 2]`, ..., `['c', n]`.

A user who is at district "c" who can only see the level directly below them would query the view for keys: `['c', 0]` which wouldn't return the above report because it's too deep.

This could be set either as a permission (eg: `can_access_deep_hierarchy` (or something much better) defaulting to `true` and set to `false` for LG), or as a system wide setting (eg: `visible_depth = 2`).

@SCdF @alxndrsn Feedback appreciated.

**Comment by estellecomment** [comment] 2016-08-23 08:30
Ha was thinking about this! (but didn't get it properly out of my brain, so that wasn't so helpful)

Works for places too : 
I’m a manager, here's my place:
```
{
  _id: ‘myDistrict’,
  type: 'district_hospital',
  contact : {_id: ‘me’,  type: person}
}
```
And a sub-place
```
{
  _id: aSubPlace
  type: 'health_center',
  contact : {_id: ‘aCHW’,  type: person}
  parent: {
    _id: ‘myDistrict’
    type: 'district_hospital',
    contact : {_id: ‘me’,  type: person}
  }
}
```
Outputs for places : 
```
['myDistrict', 0] - doc: 'myDistrict'
['aSubPlace', 0] - doc: 'aSubPlace'
['myDistrict', 1] - doc: 'aSubPlace'
```
And thus `myDistrict` user gets only the first doc if `depth=0`, or the first and third docs if `depth=1`.

And for contacts : 
```
{
  _id: ‘me’,
  type: person,
  parent: {
    _id: 'myDistrict'
    type: 'district_hospital',
  }
}
```
```
{
  _id: 'aCHW',
  type: person,
  parent: {
    _id: 'aSubPlace',
    type: 'health_center',
    parent: {
      _id: 'myDistrict'
      type: 'district_hospital',
    }
  }
}
```
Outputs contacts : 
```
['myDistrict', 0] - doc: 'me'
['aSubPlace', 0] - doc: 'aCHW'
['myDistrict', 1] - doc: 'aCHW'
```

+1 for variable depth. That way we can change it easily if we sort out space issues, and configure it differently for different projects.
You may want different depths for different users within the same project, too. In 0.4 projects, the 3 levels can be national managers, local managers and CHWs, all of which are sending forms potentially. We could have, for instance, `depth=0` for local managers (only the reports they submitted) vs. `depth=1` for national managers (their own reports and the local managers' reports). 

Can we have permissions with numbers? `can_access_reports_at_depth = 1`
Or, assuming that it's not a privacy issue (i.e. managers are allowed see all the data underneath them anyway, it's just that they choose not to for UX reasons, so if they spoof the depth it doesn't matter), pass the depth in the changes request: `_changes?reports_depth=0&contacts_depth=1`

**Comment by garethbowen** [comment] 2016-08-23 08:38
At the moment we only support boolean permissions which keeps things nice and simple. Maybe we just store depth separately to the permissions. It's still configurable per role but just in a different part of the settings.

**Comment by SCdF** [comment] 2016-08-23 09:01
Complex! But, simpler solutions are too simple to work unfortunately, so this looks like it's just complex enough.

**Comment by garethbowen** [comment] 2016-08-24 04:14
I've fixed the aforementioned issues and backported everything to 2.8.x. Also included a unit test to ensure the view and the api handler stay in sync. This is quite complicated but also quite powerful.

To configure it you'll need to edit the "Replication depth" section in the app settings in dashboard.

**Comment by SCdF** [comment] 2016-08-24 07:44
![image](https://cloud.githubusercontent.com/assets/583851/17922418/c8071de0-69d6-11e6-8ca8-b62997e028aa.png)
That's a lot of commits, some of which I presume are duplicates. PRs, or at least a link to commit ranges, would be really helpful here.

**Comment by garethbowen** [comment] 2016-08-24 09:17
Yeah, sorry. Because it was already committed to master I just sort of went with it. On top of that some commits are to api, and some to webapp, and some to master, and some to 2.8.x... Here are the important ones:

- https://github.com/medic/medic-api/commit/1c3db5403ae5877e84926f65651845b4e467a242 : This means instead of blowing up when a user requests a doc we don't think they should see, we just exclude that docs changes from the response. This allows us to recover from errors where we need to replicate a new ddoc to them but they have an old incompatible configuration.
- https://github.com/medic/medic-api/commit/3e1880659a3635900287202250746f94043791e7 : This makes the API handler equivalent to the webapp view which is essential so new docs are replicated using the same logic as docs that exist when the request first comes in. In a later commit I add a test to ensure these are identical in future.
- https://github.com/medic/medic-api/commit/99f0881295fce7eea1e596cc72b9d1b1c720e10e : This changes API to emit keys with depth so users can be configured to only see a certain depth below their facility.
- https://github.com/medic/medic-webapp/commit/cf209984ec07b99e6b6257a3a06e2d9e29be2d13 : This is the equivalent change in webapp.

The rest are backports or trivial.

**Comment by SCdF** [comment] 2016-08-24 11:51
Choice

**Comment by sglangevin** [comment] 2016-08-24 18:36
@garethbowen I've done initial testing and it's working mostly for branch manager type users, but it seems to be broken for CHP users. For the branch manager user, it's not downloading my history if I clear data and log in again. Might be related to this issue:

![image](https://cloud.githubusercontent.com/assets/1286381/17943038/9ade573a-69ee-11e6-8f92-34a309e1d6bc.png)

When I log in as a CHP, I see my families, but it doesn't download any people or reports about those people. Perhaps CHP users need to be depth of 2 and branch managers depth of 1? Right now they are both `district_admin`s so we'd need a new role to do that.

The good news is that the branch manager user now has 165 docs instead of over 12000 so that's a huge win!

**Comment by sglangevin** [comment] 2016-08-25 17:49
@garethbowen I tried replication depth of 1, but that doesn't show me family members when I log in as a CHP. So replication depth has to be 2 so that I see families and family members when logged in as a CHP and I see CHP Areas and families, but no family members when logged in as a branch manager. I definitely don't see any family members when I log in as a branch manager, but I do see forms about family members - some forms, but definitely not all, which is odd. Can you have another look?

**Comment by garethbowen** [comment] 2016-08-25 21:31
The problem is we've been picking depth based on the contact not the parent. This is convenient because we have the entire contact hierarchy, but it's not as accurate. If you can see a patient you should be able to see reports about that patient.

This will require a further significant change to the replication code which I'll get on to ASAP.

**Comment by garethbowen** [comment] 2016-08-29 03:53
Two PRs to review... https://github.com/medic/medic-webapp/pull/2674 https://github.com/medic/medic-api/pull/97

**Comment by SCdF** [comment] 2016-08-29 17:36
OK this is really complicated. Would be good to get you to walk me through some stuff, especially the merging and new document discovery in API. Also, would definitely be worthwhile someone else (ie Alex) reviewing this one.

**Comment by garethbowen** [comment] 2016-08-29 23:40
The rules:
* A contact (person or place) is visible to you if it's your place or a descendant of your place within the configured depth. Depth is optional and defaults to seeing all descendants.
* A report is visible to you if it's about one of your visible contacts, unless it is both (a) about you or your place AND (b) submitted by a contact that is not visible to you.

**Comment by SCdF** [comment] 2016-08-30 13:56
Consider this reviewed!

**Closed by SCdF** 2016-08-30 13:56 UTC
Labels: 4 - Acceptance Testing, Feature Request

**Comment by sglangevin** [comment] 2016-08-30 14:36
I'm getting `error getting tasks` and `error getting targets` when logging in as a branch manager and as a CHP user.

![image](https://cloud.githubusercontent.com/assets/1286381/18093363/70f18c72-6e84-11e6-83bc-a71e9772b894.png)

**Comment by sglangevin** [comment] 2016-08-30 14:39
There is one network request failing:
![image](https://cloud.githubusercontent.com/assets/1286381/18093479/dc65d7ec-6e84-11e6-9df5-1edb25ae1627.png)

**Comment by garethbowen** [comment] 2016-08-30 20:53
You can safely ignore `_local` docs - that's often just pouch looking to see if something exists. Usually there's a comment in the console saying "you can ignore this error". I'll have a look at the other issue.

**Comment by garethbowen** [comment] 2016-08-30 20:57
@sglangevin Branch manager on lg.dev is working fine for me. Can you try again or ping me on Slack with more details?

**Comment by sglangevin** [comment] 2016-08-30 23:25
Working as expected in v2.8.0-beta.8

**Comment by mandric** [comment] 2016-09-06 21:16
Guys do we have any docs or description on how this feature should work?

**Comment by garethbowen** [comment] 2016-09-06 21:20
Replication depth can be configured for user roles. If a user has multiple roles with different depths the biggest number is used. The depth controls which docs are replicated based on these rules:

- A contact (person or place) is visible to you if it's your place or a descendant of your place within the configured depth. Depth is optional and defaults to seeing all descendants.
- A report is visible to you if it's about one of your visible contacts, unless it is both (a) about you or your place AND (b) submitted by a contact that is not visible to you.
