### ISSUE TITLE
Style History and Tasks lists

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2786] opened 2016-09-27 11:52 UTC
They can probably use the same template.

See design spec:
For History
https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.9quirbw60jeb

For Tasks
https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.3geb36f0xc64

**Comment by estellecomment** [comment] 2016-09-30 14:28
@garethbowen please review!
PR : https://github.com/medic/medic-webapp/pull/2799

Known issues : 
 - Icons for Reports : #2794, we could add the feature
 - Icons on tasks are not fontawesome, so the sizing is all wrong : deferred to #2730
 - Tasks have the patient name displayed twice (in the title, and in the patient name) : #2793

**Comment by estellecomment** [comment] 2016-10-06 08:28
Oh, no Gareth this week. @SCdF you're the backup!

**Comment by SCdF** [comment] 2016-10-06 13:00
Back to you!

**Comment by diannakane** [comment] 2016-11-07 15:08
History and task items should show the person or place that the item relates to, and the title of the task or record below. 

Current:
![screen shot 2016-11-03 at 12 36 36](https://cloud.githubusercontent.com/assets/1675870/20062481/92fa4034-a50c-11e6-94b6-bae2f587a039.png)

Mockups:
![pasted graphic](https://cloud.githubusercontent.com/assets/1675870/20062521/b87257d4-a50c-11e6-923d-cf1a565d4af7.png)

**Comment by diannakane** [comment] 2016-11-07 15:19
Is verified / unverified configurable by project? I expect to see it them here in alpha (per mockups directly above). Same for valid/invalid checkmark. All records in app projects are “valid” so we can choose to show them all with a check or leave it as-is.

**Comment by abbyad** [comment] 2016-11-07 15:58
**Verified/Unverified** has no actual configuration, it is up to each project to decide how/if to use it. 

As for **Valid/Invalid**, the XForms have validation checks within the form so you cannot submit an invalid form. This is to have a better UX - if you were to configure that the SMS workflow validation for a XForm it would reply with a SMS. Since we dont use that validation for XForms they will all be valid. **Bottom line is that the validation checks which would affect the coloured circle are for SMS workflows only.**

**Comment by abbyad** [comment] 2016-11-07 15:59
Seems like this is being returned from `Acceptance Testing` -- so moving to `Active Work` and `Returned` as opposed to `Bug`.

**Comment by garethbowen** [comment] 2016-11-07 20:40
@diannakane You can mark a report as verified on the History tab and then on the People tab it renders like so:

![verified](https://cloud.githubusercontent.com/assets/2064938/20074898/f7c5e826-a596-11e6-90d6-d9b74a57ac16.png)

WRT showing the person/place the report relates to in the People tab History section, we decided at some point to hide it if it relates to the currently selected person/place. This is so when you're viewing a person so _all_ the reports are about them you don't see the person's name again and again. Should we just always show it? Should we always show it when viewing a place, and always hide it when viewing a person? Any other ideas?

**Comment by abbyad** [comment] 2016-11-07 21:44
I understood it as needing to show the _person_ name if you are on the _place_ profile - basically resolving any ambiguity about who the form is about. Looking at a place form on a place profile should still not need to show their name. 

The general rule seems to be show the name of the place/person the form is about unless you are on that place/person's profile.

**Comment by garethbowen** [comment] 2016-11-07 21:45
@abbyad That is the current implementation and that is shown in the screenshot above, but it obviously doesn't match what @diannakane was expecting.

**Comment by sglangevin** [comment] 2016-11-07 21:54
Does this mean we'll be able to see the person whom/place which the report is about on the History page as well? Or will the History page always show the person who submitted the report?

**Comment by garethbowen** [comment] 2016-11-07 22:10
@sglangevin Currently the History tab will show who submitted it. This could be changed to show the subject (who it's about), or even show both. I think CHPs want to see who it's about, but admins may want to see who submitted it. But maybe it's a case where we show both but hide the submitter if it's the currently logged in user. Needs some design...

**Comment by sglangevin** [comment] 2016-11-07 22:18
Ok, cool, thanks for clarifying. I do think it's worth exploring what info to display when. For example, I think you're right that users may want to see who it's about for reports that they submitted but may want to see the person who submitted the report for any reports they can see but didn't submit. And it also may depend on the user type.

**Comment by diannakane** [comment] 2016-11-08 10:53
I think consistency is important with these cards that appear in different places (place card, people card) and different parts of the app (people, history, and even tasks feels similar).  I would make the person or place to whom the tasks or history record refers to a standard line, no matter which page it appears. The repetition on the person's profile is the only place we'll see redundancy, and even then I don't think it's a bad thing to reinforce whose tasks or history records you are looking at. 

I agree with @sglangevin that in a manager's view, they may want to see who submitted it (or whom the task is assigned to). I will add that to our manager spec and we can consider how to add that piece of information in. I don't think it negates the need to see who the task or form is about, though, particularly since managers will also be searching for patients or performing some actions related to them.

**Comment by garethbowen** [comment] 2016-11-09 00:53
The subject now always shows on the Contact history section. This is not consistent with how it's shown on the History tab because some design is required here. It'll need some thought to work out how to clearly show who is the subject and who is the sender.

@diannakane Please raise a separate design issue for how the information should be shown.

**Comment by diannakane** [comment] 2016-11-09 12:41
I am having trouble finding anyone with an open task in the instance who I can acceptance test on.

**Comment by diannakane** [comment] 2016-11-09 12:42
I have filed #40 in medic-design to resolve the issue of displaying the sender's name.

**Comment by diannakane** [comment] 2016-11-09 15:01
Please refer to Zeppelin for bubble styling. The bubble is much larger and a darker grey.
https://zpl.io/2tsIvg
Also the number is medium weight not bold.

Here is the size and color of the task bubble
width: 32px;
height: 26px;
background-color: #4c4c4c;

Font specs:
font-family: HelveticaNeue;
font-size: 14px;
font-weight: 500;
text-align: center;
color: #ffffff;

**Comment by garethbowen** [comment] 2016-11-09 19:15
@diannakane That background colour is not in our current palette so I chose to use the closest existing colour to tie it in with other similar elements. Also the bubble sizing is using the same styling as other bubbles in the app for consistency. We need to consider how changes like this will affect the site as a whole.

**Comment by diannakane** [comment] 2016-11-10 09:48
@Lesterng, @garethbowen makes a good point. He is referring to bubbles that appear on the tabs, as such: 
![bubbles](https://cloud.githubusercontent.com/assets/1675870/20171870/5586cbd8-a73b-11e6-8816-d56a053bb0e6.png)

If we want to implement changes to the stye guide, we should call that out as its own issue to be implemented across the app, otherwise design within the existing style guide.

**Comment by garethbowen** [comment] 2016-11-15 03:21
Clearly some design is required so I'm removing this from the milestone.

**Comment by diannakane** [comment] 2016-11-15 08:57
That's fine. This is labeled as nice-to-have and is more relevant to app workflows than SMS so it's not an immediate priority.

**Comment by sglangevin** [comment] 2017-01-27 23:35
@diannakane is this one worth revisiting? Seems like it ended up needing design work.

**Comment by diannakane** [comment] 2017-01-27 23:48
Some of this is covered by other issues, but there's good stuff in this thread so I'll create an overarching issue to holistically re-examine the styles of history and task lists. https://github.com/medic/medic-design/projects/1#card-1520900

**Comment by garethbowen** [comment] 2017-06-29 21:58
It looks like this issue is covered by design issues so I'm closing this. Please reopen if there's more development work ready to be done.

**Closed by garethbowen** 2017-06-29 21:58 UTC
Labels: Contacts, Needs Design Work, Nice To Have, UI/UX
