### ISSUE TITLE
Error when adding Place with new person

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3420] opened 2017-04-26 23:16 UTC
Getting 409 when creating places with a new primary contact on 2.11.0. 

```
PUT https://clone-REDACTED.app.medicmobile.org/medic/2403111f9f4bdee781b8dcf37113edb4 409 (Conflict)
2017-04-26 19:11:35.627 Error submitting form data Object {error: "conflict", reason: "Document update conflict.", status: 409, name: "conflict", message: "Document update conflict."}
```

To reproduce create a new district or health center, and for "Set the Primary Contact" choose "Create a new person" then complete the form.

Despite the error the place seems to be created properly, **but the person does not have the parent set, and the place doesn't show in the LHS until refresh**

**Comment by abbyad** [comment] 2017-04-27 01:07
Perhaps due to the person's MM ID being added while the parent field is also added?

**Comment by abbyad** [comment] 2017-04-27 01:56
Was not able to reproduce this issue when creating people as a restricted user. This would make sense with the theory that the conflict is due to MM ID because with restricted users the person is created in pouchdb first.

**Comment by SCdF** [comment] 2017-04-27 08:37
@abbyad I'm looking at fixing issues around this today.

The problem is that sentinel transition metadata is stored directly on the document, so if the app ever tries to write a doc and then write that doc again, and the first write was valid for transition processing, we can get conflicts.

I'm partially fixing this by moving transition metadata out of the document. However, this is similar to #3356, and will not be properly solved until we want to expend the energy in a proper conflict management solution.

**Comment by SCdF** [comment] 2017-04-27 10:32
Actually I don't think I'm going to fix this today actually, since you did it in 2.11.0 and 2.11.0 doesn't actually have the code I'm fixing in it.

I'll have to look into this specifically, but I think this will be the same as #3356: until we put a plan into action for dealing with conflicts we will keep finding situations like this

**Comment by SCdF** [comment] 2017-05-03 14:18
OK this is complicated:
 - A Place is being created, and a person along with it
 - The place's contact should be the person
 - And the person's parent should be the place

There is a lot of code that I'm having trouble groking that deals with taking the js object created from enketo and storing that as documents in CouchDB.

That code will need to be changed to no longer persist and go, and instead build up a collection of docs (with client-side generated ids instead of letting CouchDB create them) and then save in one go.

**Comment by sglangevin** [comment] 2017-05-03 21:00
If we're not able to get a fix out for this tomorrow (Thursday), I think we will need to go ahead and release 2.11.1 without it. Ideally this fix should be included in v2.11.1, though.

**Comment by SCdF** [comment] 2017-05-04 10:49
This won't be fixed, code reviewed and tested by EOB today, no.

**Comment by SCdF** [comment] 2017-05-04 17:56
Initial PR: https://github.com/medic/medic-webapp/pull/3447

@garethbowen can you take a look at this one for me please.

**Comment by SCdF** [comment] 2017-05-04 17:57
Still assigned to me and active because I need to do more testing, and I broke the sidebar somehow (or it was always broken…), which I need to look into, But the bulk can still be code reviewed)

**Comment by SCdF** [comment] 2017-05-05 13:08
Merged.

AT notes, things that should be tested:
 - The core problem is that if sentinel is running, and up to date idling for new changes, *all* creations and edits of contacts should work without flaw, both that the contact should be stored correctly, but also that sentinel should run on those contacts correctly as well
 - This change affects *all* creation and editing scenarios for any kind of contact (DH, clinic, family, person etc).
 - There are notable differences in logic depending on whether you use children (such as the LG family form does), or whether you are creating and attaching sibling records, such as creating a place and the person who is the contact for that place at the same time.
 - So, ideally a wide range of forms and scenarios would be looked at

NB: earlier I noted that I had somehow broken the side bar. It has somehow been fixed again. I think me seeing it broken was due to how I was debugging my work, and not my work itself.

**Closed by SCdF** 2017-05-05 13:08 UTC
Labels: 4 - Acceptance Testing, Bug, Priority

**Comment by sglangevin** [comment] 2017-05-05 17:54
This is working well with Standard config - I tested all types of place creation where I was also creating a new person to be the primary contact. I also tested editing of people who didn't previously have Medic IDs and those were created once I saved. Not exactly sure how to test other types of editing.

We don't currently have transitions enabled for LG or any projects that are Android-app only. Should we still test that scenario? I think this is working well enough to support SMS project. I'll try enabling the transition that creates IDs for and LG-like config and see how that goes - I'll test creation of contact online and as a restricted user for that.

**Comment by sglangevin** [comment] 2017-05-05 18:47
I've now tested with the `generate_patient_id_on_people` transition enabled on an LG config. I tested creating different types of places with new people as the primary contact, and I tested creation of families both online (as admin) and offline (as a CHP, logged in as restricted user) and I haven't encountered any conflict issues. I've also confirmed that patient IDs are being created as expected in all cases. I'm moving this to Ready.
