### ISSUE TITLE
Changing languages does not change form labels

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3323] opened 2017-03-30 18:53 UTC
When a user changes their language setting the app changes languages but the form labels do not.

Notice that the app labels, including the Next button are in English whereas the form is still in Hindi:
![image](https://cloud.githubusercontent.com/assets/789512/24520789/b33de7ae-1557-11e7-931a-bc4c632bd243.png)

I have tried logging in a completely fresh browser and the same problem exists. Even creating a new user is stuck to using Hindi, even if they are set to use English from the user creation form.

Tested on `2.10.3-beta.1`

**Comment by garethbowen** [comment] 2017-03-30 19:26
Duplicate of #3174 ?

**Comment by abbyad** [comment] 2017-03-30 19:27
Yes, looks like a duplicate.

**Comment by abbyad** [comment] 2017-03-30 19:35
Closed this one accidentally... I need to still confirm that it is a duplicate.

**Comment by abbyad** [comment] 2017-03-30 19:53
Action places translate accordingly, but People/Place forms are stuck in Hindi.

**Comment by garethbowen** [comment] 2017-03-30 19:54
Looking into it now

**Closed** 2017-03-30 21:33 UTC
Labels: 4 - Acceptance Testing, Bug

**Comment by abbyad** [comment] 2017-03-31 01:14
Works well for both Contact and Action forms, moving to Ready.
