### ISSUE TITLE
App doesn't store data on SD card

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2613] opened 2016-08-08 12:11 UTC
App is on SD card, but most of the data is still saved to main storage. Figure out if we can have it save data to SD card. 

![screenshot_2016-08-08-15-06-54](https://cloud.githubusercontent.com/assets/911434/17479290/01d8489e-5d72-11e6-9834-42d74f991973.png)

**Comment by estellecomment** [comment] 2016-08-08 14:01
Tried `adb shell pm set-install-location 2` and setting default install location in Settings.

Added `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` permissions.

Tried setting the [app cache dir](https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L178) in our code to an external storage dir, but I don't think that's where the indexeddb data is stored. I got a tiny amount of data on the SD card, rather than a clean 0. 

Maybe set another of the [WebSettings](https://developer.android.com/reference/android/webkit/WebSettings.html) to change the data dir for the WebView... Hmmm.

(Interestingly all `getExternalStorageDirectory`, `getExternalStoragePublicDirectory`, `getExternalFilesDirs` all return a path on `sdcard0` which is the main storage, instead of `sdcard1` which is the SD card.)

**Comment by alxndrsn** [comment] 2016-08-08 14:26
Long shot, but have you tried overwriting `EmbeddedBrowserActivity.getCacheDir()`?  I hope it doesn't work, as from the docs:

> ** Note: you should not rely on the system deleting these files for you; you should always have a reasonable maximum, such as 1 MB, for the amount of space you consume with cache files, and prune those files when exceeding that space.**

So I guess it's some consolation that `webSettings.setAppCachePath()` does not seem to dictate where our database ends up, as having that randomly deleted could make for poor UX.  And we'd definitely be using more than 1MB already.

**Comment by alxndrsn** [comment] 2016-08-08 14:34
Have you tried [`WebSettings.setDatabasePath()`](https://developer.android.com/reference/android/webkit/WebSettings.html#setDatabasePath(java.lang.String))?

**Comment by estellecomment** [comment] 2016-08-08 14:37
> Long shot, but have you tried overwriting EmbeddedBrowserActivity.getCacheDir()

No, I did see a blog post where someone was doing that though... Could try it. 
I'm doubting that it's the cache dir at all. Something gets in it, but I don't think the db does.

> Have you tried WebSettings.setDatabasePath()?

I saw it, but it's deprecated in Kitkat (api 19), so didn't try it. Also could give it a shot.

**Comment by estellecomment** [comment] 2016-08-19 08:12
Conclusion : on android 4, you can't write app data to SD card.

On android 5+ though, you might : 
http://www.androidcentral.com/lollipop-brings-changes-way-your-sd-card-works-kind-youll
I can't test it though, my old Samsung is not as fancy as the new Tecnos and is on android 4.

**Comment by garethbowen** [comment] 2016-08-21 20:14
The problem is we're not talking about our app's data, we're talking about the webview's data. We need to find a way to convince the webview to store data on the SD card.

**Comment by garethbowen** [comment] 2016-09-01 02:07
I don't think this is possible for webviews without some tricky mangling to get pouch to write to the app which writes to its local storage. We've found some ways to reduce our data requirements which make this less important. @estellecomment Would you agree with either closing or unscheduling this issue?

**Comment by estellecomment** [comment] 2016-09-01 07:27
We could unschedule if we've solved data size issues, yes.

I don't have enough info to close, because I haven't researched and tested for Android 5, in which there's different ways for apps to interact with SD card.

**Comment by garethbowen** [comment] 2016-09-01 09:11
Ok, let's unschedule it for now and see how the other tactics pan out.

**Comment by garethbowen** [comment] 2017-01-26 19:19
Worked around the space issue by crosswalking.

**Comment by alxndrsn** [comment] 2017-10-19 07:43
Re-investigate if we can store xwalk webview data on SD card...

**Comment by alxndrsn** [comment] 2017-11-17 19:52
Should be achievable by setting `android:installLocation` to `auto` in `AndroidManifest.xml`:

* https://developer.android.com/guide/topics/data/install-location.html
* https://crosswalk-project.org/jira/browse/XWALK-774

No idea if we want or need to enable this - revisit if space issues recur.

**Closed by alxndrsn** 2017-11-17 19:52 UTC
Labels: Storage
