### ISSUE TITLE
poor error handling in medic-api:/api/v1/records

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3330] opened 2017-03-31 18:08 UTC
Submitting data missing the `from` field I only get "Server Error" in the http response, it should pass the useful message through "Missing required field: from":

```
$ cat test.json | curl -H 'content-type:application/json' -d@- $COUCH_URL/api/v1/records
Server error
```

Also the log entry in the medic-api log seems incomplete because it doesn't include the stack trace?

```
 2017-03-31T18:01:44.941Z - info: 127.0.0.1 - admin [31/Mar/2017:18:01:44 +0000] "POST /api/v1/records HTTP/1.0" - - "-" "curl/7.51.0"
 
2017-03-31T18:01:44.977Z - error: ~~~~~~~~~~ SERVER ERROR
 
2017-03-31T18:01:44.977Z - info: Missing required field: from
 
2017-03-31T18:01:44.978Z - info: ~~~~~~~~~~ STACK
 
2017-03-31T18:01:44.978Z - info: undefined
 
2017-03-31T18:01:44.978Z - info: ~~~~~~~~~~ URL
 
2017-03-31T18:01:44.978Z - info: /api/v1/records
```

Also why do we have extra newlines in those logs?

**Comment by garethbowen** [comment] 2017-04-02 18:27
Yeah absolutely agree that validation errors shouldn't end up as server errors (502s). It doesn't need a stack because it's not an exception - it's an expected case we should handle gracefully.

To complicate the matter further, those look like the log statements I added to a specific instance to get better logging to fix an unrelated bug - usually we just have the server error line and not even a stack trace or URL.

**Comment by nice-snek** [comment] 2017-07-19 13:25
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by abbyad** [comment] 2017-08-09 18:08
Duplicate of #2994?

**Comment by garethbowen** [comment] 2017-08-09 21:11
Looks like it, good catch. Closing.

**Closed by garethbowen** 2017-08-09 21:11 UTC
Labels: Needs Triage
