### ISSUE TITLE
Condition card for pregnancy does not appear for newly created person

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4679] opened 2018-06-29 02:56 UTC
_Condition card for pregnancy does not appear for newly created person but works for existing persons_.

**Steps to reproduce**:
 - _login as admin
Add a new woman of childbearing age to your family (if you don’t already have one) using the add person form in the web app
Register a pregnancy for this woman using the web app
 _

**What should happen**:
 - _The condition card for pregnancy should appear_

**What actually happens**:
 - _Report submitted but condition card not updated_

_Contact: [here](https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/07d93e51-6e72-408c-9d04-c04ec36807e3)_
![image](https://user-images.githubusercontent.com/6979995/42070888-909ba31e-7bac-11e8-890f-bc512f078fa9.png)

_Report: [here](https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/544a8e65-a06c-47eb-8b3b-5e6b66d0dc6c) _ (Notice there is no ID)

![image](https://user-images.githubusercontent.com/6979995/42070844-5c0d2c9e-7bac-11e8-8be4-322ad9063cef.png)

**Environment**:

- Instance: _beta-old.dev.medicmobile.org_
- Browser: _Chrome)_
- Client platform: _MacOS_
- App: _webapp_
- Version: _(2.16.beta-7)_

**Comment by sglangevin** [comment] 2018-06-29 16:32
@ngaruko the problem is that the form you submitted has no ID. You must have a patient ID in your form in order for the report to be associated with the patient and for the condition card to be generated.

**Comment by abbyad** [comment] 2018-06-29 16:36
This seems to be related to https://github.com/medic/medic-webapp/issues/4446.

**Comment by abbyad** [comment] 2018-06-29 17:09
The report in question has the the patient UUID, but not the ID: `"patient_uuid":"07d93e51-6e72-408c-9d04-c04ec36807e3","patient_id":""`

The person's doc doesn't have a `patient_id` because they do not have the `generate_patient_id_on_people` transition enabled. This means that any project in 2.15 will not have app reports showing up for the people unless they set that transition, and many projects would not. This means that either #4446 needs to be backported to 2.15, or that we require that `transitions.generate_patient_id_on_people` be set to true for all 2.15 projects. This could have been missed in release testing since the Standard config has that transition enabled.

**Comment by abbyad** [comment] 2018-06-29 17:14
Actually, @sglangevin just reminded me that app projects don't have `patient_id` fields on the person, but do in the forms to link them back to the person's `_id`.

**Comment by abbyad** [comment] 2018-06-29 17:15
Closing as a duplicate.

**Closed by abbyad** 2018-06-29 17:15 UTC
Labels: Won't fix: Duplicate
