### ISSUE TITLE
BACK button from newly-created contact is weird

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1513] opened 2015-11-02 23:47 UTC
As per https://github.com/medic/medic-webapp/issues/1459#issuecomment-152605054 and report from @joshnesbit, when you create a new contact and then hit the `<` button (or press browser back button), you are returned to the New Contact/New Family form.

# Steps to reproduce

1. log in
1. browse to _Contacts_
1. _Add Family_
1. save family
1. observe that you are now viewing the family's content page
1. click the `<` button, or press **BACK** button
1. observe you are now back at the _New Family_ form (although without content)

# Expected behaviour

## Pressing `<`

Seems intuitive to me that this would take you back to the list of contacts.  __However__, this may be because I am used to the app in desktop mode, so the list view feels like it's to the left of the content view.  This may not be a natural association for mobile users... or it may be, as LEFT and BACK are commonly linked.

## Pressing browser **BACK**

Not sure what should happen there.  Stay consistent with the `<`?  Stay consistent with the literal browsing history?

@abbyad @Lesterng would be interested in your thoughts on this.

**Comment by joshnesbit** [comment] 2015-11-03 00:24
May be worth noting that the same thing happens after submitting any form. For example:

1. Do an assessment for a child and submit form
2. Observe that you're viewing the child's profile page
3. Click the < button
4. You're now back in the assessment form

I agree with Alex, I think the expected behavior on mobile is to press < from the profile and be taken back to the family page (when viewing a person profile) or back to the main tabs (when viewing a family profile).

**Comment by garethbowen** [comment] 2015-11-03 08:27
I think having the `<` button go to the list makes sense.

My main concern here is that if we work on the navigation piecemeal we will end up with an inconsistent result. I think there needs to be some design thought about what each back button means and how that should be communicated to the user. Currently as a user I would have little confidence that hitting the `<` button, the android back button, the `< Prev` button or the `X` button will do what I want, and not result in any loss of data.

**Comment by abbyad** [comment] 2015-11-03 13:10
I think this is a side effect of having the back button using the browser history back rather than navigating up the app hierarchy - which is what a user on a mobile device would expect, as @joshnesbit has experienced.

I will re-post here the app structure and we can create a new issue to consolidate all the back button and `<`/`x` issues.

**Comment by abbyad** [comment] 2015-11-03 13:24
Going back to the app hierarchy mockup, the hardware back button, `<`, and `x` should bring you one column left in the diagram. This would match the typical navigation of most native apps.

If you are in left-most column and press the back button you should go to the default tab (eg Task)

If you are in the default tab and press back again, it should exit the app.

![image](https://cloud.githubusercontent.com/assets/789512/10909019/deb4370a-8203-11e5-9de0-0dfbc3c486ec.png)

@joshnesbit, can you please let us know if this matches your thinking.

**Comment by joshnesbit** [comment] 2015-11-03 14:40
I think this could work, but I was proposing something slightly different:

- Use X when you're at least one step into a form, to show that you're closing a form (ideally, with a confirmation).

- Use < to navigate the app hierarchy, specifically the profiles (family page, person pages). If we also need to use < on the task info page and first page of a form, that's OK.

My thinking is that we want the X and < buttons to mean something to the user. "X means I might lose my data. < means I'm going back towards the home screen." I was thinking the hardware back button could retrace my steps.

**Comment by abbyad** [comment] 2015-11-03 15:06
`X` is destructive, and at any point during form entry
`<` is for non destructive app hierarchy navigation

**Comment by alxndrsn** [comment] 2015-11-03 16:26
@abbyad I think your proposal is consistent.  I propose an alternative:

1. ditch `<` - always use `X` instead
2. in every case, `X` returns to the list view, except
3. when _editing_ something, `X` cancels the edit, and returns to viewing the _content_ of that item

**Comment by abbyad** [comment] 2015-11-03 16:40
> ditch < - always use X instead

I think X is clearer for cancelling a form, < for going back up. Why should we use a single icon for this?

> in every case, X returns to the list view, except

If you drill to a contact, you should be able to go out one step at a time. When going Contacts > Family > Child 1 then Back the workflow you'd want is to go back to the family to select another child, not back to Contacts

> when editing something, X cancels the edit, and returns to viewing the content of that item

Agreed

**Comment by abbyad** [comment] 2015-11-03 20:15
Updated mockup with further drilling - eg accessing a task from a patient:

![image](https://cloud.githubusercontent.com/assets/789512/10920331/88651c5e-823d-11e5-923c-00c7d5164e24.png)

**Comment by browndav** [comment] 2015-11-03 22:32
<img width="1552" alt="back-button-directed-cyclic-graph" src="https://cloud.githubusercontent.com/assets/763977/10923764/995967dc-8237-11e5-977a-ef9e2c16538f.png">

Here's an attempt at exhaustive documentation of the long-term intended navigation flow. This was put together on a development team call this morning.

**Comment by alxndrsn** [comment] 2015-11-04 09:25
This is still tagged **Blocked**; is it clear what we want to do to move fowards?

**Comment by abbyad** [comment] 2015-11-04 13:30
Here are the guiding principles for the flow chart. If something is inconsistent please point it out. 

**From default tab (leftmost tab eg Tasks):**
- Hardware Back Button (HBB) exits app

**Other top level pages/tabs (eg Contacts, Help):**
- HBB goes to default tab 

**Sub pages (eg Contact profile):** 
- HBB, and chevron in top bar: back up one step out of the hierarchy, but not through empty forms.

**On Enketo forms (any form, including contact creation):**
- HBB: same as prev, until first page, then exit form.
- Use `x`, not chevron in top bar, which exits form

**Comment by abbyad** [comment] 2015-11-04 13:51
@browndav, please review and remove Blocked & Needs Design Work labels as you see fit.

**Comment by abbyad** [comment] 2015-11-05 18:46
It seems as though the is no longer blocked. Setting to Scheduled since this is high priority for the field test and will resolve some other related issues.

**Comment by joshnesbit** [comment] 2015-11-09 01:35
I think the priority for the field test is making it easy to get back to main tabs after submitting a form. If < takes you back to main tabs from profiles, that will work.

Reworking the UX for exiting a form (mid-form) is a lower priority, from my perspective. Currently, you have to back out of the form (all the way) with the chevron button, and that’s hard to do by mistake. I'm all for implementing the principles listed above, and I admit it’s confusing to have < back out of a form and also < get you to main tabs – but that specific confusion is better than not doing the field test.

**Comment by alxndrsn** [comment] 2015-11-10 13:34
Version with this fix is now deployed to `lg.dev`.

**Comment by alxndrsn** [comment] 2015-11-10 13:45
The `livinggoods`-branded `medic-android` build compatible with the webapp changes (`0.1.102`) is uploaded to appstore.  This will need an update to `lg.app` to work.  Uploading `unbranded` to appstore fails.

**Closed** 2015-11-10 14:38 UTC
Labels: 4 - Acceptance testing, Priority, UI/UX

**Comment by alxndrsn** [comment] 2015-11-11 21:11
Re-animated as https://github.com/medic/medic-webapp/issues/1564
