### ISSUE TITLE
Bullet displayed incorrectly

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3020] opened 2016-12-21 01:25 UTC
This is on the same instance, logged in as admin on the left, and restricted user on the right:

![image](https://cloud.githubusercontent.com/assets/789512/21374076/dcb02d18-c6f1-11e6-931d-09d044457eb4.png)

Took me a while before I noticed it, so it is possible that it is not happening consistently

Running 4668

**Comment by abbyad** [comment] 2016-12-23 15:02
Can reproduce now... 

1. In console run `angular.reloadWithDebugInfo();`, which is done when trying to [debug the XForm](http://medicmobile.cloud.answerhub.com/questions/209/how-can-i-debug-the-values-of-a-xform-in-progress.html)
2. See weird bullets

Users won't run into this, but will leave open for now so that a developer can assess in case it hints at another issue.

**Comment by ngaruko** [comment] 2017-01-03 22:05
It looks intermittent without any debugging. Just refreshed the page and it is properly rendering.

**Comment by sglangevin** [comment] 2017-01-23 18:51
I have also seen this intermittently. Reloading the page fixed it though.

**Comment by nice-snek** [comment] 2017-03-28 15:17
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment] 2017-03-28 15:38
This is odd. Scheduling.

**Comment by estellecomment** [comment] 2017-04-10 15:18
Looks like an encoding problem, with UTF-8 not being read as UTF-8 : http://stackoverflow.com/a/16024449

**Comment by estellecomment** [comment] 2017-04-11 08:37
I wasn't able to reproduce this, so I'm not completely sure which part is doing this. 
Replaced `•` with `\2022`.
http://stackoverflow.com/questions/5316545/libefore-content-%E2%96%A0-how-to-encode-this-special-character-as-a-bullit-in-a

Let me know if it's worse. :)

@alxndrsn please review!

**Comment by alxndrsn** [comment] 2017-04-11 10:44
@estellecomment The change looks good, but I recommend you test this with @abbyad - it's likely that this is caused by Windows encoding, so I doubt I'd have any more luck than you in recreating.

**Comment by abbyad** [comment] 2017-04-11 12:55
I'll test when this gets merged to alpha. Sharon and Bede have also seen it, which means it was seen by at least one person not on Windows as well.

**Comment by estellecomment** [comment] 2017-04-11 13:47
Merged to master, @ngaruko can you AT, since you've seen it happening too?

**Closed** 2017-04-11 13:47 UTC
Labels: 4 - Acceptance Testing, Bug

**Comment by ngaruko** [comment] 2017-05-15 04:41
LGTM. Will close this for now
