### ISSUE TITLE
When creating a new person as a district's primary contact, that person is not created within the district

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2327] opened 2016-05-27 22:55 UTC
![image](https://cloud.githubusercontent.com/assets/1286381/15622946/3035b3da-2423-11e6-948b-2ae39d7337d8.png)
![image](https://cloud.githubusercontent.com/assets/1286381/15622952/3d2f04ba-2423-11e6-8693-2b24c393ca9c.png)

Looking in Futon, the `parent` field is blank for this contact. It should be set to the district place that is being created at the same time.

**Comment by abbyad** [comment] 2016-05-27 23:15
How are you creating the person? A link to the form definition may be helpful.

**Comment by sglangevin** [comment] 2016-05-27 23:16
Using the built-in form for District

**Comment by abbyad** [comment] 2016-05-27 23:17
I think this is because being a primary contact for a place does not guarantee that you are in the place. You can set this differently in custom forms for a project.

**Comment by sglangevin** [comment] 2016-05-27 23:22
So should we be creating custom forms for districts as well then?

**Comment by sglangevin** [comment] 2016-06-02 23:42
Confirmed that this is possible using custom forms. However, if I try to use the `allow-new` appearance in a custom form, when I select `New Person` in the drop-down, I don't see the Submit button change to Next. @abbyad maybe there is something obvious I am doing wrong?

**Comment by garethbowen** [comment] 2016-07-26 23:33
Closing as duplicate of #1710

**Closed by garethbowen** 2016-07-26 23:33 UTC
Labels: Duplicate
