### ISSUE TITLE
Contact fields not accessible in auto replies

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3892] opened 2017-09-11 19:58 UTC
As discovered by @jillrshah, between `2.13.0-beta.11` and `13` the `{contact.*}` fields in a auto reply are no longer populated.

**Comment by abbyad** [comment] 2017-09-11 20:06
Possibly related to https://github.com/medic/medic-webapp/issues/3838

**Comment by sglangevin** [comment] 2017-09-11 23:32
This appears to be working on `master` so may be useful as a comparison point.

**Comment by SCdF** [comment] 2017-09-12 10:55
@abbyad do you mean that somewhere between beta 11 and beta 13 it stopped working? Or that it worked in 11 but not in 13?

FWIW there is no change to any code related to this between 11 and 13, so presumably you mean the former. Do you have an example of a beta where this worked?

**Comment by SCdF** [comment] 2017-09-12 11:06
It would be helpful if there was some examples, ones that work and ones that don't, things like that. There are lots of different "auto replies", so it's not clear which one you have an issue with. Do you mean registrations?

**Comment by abbyad** [comment] 2017-09-12 11:42
Any auto reply with `{contact.*}` works properly in beta 11 on standard.app, and has no value for those fields in beta 13, which is on standard.dev. @jillrshah, can you add specific reports here?

@SCdF, in the meantime you can find which auto replies use `{contact.name}` in messages-en.properties.

**Comment by SCdF** [comment] 2017-09-12 12:54
So beta.11 has this version of sentinel:
![image](https://user-images.githubusercontent.com/583851/30326795-968e0502-97c1-11e7-9769-87a5dd2edd38.png)
And beta 13 has this version:
![image](https://user-images.githubusercontent.com/583851/30326811-a6230346-97c1-11e7-940e-bb89d81097bb.png)
If we use those two sentinel versions and the power of github, we can see what is different between the two: https://github.com/medic/medic-sentinel/compare/aa0644c...cca99df

As you can see, it's a change to one transition, that doesn't have anything to do with auto-replies?

@abbyad , are you *sure* it works in 11 and not in 13?

**Comment by abbyad** [comment] 2017-09-12 13:25
Thanks for checking. I'll test again and post the records here

**Comment by SCdF** [comment] 2017-09-12 13:27
Cool. FWIW I tested against 2.13.x in my local and it worked for me:
![image](https://user-images.githubusercontent.com/583851/30328176-7cb1fde6-97c6-11e7-9a1d-4e4694e3371a.png)

**Comment by abbyad** [comment] 2017-09-12 13:29
That one doesn't use `contact.*`
`messages.p.report_accepted = Thank you for registering the pregnancy for {{patient_name}} ({{patient_id}}).{{\#expected_date}} Their EDD is {{\#date}}{{expected_date}}{{/date}}{{/expected_date}}`

Can you try a `V` form?

`messages.v.report_accepted = Thank you {{contact.name}}, visit for {{patient_name}} ({{patient_id}}) has been recorded.`

**Comment by SCdF** [comment] 2017-09-12 13:38
Whoops, sorry!

![image](https://user-images.githubusercontent.com/583851/30328712-10a8a6d4-97c8-11e7-8ae6-dfc23567ae33.png)

Looks to work through :-)

**Comment by abbyad** [comment] 2017-09-12 13:41
Nice, glad to hear! What beta version of 2.13 do you have there?

**Comment by SCdF** [comment] 2017-09-12 13:51
Sorry if I wasn't clear, that is technically the 2.13.x branch, which is the same as the 2.13.0-beta.13 tag.

**Comment by SCdF** [comment] 2017-09-12 13:56
@abbyad I'll hand this over to you. Let me know if you can narrow down the issue further, otherwise we can close as cannot reproduce?

**Comment by abbyad** [comment] 2017-09-12 13:57
Thanks for clarifying. From my tests I see `{contact.name}` work in [this doc](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/800e6180f58905dafb5562238508ae17) in 2.13.0-beta.11, fails in [this one](https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/82c1c868215daa278f45209ab7135569) on 2.13.0-beta.13. The config was just updated to be exactly the same.

**Comment by SCdF** [comment] 2017-09-12 17:03
This appears to be something to do with the data structure used in standard.dev. I'm still investigating

**Comment by SCdF** [comment] 2017-09-14 12:15
OK, this appears to work in standard.app because in those examples, *the area's contact is inlined into the area*. I may be getting my timelines mixed up, but I imagine this is because these areas were created back in an old beta where we weren't extracting contacts correctly in all cases.

The examples in standard.dev are the more correct ones, and they fail. I've created a fix for this, and merged it into the 2.13.x branch and master (this occurred after beta.15).

**Comment by sglangevin** [comment] 2017-09-14 15:46
Assigning @abbyad for AT.

**Comment by abbyad** [comment] 2017-09-15 13:47
Works well `2.13.0-beta.16`, moving to Ready.

**Closed** 2017-09-15 13:47 UTC
Labels: Priority: 1 - High, Regression, Status: 4 - Acceptance testing, Type: Bug
