### ISSUE TITLE
Show XForm in User's language

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3174] opened 2017-02-28 20:28 UTC
Currently different languages are supported by replacing all labels during form creation/editing. As we start having projects with multiple languages, and Standard projects using the same forms but in different languages, we should pass the user's language to the form to show the appropriate labels, according to the [multi-language support](http://xlsform.org/#language) in XForms (and XLSforms).  

For flexibility we should consider supporting the language as a 2-3 letter code, as well as a full name eg `sw` and `Kiswahili (Swahili)`.

Related to https://github.com/medic/medic-webapp/issues/2408

**Comment by garethbowen** [comment] 2017-02-28 20:35
This should be working, fixed in https://github.com/medic/medic-webapp/issues/1244

**Comment by abbyad** [comment] 2017-02-28 21:21
Great, will test now.

**Comment by abbyad** [comment] 2017-02-28 21:33
Works well, thanks for taking care of that 18 months ago!

**Comment by abbyad** [comment] 2017-02-28 21:39
In case someone comes back here looking to do this, use the language _code_ in the XForm or XLSForm, not the name. For instance, in a XLSform the headers would be something like `label::en`, `label::fr`, `hint::sw`.

**Comment by abbyad** [comment] 2017-03-03 22:31
It turns out I tested this inadequately and I could not get a form to be shown with the user's language code. The language shown is that of translation with `default="true()"`, or if none have that then will show the first one in the XML.

**Comment by garethbowen** [comment] 2017-03-06 07:27
@abbyad Works for me...

![englais](https://cloud.githubusercontent.com/assets/2064938/23600386/43f038ca-02ab-11e7-950a-1092e1786549.png)
![french-fry](https://cloud.githubusercontent.com/assets/2064938/23600387/43f147ce-02ab-11e7-8e05-219edaf93b70.png)

Can you send me the XML you're using?

**Comment by garethbowen** [comment] 2017-03-07 22:36
The config that works is...

```xml
      <itext>
        <translation lang="en">
          <text id="select_patient:label">
            <value>Patient ID</value>
          </text>
        </translation>
        <translation lang="fr">
          <text id="select_patient:label">
            <value>Identification du patient</value>
          </text>
        </translation>
        <translation lang="en">
          <text id="patient:label">
            <value>Patient</value>
          </text>
        </translation>
        <translation lang="fr">
          <text id="patient:label">
            <value>The French patient</value>
          </text>
        </translation>
      </itext>
```

The configuration that doesn't is:

```xml
      <itext>
        <translation lang="en">
          <text id="select_patient:label">
            <value>Patient ID</value>
          </text>
          <text id="patient:label">
            <value>Patient</value>
          </text>
        </translation>
        <translation lang="fr">
          <text id="select_patient:label">
            <value>Identification du patient</value>
          </text>
          <text id="patient:label">
            <value>The French patient</value>
          </text>
        </translation>
      </itext>
```

This is problematic because the second format is what's emitted from the xsl converter that configurers use. We should support both.

I think this might be a bug somewhere in the transformer but I don't know it enough to track it down. @alxndrsn Any ideas on this?

**Comment by alxndrsn** [comment] 2017-03-08 05:01
`<translation>` is a java rosa (ODK) extension to XForms:

> XForms provides no way to dynamically support multi-lingual content in a single form. We've devised our own way
> – _https://bitbucket.org/javarosa/javarosa/wiki/xform_

However, I think the non-working format is the correct one:

> The `<translation>` block is duplicated _for each supported language_. The content should be the same (same set of text ids) but **with all strings translated** to the new language.
> –_https://bitbucket.org/javarosa/javarosa/wiki/xform_ (emphasis mine)

> <img width="764" alt="screen shot 2017-03-08 at 10 33 06" src="https://cloud.githubusercontent.com/assets/191496/23690559/abc173ca-03ea-11e7-9599-fe8956701a53.png">
> 
> – _https://opendatakit.github.io/xforms-spec/_

> Each `<translation>` defined in the model **must** provide a definition for **every** id defined in every other model.
> – _https://github.com/dimagi/commcare-j2me/wiki/XForms-Specification:-IText_ (emphasis mine)

----

> We should support both.

I disagree - we should support the standard as defined.

> I think this might be a bug somewhere in the transformer

I'm interested to hear more on this - does the correct `<translation>` format work with vanilla enketo?  It doesn't look like anything significant has changed in enketo's `translations` code for a long time, so a problem with the transformer is a distinct possibility.

**Comment by garethbowen** [comment] 2017-03-08 06:56
@alxndrsn My guess was a complete stab in the dark. I'll have a look at the ODK code to see if I can work it out. Thanks!

> > We should support both.

> I disagree - we should support the standard as defined.

We should definitely support the standard as defined. If the other format happens to work as it does now, I don't think we should break it on purpose.

**Comment by garethbowen** [comment] 2017-03-13 03:23
Code review please @alxndrsn https://github.com/medic/medic-webapp/pull/3221

Don't worry about the failing build - I think it's some transient npm issue...

As far as I can tell the enketo/odk code is working perfectly. I managed to reproduce this by changing language and then loading the form without refreshing. We cache the form html so it was being generated once and stored regardless of if the user language changed. I've changed it to cache by the user language, so if it changes the cache lookup will miss.

**Closed** 2017-03-14 10:07 UTC
Labels: 4 - Acceptance Testing, Enketo, Feature Request

**Comment by abbyad** [comment] 2017-03-31 01:03
Works well, moving to Ready.
