### ISSUE TITLE
dashboard update UI hangs when medic-api is restarted/updated.

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#975] opened 2015-05-26 19:24 UTC
the install hangs during the installation of medic-sentinel module.

**Comment by sglangevin** [comment] 2015-05-26 19:25
![screen shot 2015-05-26 at 12 25 06 pm](https://cloud.githubusercontent.com/assets/1286381/7821251/4ed91da6-03a2-11e5-8cf1-774765a7d0f4.png)

**Comment by garethbowen** [comment] 2015-05-28 22:45
Just updated no problem. Either it's resolved, or more likely, occurs randomly. If this happens again we should grab the logs to see if there's a problem with the module. It could also be a bug in dashboard so we should check the browser console in case there's something obvious.

**Comment by mandric** [comment] 2015-05-29 01:30
I think it might only happen when medic-api has an update and is restarted during the install.  Sharon  uploaded gardener logs in slack but I haven't diagnosis it yet, would be good to have browser console logs also. https://medic.slack.com/archives/support/p1432669247000084

**Comment by garethbowen** [comment] 2015-05-29 09:33
Going through the logs, there are a couple of errors in startup.log...

```
/srv/software/gardener/v1.1.0/lib/utils.js:20
    return (module_name.indexOf(suffix, module_name.length - suffix.length) !=
                                                   ^
TypeError: Cannot read property 'length' of undefined
    at Object.exports.is_tgz (/srv/software/gardener/v1.1.0/lib/utils.js:20:52)
    at is_remote_package (/srv/software/gardener/v1.1.0/lib/processes.js:169:49)
    at /srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:570:21
    at /srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:249:17
    at /srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:46:24)
    at async.each (/srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:248:13)
    at Object.map (/srv/software/medic-core/v1.6.0/x64/lib/node_modules/async/lib/async.js:219:23)
```

The logging isn't timestamped so I can't tell if it's related but I suspect it's not. It's also fixed (by ignoring nameless modules) by this commit: https://github.com/garden20/gardener/commit/4061ad56507567ae47dd3fb7649644d090a27e77 . So I recommend we update gardener in medic-os and ignore.

The actual problem looks to be in the gardener.log where we get into an infinite loop of installation:

```
2015-05-20T20:16:38.076Z - info: adding install task to the queue.  
2015-05-20T20:16:38.077Z - info: adding install task to the queue.  
2015-05-20T20:16:38.077Z - info: pulling install task from the queue. 1 remaining 
2015-05-20T20:16:38.361Z - info: pulling install task from the queue. 0 remaining 
2015-05-20T20:17:06.408Z - info: polling couch for design doc changes. 
2015-05-20T20:17:07.401Z - info: Scanning design docs on _replicator 
2015-05-20T20:17:07.700Z - info: Scanning design docs on _users 
2015-05-20T20:17:08.125Z - info: Scanning design docs on dashboard 
2015-05-20T20:17:08.794Z - info: Scanning design docs on medic 
2015-05-20T20:17:08.795Z - info: _design/medic on db medic has a module medic-api-0.1.0.tgz 
2015-05-20T20:17:08.795Z - info: _design/medic on db medic has a module medic-sentinel-0.1.0.tgz 
2015-05-20T20:17:08.905Z - info: Scanning design docs on medic-reporter 
2015-05-20T20:17:08.905Z - info: adding install task to the queue.  
2015-05-20T20:17:08.906Z - info: adding install task to the queue.  
2015-05-20T20:17:08.906Z - info: pulling install task from the queue. 1 remaining 
2015-05-20T20:17:09.112Z - info: pulling install task from the queue. 0 remaining 
```
I'm still investigating why this is happening.

**Comment by garethbowen** [comment] 2015-05-29 09:56
I've made a [commit](https://github.com/garden20/gardener/commit/f581a89a4e53af9e2e04b1c125969f8a07b6027a) which fixes installation in dashboard installation which will fix the first error above, which should mean installation completes successfully avoiding the infinite polling.

Essentially the status bar is never updating because the installation process dies unexpectedly. The commit @mandric made above would mean the error gets caught and displayed, and with the commit I just made it shouldn't error in the first place.

**Comment by browndav** [comment] 2015-05-29 14:27
Looks good to me; this also retains/caches all of those properties on `module`, which seems to make sense.

I'll file an issue for timestamping the logs – I was going to just put together a little `awk` timestamper script to minimize dependencies and cover all of the `stdout` / `stderr` style logs... and then we'll have to do something different for gardener (since it's using winston and we can't pipe the log output through anything).

**Comment by mandric** [comment] 2015-05-29 14:40
There isn't an infinite loop of installation, it just say it will install but the installer aborts when md5s match.  I think we're missing a log entry when aborting the install call, I'll check that too...

**Comment by garethbowen** [comment] 2015-06-01 20:28
> There isn't an infinite loop of installation

Oh right. I expected it wouldn't even get on the queue if the md5s matched. Maybe we can output something like "install not required due to md5 match" in this case?

**Comment by garethbowen** [comment] 2017-09-07 07:01
Duplicate of #863

**Closed by garethbowen** 2017-09-07 07:01 UTC
Labels: Type: Bug
