### ISSUE TITLE
Cannot use Collect with username/password fields

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3118] opened 2017-02-13 15:51 UTC
As reported by @ngamita and @smbuthia in https://github.com/medic/medic-projects/issues/1333, authentication does not work with Collect in v2 using the username + password fields. The workaround for now is to put the username + password in the URL (eg https://user:pass@project-url.medicmobile.org).

**Comment by SCdF** [comment] 2017-02-28 12:17
So I've never looked at the collect code before…

[Here is where I think it's attaching the configured username and password](https://github.com/medic/medic-collect/blob/master/src/org/odk/collect/android/activities/InstanceUploaderActivity.java#L332-L346):

```java
Collect.getInstance().getActivityLogger().logAction(this, "onCreateDialog.AUTH_DIALOG", "OK");
EditText username = (EditText) dialogView.findViewById(R.id.username_edit);
EditText password = (EditText) dialogView.findViewById(R.id.password_edit);

Uri u = Uri.parse(url);
WebUtils.addCredentials(username.getText().toString(), password.getText()
        .toString(), u.getHost());

showDialog(PROGRESS_DIALOG);
mInstanceUploaderTask = new InstanceUploaderTask();

// register this activity with the new uploader task
mInstanceUploaderTask.setUploaderListener(InstanceUploaderActivity.this);

mInstanceUploaderTask.execute(FormEntryActivity.KEY_UPLOAD_METHOD_HTTP, mInstancesToSend);
```

The source for [add credentials](https://github.com/medic/medic-collect/blob/master/src/org/odk/collect/android/utilities/WebUtils.java#L151-L180) looks legit (albeit confusing) as well. AFAICT it's just using standard HTTPS basic auth, like you would do if you put the password in the URL.

**Comment by SCdF** [comment] 2017-02-28 13:45
Trying to get this to run locally, I get a 301 in Collect, and this in my api logs:
```
::ffff:192.168.0.10 - - [28/Feb/2017:13:44:37 +0000] "HEAD /medic/_design/medic/_rewrite/add?deviceID=imei%XXYYZZ HTTP/1.1" - - "-" "-"
::ffff:192.168.0.10 - - [28/Feb/2017:13:44:37 +0000] "HEAD /medic/login?redirect=%2Fmedic%2F_design%2Fmedic%2F_rewrite%2Fadd%3FdeviceID%3Dimei%XXYYZZ HTTP/1.1" - - "-" "-"
::ffff:192.168.0.10 - - [28/Feb/2017:13:44:37 +0000] "POST /medic/_design/medic/_rewrite/add?deviceID=imei%XXYYZZ HTTP/1.1" - - "-" "-"
```

That redirect is somewhat concerning…

**Comment by SCdF** [comment] 2017-02-28 13:53
@alxndrsn might get some of your time to get this setup properly locally. I should do it anyway, this ticket is a good excuse to get it setup right.

**Comment by alxndrsn** [comment] 2017-02-28 14:49
This is caused by a change in the way we respond to auth failures:

`0.x` auth failure:
```
HTTP/1.1 401 Unauthorized
...
www-authenticate: Basic realm="Medic Mobile Web Services"
```

`2.x` auth failure:

```
HTTP/1.1 302 Moved Temporarily
...
Location: /medic/_design/medic/_rewrite/
www-authenticate: Basic realm="Medic Mobile Web Services"
```

**Comment by alxndrsn** [comment] 2017-02-28 14:56
If I'm reading the `collect` code linked above, `collect` will only provide username and password to the server when an auth dialog is triggered.  The new `medic-webapp` behaviour of issuing a `302` is probably incorrect for API endpoints which are not for direct human/browser consumption.

**Comment by SCdF** [comment] 2017-03-01 10:37
Thanks for the help @alxndrsn, much appreciated :-)

As suggested by @garethbowen:
 - [ ] Write an integration test for medic-api to make sure that the medic-collect style of connection / authentication works, so we don't break it again in the future

**Comment by SCdF** [comment] 2017-03-22 11:31
Apologies, I have no idea why I had this assigned to me, I haven't been working on it at all.

**Comment by SCdF** [comment] 2017-04-03 12:02
Reviewed and approved. @garethbowen should take a look as well: https://github.com/medic/medic-api/pull/134

**Comment by alxndrsn** [comment] 2017-04-03 12:13
Worth mentioning that future versions of ODK Collect _will_ have a user-agent set.  We backport this to Medic's build, and handle that in API as well.  Issue for this at https://github.com/medic/medic-webapp/issues/3334

**Comment by garethbowen** [comment] 2017-04-03 22:27
Back to you @alxndrsn

**Comment by abbyad** [comment] 2017-04-06 18:14
@smbuthia, can you please test this with the 2.11 beta?

**Comment by smbuthia** [comment] 2017-04-07 10:26
@abbyad we are currently in training sessions but I'll try and test this by evening my time.

**Comment by abbyad** [comment] 2017-04-07 15:41
Thanks @smbuthia, I'll do some testing then in the meantime. 

So far I have tested in 2.11.0-beta.2 and this does not yet work. Reopening for investigation.

**Comment by garethbowen** [comment] 2017-04-11 18:29
One small readability change requested then merge away!

**Comment by garethbowen** [comment] 2017-04-11 22:12
I've raised an issue for e2e testing this. I'll merge this PR so we can get 2.11 out. @alxndrsn Feel free to make the suggested readability change post merge if you want.

**Closed** 2017-04-11 22:13 UTC
Labels: 3 - Code Review, Priority, Regression, Returned, Upgrading

**Comment by sglangevin** [comment] 2017-04-11 23:21
@abbyad confirmed this is working in 2.11.0-beta.3. Moving to ready.
