### ISSUE TITLE
Test Data Clearing Functionality

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#1158] opened 2015-08-18 12:17 UTC
A feature is needed to clear reports and messages keeping all other data intact.

**Comment by abbyad** [comment] 2015-08-18 14:24
@henokgetachew is this a duplicate of #1000?

**Comment by browndav** [comment] 2015-09-04 16:33
More information needed to proceed.

**Comment by abbyad** [comment] 2015-09-04 16:34
We discussed this recently as a generic bulk edit. I can post info on that in #1000 and close this one.

**Closed by abbyad** 2015-09-04 16:34 UTC
Labels: Blocked, Returned
