### ISSUE TITLE
Assess Patient form has incorrect filter-bar rewind icon

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1663] opened 2015-11-24 12:36 UTC
Likely related to #1662 

Shows `<` instead of `X`.

<img width="1280" alt="screen shot 2015-11-24 at 15 36 11" src="https://cloud.githubusercontent.com/assets/191496/11366898/3948d61c-92c1-11e5-9463-829787a79eb7.png">

**Comment by garethbowen** [comment] 2015-11-24 18:54
Closing as a duplicate of #1649

**Closed by garethbowen** 2015-11-24 18:54 UTC
Labels: Bug, Duplicate
