### ISSUE TITLE
Some reports show `Facility Not Found` until you click on them

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#758] opened 2015-01-07 16:25 UTC
Some reports submitted 7 days ago show `Facility Not Found`, but clicking on the message resolves the facility within about 10 seconds.

Reported by @shreyakb, on instance running `0.4.3-beta.1018`

**Comment by browndav** [comment] 2015-05-15 21:14
Closing this due to its age. We can re-file if we're able to reproduce the issue on the latest development (alpha) snapshot.

**Closed by browndav** 2015-05-15 21:14 UTC
Labels: 0 - Backlog, Bug
