### ISSUE TITLE
PNC schedule is not generated when a delivery report is submitted

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4201] opened 2018-02-15 00:19 UTC
To reproduce, fill in a delivery report for a woman on standard.dev, either in the web app or via SMS. If you include a delivery date, a PNC schedule should be created. [Here is the relevant piece of JSON form config](https://github.com/medic/medic-projects/blob/master/standard/app_settings.json#L509) and the [relevant piece of app form config](https://github.com/medic/medic-projects/blob/master/standard/app_settings.json#L556). I didn't see anything obviously wrong and this config was working in 2.13.x. Perhaps an issue with the `bool_expr`? I've double-checked to make sure that the health center has the correct use cases selected, so PNC should be enabled.

**Comment by sglangevin** [comment] 2018-02-15 20:42
Updating to include links to relevant reports:

This was working in 2.13.x: https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/82c1c868215daa278f45209ab7566668

Here is a similar report submitted on 2.14.x (days since delivery is included but no schedule is generated): https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/2515675d1644f1bd5f1ce794b3437257

**Comment by abbyad** [comment] 2018-02-21 00:37
I have confirmed this problem in 2.13 as well. The PNC schedule (and many others in Standard now) rely on `doc.contact` being accessible from the bool expression -- and this works for XForms, but not SMS forms. The `contact` is added by the `update_clinics` transition for SMS, not sure about XForms. It _appears_ that the `update_clinic` transition does not run before the `registration` transition. There are some relevant conversations about Transition Ordering in https://github.com/medic/medic-webapp/issues/2978

_Note that currently we get the `Failed to eval boolean expression:` sentinel error for reports with this schedule because it is assumed that the doc has a `contact` field. We should create an issue to guard for this. Even though this will _not_ resolve this issue, it will avoid getting the error for messages from unknown contacts._

**Comment by abbyad** [comment] 2018-02-21 03:33
Thanks Gareth. Hardcoding the order does seem to make sense to me, and I can't yet think of when we would need it to be configurable.

I just tested on standard.app running 2.13.5 with `update_clinics` before `registration` and it does appear to assign the `contact` which is good, but it seems as though it is not fully hydrated from the bool expression. For instance `doc.contact.parent.parent` exists, but not its fields like `doc.contact.parent.parent.use_cases`.

**Comment by garethbowen** [comment] 2018-02-21 03:43
Ok well, maybe it's a partial fix. Definitely more investigation needed. From a quick scan this is the order I think we should define the transitions run in:

1. maintain_info_document
1. update_clinics
1. default_responses
1. registration
1. accept_patient_reports
1. generate_patient_id_on_people
1. update_sent_by
1. update_sent_forms
1. death_reporting
1. conditional_alerts
1. multi_report_alerts
1. update_notifications
1. update_scheduled_reports
1. resolve_pending

**Comment by abbyad** [comment] 2018-02-21 04:00
That order look good generally, just want to confirm a couple of things:
1) Since `default_responses` can use a newly created patient ID does it needs `generate_patient_id_on_people` need to be above it?
2) I am not sure exactly how `update_scheduled_reports` works, but can it be low on that list and still keep data changed by other transitions?

**Comment by garethbowen** [comment] 2018-02-21 04:11
> Since default_responses can use a newly created patient ID does it needs generate_patient_id_on_people need to be above it?

No. The `generate_patient_id_on_people` transition only operates on `person` type docs, so `default_responses` won't fire. However `registration` has to run before `default_responses` for that reason. I'll update the list.

> I am not sure exactly how update_scheduled_reports works, but can it be low on that list and still keep data changed by other transitions?

Yeah, nothing depends on it so I put it low.

The updated list:

1. maintain_info_document
1. update_clinics
1. registration
1. accept_patient_reports
1. generate_patient_id_on_people
1. default_responses
1. update_sent_by
1. update_sent_forms
1. death_reporting
1. conditional_alerts
1. multi_report_alerts
1. update_notifications
1. update_scheduled_reports
1. resolve_pending

**Comment by sglangevin** [comment] 2018-02-21 05:59
I'm supportive of having ordered transitions and I think you both are best-positioned to decide on the order. Let me know if I can help - looks like you've got this covered though!

**Comment by garethbowen** [comment] 2018-02-22 10:01
Merged and backported to `2.14.x`.

**Comment by abbyad** [comment] 2018-02-23 21:34
This works well in `2.14.0-beta.13`, moving to Ready.

**Closed** 2018-02-26 03:28 UTC
Labels: Configuration, Priority: 1 - High, Status: 5 - Ready, Type: Bug
