### ISSUE TITLE
select language dialog has lost the plot

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2332] opened 2016-06-01 08:32 UTC
I'm seeing some strange boxes:

<img width="1022" alt="screen shot 2016-06-01 at 10 31 43" src="https://cloud.githubusercontent.com/assets/191496/15703138/1b4bd99e-27e4-11e6-81e1-049e2aa82590.png">

Zoom out to see what they say:

<img width="512" alt="screen shot 2016-06-01 at 10 31 32" src="https://cloud.githubusercontent.com/assets/191496/15703154/29312b86-27e4-11e6-9481-86db6ebe3fbc.png">

**Comment by estellecomment** [comment] 2016-06-02 07:57
hmmm maybe introduced by 919183252e8090808793bb79df765c7a75526150?
I'll take a look.

**Comment by estellecomment** [comment] 2016-06-02 09:49
It looks like maybe you have an old version of inbox.js and the latest version of the modal, so it's being used wrong.
Have you pulled lately? How did you get this?

**Comment by alxndrsn** [comment] 2016-06-02 09:53
More likely the other way round - latest `develop` for `webapp` and `api`, and a cloned 0.4 database.

**Comment by estellecomment** [comment] 2016-06-02 13:22
Hmm. I'm not seeing it. I cleaned out the browser cache and all.
That piece of html I'm seeing in your screenshot, with the `ng-include` for the user_language modal, hasn't been there for a while. 
So maybe it's 0.4-related...

**Comment by garethbowen** [comment] 2016-08-22 03:42
Closing as can't reproduce. Reopen if it happens again.

**Closed by garethbowen** 2016-08-22 03:42 UTC
Labels: Bug
