### ISSUE TITLE
Messaging reliability

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1823] opened 2016-01-22 20:23 UTC

**Comment by abbyad** [comment] 2016-02-19 20:32
Marking this as high priority for our support projects that send SMS notifications.

**Comment by alxndrsn** [comment] 2016-03-29 09:21
Is there any information that can be added to this ticket?  Otherwise I will close it.

**Comment by sglangevin** [comment] 2016-03-29 10:11
@alxndrsn this is an issue that was created for investigating the root causes for duplicate messages and slow responses that have been seen across support projects and DIY projects. We are seeing the effects of these issues in our use of SMSSync as well. Some of the problems we've had with gateways are due to SMSSync but others are due to the messaging layer in our software stack. I don't have more technical information, but @browndav can provide more background that would probably help you. We can also create a set of more specific issues to make sure we are investigating and resolving this. It's a huge pain point in all of our deployments that rely on SMS.

**Comment by browndav** [comment] 2016-03-30 23:02
I'd be in favor of at least marking this as blocked on #2109. An alternate but totally agreeable option would be to close this and reevaluate the need after #2109. I suspect that most of our current critical-path reliability issues are related to SMSSync, but IMO we need to prove/disprove that.

Proposal: mark this blocked and I'll update the summary to something a little more helpful?

**Comment by btbonval** [comment] 2016-05-29 06:07
How is this issue different from #1220?

**Comment by garethbowen** [comment] 2016-07-05 04:31
Closing this as the gateway has been rewritten. Acceptance testing will occur on the new code.

**Closed by garethbowen** 2016-07-05 04:31 UTC
Labels: 1 - Scheduled, Priority
