### ISSUE TITLE
Bulk delete errors on conflict

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4469] opened 2018-04-25 05:54 UTC
Raised from #4113 

The bulk delete should make sure that when it's done all documents that were asked to be deleted are deleted.

Currently this can fail to be true if there are conflicts, which not only stops the conflicted documents from being deleted, but also halt the bulk delete completely.

One solution would be to take conflicts and add those documents to the end of the queue to be retried later.

**Comment by ngaruko** [comment] 2018-05-28 01:26
Getting errors on `beta-old` even for a couple of reports...`Version 2.15.0-beta.14`. Is this a regression @garethbowen ?
![image](https://user-images.githubusercontent.com/6979995/40593091-f19d251c-6279-11e8-9a13-d9bdc7ec861d.png).

**Comment by garethbowen** [comment] 2018-05-28 01:31
cc @rmhowe @SCdF

**Comment by garethbowen** [comment] 2018-05-28 01:32
@ngaruko Can you switch to the network tab and see what the response is? I suspect you're getting an error or something which isn't valid JSON so is failing to parse.

**Comment by ngaruko** [comment] 2018-05-28 01:37
Network tab...
Response 
![image](https://user-images.githubusercontent.com/6979995/40593319-f41315e8-627b-11e8-84ee-caf5eff87109.png)

Request payload...
```{"docs":[{"_id":"dd32e2d08c7def675f5de6ab960e3295"},{"_id":"dd32e2d08c7def675f5de6ab960e2c1d"},{"_id":"dd32e2d08c7def675f5de6ab960e211f"},{"_id":"dd32e2d08c7def675f5de6ab960e1e0c"},{"_id":"dd32e2d08c7def675f5de6ab960e1345"},{"_id":"dd32e2d08c7def675f5de6ab960e1280"},{"_id":"dd32e2d08c7def675f5de6ab960e02bf"}]}```

**Comment by SCdF** [comment] 2018-05-29 10:47
@ngaruko api server logs would be helpful here.

Does this reproducibly break or just sometimes?

**Comment by ngaruko** [comment] 2018-05-29 11:21
@SCdF It seems to break all the time. Easily reproducible on [beta-old](https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/). Even for a couple of reports.
![image](https://user-images.githubusercontent.com/6979995/40655889-c88db632-6396-11e8-95fe-b74e059ae554.png).

**Comment by rmhowe** [comment] 2018-05-29 15:42
@ngaruko working locally for me but can definitely see the bug on beta-old, can you post the api server logs?

**Comment by ngaruko** [comment] 2018-05-30 04:56
I looked at the logs and I found this @SCdF @rmhowe 
```
2018-05-29T11:19:30.854Z - error: TypeError: Cannot read property 'filter' of undefined
        at utils.updateParentContacts.then.updatedParents (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/services/bulk-docs.js:79:41)
        at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by SCdF** [comment] 2018-05-30 13:48
This is a known issue with gardener being terrible: you basically have to delete api and sentinel before upgrading. People should know this, but it's very easy to forget, and that sounds like what has happened here.

@henokgetachew do you have any bright ideas for how to avoid people forgetting to do this in the future. Maybe we really do have to fix gardener and deploy a new version?

**Comment by abbyad** [comment] 2018-05-30 15:50
How involved and time consuming is the fix to Gardener?

**Comment by garethbowen** [comment] 2018-05-30 22:32
Moving this back to AT.

**Comment by SCdF** [comment] 2018-05-31 07:10
> How involved and time consuming is the fix to Gardener?

No idea. It would involve:
 - Investigating the code and fixing the issue
 - Knowing how to "deploy" / "package" / "something" gardener (no idea)
 - Knowing how to update old medic os to the new version
 - Then deploying that everywhere.

Anyway, if we want to do this we should raise a ticket about it, this has nothing specific to do with this ticket and this ticket still needs to be AT'd correctly (ie 2.15.0-beta.whatever needs to be deployed properly).

**Comment by sglangevin** [comment] 2018-05-31 22:34
@ngaruko I've deleted api and sentinel and then upgraded beta-old.dev. If you can give this a test today to make sure everything looks good, that would be helpful as it's the last item waiting for AT for 2.15.0.

As far as updating gardener, I'm not sure if it's worthwhile given that we will be upgrading people to 3.0 fairly soon and gardener won't be used anymore. It does add a little extra effort to upgrades in the meantime, but we won't be doing many upgrades between now and 3.0's release.

**Comment by henokgetachew** [comment] 2018-06-01 06:46
>@henokgetachew do you have any bright ideas for how to avoid people forgetting to do this in the future.

I can script it so that it's at least easier.  But people would still have to remember to do it.

**Comment by SCdF** [comment] 2018-06-01 10:34
@henokgetachew / @sglangevin yeah that's the issue IMO: how do we make sure people remember this stupid manual step.

Having said that, I think at the moment we have two deploy situations:
 - Lots of people deploy alphas and betas
 - Henok deploys finals

Alpha and beta deployments are about to move completely to horti, and even for legacy ones (which I have no doubt will continue for months) worst case AT fails and we wonder why for a little bit: we at least haven't broken production.

So IMO as long as Henok is the only one who deploys finals, and he remembers / has a script then we're fine.

**Comment by ngaruko** [comment] 2018-06-05 02:44
It still seems not to be working. Does the `bulk-delete` works for you @sglangevin on [beta-old.dev](https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/)?

**Comment by garethbowen** [comment] 2018-06-05 04:13
@ngaruko What's in the log?

**Comment by sglangevin** [comment] 2018-06-05 14:46
I wouldn't be surprised if the error is related to the bad report that was causing #4596. We should delete that report and see if that resolves the issue.

**Comment by ngaruko** [comment] 2018-06-06 10:41
Same error as above @garethbowen. 
And I am not sure if it is related to #4596 @sglangevin. I think this issue has to be looked at because at the moment, not even one report can be deleted, apparently. Is anyone able to delete a report on this instance?

**Comment by sglangevin** [comment] 2018-06-06 17:01
@ngaruko I just deleted a report on that instance using the delete button and it worked fine. I'm wondering if bulk delete is failing due to the same report that is causing the other issue. Even if you aren't trying to delete that report, perhaps it is still breaking the bulk delete process in some way.

**Comment by garethbowen** [comment] 2018-06-06 21:31
The bulk-delete-utils shared library on beta-old hasn't been updated. I'm looking in to it.

**Comment by garethbowen** [comment] 2018-06-06 23:01
When I followed the instructions that Stefan has pinned in the #development channel in Slack and installed the next beta the code was updated and bulk delete appears to work for me. No idea what happened but it's possible the instructions weren't followed, or that the instructions don't work 100% of the time. Anyway, this is now unblocked and ready for you to test again @ngaruko

**Comment by sglangevin** [comment] 2018-06-06 23:03
Thanks @garethbowen - I updated beta-old.dev last (I believe) and I did follow the instructions, so I'm not sure what happened. Glad it appears to be fixed!

**Comment by ngaruko** [comment] 2018-06-07 01:11
Thanks @garethbowen and @sglangevin. Bulk delete is now working. While on this, I discovered another strange behavior. If a report is selected and the user uses a filter (I used 'date' and form type  in here but will try other filters as well), the selected report still shows on the RHS with 'no report' on the LHS if no matching report  (see screenshot 1) or reports matching the filter on the LHS. Not entirely related, I will raise an issue for this, unless there is a known issue related @sglangevin ?.

>Screenshot 2 | Filter == form type | instance: beta-old.dev |version 2.15.0-beta.16
![image](https://user-images.githubusercontent.com/6979995/41072693-8b4d6826-6a53-11e8-8336-196ce496e41d.png)

>Screenshot 2 | Filter == form type | instance: alpha.dev |version 3.0.0
![image](https://user-images.githubusercontent.com/6979995/41072752-d74644c8-6a53-11e8-8374-0cb69176a696.png)

**Comment by garethbowen** [comment] 2018-06-07 01:49
@ngaruko I think this is by design - we don't change the RHS when displaying search results on the LHS.

**Comment by garethbowen** [comment] 2018-06-11 21:11
@rmhowe It appears this change was never forward ported to `master` - can you have a look please?

**Comment by rmhowe** [comment] 2018-06-12 17:33
@garethbowen yep sorry must have forgotten to forward port it, having some issues with `master` currently but will do once they're resolved

**Closed** 2018-06-12 18:16 UTC
Labels: Priority: 2 - Medium, Status: 5 - Ready, Type: Bug
