### ISSUE TITLE
Bulk Select is impressively slow

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3465] opened 2017-05-11 16:53 UTC
In desktop Chrome, selecting an item in the bulk select list takes a few seconds.

I suspect it's doing something sub-optimal.

**Comment by sglangevin** [comment] 2017-05-11 17:58
We've got a bunch of bugs in this iteration already, but I'd like us to look at this next iteration as bulk select and bulk delete are used across most of our deployments. I'll put this one on deck.

**Comment by garethbowen** [comment] 2017-06-20 01:41
@alxndrsn It's fast for me. I've tried to reproduce this as admin and as restricted user, and in Chrome and Firefox. Selecting an item is always really fast (~200ms), and even select all with 360 items completes in a reasonable time (~3s). Can you try and reproduce?

**Comment by alxndrsn** [comment] 2017-06-20 05:40
@ranjuts we saw this on a live instance in Bali.  Do you recall which it was?

**Comment by ranjuts** [comment] 2017-06-20 05:47
This was in [tts-indonesia.app.medicmobile.org](https://tts-indonesia.app.medicmobile.org/). Could it also be the internet connection/device?

**Comment by garethbowen** [comment] 2017-06-20 08:30
Was it as admin or a restricted user? If admin, it could definitely be the internet connection. Every time you select a record it makes a request to the server. If you have a lot of lag it'll definitely be slow.

**Comment by ranjuts** [comment] 2017-06-20 09:07
It was the same time I filed this issue: https://github.com/medic/medic-webapp/issues/3453

It looks like a full access user, admin but not the tech lead kind of admin in case that info is relevant here.

**Comment by alxndrsn** [comment] 2017-06-20 12:22
> If you have a lot of lag it'll definitely be slow.

Interesting.  What are the requests doing?  Would it be possible to check the box before the response is received from the server?  This might make the UI more responsive.

**Comment by sglangevin** [comment] 2017-06-20 16:25
@garethbowen I would test this on a server with a lot of data. I've also seen bulk select be very slow, even on fast internet connections. You can try on lg.app, for example.

**Comment by sglangevin** [comment] 2017-07-24 22:23
This seems to have been fixed with the recent bulk delete performance improvements. @garethbowen @SCdF can we close this?

**Comment by garethbowen** [comment] 2017-07-24 22:50
@sglangevin Have you tested on 2.13.0 alpha or 2.12.1? The code is subtly different.

**Comment by sglangevin** [comment] 2017-07-24 22:52
2.12.1-beta.2. I can test on alpha as well, though.

**Comment by garethbowen** [comment] 2017-07-24 22:56
That'd be conclusive!

**Comment by garethbowen** [comment] 2017-07-26 21:50
As @sglangevin think this is resolved I'm going to close it and set it to AT to make sure.

**Closed by garethbowen** 2017-07-26 21:50 UTC
Labels: 1 - Scheduled, Bug, Next Feature Release, Performance

**Comment by sglangevin** [comment] 2017-08-02 21:39
Much improved in v2.13.0-beta.2. Moving to ready.
