### ISSUE TITLE
Upgrading corrupted a scheduled message string

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2906] opened 2016-11-10 17:39 UTC
When upgrading from v0.4 to v2.8.2 [this Hindi string](https://github.com/medic/medic-projects/blob/master/diy/app-settings.json#L1662) in `app_settings` became corrupt:

`"content": "कृपया {{patient_name}} ({{patient_id}}) को याद दिलाएँ कि इस हफ्ते, वह स्वास्थ्य सुविधा जाएं स्वास्थ्य की जांच के लिए | स्वास्थ्य की जांच के बाद, हमें बताइए  'V {{patient_id}}' से जवाब भेजकर | धन्यवाद !",`

`"content": "कृपया {{patient_name}} ({{patient_id}}) को याद दिलाएँ कि इस हफ्ते, वह स्वास्थ्य सुविधा जाएं स्वास्थ्य की जांच के लिए | स्वास्थ्य की जांच के बाद, हमें बताइ���  'V {{patient_id}}' से जवाब भेजकर | धन्यवाद !",`

**Comment by garethbowen** [comment] 2016-11-10 22:03
I can't spot anything obvious here - throwing back on to the stack in case anyone else wants to have a look.

**Comment by garethbowen** [comment] 2016-11-15 22:58
Can't reproduce. I think this is probably a bug within dashboard somewhere as it manages how settings are copied into the latest ddoc.

That same character was copied successfully in other places in the same settings doc which implies it's a random occurrence or corruption rather than the inability to handle special characters.

We're planning to rethink how we do deployment in the near future so we could put this off till then. The workaround is to back up the app_settings before the upgrade then reapply afterwards.

I'll leave this in the iteration in case someone else comes up with any good ideas.

**Comment by alxndrsn** [comment] 2016-11-25 11:01
@garethbowen If the upgrade is triggered through Dashboard, it may depend on the default string encoding used on the user's browser or machine.  So, if @abbyad triggered the upgrade on Windows, it seems possible that you wouldn't be able to recreate the issue on Ubuntu.  Does that seem plausible?
@abbyad do you remember the OS/browser combination you used when this corruption occurred?

**Comment by abbyad** [comment] 2016-11-25 15:27
Interesting theory! I was on Windows + Chrome when updating that instance.

**Comment by garethbowen** [comment] 2016-11-27 18:56
@alxndrsn Nice one. Gotta love upgrading on the client... It's definitely worth a test. This would mean it's a dashboard issue not a migration one as migrations happen in node on the server.

@abbyad Can you try upgrading again via Windows with clean translations and see if it's reproducible?

**Comment by abbyad** [comment] 2016-12-06 05:57
My most recent upgrade of a config with Nepali characters did not get corrupted. I'll try again later this week with the same config as above.

**Comment by garethbowen** [comment] 2016-12-08 21:53
Closing for testing - reopen if it happens again.

**Closed by garethbowen** 2016-12-08 21:53 UTC
Labels: 1 - Scheduled, Bug, v0.4 upgrading

**Comment by ngaruko** [comment] 2017-02-13 21:56
Will move the AT label and wait for another occurrence (hopefully NOT!)

**Comment by abbyad** [comment] 2017-02-13 22:06
@ngaruko you can also try upgrading with the [app_settings](https://github.com/medic/medic-projects/blob/9416d6fb584cf18c152d87131319592b33ad21a3/diy/app-settings.json) in the original post and seeing if you can reproduce from your Windows environment.
