### ISSUE TITLE
Show parent place after deleting a place/person

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2936] opened 2016-11-17 21:09 UTC
When you delete a person or place you are brought to the blank `No person selected` page. We should return to the parent place after deleting a place. When deleting top level places there is no parent so it is OK to show the blank RHS.

**Comment by garethbowen** [comment] 2016-11-20 18:51
Not a bug. Removing from this milestone.

**Comment by sglangevin** [comment] 2016-11-22 00:31
I would argue that this is a UX bug. Getting to a blank screen after deleting something means that you no longer know where you are in the hierarchy, which is jarring to the user.

**Comment by garethbowen** [comment] 2016-11-24 00:52
@sglangevin It's not a bug because it's working as it was intended to.

**Comment by garethbowen** [comment] 2016-11-24 00:52
@SCdF PR please: https://github.com/medic/medic-webapp/pull/2947

**Comment by SCdF** [comment] 2016-11-24 10:53
LGTM, merged.

**Closed by SCdF** 2016-11-24 10:53 UTC
Labels: 3 - Code Review, Contacts, UI/UX
