### ISSUE TITLE
App Settings disappears on update

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1610] opened 2015-11-18 09:25 UTC
Every time app is updated through Garden, `app_settings` gets lost.

We then see extra tabs, the Welcome dialog, and _Guided Tour_ when logged in as non-admin.

**Comment by garethbowen** [comment] 2015-11-18 09:31
I vaguely recall something like this happening, maybe with JSON parse errors or something... There might be something useful logged in the console on the dashboard upgrade screen next time you run an update.

**Comment by alxndrsn** [comment] 2015-11-18 09:35
I'll keep a closer eye on the dashboard update screen, but IIRC this never shows the process as completing successfully, even when `app_settings` are not lost.

**Comment by abbyad** [comment] 2016-05-04 18:26
Have we reproduced this since only doing updates with a reliable connection? If not, is there anything that we need to do to protect app_settings during a failed update?

**Comment by garethbowen** [comment] 2016-05-04 21:12
I think this was improved (maybe even fixed) by removing the kanso settings migrations.

**Comment by sglangevin** [comment] 2017-02-01 22:59
This hasn't recurred in quite some time. Closing.

**Closed by sglangevin** 2017-02-01 22:59 UTC
Labels: 0 - Backlog, Bug, Configuration
