### ISSUE TITLE
Add "Create Place" to the wizard

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#914] opened 2015-05-01 22:21 UTC
We'd like to Include “create place” for the clinic-level in the wizard, with instructions for how to add CHWs and catchment areas in the Contacts Manager later. This is the only thing left that users need to do to get started using Medic that we aren't addressing in the wizard.

**Comment by abbyad** [comment] 2015-05-06 03:56
@diannakane, is this a duplicate of #858?

Either way, can you or @sglangevin post mockups in this issue with the content needed in the wizard? Once we have that we can move forward to get it ready for the Beta Two release.

**Comment by garethbowen** [comment] 2015-05-25 09:26
I'm pretty sure this is a dupe. Closing for now.

**Closed by garethbowen** 2015-05-25 09:26 UTC
Labels: 0 - Backlog, Feature Request, Needs Design Work
