### ISSUE TITLE
Need cancel button when adding or editing places and people

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2192] opened 2016-04-13 00:03 UTC
Two examples of edit screens below, neither of which has the option to cancel the changes you are making. The first is in a new place creation; the second in editing a person.
![create place](https://cloud.githubusercontent.com/assets/1675870/14479134/7f0014c2-00d0-11e6-8fc2-14510920fc45.png)
![person edit](https://cloud.githubusercontent.com/assets/1675870/14479135/812392f6-00d0-11e6-8e39-c987195b8ec7.png)

**Comment by garethbowen** [comment] 2016-04-13 00:24
Closing as a duplicate of #1984

**Closed by garethbowen** 2016-04-13 00:24 UTC
