### ISSUE TITLE
HBB/FBB does not work as expected on contact-forms

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1681] opened 2015-11-25 22:50 UTC
# Steps to recreate

1. view a contact
2. select an action
1. observe `<` is displayed instead of `X`
3. press HBB or FBB
4. observe form-loading error

**Comment by garethbowen** [comment] 2015-11-26 00:44
Duplicate of #1649 and #1662.

**Closed by garethbowen** 2015-11-26 00:44 UTC
Labels: Bug, Duplicate
