### ISSUE TITLE
re-add help text

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1733] opened 2015-12-02 21:43 UTC
In Issue https://github.com/medic/medic-webapp/issues/1722 we removed the help pages.  We need to revert that commit and file a feature request to support smaller builds/ddocs for faster replication and mobile device initialization.

**Comment by mandric** [comment] 2015-12-02 21:58
Related https://github.com/medic/medic-webapp/issues/1700

**Comment by alxndrsn** [comment] 2015-12-17 11:42
#1700 is the feature request to include help pages in a more bandwidth-friendly way.

**Comment by alxndrsn** [comment] 2015-12-17 11:42
If help docs are re-added, this should not be done in a way which affects the LG trial.

**Comment by alxndrsn** [comment] 2015-12-17 13:07
Duplicate of #1727

**Closed** 2016-01-08 11:34 UTC
Labels: 1 - Scheduled, Duplicate, Technical Debt
