### ISSUE TITLE
Mobile app tries to fetch form definitions from old forms

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2135] opened 2016-03-23 12:13 UTC
During initial replication, the app tries to fetch form definitions for forms that were deleted from Couch. Is there a way to only fetch form definitions for current forms?

**Comment by garethbowen** [comment] 2016-03-23 19:12
@sglangevin Can you define what you mean by "fetch"? Are you seeing a request in the Network tab or something in the console?

Once the app is fully replicated nothing should be fetched from the server (unless you're logged in as admin).

**Comment by sglangevin** [comment] 2016-03-23 19:21
@garethbowen I see requests in the Network tab. I can get you a screen shot, might have to do that tomorrow morning my time though. I thought this might contribute to the other issues I was having during initial replication on slow connections - requesting lots of forms you don't need could be getting in the way of successfully getting the forms you do need. If you plug your Tecno into developer tools and watch the network tab on initial replication, you should see a whole bunch of forms come through, some of which are supervisor forms and aren't currently in Couch.

**Comment by garethbowen** [comment] 2016-03-23 19:22
Yes the screenshot would be very useful, thanks! The only requests I can see are `(from cache)` which means they don't actually go over the internet. I'll keep testing...

**Comment by garethbowen** [comment] 2016-03-23 21:10
Also what's an example of an old form?

**Comment by sglangevin** [comment] 2016-03-23 21:11
I see requests for forms with "test" in the title and others with supervisor in the title, none of which are currently listed in the forms view in Couch. We should have 11 forms (I believe) and I see almost double that number of forms being requested.

**Comment by garethbowen** [comment] 2016-03-23 21:52
Right. After a prolonged investigation and deep dive into the code I think this is by design. On one hand I think couchdb could be smarter about not bothering to replicate deleted docs but on the other hand I think it's trying to allow for incremental replications. Either way I don't think it's something we have control over.

The next version of couchdb has a feature to make this initial replication faster by getting all these docs in one go, rather than potentially thousands of individual requests so I'm hoping we can start using that soon.

Closing as I can't see any way to fix this, or even workaround it.

**Closed by garethbowen** 2016-03-23 21:52 UTC
Labels: Mobile Only, v0.6

**Comment by sglangevin** [comment] 2016-03-23 21:57
Thanks for looking into this @garethbowen!

**Comment by garethbowen** [comment] 2016-03-23 21:58
Sorry I couldn't do more  :(

We really need couchdb 2.0
