### ISSUE TITLE
support offline builds

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2271] opened 2016-05-04 16:35 UTC
Example of cutting network during the npm install step of `grunt dev` on develop... npm just sits here waiting for a very long timeout, I didn't wait it was over 5 mins:

fetchMetadata → network   ▄ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by garethbowen** [comment] 2016-05-04 21:15
Good thinking. Also have a look at [local-npm](https://www.npmjs.com/package/local-npm) which is a local node proxy which will respond immediately.

**Comment by garethbowen** [comment] 2016-08-31 23:05
Duplicate of #2679

**Closed by garethbowen** 2016-08-31 23:05 UTC
Labels: 0 - Backlog
