### ISSUE TITLE
No contact found, no reports when upgrading from v2.12 to v2.13

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3754] opened 2017-08-02 22:51 UTC
After updating from 2.12 to 2.13 on mobile (restricted user), I got errors in the console, "No contacts found" on the people tab and "No reports" on the Reports tab. Refreshing and logging out and back in didn't resolve the errors. This seems to only apply to users who are updating. Logging in to an instance already on 2.13 gave some similar errors, but they appeared to be resolved as the app loaded and there were no issues viewing contacts.

Console:
![image](https://user-images.githubusercontent.com/1286381/28898200-6b216ca8-7799-11e7-8118-efb998226347.png)

inbox.js detail:
![image](https://user-images.githubusercontent.com/1286381/28898218-80245c3c-7799-11e7-9669-2605ef1eecf2.png)
![image](https://user-images.githubusercontent.com/1286381/28898305-0962ee8c-779a-11e7-8216-f36874442e33.png)

**Comment by garethbowen** [comment] 2017-08-08 22:47
The only way I can see this happening is...

1. app cache is updated and user is prompted to refresh which they dutifully do immediately and before the ddoc replication has finished.
2. The app loads and immediately tries to execute code that relies on the latest version of the ddoc which throws the exception you're seeing.
3. The exception causes the replication to not start which means the ddoc is never updated which means the error never goes away.

If I'm right it's amazing we've gone this far without hitting this issue before! I'm going to look at fixing it by running replication first (but not blocking on it), then hopefully the callbacks will fire and the user will be prompted to refresh and then everything will load as expected.

**Comment by garethbowen** [comment] 2017-08-10 10:52
I can reproduce these symptoms if I manually disable replication so the appcache (app code) gets updated but the database (views) does not. But as soon as I turn replication back on and refresh the app it works as expected.

@sglangevin Have you tested more than one device, and if so, does this happen every time? Was this tested in the app or a browser? Is it possible you ran out of space on the phone so replication couldn't complete? Can you copy more of the log, for example, can you find any log messages about replication? Can you find a request in the network tab for `_changes` and is it running or failing?

**Comment by garethbowen** [comment] 2017-08-10 23:09
From Sharon:

> I only tested this on a Tecno Y4 that was already logged in to the app. I don’t think I ran out of space on the phone because I had the Crosswalk version of the container installed. I don’t have the network tab saved anywhere and don’t remember seeing anything else about replication in the console that looked suspicious, but I’m not sure. In order to test again, I’d have to try to repeat what I did last time, but would need a clone of an instance that is on a previous version.

**Comment by garethbowen** [comment] 2017-08-14 04:00
While I couldn't reproduce the issue, the uncaught error is a problem. We are actually catching it properly so it's another case of this issue: https://github.com/pouchdb-community/worker-pouch/issues/15

The PR patches the uncaught exception error which might have been causing this problem. This will need extensive testing to determine if it fixes the issue.

@sglangevin If it happens again while testing this patch can you please attach your entire console output (right click > Save As...)?

@SCdF Code review please!

**Comment by SCdF** [comment] 2017-08-14 08:15
Merged!

**Comment by SCdF** [comment] 2017-08-14 08:16
Acccccctually should I be closing this ticket? I just noticed it's not labeled code review. Is this PR only part of the solution?

**Comment by garethbowen** [comment] 2017-08-14 08:51
Backported to 2.13.x. Closing for further testing and reproducing...

**Closed by garethbowen** 2017-08-14 08:51 UTC
Labels: 1 - Scheduled, Bug

**Comment by sglangevin** [comment] 2017-08-15 21:15
I've tried testing this again but am blocked by #3778 for now. I know that's being worked on currently. Once there is a fix in place, I'll proceed.

**Comment by sglangevin** [comment] 2017-08-18 18:27
I tested the upgrade from v2.12.x to v2.13.0-beta.5 again and could not reproduce this error on any of the 4 devices I tested on (including the Y4, where I originally got the error). Moving to ready!
