### ISSUE TITLE
Contact schema refactor, remove JSON-to-Xform conversion process

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1445] opened 2015-10-16 01:07 UTC
On today's technical design call, we decided it would be nice if fields were defined inside of the Xform exclusively, both for reports (done) and contacts (not yet done). We agreed that there was some need for the current static-assignment schema definitions to become configurable, and agreed that the schema may need to reference either (a) a set of fields to be displayed in summary view, or (b) an Xform or portion of an Xform to be used for rendering the entire summary view.

Figure out how to modify the current schema definitions to take field definitions exclusively from an associated Xform. Remove the code that generates an Xform dynamically from the Javascript-object schema. Figure out how we want to configure the summary view. Then, move on to #1401.

**Comment by garethbowen** [comment] 2017-09-07 07:05
Duplicate of #3570

**Closed by garethbowen** 2017-09-07 07:05 UTC
Labels: Type: Technical issue
