### ISSUE TITLE
The Contact list doesn't load when Indonesian is the user language

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-webapp#3473] opened 2017-05-12 04:33 UTC
When Indonesian is selected as the language for the user, the Contact list doesn't load.
<img width="866" alt="screen shot 2017-05-12 at 12 32 07 pm" src="https://cloud.githubusercontent.com/assets/13689284/25982435/0bd7fdd6-370f-11e7-8c03-0c59a871b9b3.png">

Console displayed following error:
<img width="564" alt="screen shot 2017-05-12 at 12 29 26 pm" src="https://cloud.githubusercontent.com/assets/13689284/25982419/f1a54e0a-370e-11e7-8810-7ec6db0a0d26.png">

cc @alxndrsn

**Comment by bishwas-medic** [comment] 2017-05-12 04:50
Very likely caused by missing translations:

<img width="543" alt="screen shot 2017-05-12 at 12 47 19 pm" src="https://cloud.githubusercontent.com/assets/13689284/25982718/7ecf913a-3711-11e7-9e6a-0847bf798efc.png">

It shouldn't fail this hard.

**Comment by bishwas-medic** [comment] 2017-05-12 04:58
This is caused by a missing translation for `contact.primary_contact_name`.  This is no longer a priority, but as above a missing translation key should not cause a whole tab to fail to load.

**Comment by sglangevin** [comment] 2017-05-12 23:23
Added to the list of bugs to be triaged.

**Comment by garethbowen** [comment] 2017-05-22 08:47
Probably related to #3195

**Comment by garethbowen** [comment] 2017-05-22 08:51
If it is the same as #3195 then it should be fixed in 2.11.0. @bishwas-medic What version is this on?

**Comment by bishwas-medic** [comment] 2017-05-22 09:56
@garethbowen the webapp is in v2.11.1

**Comment by garethbowen** [comment] 2017-05-24 23:40
@bishwas-medic I cannot reproduce this bug. Can you try to reproduce it, perhaps with a language you're not using, and send me the instance URL so I can investigate further?

**Comment by garethbowen** [comment] 2017-06-09 03:44
Cannot reproduce. Please reopen if you have an example I can look at.

**Closed by garethbowen** 2017-06-09 03:44 UTC
Labels: Bug
