### ISSUE TITLE
changes feed is not filtered or limited in api (2.12.0)

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4155] opened 2018-02-01 17:19 UTC
# Environment

* `medic-api 2.12.0` / `couchdb 1.6.1`
* `medic-api master` / `couchdb 1.6.1` (ec6104dcb79df31eb68ee061ff0ee11ce5a2ed18)

# Observed

When re-running the first changes request made from client in `cURL`:

```
$ curl 'http://my_user:pass@localhost:5988/medic/_changes?timeout=595000&style=all_docs&heartbeat=10000&filter=_doc_ids&since=0&limit=100' -H 'Accept: application/json' -H 'Referer: http://localhost:5988/medic/_design/medic/_rewrite/' -H 'Origin: http://localhost:5988' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'Content-Type: application/json' --data-binary '{"doc_ids":["org.couchdb.user:my_user"]}' --compressed | jq .results[].id | wc -l
   20552
```

Changing the port number from `5988` to `5984` produces a single result.

# Expected
1. if the `doc_ids` filter is obeyed, this request should return zero or one results
2. if the `limit` param is obeyed, this request should return 100 or fewer results
3. 20,000 is greater than zero, one and 100

**Comment by alxndrsn** [comment] 2018-02-01 17:36
# Addendum: metrics

port | response time | subsequent doc fetches
---|---|---
5984 | 0.03s | 1
5988 | 40.0s | 20,000

**Comment by garethbowen** [comment] 2018-07-09 00:43
Duplicate of #4172

**Closed by garethbowen** 2018-07-09 00:43 UTC
Labels: Priority: 1 - High, Status: 2 - Active work, Type: Bug
