### ISSUE TITLE
medic-api weird behavior?

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2273] opened 2016-05-04 20:31 UTC
While doing a data import to medic-api I noticed some strange behavior.   The import process makes lots of requests and after I do some thousands of request and the import process is complete, I think medic-api is still holding on to some connections, probably a timeout value somewhere.  So if I shutdown couchdb (the target server for the proxy) after all the requests have completed I get tons of these stacktraces, even though the requests have completed some time ago.

```
UNCAUGHT EXCEPTION!
{ [Error: Can't set headers after they are sent.]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
Server error: 
  detail: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.writeHead (_http_server.js:180:21)
    at Object.module.exports.serverError (/Users/mandric/dev/medic-api/server-utils.js:36:9)
    at Domain.<anonymous> (/Users/mandric/dev/medic-api/server.js:69:17)
    at emitOne (events.js:90:13)
    at Domain.emit (events.js:182:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:126:16)
    at process._fatalException (node.js:261:33)
    at Domain.errorHandler [as _errorHandler] (domain.js:137:26)
```

**Comment by garethbowen** [comment] 2016-05-04 21:20
I'd expect more logging than this. The "can't set headers" thing is usually a symptom not a cause. Is there anything more logged?

**Comment by mandric** [comment] 2016-05-05 00:50
This is repeated logged many times.

**Comment by mandric** [comment] 2016-05-05 00:54
I have a feeling I could reproduce fairly easily with a simple script that POSTs new objects to the API and then delete the medic database after all the POSTs complete.

**Comment by garethbowen** [comment] 2017-04-26 10:26
This is probably a duplicate of [one of many similar issues](https://github.com/medic/medic-webapp/issues?q=is%3Aissue+Can%27t+set+headers+after+they+are+sent+is%3Aclosed) but regardless without more logs and without it being reproduced in a year we aren't going to be able to track it down.

**Closed by garethbowen** 2017-04-26 10:26 UTC
Labels: 1 - Scheduled, Performance, Technical Debt
