### ISSUE TITLE
Analytics screen blank on mobile device

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3906] opened 2017-09-13 03:23 UTC
Steps to reproduce:
1. Installed the app on phone (`unbrandedDebug`, latest from GH)
2. Log in as a restricted user (`apha.dev`, `Version
2.13.0-alpha.7458`)
3. Go to `Analytics` screen
4. Expected: The desktop equivalent has some data
![image](https://user-images.githubusercontent.com/6979995/30358193-193b441c-9897-11e7-9322-244ecd1bd712.png)

But on phone - Blank (for the same user)
![image](https://user-images.githubusercontent.com/6979995/30358203-29a17092-9897-11e7-96a5-913c38a8de54.png)
 
and from logcat:

```09-13 15:20:34.198 31679-31679/org.medicmobile.webapp.mobile D/ViewRootImpl: ViewPostImeInputStage processPointer 0
09-13 15:20:34.288 31679-31679/org.medicmobile.webapp.mobile D/ViewRootImpl: ViewPostImeInputStage processPointer 1
09-13 15:20:34.348 31679-31679/org.medicmobile.webapp.mobile W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-13 15:20:34.398 31679-31679/org.medicmobile.webapp.mobile I/chromium: [INFO:CONSOLE(3)] "AnalyticsMobules. Enabled modules: ", source: https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js (3)
09-13 15:20:34.408 31679-31679/org.medicmobile.webapp.mobile W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 31679
09-13 15:20:34.448 31679-31679/org.medicmobile.webapp.mobile I/chromium: [INFO:CONSOLE(3)] "Error fetching targets", source: https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js (3)
09-13 15:20:34.458 31679-31679/org.medicmobile.webapp.mobile W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 31679```

**Comment by SCdF** [comment] 2017-09-13 06:32
@ngaruko can you please start reporting which version you are seeing these problems in? We have a lot of plates in the air at the moment, and it's a basic piece of information that is incredibly helpful in working out where to look

**Comment by ngaruko** [comment] 2017-09-14 01:20
@SCdF the issue was tested on `apha.dev, Version 2.13.0-alpha.7458`

**Comment by garethbowen** [comment] 2017-10-05 09:36
@ngaruko Thanks for including the log. Unfortunately logcat gives a very truncated output. You can get a complete log using the [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews) feature in a desktop Chrome and checking the dev tools console.

@sglangevin You've been testing the targets page for the 2.14.0 release - have you come across this issue? I'm tempted to close it as cannot reproduce.

**Comment by sglangevin** [comment] 2017-10-05 16:29
@ngaruko what user were you logging in as? What mobile device were you using? What version of the Android app? I haven't reproduced this on my side lately but will test again today.

**Closed** 2017-11-12 22:11 UTC
Labels: Mobile Only, Type: Bug
