### ISSUE TITLE
Task is not removed from LHS list when resolved

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1562] opened 2015-11-11 15:04 UTC
# Observed behaviour

Task is not removed from list when it has been resolved.  Page must be manually refreshed to update the task list.

## 1 Filling the _Follow up_ form
<img width="1280" alt="screen shot 2015-11-11 at 16 01 39" src="https://cloud.githubusercontent.com/assets/191496/11093997/9878ee44-888d-11e5-8b16-11c08b092521.png">

## 2 Form submitted
<img width="1280" alt="screen shot 2015-11-11 at 16 01 43" src="https://cloud.githubusercontent.com/assets/191496/11094001/9c7b08c4-888d-11e5-89f7-89d9dd4cbbd0.png">

## 3 Hard refresh of page
<img width="1280" alt="screen shot 2015-11-11 at 16 01 49" src="https://cloud.githubusercontent.com/assets/191496/11094005/a1630832-888d-11e5-84f4-8a5347bea9df.png">

# Expected behaviour

Task should be automatically removed from list when resolved.

**Comment by abbyad** [comment] 2015-11-14 05:05
Thanks for reporting this @alxndrsn, I was just noticing this too. I am bumping the priority as we ideally want this resolved ahead of the field-test.

**Comment by alxndrsn** [comment] 2015-11-16 18:18
Think I have a fix for this - will push a PR.

**Comment by alxndrsn** [comment] 2015-11-17 08:05
Can't create tasks locally, but I think I understand the issue.  PR @ https://github.com/medic/medic-webapp/pull/1581.  No updates to unit tests, as could not understand them.

**Comment by garethbowen** [comment] 2015-11-17 21:09
After talking with @abbyad it looks like the problem is that this instance is configured to not emit tasks that have been followed up. This needs to be changed to emit the tasks with `resolved: true`.

This is because if tasks are not emitted then we don't know what to remove from the UI unless we regenerate all the tasks again which is a large performance hit. This is why refreshing the screen removes the task.

So the rule is, the task configuration must not contain logic to determine whether or not to emit a task based on mutable data (new reports, updated contacts, etc). That logic should instead be used to set the `resolved` property of the task.

**Comment by abbyad** [comment] 2015-11-18 03:52
Moving to Active Work while I rework the tasks.

**Comment by alxndrsn** [comment] 2015-11-19 09:31
Please delete branch on https://github.com/medic/medic-webapp/pull/1581 when this passes **`Acceptance Testing`**.

**Comment by abbyad** [comment] 2015-11-29 17:12
I cleared the ones I could test with my limited connection. As part of acceptance testing we should test all of the workflows:

- [ ] `register-pregnancy`
- [ ] `pregnancy-high-risk`
- [ ] `pregnancy-healthy`
- [ ] `postnatal-acute-conditions`
- [ ] `postnatal-healthy`
- [ ] `pregnancy_referral_follow_up`
- [ ] `pregnancy-acute-conditions`
- [ ] `assessment-treatment-referral`
- [ ] `assessment-treatment`
- [ ] `assessment-referral`
- [ ] `family-survey`

**Closed** 2015-11-30 09:27 UTC
Labels: 4 - Acceptance testing, Bug, Priority
