### ISSUE TITLE
New Place form doesn't set person.parent

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2390] opened 2016-06-14 14:42 UTC
If you create a place from the LHS "Add place" menu, the place created has a `contact` field set right, but conversely the contact `person` doesn't have a `parent` field linking to the place.

(I suspect this is not specific to .4 Compat, too)

**Comment by estellecomment** [comment] 2016-06-14 14:45
Probably the same as https://github.com/medic/medic-webapp/issues/2327

**Comment by estellecomment** [comment] 2016-06-14 14:46
And https://github.com/medic/medic-webapp/issues/1710

**Comment by garethbowen** [comment] 2016-07-26 23:33
Closing as duplicate of #1710

**Closed by garethbowen** 2016-07-26 23:33 UTC
Labels: Duplicate
