### ISSUE TITLE
After adding a contact, the name doesn't show up on the messages or reports tab

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#873] opened 2015-03-31 00:21 UTC
Sample contacts show up with their names on other tabs but contacts that I added do not
![screen shot 2015-03-30 at 5 18 08 pm](https://cloud.githubusercontent.com/assets/1286381/6909948/23696b94-d701-11e4-8849-1c81c338abb2.png)

**Comment by garethbowen** [comment] 2015-03-31 21:57
Although it's not obvious, I think this is a duplicate of #482 . This happens if you have a Person that is not a primary contact at a Catchment Area, and only primary contacts of Catchment Areas are resolved.

**Comment by garethbowen** [comment] 2015-05-27 01:45
This is now fixed - if the phone number resolves to any person then that person is associated even if they have no location, district, etc.

**Closed by garethbowen** 2015-05-27 01:45 UTC
Labels: 3 - Acceptance testing, Bug
