### ISSUE TITLE
unstable transition on sentinel

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3048] opened 2017-01-13 19:47 UTC
Disable `update_sent_forms` and `update_sent_by` they can be enabled if needed but seem unstable. Related https://github.com/medic/medic-projects/issues/1178

Does this affect all instances and can it be reproduced in sentinel locally?

**Comment by browndav** [comment] 2017-01-17 19:37
To do (from iteration call):

  - [ ] Post backtrace from original medic/medic-projects#1168 (with identifying information removed)
  - [ ] Understand root cause
  - [ ] Decide whether or not other instances are affected
  - [ ] Decide whether to fix transitions, remove transitions entirely and release a v0.4 point release, or fix via script in a configuration-only capacity

**Comment by browndav** [comment] 2017-01-18 23:49
Reminder: could we add a backtrace to this as soon as possible? We need it for a partner-facing post-mortem writeup this week. Thanks.

**Comment by mandric** [comment] 2017-01-19 17:50
See related issue https://github.com/medic/medic-projects/issues/1178 and #safesimbaglung slack channel.

**Comment by mandric** [comment] 2017-01-24 18:08
Post-mortem is in the related issue.  If you need something more there please request it.

**Comment by garethbowen** [comment] 2017-02-09 22:30
This is in AT so closing...

**Closed by garethbowen** 2017-02-09 22:30 UTC
Labels: 4 - Acceptance Testing

**Comment by ngaruko** [comment] 2017-02-13 00:37
Is this acceptance testable on all instances @mandric ?

**Comment by mandric** [comment] 2017-02-13 00:59
This was pretty much replaced by https://github.com/medic/medic-webapp/issues/3102

**Comment by ngaruko** [comment] 2017-02-13 02:14
Thanks @mandric . I will go ahead and remove the AT level, pending #3102
