### ISSUE TITLE
Pouch view error seen in console

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1671] opened 2015-11-25 07:35 UTC
On Android phone:

> `map/reduce function threw an uncaught error`

<img width="1280" alt="screen shot 2015-11-25 at 10 17 13" src="https://cloud.githubusercontent.com/assets/191496/11391011/3a6cb8e8-9360-11e5-924b-b9d6fafcf9a9.png">

**Comment by browndav** [comment] 2015-11-25 15:46
Were you able to associate this with a specific action? I've definitely seen this, but haven't been able to pin it down to something reproducible.

**Comment by garethbowen** [comment] 2016-02-29 23:35
This is probably a dupe of #1973 but it's hard to know without all the stack traces expanded. Closing for now. If it happens again expand the expandables to get more information about which view is failing and reopen.

**Closed by garethbowen** 2016-02-29 23:35 UTC
Labels: 0 - Backlog, Bug, v0.6
