### ISSUE TITLE
Fields not hydrated in objects passed to Context for app forms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3912] opened 2017-09-14 03:39 UTC
As mentioned in https://github.com/medic/medic-webapp/issues/3890#issuecomment-328918429 the `contact` and `user` objects passed to the app form's context are not hydrated. Tested in `2.13.0-beta.14`.

Technically this info could be [passed via the contact-summary](https://github.com/medic/medic-docs/blob/272b9f658f5502859fa3ac68e7ede64e941f4303/configuration/contact-summary.md#context) instead, but this could mean changing existing forms upgrading to 2.13. 

This may be resolved by #3890, which has a fix coming in the next beta, but opening a separate issue to make sure this is tracked too.

**Comment by abbyad** [comment] 2017-09-14 12:06
Does not seem to be resolved by 2.13.0-beta.15. We can work around this for Standard, but we will have to see if other projects are counting on this to know if it is a blocker for 2.13. cc @sglangevin

**Comment by garethbowen** [comment] 2017-09-14 21:55
@abbyad I don't think the `user` was every hydrated - can you confirm? `contact` definitely needs to be fixed...

**Comment by sglangevin** [comment] 2017-09-14 21:59
I think it was because we are using fields from the `user` in our place creation forms, e.g. https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/contact/clinic.xml

**Comment by garethbowen** [comment] 2017-09-14 22:00
@sglangevin The only user field I can see there is `facility_id` which is definitely not hydrated - it's just the uuid. Am I missing something?

**Comment by sglangevin** [comment] 2017-09-14 22:04
Standard place creation forms also use the name of the logged in user. https://github.com/medic/medic-projects/blob/master/standard/forms/contact/clinic-create.xml

**Comment by garethbowen** [comment] 2017-09-14 22:09
Yeah that'll work too. This is what we have (and I assert we always had) available:

```json
{
  "contact_id": "2F6A3788-99F1-BD8F-8B68-60C9B5FD41F5",
  "email": "da@ga.com",
  "facility_id": "73687896-89C8-AD4C-AE68-099004E225FB",
  "fullname": "da",
  "known": true,
  "language": "en",
  "name": "districtadmin",
  "phone": "+64274622636",
  "roles": ["district-manager", "kujua_user", "data_entry", "district_admin"],
  "type": "user-settings",
  "_id": "org.couchdb.user:districtadmin",
  "_rev": "66-6f4224c1fe1fcddc8b0b9b076c1dfc05"
}
```

If you need any of the fields on contact or facility then that'll require hydration, but `user` always had linked contacts - this is nothing new.

Do you know of any forms that use `user.contact.xxx` or `user.facility.xxx`?

**Comment by sglangevin** [comment] 2017-09-14 22:17
I don't know of any off the top of my head and I've searched medic-projects but haven't found any. So I think you are right, that what we have is what we always had.

**Comment by garethbowen** [comment] 2017-09-14 22:26
Looking through the code I also now believe that `contact` was never hydrated either. We only ever bound raw IDs. @sglangevin @abbyad Can you point me to a specific field on a specific form that used to work but has regressed?

**Comment by sglangevin** [comment] 2017-09-14 22:28
Assessment follow-up for LG uses parent contact info: https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/app/assessment_follow_up.xml

Also, we get the CHW phone number in all Standard forms, like this one: https://github.com/medic/medic-projects/blob/master/standard/forms/app/delivery.xml

**Comment by sglangevin** [comment] 2017-09-14 22:33
I just realized this issue was actually about form context, so the properties files. In that case, we were using a hydrated version of the user and the contact. That's what I get for trying to step in on an issue that I didn't file 😐

Anyway, here is an example where we are using the user's parent for form context: https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/app/assessment.properties.json

Perhaps @abbyad can provide an example of where we need a hydrated contact (I don't know of any off the top of my head but will look for one).

**Comment by garethbowen** [comment] 2017-09-15 01:05
I think I see the problem now. If you're filing a report about a patient the patient bound to the form isn't hydrated. We have too many overloaded terms  :(

**Comment by garethbowen** [comment] 2017-09-15 01:45
Code review please @estellecomment

**Comment by garethbowen** [comment] 2017-09-15 10:06
Merged and backported to `2.13.x`

**Comment by abbyad** [comment] 2017-09-15 14:14
Tested on `2.13.0-beta.16` and appears to work well.

With a form that has `context.expression` of `user.parent.type != 'district_hospital'`, the user that belonged to a `district_hospital` could not access the form via the contact or reports tabs, whereas a user associated to a `health_center` could.

Although it is a little fuzzy whether the `parent` is the user's facility or the associated contact's parent, the fields for `user` are definitely hydrated in this case. @sglangevin, do you you may want to test with some actual project configurations as well, or move directly to Ready?

**Comment by sglangevin** [comment] 2017-09-15 18:36
@abbyad that is the expected behavior to me. I've tested beta.16 on LG's config and the correct forms show up for the correct users as expected. I'm going to move this to Ready. Thanks!

**Closed by sglangevin** 2017-09-15 18:36 UTC
Labels: Priority: 2 - Medium, Regression, Status: 4 - Acceptance testing, Type: Bug
