### ISSUE TITLE
when `require_valid_user` couchdb config is false medic-api login redirects infinitely

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1742] opened 2015-12-04 12:56 UTC

**Comment by nice-snek** [comment] 2017-03-01 10:32
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment] 2017-03-01 16:52
Can't reproduce it. Closing.

**Closed by estellecomment** 2017-03-01 16:52 UTC
Labels: 0 - Backlog, Needs Triage
