### ISSUE TITLE
[enketo] Associate sent report to User/Person

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1229] opened 2015-08-30 22:53 UTC
This may be two issues, but combining the idea as one. Right now the sender is selected from a drop down on the Edit Report modal. The sender should be the currently logged in user, which needs to be associated to a Person. 

1. Associate User to Person: We could associate the User and Person by making sure they have the same phone number, but ideally, in the User creation/edit page we would select the associated Person for a User. 
2. Associate reports: All reports sent by the User should automatically show up as being sent from the Person.

**Comment by garethbowen** [comment] 2015-09-21 23:47
Duplicate of #1292

**Closed by garethbowen** 2015-09-21 23:47 UTC
Labels: 1 - Scheduled
