### ISSUE TITLE
Deleting contact shows blank right pane

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1900] opened 2016-02-11 13:22 UTC
On 2660, deleting a contact showed a blank grey right pane. It should return to the place that the contact belonged to with a toast "Contact deleted".

**Comment by alxndrsn** [comment] 2016-02-11 13:25
May be caused by recent work in either #1862 or #1348

**Comment by estellecomment** [comment] 2016-02-24 16:55
Actually, should it always go to its parent place? If you were in the parent place just previously, then yes. But if you selected the contact from the left-hand list, then delete it, you'll jump to the parent place which was not the last page you were at (it was the contacts list)

Example : you are in contact list
![screen shot 2016-02-24 at 17 52 54](https://cloud.githubusercontent.com/assets/911434/13293320/7e28023e-db1f-11e5-800e-8b33bff02a50.png)
Then you select a family
![screen shot 2016-02-24 at 17 49 22](https://cloud.githubusercontent.com/assets/911434/13293261/43bba2c2-db1f-11e5-8a9d-8639ad560f10.png)
Then you delete it. I'd expect to go back to the contact list with no right pane.
Instead, jumping to parent sends you to the parent contact : 
![screen shot 2016-02-24 at 17 49 37](https://cloud.githubusercontent.com/assets/911434/13293293/5d94bbca-db1f-11e5-9e36-673e93f6791f.png)

Thoughts @abbyad ?

**Comment by alxndrsn** [comment] 2016-02-24 16:59
IMO it should just go to _No contact selected_ until we are properly tracking breadcrumbs for the HBB / chevron-back behaviour.

**Comment by estellecomment** [comment] 2016-02-24 17:34
Stuff that should be fixed regardless of where to navigate back to : 
 - The "Contact Deleted" toast is missing, both on mobile and desktop.
 - The desktop's right pane doesn't display "No contact selected" when you get to it after a deletion (it's empty)

**Comment by estellecomment** [comment] 2016-02-25 11:18
The "No contact selected" is displayed when you're in `contacts.detail` state. It's not being displayed after deletion because we're redirecting to `contacts`. 
In practice, the links all over the UI are to `contacts.detail`, never `contacts`, and it doesn't look like we use `contacts` at all (except if you navigate to `<url>/contact`, without trailing slash).

What makes the most sense to me is to make `contacts` a transient state that redirects to `contacts.detail`.

**Comment by estellecomment** [comment] 2016-02-25 14:11
The cosmetic UX stuff is done, and I filed a separate issue for navigation (#1975).

@alxndrsn, can you review please?

**Comment by alxndrsn** [comment] 2016-02-25 14:56
> In practice, the links all over the UI are to `contacts.detail`, never `contacts`, and it doesn't look like we use `contacts` at all (except if you navigate to `<url>/contact`, without trailing slash).
Sounds to me like we should fix `/contacts` - if `contacts.detail` is loading `ContactsContentCtrl

**Comment by alxndrsn** [comment] 2016-02-25 15:02
Hmm this behaviour actually seems consistent with other controllers... wonder why we have all these dead states.

**Comment by estellecomment** [comment] 2016-02-25 15:06
> If contacts.detail is loading ContactsContentCtrl when it isn't needed
I think it is needed : it loads the contact list in the left pane. That's needed for all child states of `/contacts`, so it should stick around as a parent state.

**Comment by alxndrsn** [comment] 2016-02-25 15:43
> > If contacts.detail is loading ContactsContentCtrl when it isn't needed
>
> I think it is needed : it loads the contact list in the left pane. That's needed for all child states of `/contacts`, so it should stick around as a parent state. 

I'd have thought `ContactsCtrl` loaded the list and was parent state to both of `ContactsContentCtrl`, `ContactsEditCtrl` and `ContactsReportCtrl`...

**Comment by alxndrsn** [comment] 2016-02-25 22:42
Very minor comments on commits.

**Comment by estellecomment** [comment] 2016-02-29 12:47
Turns out what I'd done worked for contacts but not for tasks (??). 
What was missing was make the parent state abstract, so added that : 
https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-set-up-a-defaultindex-child-state

Abstract states still have their controllers run, and have templates, like normal states.
https://github.com/angular-ui/ui-router/wiki/Nested-States-&-Nested-Views#abstract-states

For `messages` I've tested by hand that it doesn't break the tour. 

For `reports`, I have to figure out what the `query` param does and make sure the redirecting will not break it. There aren't any tests about that, so I don't want to touch it without writing tests. That'll be handed over to #1976.

**Comment by alxndrsn** [comment] 2016-03-04 07:57
Causes #2006 & #2007 and potentially #2008.  Recommend fixing states so that:

`/contacts` -> _No contact selected_
`/contacts/bad-id` -> _Contact not found_

**Comment by estellecomment** [comment] 2016-03-04 12:27
Removing that state-jumping stuff. Solves #2006 and #2007 on my local env. (#2008 is not very descriptive so don't know)

**Comment by garethbowen** [comment] 2016-03-15 01:37
I removed the above commit as it caused the regression in #2043 . I'm not sure what state this issue is in now....

**Comment by estellecomment** [comment] 2016-03-15 05:16
cursed?
Back to zero.

**Comment by alxndrsn** [comment] 2016-03-15 06:07
Not much point reviewing code that's been reverted.

**Comment by estellecomment** [comment] 2016-03-29 13:52
Code looks good but it doesn't solve the issue on desktop, I still see a blank right pane after contact deletion.

**Comment by estellecomment** [comment] 2016-03-30 09:31
Works for contacts, mobile and desktop.

For reports, on mobile and desktop, when you delete a report it stays displayed. The url does go to `reports/`. It does disappear from the reports list (on desktop), and apparently does get deleted (when you interact with it things go all wrong)

**Comment by estellecomment** [comment] 2016-03-30 09:41
Actually, that's probably caused by #1963, `clearSelected()` is not called any more when `id` is empty.

https://github.com/medic/medic-webapp/commit/74d55eca393d2869de5266bfb47cd07032f0de23#diff-ae2ab03c7390b4a1da61f490703e73daR130

**Comment by estellecomment** [comment] 2016-03-31 12:04
A couple questions : https://github.com/medic/medic-webapp/commit/1d27e50bb9fef67d23e9866a297f62892373d4cf

Contacts looks like it works fine.
Reports has a problem : when you delete a report, it stays displayed in the LHS list.

**Comment by estellecomment** [comment] 2016-03-31 12:50
Oh fun : navigation for messages deletion is now messed up. When you delete a message from a conversation, you land back on "No message selected" instead of staying on the conversation.

Delete the 2nd message : 
![screen shot 2016-03-31 at 14 46 42](https://cloud.githubusercontent.com/assets/911434/14176109/9eaae610-f74f-11e5-98e2-d2dca456a4f4.png)

You get sent back to "No message selected" :
![screen shot 2016-03-31 at 14 46 57](https://cloud.githubusercontent.com/assets/911434/14176120/afe10446-f74f-11e5-9724-6ea81d42b52c.png)

**Comment by garethbowen** [comment] 2016-03-31 19:20
LGTM

**Closed** 2016-03-31 19:20 UTC
Labels: 4 - Acceptance testing, Bug

**Comment by estellecomment** [comment] 2016-04-01 08:08
omg closed at last
