### ISSUE TITLE
User type should be required when creating/editing a user

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3066] opened 2017-01-20 20:01 UTC
![screen shot 2017-01-20 at 17 59 43](https://cloud.githubusercontent.com/assets/911434/22163522/510a5e1c-df3a-11e6-8a4d-b91c8790fc7b.png)

Only required fields are username and password. 
I can't think of a reason why we would leave the user type unset. We should make it required. (you get some weird errors on login if you don't set it, anyway)

**Comment by nice-snek** [comment] 2017-03-28 15:17
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment] 2017-04-11 13:52
I still agree with myself (who filed this) that it should be fixed. Scheduling.

**Comment by cbrwizard** [comment] 2017-10-19 15:47
Hey, this seems to be fixed already on `master` branch. 
<img width="953" alt="screen shot 2017-10-19 at 18 46 12" src="https://user-images.githubusercontent.com/1615659/31780244-d837fe0a-b4fd-11e7-96c6-652057be1887.png">

**Comment by garethbowen** [comment] 2017-10-19 20:09
Good spotting - this is a duplicate of #3904

**Closed by garethbowen** 2017-10-19 20:09 UTC
Labels: Configuration, Status: 1 - Triaged, Users
