### ISSUE TITLE
`User Type` in user creation should be required

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3411] opened 2017-04-24 18:58 UTC
If the user type is omitted during user creation the user gets redirected to the error page when logging in. In console it shows `Error: No tabs available`. Simplest fix is to make the User Type field required in the UI.

**Comment by SCdF** [comment] 2017-04-25 07:03
NB: https://github.com/medic/medic-webapp/issues/2222 would also help here.

**Comment by garethbowen** [comment] 2017-11-16 00:53
Duplicate of #3904

**Closed by garethbowen** 2017-11-16 00:53 UTC
Labels: UI/UX, Users
