### ISSUE TITLE
Pressing HBB on datepicker kills calendar

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1691] opened 2015-11-27 05:47 UTC
Seen on _Add family member_ form:

1. click on date-of-birth field
2. observe datepicker
3. press HBB
5. observe datepicker no longer visible
8. click on date-of-birth field
13. observe datepicker will no longer appear
21. check and uncheck _unknown date_
34. click on date-of-birth field
55. observe datepicker

**Comment by garethbowen** [comment] 2015-11-30 01:34
@alxndrsn Surely this is a duplicate of #1693 ?

**Comment by alxndrsn** [comment] 2015-11-30 07:52
Likely.  Hard to keep track when pages load so slow, and better to get them all in with a few dupes than to miss some stuff.

**Comment by alxndrsn** [comment] 2015-12-02 08:18
Some interesting points:
* happens in the Y4 Browser as well as the wrapper (on simple test page - https://alxndrsn.github.io/medic-js-dbg/)
* I have not been able to detect a javascript event when the HBB is pressed
* proper behaviour can be re-instated by changing from `<input type="date">` -> `<input type="text">` -> `<input type="date">`

**Comment by alxndrsn** [comment] 2015-12-02 08:29
A similar problem can be created by adding an `onclick` event listener to the `input[type=date]` field:
* if the code evaluation is continued quickly, the native datepicker will appear, but
* if a few seconds are waited before continuing the code, the datepicker will not be displayed

**Comment by alxndrsn** [comment] 2015-12-02 09:55
I think this is an Android / Chrome / Tecno bug.  @abbyad @browndav interested in hearing your thoughts

**Comment by alxndrsn** [comment] 2015-12-02 09:55
Can also get the popup working again by hiding and unhiding the field's parent element.  However, if this is done in the click listener, then the datepicker dialog does not set the element value on `Set`.

**Comment by alxndrsn** [comment] 2015-12-02 10:01
@abbyad @browndav 

## Recommendations

### Long-term

Add a native datepicker to the android wrapper which is triggerable via JS.  Create an enketo datepicker widget which will trigger this datepicker, and insert it's value into the DOM.

### Immediate

Either:

a. Consider this a known issue and warn users, or
b. add a 'refresh' button next to date fields on Android, so they can be re-initialised without having to change page or check-uncheck 'date unknown'

**Comment by alxndrsn** [comment] 2015-12-02 10:11
Bug not present on Samsung Galaxy S5

**Comment by alxndrsn** [comment] 2015-12-02 12:01
Should be deployed in build `2462`.

Apologies for the ugly CSS; couldn't work out why the button was appearing in such a weird vertical position in `WebView` when I used the initial CSS.

**Comment by alxndrsn** [comment] 2015-12-02 16:20
TODO this may have caused desktop chrome to use `input[type=text]`, which we don't want - I will revisit and fix this.

**Closed** 2015-12-02 21:51 UTC
Labels: 3 - Code Review, Bug, Mobile Only
