### ISSUE TITLE
Task won't clear up after registration. 

### ISSUE THREAD

**Issue by ngamita** [medic/medic-webapp#1677] opened 2015-11-25 09:21 UTC
After initial pregnancy registration the Task won't clear as noted on attachment. 
![screenshot_2015-11-25-12-18-37](https://cloud.githubusercontent.com/assets/294861/11393158/135cda80-936f-11e5-8939-fb3f2e2551b5.png)
![screenshot_2015-11-25-12-18-19](https://cloud.githubusercontent.com/assets/294861/11393159/135e4366-936f-11e5-87c7-e4796b1d91aa.png)

**Comment by abbyad** [comment] 2015-12-01 20:35
Duplicate of https://github.com/medic/medic-webapp/issues/1562, which is now resolved.

**Closed by abbyad** 2015-12-01 20:35 UTC
