### ISSUE TITLE
Export server logs from webapp does not work

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3089] opened 2017-01-27 16:34 UTC
From @smbuthia in https://github.com/medic/medic-projects/issues/1301:
> I tried exporting server logs from the web app [...] but nothing seems to happen when I click on the export button, even with the `can_export_server_logs` permissions set.
>
> ![export](https://cloud.githubusercontent.com/assets/1491710/22329430/301cf308-e3d2-11e6-8d9b-120c5f47d095.png)

Seems related to #2694

**Comment by garethbowen** [comment] 2017-01-29 18:40
@smbuthia @abbyad Were there any errors in the JS console or API logs?

**Comment by smbuthia** [comment] 2017-01-29 18:46
@garethbowen ,yes. I've attached below.

![export-server-logs](https://cloud.githubusercontent.com/assets/1491710/22406862/336670f6-e66c-11e6-80e2-59026eda682f.png)

**Comment by garethbowen** [comment] 2017-01-29 18:50
That's perfect @smbuthia thanks! The "Internal Server Error" bit implies that it's an issue with API so there's almost certainly more information in the API logs. Can you please check there too?

**Comment by smbuthia** [comment] 2017-01-29 19:07
Not sure if this is what you need @garethbowen but here is what I get from `error-ssl.log`

```
2017/01/29 19:04:02 [error] 949#0: *27420 connect() failed (111: Connection refused) while connecting to upstream, client: 197.237.241.xxx, server: _, request: "POST /api/v1/export/logs?format=zip&locale=en HTTP/1.1", upstream: "http://127.0.0.1:280/api/v1/export/logs?format=zip&locale=en", host: "cbhipp.dev.medicmobile.org", referrer: "https://cbhipp.dev.medicmobile.org/medic/_design/medic/_rewrite/"
```

**Comment by garethbowen** [comment] 2017-01-29 20:45
There's an error in the medic-api logs:

```
2017-01-29T19:23:55.749Z - error: Server error:
 [Error: Log export exited with non-zero status 1]
```

So the log bundling script is exiting with a 0. I'm not sure if we have any more data...

**Comment by garethbowen** [comment] 2017-01-29 20:52
Host: cbhipp.dev.medicmobile.org

Maybe it can't find the `print-logs` script? I can find a copy in `/srv/storage/system-services/home/vm` but it fails to execute directly with:

```
./print-logs: source: line 4: can't open '/boot/include/formatter'
```

@browndav Can you take a look at this?

**Comment by browndav** [comment] 2017-02-21 17:31
Self-assigning this and placing it in the current sprint.

**Comment by browndav** [comment] 2017-02-28 12:58
This is fixed in the current Medic OS `master`, and will be automatically patched as part of the upgrade process outlined in https://github.com/medic/medic-servers/blob/master/docs/package-update-checklist.md. That work is currently being tracked by https://github.com/medic/medic-webapp/issues/3110.

**Comment by browndav** [comment] 2017-02-28 13:00
Root cause: merge error resulted in `formatter` being omitted during a release. It is now checked in at https://github.com/medic/medic-os/blob/master/platform/initrd/common/boot/include/formatter.

**Closed by browndav** 2017-02-28 13:00 UTC
Labels: Bug

**Comment by ngaruko** [comment] 2017-03-02 05:33
Was this issue specific to an instance or are we able to test it on our test instances @abbyad ? Can @smbuthia check if he can now export logs on the same instance?

**Comment by sglangevin** [comment] 2017-03-02 18:25
I just tested this on lg.dev (latest beta) and exporting server logs isn't working. Here are the console errors I'm seeing:
![image](https://cloud.githubusercontent.com/assets/1286381/23521110/8c3bb5ae-ff32-11e6-9245-afdc76a83b04.png)

**Comment by browndav** [comment] 2017-03-02 18:31
This server would need to be upgraded for you to see a difference, and AFAICT https://github.com/medic/medic-webapp/issues/3173 is blocking that. I'll upgrade `lg.dev` ASAP after a resolution to medic/medic-webapp#3173 – it's the sole remaining blocker for a Medic OS release.

**Comment by sglangevin** [comment] 2017-03-02 18:32
Ah, makes sense. I guess we can hold off on AT for now then. We can easily AT this on one of the upgraded cloned instances.

**Comment by ngaruko** [comment] 2017-04-04 04:08
This issue is still pending/happening but has AT label. Shall we move it to ready and leave the open #3209 
@garethbowen @sglangevin ?
![image](https://cloud.githubusercontent.com/assets/6979995/24641114/d99a1146-1950-11e7-903b-038318d30f59.png)

**Comment by ngaruko** [comment] 2017-04-04 04:30
Will move this one and will do full AT with  #3209

**Comment by sglangevin** [comment] 2017-04-05 18:36
This should be working on an instance with upgraded Medic OS. Where did you test?
