### ISSUE TITLE
Deleting report forwards to a blank screen

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2081] opened 2016-03-15 07:51 UTC
# Observed

On deleting a report, the new page is blank:

## Mobile

<img width="572" alt="screen shot 2016-03-15 at 10 47 55" src="https://cloud.githubusercontent.com/assets/191496/13770982/acee65fa-ea9b-11e5-933c-82ffa5f58179.png">

## Desktop

<img width="1280" alt="screen shot 2016-03-15 at 10 48 48" src="https://cloud.githubusercontent.com/assets/191496/13770979/a9f968e0-ea9b-11e5-8bea-a6a946314840.png">

# Expected

## On mobile

Should return to the list of reports.

## On desktop

Right pane read say _No report selected_.

# Notes

Related: #1900

**Comment by SCdF** [comment] 2016-03-22 12:46
NB: CHPs are not able to delete reports, only admins.

**Comment by estellecomment** [comment] 2016-03-29 08:36
LGTM, thanks!

**Comment by estellecomment** [comment] 2016-03-29 13:55
Actually, this fixes mobile but not desktop. Still see a blank right pane. Reopening.

**Comment by garethbowen** [comment] 2016-03-31 03:24
Closing this as a duplicate of #1900

**Closed by garethbowen** 2016-03-31 03:24 UTC
Labels: 2 - Active Work, Bug
