### ISSUE TITLE
If two groups of scheduled_messages fall within the silence window, only the first one is silenced

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3818] opened 2017-08-23 14:51 UTC
Not sure if you _want_ to have several groups falling within your silence window, but it seems that if you do, then they should both be silenced.

**Comment by sglangevin** [comment] 2017-08-23 14:59
I actually think this is the desired behavior. Sometimes the schedule has groups that are very close together, you wouldn't want to clear two groups because you would miss messages that you are expecting to get. I think some projects may be using this as a feature.

**Comment by abbyad** [comment] 2017-08-23 15:25
This is not the intended behavior, and so I would still consider this a bug.

**Comment by estellecomment** [comment] 2017-08-23 15:39
Well, if it's a bug that we're counting on in production, isn't it a feature? :)

**Comment by abbyad** [comment] 2017-08-24 15:58
I still think the intended behaviour is to clear all groups that have a message within the silence window. If groups are close together and clearing one near a boundary should not affect the other than I'd expect the silence window to be set accordingly (eg 1 day vs 1 week).

**Comment by abbyad** [comment] 2017-08-25 13:10
Just thought that I'd add that many project configs have been written over the last five years with this rule in mind. I'd be curious to see one that expects only one of the overlapping/proximity groups in the same time window to be cleared.

**Comment by SCdF** [comment] 2017-09-12 15:17
FWIW I actually implemented this as described in medic/medic-sentinel@f9b539a7f9a8ddec245307bb216b19d6e7a31fb7, based on a conversation on #3857

@abbyad / @sglangevin this may put us in a pickle if people are relying on it, and we may have to have more conversations about it.

To me (as a doe-eyed developer, unwise of the ways of the world), what I implemented makes sense: if you want to clear N days ahead, then it should clear everything, not just the first thing. In no small part because the first thing being the right thing is just accidental, and could break in the future (ie we are relying on some implicit ordering here).

**Comment by garethbowen** [comment] 2017-10-09 21:12
@SCdF I'm unclear whether we have regressed on a feature or fixed a bug. Would you mind doing a little triage with Sharon and Marc to clarify where we're at?

I'd like to get the [associated PR](https://github.com/medic/medic-sentinel/pull/162) either fixed and merged, or closed.

**Comment by SCdF** [comment] 2017-10-10 14:50
I've closed the PR, it's no longer relevant. There are already tests covering the same thing.

Basically we now need to make a decision about whether, when more than one group falls within a silence window:
 - All groups within the silence window gets silenced (how master works right now)
 - Only the "first" (where first is the one the code gets to first) group gets silenced (how the code used to work)

@abbyad , @sglangevin and I will have a conversation about it and report back here

**Comment by abbyad** [comment] 2017-10-10 15:43
I'm all for option 1 (clear all groups within silence window) and can't see a reasonable case for 2, but open to chat about it if anyone feels differently.

**Comment by SCdF** [comment] 2017-10-10 16:21
So Option 2 was _apparently_ intentional years ago, but there is little documentation on the reasoning: https://github.com/medic/medic-webapp/blob/master/Changes.md#0311

> When silence_for is specified we should only silence/clear one group, I introduced a bug a few commits ago that would ignore the group and silence/clear based on date. Use the silence_for window to match and clear the first group.

In any case, if we want to continue down route 1 a documentation PR is here: https://github.com/medic/medic-webapp/pull/3954

**Comment by garethbowen** [comment] 2017-10-11 00:29
Documentation looks good to me. I'll schedule this for 2.14.0. Thanks everyone.

**Comment by SCdF** [comment] 2017-10-11 08:56
AT: Making sure this actually works like we just documented in the above PR (as seen if you read release notes, or look at kanso configuration for the `silence_for` variable)

**Closed** 2017-10-12 08:55 UTC
Labels: Priority: 2 - Medium, Status: 5 - Ready, Type: Bug
